### ISSUE TITLE
Update button styles

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#1007]
From a user via contact form:

> Like and Twitter symbol at each project page should be little bold, or have colored boundary, cause, they are difficult to notice with white background and I mistakenly added that project instead of marking it as favorite.

![group](https://user-images.githubusercontent.com/5816130/52075380-1fa98b00-255a-11e9-8bb1-a78ce5ad0060.jpg)

**Comment by AdityaSrivast** [comment]
@gideonthomas I would like to work on this issue. Can you brief me about what's to be done, please?

**Comment by gideonthomas** [comment]
Hi @AdityaSrivast, there isn't any direction on what needs to be done here yet so this isn't a great issue to work on. Feel free to contribute to one of the tickets in this list instead: https://github.com/mozilla/network-pulse/labels/help%20wanted%20%3Awave%3A

**Comment by AdityaSrivast** [comment]
@gideonthomas I want to work on this. Can I take it up?

**Comment by gideonthomas** [comment]
Hi @AdityaSrivast I think this work is being done as part of larger brand work in pulse so I'm going to have to close this ticket. Please do look at the list I link above if you would like to contribute.
