### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#1009]
https://wiki.mozilla.org/GitHub/Repository_Requirements

**Comment by AdityaSrivast** [comment]
@alanmoo I want to work on this issue. Can you brief me on what needs to be done, please?

**Comment by Pomax** [comment]
Hi @AdityaSrivast. https://wiki.mozilla.org/GitHub/Repository_Requirements explains what is necessary. Do note that that the text that's in HTML comments (about project-specific CoC) can be omitted.
