### ISSUE TITLE
Replace "Open Innovation" with "Openness"

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#1012]
This internet health issue has been renamed. We should also rename it on pulse.

I think the only engineering fix that needs to be done is to replace every hardcoded occurrence of "open innovation" with "openness".

Note to self: I will need to update this via the admin interface after this lands.

@AdityaSrivast would you be willing to try to fix this? It's similar to your work in https://github.com/mozilla/network-pulse/pull/1003.

**Comment by AdityaSrivast** [comment]
@gideonthomas Sure. On it

**Comment by gideonthomas** [comment]
Thanks @AdityaSrivast
