### ISSUE TITLE
Build Profile Search frontend

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1013]
Profile search will allow staff and partners to find experts in our network to engage with for conferences, press, and projects. 

A few steps to this work: 
 - [x] api stuff (https://github.com/mozilla/network-pulse-api/issues/453)
 - [ ] search view tab (see below)
 - [ ] profile card for search results
 - [ ] thinking about search field on foundation site

At top of search results, below search input, we display two tabs. One for Projects and one for People. Default to Projects and list results. Search for people can wait until user tabs to that view (though we _could_ pre-fetch after a pause on user input).

 
Demo of UX (ignore UI)

<img width="872" alt="image" src="https://user-images.githubusercontent.com/53411/53191302-7cd4b180-35d9-11e9-970f-ee82aac66c7a.png">

**Comment by xmatthewx** [comment]
Here's a comp of the people tab, keeping all the styles used in a profile. 

 - [ ] Name and photo should link to profile
 - [ ] Let's limit width of bio text on desktop. Maybe `md-8`.
 - [ ] Ideally, let's preserve search term as users switch tabs
 - [ ] No need to do anything fancy fetching or preserving queries between tabs, unless it's tooootally trival
 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/53411/55024424-31953080-4fd5-11e9-8087-bbf5519fea7b.png">

**Comment by gideonthomas** [comment]
I'm going to suggest using the same "View More" pagination that we have for entry search because image sizes are really large at the moment. I can add pagination to the API per https://github.com/mozilla/network-pulse-api/pull/464#issuecomment-476886273

**Comment by xmatthewx** [comment]
@mmmavis let me know if you have any questions about this plan.

**Comment by gideonthomas** [comment]
complete front-end implementation blocked on https://github.com/mozilla/network-pulse-api/pull/469 landing...but shouldn't block getting this started.

**Comment by gideonthomas** [comment]
unblocked. Documentation for the route is here: https://github.com/mozilla/network-pulse-api#get-apipulseprofiles-with-filter-arguments-and-optional-formatjson

**Comment by mmmavis** [comment]
@gideonthomas are we switching everything over to Pulse API v3 or just that route?

**Comment by gideonthomas** [comment]
Currently that's the only route that's on v3. If you switch others to v3, nothing will break since it's still serving the same data.

**Comment by mmmavis** [comment]
PR has been merged and pushed to staging.

Re-opening this ticket as I'm not sure if the backend work has been pushed to production API yet.

/cc @gideonthomas

**Comment by gideonthomas** [comment]
I'll do it tomorrow morning

**Comment by gideonthomas** [comment]
Done @mmmavis

**Comment by mmmavis** [comment]
Sounds good with me!
