### ISSUE TITLE
Update Pulse UI to align with Foundation site 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1014]
Let's focus on the least amount of work that gets us most of the way there. For example, prioritize the header and fonts rather than worrying about all the layout details. 

TBD: Can we leverage fo'mo CSS directly for this? And just add specific pulse styles where needed?

**Comment by natalieworth** [comment]
I've updated the Pulse UI based on brand talk/ feedback from team and Sabs. 
Latest version (V3) with some questions posted in the redpen: https://redpen.io/sob6953ec4e0a6bde5
Search/ Help homepage alternatives: https://redpen.io/oj6a13a99008ba0cae

**Comment by natalieworth** [comment]
Final Pulse UI is [in this redpen](https://redpen.io/p/uk95e2dc951b414a1d)

Closing this ticket, as dev/ implementation tickets have been opened.
