### ISSUE TITLE
Add pulse form tag feature to wagtail docs 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1019]
Pulse landed a great [new feature](https://github.com/mozilla/network-pulse/issues/1011) that allows staff to help people more easily tag an entry for a specific use case. Let's add this to wagtail documentation to make it available to others. 

@gideonthomas - if you can write a quick rough how-to description i can refine it and add screenshots and figure where to post it.

**Comment by gideonthomas** [comment]
"""
You can now share a pre-tagged Pulse form to add a new entry.

To do this, simply [use this tool](https://moz-pulse-tag-encode.glitch.me/) to type out your tags separated by commas and it will generate a URL address to a pre-tagged Pulse form that you can share.
"""

One thing to note - the pre-tagging doesn't really work for tags with spaces; filed https://github.com/mozilla/network-pulse/issues/1020

**Comment by xmatthewx** [comment]
@sabrinang - staff can give people a custom pulse URL so that submission get an auto tag. @gideonthomas kindly wrote a description above (with a note on a limitation). But I never got around to adding it to the wagtail docs. Can I bother you to do that? It's a good feature for to understand and be able to leverage with program staff.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
