### ISSUE TITLE
Pre-tagged add entry form does not work for tags with spaces

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#1020]
Currently, hitting up https://www.mozillapulse.org/add?tags=mozsprint,mozilla works fine, but https://www.mozillapulse.org/add?tags=moz&20sprint,mozilla does not (it gets rid of the space).

This works for other special characters, so ideally this should work for spaces as well.

**Comment by xmatthewx** [comment]
Good catch! And, let's make sure it really matters. Feels like programs could work around this with creative tag names.

**Comment by gideonthomas** [comment]
We should close or prioritize this ticket after looking at metrics for tagging.

**Comment by Pomax** [comment]
Did you mean https://www.mozillapulse.org/add?tags=moz%20sprint,mozilla ? The original url shown has `&20`, where `&` is a query argument delimiter.

**Comment by xmatthewx** [comment]
I think we can skip this. It doesn't need to work for a all tags, just tags that help programs.

**Comment by gideonthomas** [comment]
@xmatthewx sounds good!

@Pomax yep sorry, typo.
