### ISSUE TITLE
Pre-filled tags don't work without `www`

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#1021]
[https://www.mozillapulse.org/add?tags=mozsprint,mozilla](https://www.mozillapulse.org/add?tags=mozsprint,mozilla) adds the autocompleted tags, but when attempting to visit the site from [https://mozillapulse.org/add?tags=mozsprint,mozilla](https://mozillapulse.org/add?tags=mozsprint,mozilla), the query params get stripped

(This may be server related, so @cadecairos I'm tagging you too)

**Comment by Pomax** [comment]
Yeah, that feels like like the old mod_rewrite forgetting to pass through $1, but then for whatever we're actually using because I doubt it's Apache =P

**Comment by cadecairos** [comment]
I just modified the CDN to forward querystrings, this should work now.

**Comment by gideonthomas** [comment]
Thanks @cadecairos!
