### ISSUE TITLE
Make plan to reduce spam

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1024]
Looks like Pulse is starting to receive spam. [see moderation](https://www.mozillapulse.org/moderation?moderationstate=Declined). Let's take a look at figure where it's best to intervene. Login is best if possible. Submission if not. 

cc @gideonthomas @cadecairos @alanmoo to triage and file tickets.

**Comment by cadecairos** [comment]
It looks like we're receiving a smaller amount of spam than we'd need to really engineer a solution here. Moderation seems like the way to handle a few spammy submissions.

We might want to consider adding in a way to put a ban on an account (i.e no longer allowed to log in and submit), but something like rate limiting would only be necessary if we're being flooded with spam accounts and submissions.

**Comment by xmatthewx** [comment]
Alrighty. That view (Declined) isn't all the spam. There's more in Pending. But, agreed, we can hold off on captcha or rate limiting for now. If we see repeat offenders, banning would be good too. I'll close this for now.
