### ISSUE TITLE
Building entry types and email login for MozFest

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#1026]
**TODO:** Individual tickets to be filed and linked here

### Email login

**Backend**
  1. Add username/password login to pulse using django-allauth
     - Use bcrypt as the hashing algorithm
     - Salt passwords individually
     - Only allow Google auth access to the admin interface (and superusers)
     - NICE TO HAVE: cooldowns between failed logins and resets
  2. Enforce IP rate limit on the login form

### Entry Types

**Backend**
1. [Create these models](https://docs.google.com/presentation/d/1Oo0VSVokfAMLbNc8TR9-o4y5_YRBKeFSO_dQH07tP64/edit) (names - TBD, along with plugging in moderation)
2. Enable the following routes ("scope" will be based on the data model chosen):
   - `GET /scope/:id/proposals/form` - Get a form with all the question fields
   - `POST /scope/:id/proposals` - Add a new submission
   - `GET /scope/:id/proposals/:id` - Get a submission (without PII)
   - `GET /scope/:id/proposals` - Get all submissions for a form
       - Without PII
       - MozFest-specific for Zapier: I will add a permission to allow PII via authZ using an API key
3. Subtle changes:
   - Make the description in `Entry` a `TextField` instead of a `CharField`
   - Make `content_url` optional for initiatives
4. Configure the admin to easily create a form

**Frontend**
1. Create `/initiatives/:id/add` (route TBD) - Asks a user to login if they aren’t. Hits the `GET /scope/:id/proposals/form` API and renders the result as a form. Submit posts to `/scope/:id/proposals`.
2. Create `/initiatives/:id` (route TBD) - Shows all the proposals along with their moderation state.
3. Modify `/entry/:id` for proposals to show the non-PII data appropriately.

**Nice to have**
1. Moderator view for specific initiatives

### Editable Entry Types

**Backend**
1. `PUT /scope/:id/proposals/:id` - Update a submission

**Frontend** (UX TBD based on designer input)
1. Add a section to `/profile/:id` to show list of proposals submitted (can also just be part of published entries if that’s easier)
2. Add a button to `/entries/:id` if it was submitted by the user to edit their submission
3. Show pre-filled form with their submission and hit the `PUT` route to update.

**Comment by Pomax** [comment]
Do we have concrete issues that items can point at?

**Comment by gideonthomas** [comment]
Sorry, I'm gonna close this: let's work from this ticket - https://github.com/mozilla/network-pulse/issues/1030
