### ISSUE TITLE
Add IP rate limiting for login

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#1028]
Enforce IP rate limiting for the login view - primarily for email/password login (depends on https://github.com/mozilla/network-pulse/issues/1027).

We could use django-ratelimit to do so.

cc @cadecairos @patjouk

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
