### ISSUE TITLE
Review Pulse for SEO and sharing improvements

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1033]
No code to write for this ticket. But let's take a look at Pulse and identify small enhancements to improve SEO and sharing. I noticed that profiles don't wrap the person's name with an H1 tag. There might be other things we can identify now, before we do a little UI refresh to align with foundation site. It might be all good besides the h1, I haven't really dug around.

**Comment by xmatthewx** [comment]
- [ ] Add OG title, thumb, description tags for home, tag list, entries and profiles
 - [ ] Add description meta tag for home, tag list, entry, profile
 - [ ] Add H1 on user's name in profile view

**Comment by mmmavis** [comment]
Thanks for adding the list. I probably won't have time to take a stab at this ticket anytime soon 😬
