### ISSUE TITLE
Add a 'featured' flag

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1035]
Create a 'featured' tag. Text is custom/ one-off: Body-small (bold) in uppercase with .7px letter-spacing.

Featured symbol
<img width="616" alt="Screen Shot 2019-04-24 at 7 31 13 PM" src="https://user-images.githubusercontent.com/14876567/56705858-92dd1c00-66c7-11e9-9f45-0072885344cf.png">

Featured example
<img width="733" alt="Screen Shot 2019-04-24 at 7 31 26 PM" src="https://user-images.githubusercontent.com/14876567/56705868-9b355700-66c7-11e9-8190-0fcfb60a50b3.png">

The svg star icon is here:
[Star-icon.svg.zip](https://github.com/mozilla/network-pulse/files/3114855/Star-icon.svg.zip)

cc @xmatthewx @alanmoo @gideonthomas @mmmavis @youriwims

**Comment by natalieworth** [comment]
Redpen for reference: https://redpen.io/p/uk95e2dc951b414a1d

**Comment by youriwims** [comment]
Where would be a good starting point for this? @alanmoo @gideonthomas @mmmavis

**Comment by alanmoo** [comment]
Every Pulse entry seems to have a "featured" property. Seems like the ask here is to apply that banner to the card if `featured==true`, so an update to the React component that generates the card is in order.

While this will result in every card on the current homepage having the flag, I think that's ok and we can re-evaluate what we display on first page load in the future if later updates don't address that.

**Comment by youriwims** [comment]
Sounds good—thanks for that explanation!

**Comment by youriwims** [comment]
@natalieworth should the featured flag still be on the thumbnail once the user clicks for a more detailed view of the entry? ...this view ➡️ https://redpen.io/ht84cc12654cc53ce8

**Comment by natalieworth** [comment]
> @natalieworth should the featured flag still be on the thumbnail once the user clicks for a more detailed view of the entry? ...this view ➡️ https://redpen.io/ht84cc12654cc53ce8

I think we could just leave the featured on the homepage cards.

**Comment by natalieworth** [comment]
Also exported another svg of the updated star icon:
[star icon.svg.zip](https://github.com/mozilla/network-pulse/files/3175377/star.icon.svg.zip)
