### ISSUE TITLE
Update site footer

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1036]
Update/ apply the foundation.mozilla.org footer to the Pulse site.

<img width="741" alt="Screen Shot 2019-04-24 at 7 37 02 PM" src="https://user-images.githubusercontent.com/14876567/56706058-5fe75800-66c8-11e9-8112-57ccd6f469b8.png">
<img width="275" alt="Screen Shot 2019-04-24 at 7 37 14 PM" src="https://user-images.githubusercontent.com/14876567/56706062-6249b200-66c8-11e9-871b-34095fe0b554.png">

cc @xmatthewx @mmmavis @youriwims @alanmoo @gideonthomas

**Comment by gideonthomas** [comment]
for awareness during implementation: https://github.com/mozilla/foundation.mozilla.org/issues/3060

**Comment by xmatthewx** [comment]
- [ ] link to foundation.mozilla.org, not mozilla.org in the footer. Both the visible link and the logo.

**Comment by mmmavis** [comment]
@xmatthewx @alanmoo can we land this in 2 stages? Pulse doesn't have a newsletter sign up component yet. To reduce implementation & PR review complexity I'm hoping we can 1) land all non-form elements in first 2) implement sign up component & add it to the footer.

**Comment by alanmoo** [comment]
Makes sense to me.

**Comment by youriwims** [comment]
@xmatthewx which link should we use for the donate link in the Pulse footer? https://github.com/mozilla/network-pulse/pull/1054#discussion_r283459053

**Comment by alanmoo** [comment]
Likely this: https://donate.mozilla.org/?utm_source=mozillapulse.org&utm_medium=referral&utm_content=footer

**Comment by youriwims** [comment]
Awesome, thanks!
