### ISSUE TITLE
Update ‘View more’ button

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1037]
Changing the 'View more' button to be in line with the updated brand styling: .btn-secondary

<img width="708" alt="Screen Shot 2019-04-24 at 7 42 17 PM" src="https://user-images.githubusercontent.com/14876567/56706242-177c6a00-66c9-11e9-90c8-54c1477511a9.png">
<img width="357" alt="Screen Shot 2019-04-24 at 7 42 06 PM" src="https://user-images.githubusercontent.com/14876567/56706244-19462d80-66c9-11e9-8e80-9b8b7a938ebe.png">

cc @mmmavis @youriwims

**Comment by youriwims** [comment]
@natalieworth should I increase the spacing below the 'View More' button to match your designs or are we doing a [separate ticket for all space fixes](https://github.com/mozilla/network-pulse/pull/1048#issuecomment-488803745)?
