### ISSUE TITLE
Style standardization

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1038]
From the [redpen mockups](https://redpen.io/p/vqdf0d6fb857181a19) it seems like we borrowed quite a few of styles from [Foundation site](http://foundation.mozilla.org/style-guide/). Before updating individual component's styling on Pulse (e.g., nav, footer, buttons, links etc), we should have style standardization in place first.

@natalieworth can you give a complete list of what we should include on Pulse's "style guide"?

For example,

- Colours? (Do we copy the entire colour variable set from Foundation site?)
- Typography?
- Link style?
- Button style?
- anything else?

/cc @youriwims

**Comment by natalieworth** [comment]
@mmmavis Are you thinking we should build out a page for a Pulse Style Guide too. Is that helpful for implementation? I was originally thinking we could use all the Foundation Styles (in terms of type, colors, links, etc.) I did do some overrides on type (since not all the styles worked) though, but otherwise it's using the styles for the Foundation site (since we wanted the design to be the same styles for user experience when navigating between the foundation site and pulse).

**Comment by mmmavis** [comment]
@natalieworth we don't need a web page to showcase Pulse's style guide. You mentioned there are some overrides on type & I noticed link behaviours are different than what we have on Foundation site. Can you list out these kinds of overrides here? It would be super helpful for devs to know. 👍

**Comment by natalieworth** [comment]
Awesome! thanks @mmmavis I'm just working on finishing the Mobile versions, and will post any Pulse style overrides here for desktop/ mobile.

**Comment by mmmavis** [comment]
@natalieworth awesome! Thank you!

**Comment by natalieworth** [comment]
Hey @mmmavis @youriwims , the designs that are in redpen (and in Sketch) are ready for implementation.
The desktop and mobile [mockups are in Redpen here](https://redpen.io/p/uk95e2dc951b414a1d).

Additionally, these files are in the Pulse Sketch document under the "Pulse Comps" page in the left menu. The document shares/ has the same Style Guide library linked to it as the Foundation site—but I will create annotations for the styles that have been overridden in the Pulse UI.

<img width="417" alt="Screen Shot 2019-04-29 at 5 13 20 PM" src="https://user-images.githubusercontent.com/14876567/56934845-a7902a00-6aa2-11e9-9809-bdd3d0587e11.png">

All pages ready for implementation are labelled at the top:
<img width="1049" alt="Screen Shot 2019-04-29 at 5 13 42 PM" src="https://user-images.githubusercontent.com/14876567/56934881-d0182400-6aa2-11e9-97f5-2dc23aeac3ef.png">
<img width="399" alt="Screen Shot 2019-04-29 at 5 13 56 PM" src="https://user-images.githubusercontent.com/14876567/56934882-d0182400-6aa2-11e9-83ef-9d127b8eb267.png">

**Comment by natalieworth** [comment]
I made a temporary style guide with all the styles coming from the Style Guide document we used for the Foundation site. It's in the Sketch file pages under "Style Guide"

<img width="967" alt="Screen Shot 2019-04-29 at 7 15 34 PM" src="https://user-images.githubusercontent.com/14876567/56937760-5dfc0b00-6ab3-11e9-96c7-ea0c3a8f1699.png">

<img width="1067" alt="Screen Shot 2019-04-29 at 7 13 13 PM" src="https://user-images.githubusercontent.com/14876567/56937768-694f3680-6ab3-11e9-8a46-0741c1693cb7.png">

**Comment by youriwims** [comment]
@natalieworth, can we add also add the 'headings with links' style rules for pulse as well? Use case [here](https://github.com/mozilla/network-pulse/issues/1034). Then, can you push the pulse override styles u to abstract when you get a chance, please? Thx! :)
