### ISSUE TITLE
Update Nav: Add button and other styles

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1039]
_Note: Nav update and Search component (#1041) are dependent and should ship together._

Remove the current navigation and update with the new button:

Signed out view
<img width="842" alt="Screen Shot 2019-04-26 at 12 30 07 AM" src="https://user-images.githubusercontent.com/14876567/56791019-e8debc00-67ba-11e9-940f-9cdd4eb9822b.png">

Signed in view (with account icon added if it's possible)
<img width="746" alt="Screen Shot 2019-04-26 at 12 30 29 AM" src="https://user-images.githubusercontent.com/14876567/56790999-e0868100-67ba-11e9-9afe-cc331983c2ba.png">

@youriwims adding the nav 'x', search, and profile icons here for when you update the navigation based on #1074 

[medium-icons.zip](https://github.com/mozilla/network-pulse/files/3234713/medium-icons.zip)
![58532058-4474de80-8199-11e9-9136-65cccbe7897b](https://user-images.githubusercontent.com/14876567/58596172-e8a56680-8227-11e9-9c04-359e98df74b5.png)

**Comment by natalieworth** [comment]
[account-icon.svg.zip](https://github.com/mozilla/network-pulse/files/3120198/account-icon.svg.zip)

**Comment by AdityaSrivast** [comment]
@natalieworth I would like to work on this issue. Can I take it up?

**Comment by natalieworth** [comment]
Putting a hold on this issue as we still have to flush out some of the menu UX for mobile

**Comment by natalieworth** [comment]
@xmatthewx Just noting here, that I think we still may need some navigation for mobile so users can access their account? I've mocked this up and included some suggestions in the 'signed in' menu view: https://redpen.io/p/gc34eb3beb2157b54e

<img width="664" alt="Screen Shot 2019-04-29 at 7 32 33 PM 1" src="https://user-images.githubusercontent.com/14876567/56938269-c64bec00-6ab5-11e9-8a65-b5a0a82610f0.png">

**Comment by xmatthewx** [comment]
Yes. Pulse does currently have nav drawer on mobile. Your revised UI looks good. For items, let's just do Profile, Edit profile, Favs, Signout. (I like how you provided some shortcuts.)

**Comment by natalieworth** [comment]
Mobile menu's have been updated for this/ unblocking.

Signed out view https://redpen.io/xsf5b7302d480d9b5d
Signed in view https://redpen.io/pb2fcfb9e1a16cc0c3

**Comment by youriwims** [comment]
@natalieworth are there any active states for the mobile nav like the live pulse mobile nav? Or should I just be doing regular dark-theme anchor styles?

**Comment by natalieworth** [comment]
@youriwims let's stick to the dark-theme anchor styles
