### ISSUE TITLE
Update tagline styling

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1040]
Update the "Discover & ..." tagline area to H2 and the 'Learn More' link:

<img width="825" alt="Screen Shot 2019-04-26 at 12 35 38 AM" src="https://user-images.githubusercontent.com/14876567/56791200-52f76100-67bb-11e9-82d9-54dcbc1b9305.png">

**Comment by youriwims** [comment]
Closed by #1048
