### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1041]
Add search bar on the Pulse homepage:

<img width="461" alt="Screen Shot 2019-04-26 at 12 37 34 AM" src="https://user-images.githubusercontent.com/14876567/56791328-a8cc0900-67bb-11e9-96ea-bbd9f2968511.png">
 
deselected: https://redpen.io/me2f04acc0db359ad8
selected: https://redpen.io/bva1fe4804f5d7fa33

search icon: 
[search-icon.svg.zip](https://github.com/mozilla/network-pulse/files/3120212/search-icon.svg.zip)

## Mobile View ([redpen](https://redpen.io/sba2f6394078cece61))
<img width="306" alt="Screen Shot 2019-04-26 at 12 40 09 AM" src="https://user-images.githubusercontent.com/14876567/56791410-dca72e80-67bb-11e9-8853-5a855af11d04.png">
<img width="364" alt="Screen Shot 2019-04-26 at 12 41 02 AM" src="https://user-images.githubusercontent.com/14876567/56791473-fcd6ed80-67bb-11e9-877e-3f2a6c452e1c.png">

**Comment by natalieworth** [comment]
search icon: 
[search-icon.svg.zip](https://github.com/mozilla/network-pulse/files/3120212/search-icon.svg.zip)

**Comment by natalieworth** [comment]
*blocked : I still want to add mobile views for how this should function.

**Comment by natalieworth** [comment]
<img width="306" alt="Screen Shot 2019-04-26 at 12 40 09 AM" src="https://user-images.githubusercontent.com/14876567/56791410-dca72e80-67bb-11e9-8853-5a855af11d04.png">
<img width="364" alt="Screen Shot 2019-04-26 at 12 41 02 AM" src="https://user-images.githubusercontent.com/14876567/56791473-fcd6ed80-67bb-11e9-877e-3f2a6c452e1c.png">

**Comment by alanmoo** [comment]
Make sure that the URL still updates when using this component, as it does on the current search pages.

**Comment by alanmoo** [comment]
Presumably, at the same time as landing this we should remove the "search" link from the nav, correct?

**Comment by xmatthewx** [comment]
Yes: Nav update (https://github.com/mozilla/network-pulse/issues/1039) and Search component are dependent and should ship together.

**Comment by xmatthewx** [comment]
Note: below search area, results will still show tabs for People and Projects as currently built. And as shown in the comp called "selected" at the top of this ticket.

**Comment by youriwims** [comment]
@natalieworth just an fyi, moderation is sharing styles with this search component...not sure how this ties into overall design, just thought I'd let you know :) For now I'll just update the home search bar in this ticket. 
![Screen Shot 2019-06-10 at 4 51 40 PM](https://user-images.githubusercontent.com/36484608/59226116-4cbd1880-8ba0-11e9-930f-d509b50ab1a6.png)

**Comment by xmatthewx** [comment]
as long as it doesn't totally break, it's okay if moderation gets funky, since it's just internal.

**Comment by natalieworth** [comment]
Hey @youriwims So we are going to keep the existing search functionality that is live on the search section of the sight (where it filters are the user types). On the homepage, the 'people'projects' tabs will display as soon as the user begins typing (but once search is cleared or a help topic is selected, the tags will disappear again.

**Comment by youriwims** [comment]
Okay, thanks for the update @natalieworth!
