### ISSUE TITLE
Add a help dropdown

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1042]
The 'help' drop down will include all of the topics that people are able to volunteer/ help with in Pulse (note that I've included 'help' as an additional/ the original (default) for people to view everything):
Help
Attend
Create content
Code
Design
Fundraise
Join community
Localize & translate
Mentor
Plan & organize
Promote
Take Action
Test & feedback
Write documentation

**Comment by natalieworth** [comment]
<img width="699" alt="Screen Shot 2019-04-26 at 12 44 11 AM" src="https://user-images.githubusercontent.com/14876567/56791735-a6b67a00-67bc-11e9-8145-fd963f80f7af.png">
<img width="698" alt="Screen Shot 2019-04-26 at 12 44 18 AM" src="https://user-images.githubusercontent.com/14876567/56791738-a8803d80-67bc-11e9-8b58-6d593b475d80.png">
<img width="698" alt="Screen Shot 2019-04-26 at 12 44 32 AM" src="https://user-images.githubusercontent.com/14876567/56791741-aae29780-67bc-11e9-8972-f38989942a34.png">

**Comment by natalieworth** [comment]
<img width="260" alt="Screen Shot 2019-04-26 at 12 43 38 AM" src="https://user-images.githubusercontent.com/14876567/56791752-b46bff80-67bc-11e9-9c7c-f7d0e11e87b0.png">
<img width="260" alt="Screen Shot 2019-04-26 at 12 43 46 AM" src="https://user-images.githubusercontent.com/14876567/56791755-b59d2c80-67bc-11e9-8635-8745b5c7d7fb.png">
<img width="261" alt="Screen Shot 2019-04-26 at 12 43 53 AM" src="https://user-images.githubusercontent.com/14876567/56791764-b930b380-67bc-11e9-8461-47e0e70b8789.png">

**Comment by alanmoo** [comment]
We should pull the list from `{api}/api/pulse/v2/helptypes/` to be consistent.

**Comment by xmatthewx** [comment]
On this main list view, a user can search, pick a help cat, or tap a trending tag. All of these actions should clear each other, or not, depending. For example, if a user is viewing a search of foo, and then they tap a tending tag, search should clear. When a user selects a Help category, Nat and I are fine if it clears the search or further filters it, as long as UI updated appropriately. Combined filtering would be great, BUT only if it's trivial to build. I prefer the simplest path to shipping this. We can always enhance later.

**Comment by alanmoo** [comment]
@youriwims if you get to this today, try and start just making the component which fetched the available help categories- I don’t expect you to finish it today but it would be good if it’s at a reasonable break point before you’re at the conference next week.

**Comment by youriwims** [comment]
@natalieworth should this dropdown be similar to the multi-page mobile nav dropdown on the foundation site i.e. Initiatives page at mobile?

**Comment by natalieworth** [comment]
@youriwims In terms of visuals, I want the Foundation one to eventually be updated to match the Pulse style. So, new Pulse style is okay if it's different. I included the scroll too since the menu is pretty long/ to indicate that there is more content below. Let me know if anything's still confusing though or if it's a nightmare to implement a new style. I'm hoping to create a brand ticket in future to update the foundation site dropdown style too—but need to wait til we have more time.

**Comment by youriwims** [comment]
Okay, cool. Thanks for clarifying!

**Comment by xmatthewx** [comment]
Nice stuff. Let's be extra careful with testing on mobile, making sure users can scroll (inside the drop-down and outside on the page) without trouble.

**Comment by alanmoo** [comment]
For that reason, among others, this feels to me like it might be better suited as a `select` element. But it’s a bit more challenging to consistently style them across browsers. Are we ok with a progressive enhancement approach here, where browsers that don’t support styling simply get a standard select element?

**Comment by natalieworth** [comment]
> For that reason, among others, this feels to me like it might be better suited as a `select` element. But it’s a bit more challenging to consistently style them across browsers. Are we ok with a progressive enhancement approach here, where browsers that don’t support styling simply get a standard select element?

Sure!

**Comment by natalieworth** [comment]
@alanmoo Is there a good example somewhere? How differing would they be?

**Comment by alanmoo** [comment]
Roughly (with the arrow needing to change still), we can do this:
https://codepen.io/anon/pen/XwgmQg
Note the open state is the browser default behavior, so it is nice and functional/accessible on mobile and desktop.
