### ISSUE TITLE
Update styles of profile view in Pulse

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1043]
Update the various views of the Pulse profile.

 - [x] Use an h1 tag for profile name. 

<img width="628" alt="Screen Shot 2019-04-29 at 7 23 49 PM" src="https://user-images.githubusercontent.com/14876567/56938008-8fc1a180-6ab4-11e9-8782-8a5439fae261.png">
<img width="629" alt="Screen Shot 2019-04-29 at 7 24 05 PM" src="https://user-images.githubusercontent.com/14876567/56938009-8fc1a180-6ab4-11e9-8878-a9e723a0eb56.png">
<img width="628" alt="Screen Shot 2019-04-29 at 7 24 13 PM" src="https://user-images.githubusercontent.com/14876567/56938010-8fc1a180-6ab4-11e9-8803-464fefe21001.png">
<img width="628" alt="Screen Shot 2019-04-29 at 7 24 24 PM" src="https://user-images.githubusercontent.com/14876567/56938011-8fc1a180-6ab4-11e9-9196-7f5f2bd51c59.png">
<img width="628" alt="Screen Shot 2019-04-29 at 7 24 37 PM" src="https://user-images.githubusercontent.com/14876567/56938012-8fc1a180-6ab4-11e9-9dac-14d01d2c38d1.png">
<img width="782" alt="Screen Shot 2019-04-29 at 7 24 54 PM" src="https://user-images.githubusercontent.com/14876567/56938013-8fc1a180-6ab4-11e9-8475-5ebb9618b134.png">

For reference, pages 7-11 https://redpen.io/cd1b2adfe1242640a1
Mobile, pages 7-8 https://redpen.io/yw42647ed38b9e34d9

cc @mmmavis @youriwims @alanmoo @xmatthewx

**Comment by alanmoo** [comment]
I’m not sure what the current workflow is but this feels like it could use some amount of annotations/specs so we make sure to use the right general styles. @mmmavis @kristinashu what’s the current best practice for that?

**Comment by xmatthewx** [comment]
Hi @alanmoo. See https://github.com/mozilla/network-pulse/issues/1038#issuecomment-487802829

**Comment by xmatthewx** [comment]
For SEO purposes, it's best if we wrap profile name with an `h1` tag. I'm not sure if that will require some CSS gymnastics. I added a checklist item to the initial comment above.

**Comment by natalieworth** [comment]
Hey @youriwims here are the world and locator icons:
[Icons.zip](https://github.com/mozilla/network-pulse/files/3209588/Icons.zip)

**Comment by natalieworth** [comment]
https://redpen.io/hn85d3f9ffc9a6257a

**Comment by youriwims** [comment]
Closing since it looks like #1066 took care of this.

**Comment by youriwims** [comment]
Actually, @natalieworth can you confirm if we need this ticket open still? #1066 took care of majority of the profile about updates and then #1084 is taking care of the Hint message (https://github.com/mozilla/network-pulse/pull/1084#issuecomment-497417550) styles. Is there something else in this ticket that needs to be done that isn't/haven't being taken care of elsewhere?

**Comment by natalieworth** [comment]
I think it's good to close @youriwims! Thanks for checking
