### ISSUE TITLE
Update fallback image on Pulse

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1044]
- Change our stand in image (when a user doesn't upload a profile photo/ photos)
- Crop to square 1:1 (instead of circle):

File is here for 1:1, 4:3, and 16:9 ratios: 
[Standin Images.zip](https://github.com/mozilla/network-pulse/files/3129809/Standin.Images.zip)

![1-to-1-ratio](https://user-images.githubusercontent.com/14876567/56938887-96064c80-6ab9-11e9-995e-f4e1775b0819.png)
![4-to-3-ratio](https://user-images.githubusercontent.com/14876567/56938889-96064c80-6ab9-11e9-95af-dc061ac6cfd6.png)
![16-to-9-ratio](https://user-images.githubusercontent.com/14876567/56938890-96064c80-6ab9-11e9-9ff5-c9f0ad95923c.png)

cc @mmmavis @youriwims @alanmoo @xmatthewx

**Comment by alanmoo** [comment]
Should we use this for entries too?

**Comment by alanmoo** [comment]
Also, in some of the comps I've seen this as a blue image instead of gray. Is there a specific use case for that?

**Comment by natalieworth** [comment]
> Should we use this for entries too?

@alanmoo yep

**Comment by natalieworth** [comment]
> Also, in some of the comps I've seen this as a blue image instead of gray. Is there a specific use case for that?

Blue image I was representing as a 'filled in profile' but we'll go with the gray as the fallback, so we can ignore the blue image.
