### ISSUE TITLE
Ability to search by profile ID on admin interface

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/network-pulse#1046]
**Feature Request:**
Would it be possible to add the ability to search by ID on the User Profiles page of the admin interface?

**Comment by xmatthewx** [comment]
If I understand your case correctly, we have a way for you to get there without search. In the pulse admin, you can just use the ID in the url to jump to a profile. For example, view any profile in the pulse admin and then replace the numbers with the ID you want to see: `.../userprofile/12345/`. Does that solve your issue?

**Comment by marcwalsh** [comment]
Yeah that works for me thanks for getting back so quickly!

My use case was more when I’m searching through the profiles sections that I have their ID but occasionally their display names can be different than we have on file. So the workaround with the link is perfect for that.
