### ISSUE TITLE
Remove "prototype" ribbon

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#105]
@xmatthewx @kristinashu 

We used to have a "prototype" ribbon displayed on the screen. Do we want to keep it? Note that that ribbon is currently hidden on https://mozilla.github.io/network-pulse/

**Comment by kristinashu** [comment]
I do see it for a second on the splash screen but I'd say we get rid of it completely.

**Comment by mmmavis** [comment]
Oh yea, it only appears on the splash screen. 

Cool, I'll remove the ribbon!
