### ISSUE TITLE
Make pulse use prettier like Foundation site

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#1052]
https://github.com/mozilla/foundation.mozilla.org/blob/master/.stylelintrc

**Comment by mmmavis** [comment]
ESLint is now using prettier. It raises "warnings" for now as we have ~1000 issues to be fixed and it's easier and less risky if we do it bits by bits. 

Once all issues have been addressed we should change the severity in https://github.com/mozilla/network-pulse/blob/master/.eslintrc.json#L19-L20 to `error`.
