### ISSUE TITLE
Iterate on Profile types and categories

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1055]
Pulse profiles currently include an admin feature to identify a person's role and relationship to the foundation. Something like `{ profile_type: fellow, program_type: policy, year: 1999  }`.

As built, a profile can have zero or 1 of each attribute. And, year is not tied to type to the program. 

In reality, people shift roles and often engage with more than one program. 

Thoughts below. Warning, they require more thinking from you, and you...

We could shift to something like this: 

```
{ roles: [ staff, fellow ],
  programs: [
     { program: mozfest wrangler, year: 2012 },
     { program: mozfest speaker, year: 2019 },
     { program: fellow, year: 2025}
] }
``` 

 - I think we can insist on year: YYYY rather than strings. 
 - If someone wrangles mozfest twice, they could either have 2 program entries or 2 years attached to one program entry. No opinion here, but admin UX should probably drive the choice. 
 - I considered dates on roles, but that begs for start and end dates which require maintenance likely to fail. Probably easier to remove or role or include `staff emeritus` as a role option if people want that.

**Comment by gideonthomas** [comment]
Issues tracked in the api repo.

- [ ] [Build models](https://github.com/mozilla/network-pulse-api/issues/491)
- [ ] [Create API](https://github.com/mozilla/network-pulse-api/issues/493)

**Comment by cadecairos** [comment]
@xmatthewx iceboxing this, we can revive it later when it's a priority. Gideon says the project is recorded on airtable.

**Comment by jamilasnell** [comment]
Maybe once someone needs it, we can recreate this ticket. Until then, closing this issue until we decide to work on pulse again
