### ISSUE TITLE
Variable/Mixins cleanup

### ISSUE THREAD

**Issue by youriwims** [mozilla/network-pulse#1057]
Related PR #1049 
[Comment Reference](https://github.com/mozilla/network-pulse/pull/1049#discussion_r282940651)

In order to remove `$btn-border-radius`, we need to see where it is used and update those values.

**Comment by youriwims** [comment]
@natalieworth can you confirm if all of the buttons need to have a `0` `border-radius` now? If so, @mmmavis we can just remove all instances of `$btn-border-radius` right?

I'll update the ticket depending on what you both say :) 👍

**Comment by natalieworth** [comment]
@youriwims I'll talk to designers and mavis in office tomorrow about this. I'm not 100% sure about the radius yet.

**Comment by youriwims** [comment]
almost forgot about this...any update?

**Comment by AdityaSrivast** [comment]
@youriwims can I take up this issue?

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
