### ISSUE TITLE
Update style of pulse entry forms

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1059]
Need to update the Pulse page forms for the 'profile' and 'entry' pages:

Desktop:
https://redpen.io/ede8cba6116ad234e2
https://redpen.io/xhd5029bc3a098fdcc

Mobile:
https://redpen.io/cmd2fe6c2b0d8b4b3e
https://redpen.io/uvd52362e1ecc9003a

cc @youriwims @mmmavis Let me know if you need any more guidance for these. All files are in Sketch.

@gideonthomas @xmatthewx

**Comment by youriwims** [comment]
@natalieworth can you update the links in the initial comment to the specific design? 3/4 links go to the general RedPen Pulse UI Updates with all designs.

**Comment by natalieworth** [comment]
updated these @youriwims

**Comment by youriwims** [comment]
<img width="86" alt="Screen Shot 2019-07-09 at 3 35 48 PM" src="https://user-images.githubusercontent.com/36484608/60917585-4f726280-a25f-11e9-956a-f26f41268163.png">

@natalieworth  should both of the last two sections be titled 'Optional Details' or Optional Details' & 'Get Help' respectively?

**Comment by natalieworth** [comment]
@youriwims Lol, yes all your answers are good

**Comment by youriwims** [comment]
Lol what? @natalieworth I think you're supposed to be viewing this comment ➡️  https://github.com/mozilla/network-pulse/pull/1115#issuecomment-516457041
