### ISSUE TITLE
Add location option for bio entry form (for all users)

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1060]
Currently, only extended profiles are able to input their location in the Pulse profile forms. We want to add the location option for all users:

https://redpen.io/cz1829cfbe090505f9

<img width="803" alt="Screen Shot 2019-05-13 at 4 21 37 PM" src="https://user-images.githubusercontent.com/14876567/57660388-3d47b100-759b-11e9-8e00-0b22df1bf986.png">

cc @youriwims @mmmavis @alanmoo @gideonthomas @xmatthewx

**Comment by alanmoo** [comment]
Do you have an example profile? (Don’t post the email here, but profile link is fine).

My personal email seems to work as expected (profile 31)
![IMG_0020](https://user-images.githubusercontent.com/1682681/57701585-4f246500-762a-11e9-8d15-5f33c82977b0.png)
![IMG_0021](https://user-images.githubusercontent.com/1682681/57701597-5481af80-762a-11e9-9a3c-74d8cf7f6c34.png)

**Comment by xmatthewx** [comment]
Nat might have been filing from list in Google doc before fix landed. Nat, take a look at production and edit your profile. Is the field there?

**Comment by natalieworth** [comment]
@xmatthewx @youriwims @alanmoo Oh yes! I can see it there now!

**Comment by natalieworth** [comment]
Going to close as it appears for all profiles now.
