### ISSUE TITLE
Update 'About' profile section

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1061]
Update the 'about' profile section (and reduce the content width on desktop):
https://redpen.io/uz608a0947739eff3d
https://redpen.io/jh76a350b472a56c9e

<img width="967" alt="Screen Shot 2019-05-13 at 4 58 06 PM" src="https://user-images.githubusercontent.com/14876567/57661633-8e0dd880-75a0-11e9-9efb-7bcb3cea3d26.png">

cc @mmmavis @youriwims @alanmoo @xmatthewx @gideonthomas

**Comment by youriwims** [comment]
Where can I find the _About_ section? I'm logged into mozillapulse.org and don't see an _About_ tab there or in local dev.

**Comment by natalieworth** [comment]
> ~Where can I find the _About_ section?~ How can I replicate this state to see the _About_ tab? I'm logged into mozillapulse.org and don't see an _About_ tab there or in local dev.

@alanmoo @xmatthewx Do you know how to get the 'full profile' option for Youri?

**Comment by alanmoo** [comment]
@youriwims I enabled extended information on your profile.

**Comment by youriwims** [comment]
@natalieworth just want to clarify that I'm just updating these items in the _About_ panel:

1. Update tab text
<img width="315" alt="Screen Shot 2019-05-14 at 4 14 56 PM" src="https://user-images.githubusercontent.com/36484608/57729142-73506800-7663-11e9-9f7a-22ef48252852.png">
 ( would require updating all the tabs fonts for uniformity)
2.  Decreasing body text content width
3. Update tab underline color 
4. Ensure body text (headings, paragraph, links) line up with Abstract specs

These are the only changes I can see, let me know if I missed anything. Thanks!

**Comment by natalieworth** [comment]
@youriwims I think if it's possible, we could just copy the styling from the Foundation site menu. I used the same font/ weights. I think the only different is I removed the full-width rule underneath the menu:
<img width="1201" alt="Screen Shot 2019-05-14 at 5 21 03 PM" src="https://user-images.githubusercontent.com/14876567/57740418-af3bfb00-766c-11e9-89c1-ffaaf27fb516.png">

**Comment by xmatthewx** [comment]
Related to #1043

**Comment by youriwims** [comment]
Sorry @natalieworth, I didn't realize you followed up on the underline here. But, the underline on the foundation site is `6px` and this is what that would look like:
![Screenshot_2019-05-22 YouriYouriYouriYouri - Mozilla Network Pulse](https://user-images.githubusercontent.com/36484608/58185397-00f21000-7c81-11e9-8416-9036958990a7.png)

I think it looks a bit heavy, but let me know what you think and I can update it. Here's a comparison to what's currently on the app, `3px`
![Screenshot_2019-05-22 YouriYouriYouriYouri - Mozilla Network Pulse(1)](https://user-images.githubusercontent.com/36484608/58185464-21ba6580-7c81-11e9-9688-89d6deedb442.png)

**Comment by natalieworth** [comment]
@youriwims The 3px is definitely better! thanks.

For the location/ website on one line. I've got it on separate lines in the redpen:
https://redpen.io/uz608a0947739eff3d

Should I create a ticket for those changes?

**Comment by youriwims** [comment]
I thought #1043 was for the profile personal information update(above the line)? 😬 🙃 If not, yes, please create a ticket for that 🙏 ty!
