### ISSUE TITLE
Add sign-up section to footer

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1063]
Continuing the work from #1054 — adding the sign-up component to the footer to match the foundation.mozilla.org site.

cc @youriwims @mmmavis

**Comment by youriwims** [comment]
Blocked by https://github.com/mozilla/network-pulse-api/issues/496.

**Comment by mmmavis** [comment]
@xmatthewx do we wanna attach any GA event tracking to action(s) happening in this newsletter signup form? Looks like on Foundation site we track two things

```jsx
ReactGA.event({
    category: `signup`,
    action: `form submit tap`,
    label: `Signup submitted`
});
```

and 

```jsx
ReactGA.event({
    category: `signup`,
    action: `form focus`,
    label: `Signup form input focused`
});
```

**Comment by mmmavis** [comment]
Got okay from @xmatthewx on Slack. Will use the code snippet above.

**Comment by mmmavis** [comment]
Note that newsletter sign up form on footer will only show for logged in users.
