### ISSUE TITLE
Make sure font files are properly loaded

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1071]
Using https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/templates/pages/base.html#L9-L11 as a guide, update [server.js](https://github.com/mozilla/network-pulse/blob/master/server.js#L40) to make sure font files are properly loaded. (note: we might need to whitelist that domain)

**Comment by alanmoo** [comment]
It looks like Nunito Sans never gets loaded into the site, which causes issues if you don't have it installed locally.
