### ISSUE TITLE
Update icons on Pulse site with new iconography

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1074]
[extra-small-icons.zip](https://github.com/mozilla/network-pulse/files/3231020/extra-small-icons.zip)
### Final design + redpen link
Final design is here (and updated in the Sketch file):
https://redpen.io/p/wp17e9f94b044da4a0

On Pulse site:
- [x] Update 'down chevron arrow' on the 'help' drop down
- [ ] Update 'x' close/ cancel icon
- [x] Update the heart 'fav' icon
- [ ] Update search icon
- [ ] Add a profile icon beside the user name/ signup area

Desktop:
![02_Landing-page Copy@2x](https://user-images.githubusercontent.com/14876567/58532058-4474de80-8199-11e9-9136-65cccbe7897b.png)
![05_People-Search@2x](https://user-images.githubusercontent.com/14876567/58534812-1f846980-81a1-11e9-82c5-e848e0b85d5a.png)

Mobile:
![M  02_Landing-page Copy](https://user-images.githubusercontent.com/14876567/58532680-24461f00-819b-11e9-8a1f-a935b44851ac.png)
![M  Menu (signed out) Copy](https://user-images.githubusercontent.com/14876567/58532682-24deb580-819b-11e9-872d-ee4f4d5272b6.png)
![M  05_People-Search](https://user-images.githubusercontent.com/14876567/58534801-15fb0180-81a1-11e9-84e8-19d4fc8affcf.png)

------

### Original design ticket + related tickets
#2890 

------

### Assets
**Medium assets are here (chevron, close, heart, profile, and search icons)**
[medium-icons.zip](https://github.com/mozilla/network-pulse/files/3218878/Join.Page.Icons.zip)

**Extra small assets are here (linkedin, twitter, location icon)**
[extra-small-icons.zip](https://github.com/mozilla/network-pulse/files/3231023/extra-small-icons.zip)

----------

### Hover states
No hover on **chevron icon**
No hover on **'x' close/ cancel icon**
**Heart icons** are `$red` on save (no hover function)
Hover state of dark-blue #0d10bf for the **profile icon**
No hover on **search icon**

cc @youriwims @mmmavis @alanmoo @xmatthewx

**Comment by mmmavis** [comment]
We should be able to clean up some SCSS overrides for the icons (especially around positioning) as the new icons are all in the same square size.

**Comment by youriwims** [comment]
@natalieworth sorry if this is overkill, but can you outline in the initial comment where exactly these icons should be updated?...just so there's a list of where these icons need to be updated &/or  replaced.

**Comment by natalieworth** [comment]
> @natalieworth sorry if this is overkill, but can you outline in the initial comment where exactly these icons should be updated?...just so there's a list of where these icons need to be updated &/or replaced.

Hey @youriwims Definitely! I'll add to the top of this ticket

**Comment by youriwims** [comment]
@natalieworth are the social icons on the profile cards supposed to be x-small now? I think those icons are fine at small dimensions (16x16 on desktop & mobile) and can follow the original design. 

In #1066 I decreased the size of the icons to follow your design, but had some issues with icon legibility & mobile functionality due to the original 11x11 dimensions ([see comment](https://github.com/mozilla/network-pulse/pull/1066#discussion_r287403475)) which is why I increased those to 16x16 at mobile and 14x14 at desktop.

Let me know what you think 💭

**Comment by natalieworth** [comment]
@youriwims that'd be awesome I think! thanks for catching that. I'll have to document in our brand standards.

**Comment by natalieworth** [comment]
@youriwims sorry, sabrina said 16px is good for both mobile and desktop.

**Comment by youriwims** [comment]
Okay, so I'll leave them as is. Thanks for clarifying!

**Comment by natalieworth** [comment]
@youriwims Or should I re-export them? I think I exported them at 12px so they're too small. Or are you able to make them 16px code-wise :D

**Comment by youriwims** [comment]
haha yeah no worries, I can do it via code—thanks for checking though 😊

**Comment by youriwims** [comment]
@natalieworth should the heart icon on save be `$red` or `$dark-red`?

**Comment by natalieworth** [comment]
> haha yeah no worries, ~I can do it via code~ they're actually already 16x16 at both mobile & desktop—thanks for checking though 😊

Do you think they still look too small at 16px? I can review with Sabrina again tomorrow if they're still too small?

**Comment by natalieworth** [comment]
I also moved the 'x', search, and profile icons to the nav ticket #1039 (so feel free to close this ticket later if you don't need it anymore). @youriwims

**Comment by youriwims** [comment]
Perfect, thanks so much!

**Comment by youriwims** [comment]
Closing this since these updates will be made on the component they belong to. See initial comment for more details.
