### ISSUE TITLE
Update 'projects/ favs' section styling in profile view

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1078]
Need to update the 'projects/ favs' section underneath the profile overview page.

Current styling:
<img width="1138" alt="Screen Shot 2019-05-27 at 3 09 41 PM" src="https://user-images.githubusercontent.com/14876567/58440779-81ee4480-8091-11e9-9f53-d9f014d53f3a.png">

Updates:
<img width="1156" alt="Screen Shot 2019-05-27 at 3 08 56 PM" src="https://user-images.githubusercontent.com/14876567/58440785-8a467f80-8091-11e9-9d45-b0e9bb8922dd.png">
<img width="1140" alt="Screen Shot 2019-05-27 at 3 09 04 PM" src="https://user-images.githubusercontent.com/14876567/58440786-8a467f80-8091-11e9-9ad4-84dc0654d4c5.png">

cc @youriwims @mmmavis @alanmoo

**Comment by youriwims** [comment]
@natalieworth  should the smaller text have the `.h4-heading` styles brought over from the foundation-site or the ones in the Pulse style guide? The only difference is the line-height atm. If we should be following the Pulse style guide that you created, I can open a separate ticket to make sure our styles match that.

Super sorry I didn't notice the differences between the Pulse & Foundation-site style guide earlier 😬

**Comment by natalieworth** [comment]
> @natalieworth should the smaller text have the `.h4-heading` styles brought over from the foundation-site or the ones in the Pulse style guide? The only difference is the line-height atm. If we should be following the Pulse style guide that you created, I can open a separate ticket to make sure our styles match that.
> 
> Super sorry I didn't notice the differences between the Pulse & Foundation-site style guide earlier 😬

@youriwims No worries! We are working on updating the Foundation branding so the line-height is 1.25 across everything for h4's. So, h4 line-height should be 1.25 on Pulse

**Comment by youriwims** [comment]
Thanks for letting me know, I'll update that now :)
