### ISSUE TITLE
Update Pulse Entry page

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1079]
This is now unblocked.

@natalieworth @alanmoo @youriwims @mmmavis

**Comment by natalieworth** [comment]
Design has been finalized and approved for this ticket. 
**Desktop is here:**
https://redpen.io/zw3d9fad50ec628d2b

**Mobile is here:**
https://redpen.io/xpaad30985723f1669

Comps have also been updated and added to Sketch.

There were 2 new icons (that I based on Becca's blog designs) created for this that I have added in this file:
[Circle-blog-icons.zip](https://github.com/mozilla/network-pulse/files/3234652/Circle-blog-icons.zip)

cc @youriwims @mmmavis Let me know if you need anything else for these.

**Comment by mmmavis** [comment]
@natalieworth some projects don't have thumbnail (like https://www.mozillapulse.org/entry/1186). Do we have a different layout design for those projects or we are fine with just using the same [gradient image](https://pulse.mofostaging.net/assets/placeholder-thumbnail.png) as the fallback.

**Comment by natalieworth** [comment]
@mmmavis I'll update a default image with new colors

**Comment by natalieworth** [comment]
![placeholder-thumbnail-2019](https://user-images.githubusercontent.com/14876567/58597008-fd372e00-822a-11e9-8c37-df7cbf41ff16.png)

**Comment by natalieworth** [comment]
oh @mmmavis Do you need it in 4:3 size? I was using previous size that the old image was using?

**Comment by mmmavis** [comment]
@natalieworth we could also draw gradient in CSS but that might complicate the work for this ticket further. @youriwims you can decide how you wanna implement this and work with Nat to get the asset/specs you need.

**Comment by youriwims** [comment]
@mmmavis do you think it'd be better to do this in CSS?...or it doesn't really matter? I don't mind doing CSS, but if it doesn't provide any specific advantage and is just more complicated _just because_ , then I'll just swap out the images. Let me know what you think.

**Comment by mmmavis** [comment]
@natalieworth can you clarify mobile and desktop specs for the project image section? 

- Is there a particular aspect ratio we want to force image to be in?
- Dimension? Fixed? Or scale responsively?
- What to do for oversized image? Do we make it appear cropped so it shows up the right size we want? Or?
- What to do for undersized image? Do we scale it up? Or?

**Comment by natalieworth** [comment]
@youriwims ah sorry for delay, 
1) aspect ratio of 4:3
2) I think ideally, scale responsively. But what do you think would be best. Mobile gets a bit different but do you think this would be best for Tablet too (I can mockup the tablet version if you need): https://redpen.io/zw3d9fad50ec628d2b
3) For oversized images, let's crop so it remains in our aspect ratio
4) Undersized, let's scale it up so it maintains ratio. (I know some images will look bad, but maybe down the road in future we can do some sort of error in the form for images that are too small)
5) I think the 4:3 image will be fixed, but the banner on the right with the title/ buttons can stay centered depending on the title length if that makes sense.

Let me know if you have any questions or I can also always hop on a call.

**Comment by natalieworth** [comment]
@youriwims Hmm I can't access abstract, I think the ratio I was using was the 4:3, but if you are able to access it—can you double check. Thanks

**Comment by natalieworth** [comment]
Okay, updated my Abstract at ration is 4:3 :)

**Comment by youriwims** [comment]
>     1. aspect ratio of 4:3
> 
>     2. I think ideally, scale responsively. But what do you think would be best. Mobile gets a bit different but do you think this would be best for Tablet too (I can mockup the tablet version if you need): https://redpen.io/zw3d9fad50ec628d2b
> 
>     3. For oversized images, let's crop so it remains in our aspect ratio
> 
>     4. Undersized, let's scale it up so it maintains ratio. (I know some images will look bad, but maybe down the road in future we can do some sort of error in the form for images that are too small)
> 
>     5. I think the 4:3 image will be fixed, but the banner on the right with the title/ buttons can stay centered depending on the title length if that makes sense.
> 
> 
> Let me know if you have any questions or I can also always hop on a call.

@natalieworth I don't have any questions just yet. Let me review this comment and the designs I'll get back to you :)

**Comment by youriwims** [comment]
See this [comment](https://github.com/mozilla/network-pulse/pull/1103#discussion_r299605036) for external link button styling.

**Comment by mmmavis** [comment]
@natalieworth just so it's clear for everyone, can you make sure you have comps for desktop, tablet, and mobile 😉 ? I just checked the Sketch file and it seems like we only have desktop mockup available.

**Comment by youriwims** [comment]
@natalieworth  should the hover states for the social icons be `$dark-blue`? Also, where should the _Get Involved_ button link to?

**Comment by natalieworth** [comment]
@mmmavis Not sure if you're working on this/ have time, but added a tablet version for this in the redpen here: https://redpen.io/aj26c37c5b1a34d276 and have updated in Abstract.

**Comment by natalieworth** [comment]
> @natalieworth should the hover states for the social icons be `$dark-blue`? Also, should the _Get Involved_ button not appear if no link is present (just wanted to double check)? I noticed that the font-weight for the issues and tags changed between the mobile and desktop version. Should it be light or normal?
> 
> p.s. Sorry about so many questions.Every time I have one, i just keep adding to this comment haha

No worries about questions @youriwims ! They are all good. Hover states can be the $dark-blue for icons. 

1. I added hover states here: https://redpen.io/gy264cd0af466a87f4
Icons are here: 
[Large Icons Entry Page.zip](https://github.com/mozilla/network-pulse/files/3400560/Large.Icons.Entry.Page.zip)

2. Yes, let's remove the get involved button and just have the visit if no link is present.

3. Let's use our body-large (light) for the desktop/tablet, and then just body (normal) for mobile.

cc @mmmavis
