### ISSUE TITLE
Close button hidden by form

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#108]
When a user taps the +add project button, a form displays. That button should remain visible as the button to close the form and return to the items.

**Comment by mmmavis** [comment]
@kristinashu need design help here 😉 mind creating a mockup?

**Comment by kristinashu** [comment]
I like how it was in the original pulse. The "+" just rotated into a "x". The circle stays in the same position and size.

**Comment by mmmavis** [comment]
Can't recall what we used to have. I'll check out the old code and see.
