### ISSUE TITLE
Review GA Events for new UI 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1083]
Currently in Pulse, we track a few user events. Let's see if there's any we should drop or add considering the new UI. 

For example, it could be good to track whether users open the Help selector. 

[Spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=1060389854) has most current events, but might not be totally up to date.

Let's discuss @natalieworth

**Comment by Pomax** [comment]
closing as stale
