### ISSUE TITLE
Update h4 line-height

### ISSUE THREAD

**Issue by youriwims** [mozilla/network-pulse#1087]
Update `h4` & `.h4-heading` line-height to 1.25 at desktop & 1.28 at mobile.
References:
https://github.com/MozillaFoundation/Design/issues/357
https://github.com/mozilla/foundation.mozilla.org/issues/3270

**Comment by AdityaSrivast** [comment]
@youriwims I would like to work on this issue. Can I take it up? 
The link in the reference seems broken.

**Comment by youriwims** [comment]
Sure @AdityaSrivast! If you have some time today or tomorrow to complete this, that'd be awesome. The links should be working now. For this you're going to need to go into `./scss/overrides/_type.scss` and remove the related `h4` & `.h4-heading` styles. Then go into `./scss/foundation-styles/type.scss` to updatesitewide `h4` & `.h4-heading` styles. Feel free to let me know if you need any more guidance.
