### ISSUE TITLE
Add trending terms below search input on search page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1088]
This might help: https://github.com/mozilla/network-pulse/pull/1082/files#diff-bb08841264ceb7df9943840db8dfcfcd

Add trending terms below search input on search page/the new homepage.

@xmatthewx can you add other specs here with a list of hard coded trending terms we wanna show? Thanks!

Redpen to new homepage design: https://redpen.io/to2f6e295db54e0ed5 (please ping Nat if we need to come up with an interim design until the new homepage is built).

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
