### ISSUE TITLE
Update sign-in/ sign-up page

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1089]
Just adding/ creating the design to dev hand-off since this is a bit more robust (and we are adding the error states for the sign-up/ sign-ins).

Update the sign-in/ sign-up page on the Pulse site.

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket
- [x] Link to Redpen
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included
- [x] Hover state for elements are designed
- [x] Other states for elements are designed (e.g., error state for form)

----
All designs are finalized/ in the Sketch file and updated in Abstract. *Note that the content/ wording has changed slightly too. Buttons on this page remain the same though. Background gradient has been removed.
----
### Design Ticket
Original design ticket is here: https://github.com/mozilla/network-pulse/issues/1014

----
### Redpen:
Sign-in desktop: https://redpen.io/co71c4924aeb51d4ff
Sign-in Mobile: https://redpen.io/wc813ff07c8f0c5c07
Full UI update ticket here: https://redpen.io/p/uk95e2dc951b414a1d

----
### Error States for Pulse API login styles
Error States/ edge case designs are here:
Desktop: https://redpen.io/xe1fc447832206153f
Mobile: https://redpen.io/ufd7208dcaf8ee75f2

I have only designed one, but the 3 versions of these can follow the Redpen styling in terms of the heading and body copy. (Using H4 for the heading and body (normal) for the body copy sizing.)

The versions of these can be found here:
https://drive.google.com/drive/folders/1_kMe7k0IVMvaIYOOVcuaL3m9vEl5lVK3

----
### Notes
@youriwims As a fix for now, we also will need to change the copy and add the 'Privacy Notice' copy seen here:
https://redpen.io/co71c4924aeb51d4ff

Let me know/ ping me if there are any more questions for these :)

cc @youriwims @mmmavis

**Comment by mmmavis** [comment]
@natalieworth since this is a big ticket and not a tiny UI update, can you use the `Design to Dev Handoff` issue template to re-create this ticket so the ticket is more descriptive and has context? As far as I know we don't have a sign in / sign up page that lives on Pulse front end so I'm not sure which page you are referring to here. 👀

**Comment by mmmavis** [comment]
Did you mean the page that shows up after you click on "Signup / Signin" link to top right corner of the site? Like this page below?
https://api.mozillapulse.org/accounts/login/?next=https%3A%2F%2Fwww.mozillapulse.org%2Ffeatured
![Screenshot_2019-06-03 Sign in to Pulse](https://user-images.githubusercontent.com/2896608/58837960-f9801e80-8611-11e9-92d2-89e0355eee68.png)

**Comment by natalieworth** [comment]
@mmmavis yea! that's the one I meant. did you want me to still do the design to dev handoff/ checklist for it though? I'm not sure how much work it is dev-wise, so I only made little ticket for it, but I can definitely update.

**Comment by youriwims** [comment]
@natalieworth the buttons on your design look different. Can you clarify if we should update or keep them the same? Also, I think the checklist will help :)

**Comment by mmmavis** [comment]
> Did you want me to still do the design to dev handoff/ checklist for it though? I'm not sure how much work it is dev-wise, so I only made little ticket for it, but I can definitely update.

Hey @natalieworth , ideally we want to always utilize the handoff issue template unless it's a super simple task like copy changes or a small UI bug (include link to the page you are talking about in the ticket would be awesome ✨ ). That way we can avoid back and forth design-dev chat just to figure out the specs. I know filling out that template feels tedious (I really get it!) but a detailed ticket really helps get everyone on the same page easily as the ticket is self explanatory 😉 .

**Comment by natalieworth** [comment]
Thanks @mmmavis I totally don't mind tedious! We have a brand one too that we based it off of and it helps ALOT!

**Comment by youriwims** [comment]
Closed via #503
