### ISSUE TITLE
Remove outline on search field

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#109]
When the search field has focus, the browser displays an outline that's rather unattractive. Best to remove. 

@kristinashu - I'm not sure if we need to show that it's active. Is the cursor alone is enough?

**Comment by kristinashu** [comment]
It doesn't need any extra focus to happen so we should remove the outline.

Outline doesn't appear in FF (looks good) but does in Safari and Chrome.

Screen cap in Safari
<img width="1051" alt="screen shot 2016-08-05 at 9 37 56 am" src="https://cloud.githubusercontent.com/assets/1068783/17445192/8d108b50-5af8-11e6-82a6-3dedb3683b39.png">
