### ISSUE TITLE
Join Us Page modal

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1092]
We will be creating a 'Join Us' page to onboard future (potential) fellows and mozilla community members with our email list and the Pulse site. Users will access the page through the ['join us' page](https://redpen.io/yg8a9572ea97403818) (on the [foundation/ cms site](https://foundation.mozilla.org/cms/pages/396/edit/)) where they will be taken to the ['sign-up' page ](https://redpen.io/whd4aa98717b56cd84)and then the modal walkthru on Pulse. 

Design has been approved and designs are updated in Abstract/ Sketch file.

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket
- [x] Link to Redpen
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included
- [x] Hover state for elements are designed
- [x] Other states for elements are designed (e.g., error state for form)

----

### Original design/ related tickets:
Design ticket for Join page: https://github.com/mozilla/foundation.mozilla.org/issues/2890
Join Us landing page implementation ticket on CMS: https://github.com/mozilla/foundation.mozilla.org/issues/3147

----

### Final designs are in [Redpen](https://redpen.io/p/wp17e9f94b044da4a0) ticket:
**Desktop:** https://redpen.io/whd4aa98717b56cd84
**Mobile:** https://redpen.io/vwc2a6d249220ef50f

----

### Assets:
**New icon of 'x/ close' icon for the modal:**
[close-icon.svg.zip](https://github.com/mozilla/network-pulse/files/3249758/close-icon.svg.zip)

**Profile image placeholder:**
[profile-image (blank).svg.zip](https://github.com/mozilla/network-pulse/files/3249796/profile-image.blank.svg.zip)

----

### Hover states
_Hover states follow the brand guidelines for the Foundation site button styles_
***The **exception** is the **['select image' button](https://redpen.io/ad71776d67900eef56)** has a hover state of  # B7B9FA

----

### Error states
**Modal form error states:**
Desktop: https://redpen.io/by1eb9d156ea6942e2
Mobile: https://redpen.io/tqf62683d4b9f88ce4

**Profile form error state:**
Desktop: https://redpen.io/axd7f6cad43d9d71cb
Mobile: https://redpen.io/mqfbef1094ad9785b3

----

### Active states
On active state/ while user is clicking or typing into form, form color becomes $light-blue.
Example: https://redpen.io/nv67185acce14948c3

cc @youriwims @mmmavis @alanmoo @xmatthewx

**Comment by youriwims** [comment]
Nice descriptive ticket @natalieworth ! 🙌 💖

**Comment by mmmavis** [comment]
@xmatthewx @gideonthomas this is the screen that we need to update content for: https://redpen.io/zc4501db50f552fcbe

**Comment by gideonthomas** [comment]
TODO: push to prod and wire up with fo'mo

**Comment by gideonthomas** [comment]
Done: https://foundation.mozilla.org/en/join
