### ISSUE TITLE
Set min width on Cards

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#110]
In a narrow browser, the three columns squish to fit, disrupting content inside the card (see below). Buttons and titles get funky. 

Instead, let's maintain the width and switch to two columns. The two columns should probably remain centered. cc @kristinashu 

<img width="617" alt="screenshot 2016-08-05 00 21 18" src="https://cloud.githubusercontent.com/assets/53411/17426174/3cf9eab2-5aa3-11e6-8dd4-b9984774cc15.png">

**Comment by mmmavis** [comment]
we can adjust the breakpoint - currently for screens that are wider than `600px` we have 3-column layout and single column layout otherwise.

**Comment by xmatthewx** [comment]
With flex on the container, I don't think you need to worry about a break point. Things can flow and center automatically.

**Comment by mmmavis** [comment]
Agree but there's `margin` we need to worry about. Margin should only be presented in between cards. I guess we can set min-width for cards and make the container `align-conent: space-between`?

**Comment by mmmavis** [comment]
`justify-content: space-between` doesn't work :( see the huge gap in rows that are not full. So yea I think we still need help from break point checks.

<img width="492" alt="screen shot 2016-08-05 at 4 40 05 pm" src="https://cloud.githubusercontent.com/assets/2896608/17453096/71edd228-5b2b-11e6-91e1-5196835bf74b.png">
