### ISSUE TITLE
Note: Pulse join follow up

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1105]
After launching new join flow, we will likely want to follow up and hook it up for all new pulse users, not just people coming via the foundation site. 

@natalieworth - do think a user on pulse who hits join at the top should immediately get the modals? or should they see the value prop page?

cc @gideonthomas b/c he has a great memory for work that might otherwise be forgotten

**Comment by alanmoo** [comment]
@xmatthewx How do we close this ticket? By coming to a design decision and generating an implementation ticket?

**Comment by gideonthomas** [comment]
@alanmoo yes! @natalieworth to weigh in

**Comment by xmatthewx** [comment]
@mmmavis - do all new pulse users now get the new join flow? or is just for people who come from the /join link on foundation site?

**Comment by mmmavis** [comment]
Not everyone. The modal shows only when users visit Pulse with query param `edit_new_profile=true` (e.g., https://www.mozillapulse.org/?edit_new_profile=true).

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
