### ISSUE TITLE
app.json is missing env vars that are necessary for our bundle build step

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#1108]
https://github.com/mozilla/network-pulse/blob/master/app.json currently only has one environment variable set, and seems to be missing the `APP_HOST`, `PULSE_API_HOST`, `PULSE_LOGIN_URL`, and `PULSE_LOGOUT_URL` values, with review apps ending up building a bundle that has `undefined` in its JS where an env var value would have been expected.

Can we safely add these env vars, set to various pulse.mofostaging.net urls, or will that also cause staging/prod pushes to overwrite their env vars on deployments?

/cc @mmmavis @patjouk

**Comment by patjouk** [comment]
If you want the review apps to inherit some of the staging apps env var, you can use this in the app.json:
```
    "ENV_VAR_NAME": {
      "required": true
    },
```
It will only affect the review apps.

**Comment by Pomax** [comment]
closing for now, we've not run into it in a while.
