### ISSUE TITLE
Load new on item submit

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#111]
I'm working on a PR that covers a bulk of major updates - including spliting groups of projects into tabs/pages. Question: how should auto refresh work? Currently the one-page app fetches data every min and will load new projects into UI automatically. Do we wanna do similar things for the upcoming version as well? Does auto refresh keep user on the current tab/page or we want to switch them to the latest projects tab after auto refresh has happened?

/cc @xmatthewx @kristinashu

**Comment by kristinashu** [comment]
Users should only see new content after they have navigated to a new tab, refresh the page, or if they click on a post and then return back to the tab. Jumping someone to Latest or loading a new post on the page automatically will be jarring to a user.

**Comment by mmmavis** [comment]
agree! 👏

**Comment by xmatthewx** [comment]
I disagree in terms of engagement. But... if we refresh like @kristinashu suggests, I'm cool with that. 
 - On tab switch
 - Initiate search

During Mozfest or a global sprint, it would be exciting to see things as they pop in. Let's file a ticket to design a notice/link to display new projects when they're found.

**Comment by xmatthewx** [comment]
For now, let's disable auto refresh as discussed.

**Comment by kristinashu** [comment]
@xmatthewx so this ticket is now for 'Load new on Tab switch.' Do you still want me to mockup an alert?

**Comment by xmatthewx** [comment]
@kristinashu – we can file a new bug for that. Not critical.

**Comment by kristinashu** [comment]
Added https://github.com/mozilla/network-pulse/issues/155

**Comment by xmatthewx** [comment]
Moving to backlog of current milestone. 

To summarize the idea: check for and load new projects when a 
 - switches tabs
 - closes the Add New form (to see what you've submitted)

**Comment by xmatthewx** [comment]
This feels a bit important. I often think that my submission has failed. First, I don't see it. Then, I hit refresh. I still don't see it though, because now I'm on the Featured tab. This could disrupt our pilot test.

**Comment by mmmavis** [comment]
I'll work on this today.

**Comment by mmmavis** [comment]
Question: 

When users 
- switches tabs
- closes the Add New form (to see what you've submitted)

1) Are we reloading all existing projects to makes sure their info is up to date PLUS loading new projects?  Or 2) are we just loading new projects and keep existing projects as they are?

Regardless if it's option 1 or 2 we are choosing... as fetching data from Google Spreadsheet and displaying projects on the app might not be instant (depends on the internet connection and response time), we probably need to display some sort of loading messages. Any design suggestion @xmatthewx @kristinashu ?

**Comment by mmmavis** [comment]
One way to do it is to remember where user was and trigger a page refresh (so after the refresh she/he can land on the view she/he was on). `Open "add new project form" -> close form -> page refresh -> show splash page -> user land on the tab she/he was on before opening the form`. This flow seems okay to me but if we want to do the same every time users switch tab it seems a bit overkill to me... but maybe it's just cuz I tend to switch tabs way too often 😁 . Thoughts?

**Comment by xmatthewx** [comment]
Let's just focus on the UX bug following a submission. We can worry about tabs and search later.

Here's a proposal:

1. User taps Add new
1. User taps to Close form
1. Pulse then...
  - A) ~~Trigger browser refresh~~ – I'm worried google sheets won't be ready to return the item yet. I also don't like showing the splash screen again.
  - B) Fetch data in background after short delay. Update data in collection, but don't change display. 
1. User taps search or changes tab
1. Items display as expected, including new submission

With this approach (fetch data but don't change display), anyone looking for their item will find it soon. But we avoid the UX and code complexity of managing and changing views. 

As an added benefit, we could run this update every 10 minutes if we set this up as kiosk at Mozfest. New items would appear as people nav and search.

What do you think @mmmavis @kristinashu?

**Comment by mmmavis** [comment]
hey @xmatthewx 

> 1. User taps Add new
2. User taps to Close form
3. Pulse then...
  - Fetch data in background after short delay. Update data in collection, but don't change display. 
4. User taps search or changes tab
5. Items display as expected, including new submission

This approach sounds great ✨ . Let's get this update in first. We can file another ticket for auto refresh.

**Comment by xmatthewx** [comment]
@mmmavis – looks like this might be ready for staging. if so, feel free to hit me up for QA after it lands.
