### ISSUE TITLE
Moderation needs to be updated

### ISSUE THREAD

**Issue by youriwims** [mozilla/network-pulse#1116]
**Describe the bug**
Moderation was left behind in all the UI refresh fun 🤡 

**To Reproduce**
Visit https://www.mozillapulse.org/moderation

**Expected behavior**
Components should follow updated styling as documented in the [UI Refresh](https://github.com/mozilla/network-pulse/projects/10)

**Screenshots**
![Screenshot_2019-07-16 Mozilla Network Pulse](https://user-images.githubusercontent.com/36484608/61336920-3fc7c080-a801-11e9-9319-8c010f3aaa30.png)

//cc @mmmavis  @alanmoo @natalieworth @xmatthewx

**Comment by xmatthewx** [comment]
Good catch. Moderation can be ugly, as long as it's functional.
