### ISSUE TITLE
Add the 'X' back to the search to clear results

### ISSUE THREAD

**Issue by natalieworth** [mozilla/network-pulse#1117]
Just making a note to add the 'x' clear functionality back to mobile as a P2 when Youri returns.

cc @youriwims @mmmavis @alanmoo

**Comment by mmmavis** [comment]
@natalieworth can you provide comp and the 'x' icon file? I can't recall how Pulse used to look like 😂

**Comment by mmmavis** [comment]
For simplicity and consistency, wondering if we should do this for all screen sizes / devices other than just mobile?

/cc @alanmoo (context: the Search component doesn't know what screen size / device it's on. If we wanna target this just for mobile we'll have to write extra JS and logic to detect container size / device type to conditionally display the `x` control)

**Comment by xmatthewx** [comment]
is it a bad practice to display or not with css based on screensize?

**Comment by mmmavis** [comment]
I wouldn't say it's bad practice since it's usually case by case + how the component was set up initially. I will know more once I see the comps. Also by "mobile" do we mean when the page is displayed on viewport under 768px wide? Or on a mobile device?

**Comment by alanmoo** [comment]
> is it a bad practice to display or not with css based on screensize?

It can be kind of arbitrary. You could have a narrow desktop window when trying to view a site side-by-side, or a big tablet.

**Comment by natalieworth** [comment]
@mmmavis Sorry for delay. The previous version of pulse had the 'x' icon across all screen sizes:
<img width="1219" alt="Screen Shot 2019-07-25 at 2 45 55 PM" src="https://user-images.githubusercontent.com/14876567/61985510-64205b80-afbe-11e9-9e83-b2e92c772c32.png">

I'm okay with maintaining that functionality. 


----


### Assets
I have added the 'x' icon asset for this here:
[clear-x-icon.zip](https://github.com/mozilla/network-pulse/files/3437580/clear-x-icon.zip)

----

### Designs

Design for desktop is here:
https://redpen.io/efddc1be56ae5ffb13

Design for mobile is here:
https://redpen.io/ta03a3b0cb3d17d4bf


Let me know if you have any questions @mmmavis or I can also hop on a call to go over the functionality if it doesn't make sense. I'll also be in next week too depending on your schedule.

cc @youriwims @alanmoo

**Comment by youriwims** [comment]
@natalieworth should the 'x' icon be black when when search isn't active?

**Comment by natalieworth** [comment]
@youriwims ya, thanks

**Comment by mmmavis** [comment]
@natalieworth reminder to update Sketch file 😉

**Comment by mmmavis** [comment]
PR got merged. Closing.
