### ISSUE TITLE
Newsletter sign up to call Basket directly (both for anonymous + authenticated users)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1118]
Front end ticket: this one
Back end ticket: https://github.com/mozilla/network-pulse-api/issues/530 (blocked on front end work)

---

(Follow-up for PR https://github.com/mozilla/network-pulse/pull/1111)

Currently, `/signup` route on Pulse API requires CSRF token. However, CSRF token can only be returned via the `/api/pulse/nonce` route (```{nonce: "...", csrfmiddlewaretoken: "..." }```) which only works for logged in users. How should we handle CSRF so people can subscribe to newsletter without logging in?

/cc @gideonthomas @Pomax @alanmoo 

### Screenshots from our discussion on Slack yesterday

<img width="437" alt="image" src="https://user-images.githubusercontent.com/2896608/61745459-78f6b800-ad4e-11e9-8f5d-9dd6a2438b17.png">
<img width="429" alt="image" src="https://user-images.githubusercontent.com/2896608/61745737-0afec080-ad4f-11e9-847a-3663124bd267.png">
<img width="436" alt="image" src="https://user-images.githubusercontent.com/2896608/61745777-1e119080-ad4f-11e9-9973-96c5fe8cebd8.png">
<img width="436" alt="image" src="https://user-images.githubusercontent.com/2896608/61745816-32ee2400-ad4f-11e9-8804-50e01ca61ca9.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/2896608/61745841-3bdef580-ad4f-11e9-8799-e6548d22dd73.png">

**Comment by alanmoo** [comment]
As discussed in our meeting the other morning, we should make requests directly to basket from the client, negating the need to deal with CSRF.

**Comment by gideonthomas** [comment]
Do this ^ for authenticated users as well

**Comment by Pomax** [comment]
+ remove the signup route from the network pulse API repo

**Comment by Pomax** [comment]
Handy docs: https://readthedocs.org/projects/basket/

**Comment by mmmavis** [comment]
API work is tracked separately on https://github.com/mozilla/network-pulse-api/issues/530

**Comment by mmmavis** [comment]
> API work is tracked separately on mozilla/network-pulse-api#530

Front end work is live now production. Closing.
