### ISSUE TITLE
Make Percy work on Pulse

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1121]
Let's get some Percy tests written.

Routes:
* Homepage
* Entry page (`/entries/#`)
* Add entry page, if possible (since it's behind auth this might be more problematic)
* Moderation page, if possible (same as above)

**Comment by mmmavis** [comment]
blocked on having fake data in place

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
