### ISSUE TITLE
Main content needs more space

### ISSUE THREAD

**Issue by youriwims** [mozilla/network-pulse#1122]
**Describe the bug**
The footer is overlapping main content [when a user is signed in and out] at mobile. Then, at desktop there's a lack of space between main content and footer.

**To Reproduce**
1. Visit any page on [staging](https://pulse.mofostaging.net/)
2. Scroll down to the footer
4. See either overlapping content _OR_ lack of space between main content + footer

**Expected behavior**
No footer overlap and at least 48px between footer + main content.

**Screenshots**
<img width="322" alt="Screen Shot 2019-07-30 at 6 59 34 PM" src="https://user-images.githubusercontent.com/36484608/62171562-5c81ef00-b2fd-11e9-99d8-4148dc9aa69a.png">
<img width="1440" alt="Screen Shot 2019-07-30 at 7 06 23 PM" src="https://user-images.githubusercontent.com/36484608/62171531-2f354100-b2fd-11e9-9be0-d0e002fdbd74.png">

cc: @mmmavis

**Comment by youriwims** [comment]
@mmmavis we're currently getting space between footer & main container from a padding-bottom on `div#main`. Do we want to keep using that approach or do we have other options? Because every time the footer is updated, `div#main` will need to be updated as well 😕

**Comment by youriwims** [comment]
@alanmoo any ideas?

**Comment by alanmoo** [comment]
I'm wondering why the footer is `position: absolute`. My only guess is it's because we want to avoid having white background appear below it if the page isn't rendered yet, but we could probably solve that by slapping a `min-height` on `#main` and then removing extraneous padding on the footer/main.

**Comment by youriwims** [comment]
Okay, cool. I'll try that.

**Comment by mmmavis** [comment]
> I'm wondering why the footer is `position: absolute`. 

Yea I can't recall why it was implemented that way 2-3 years ago 😂  But Alan's guess is probably right.
