### ISSUE TITLE
Unify dropdown style

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1129]
Unify style and clean up code for dropdowns on Pulse.

### Homepage

<img width="200" alt="image" src="https://user-images.githubusercontent.com/2896608/62399990-97209d00-b532-11e9-8ecd-1478ba925b28.png">

### Moderation Page

<img width="200" alt="image" src="https://user-images.githubusercontent.com/2896608/62400035-b7e8f280-b532-11e9-92f4-5f8c0dc0ce66.png">

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
