### ISSUE TITLE
Entry images not displayed on Chrome-Android 

### ISSUE THREAD

**Issue by youriwims** [mozilla/network-pulse#1135]
**Describe the bug**
Entry images aren't being displayed on Chrome-Android mobile.

**To Reproduce**
1. Go to mozillapulse.org in the chrome browser on an android mobile device.
2. Entry images aren't visible.

**Screenshots**
![Screenshot_20190814-165018_2](https://user-images.githubusercontent.com/36484608/63055859-caf5ae00-beb4-11e9-80e8-bab255e46f62.png)

**Smartphone:**
 - OS: Android 9
 - Browser: Chrome
 - Version: 76.0.3809.111

Additional Information: https://mozilla.slack.com/archives/C4EGUBY2Z/p1565803659018100?thread_ts=1565801706.016000&cid=C4EGUBY2Z

cc: @xmatthewx @alanmoo @natalieworth @mmmavis

**Comment by xmatthewx** [comment]
@alanmoo – Can we take a look at this during this sprint? It's about 17% of traffic on Pulse. Maybe it's a thing @patjouk could help assess?

**Comment by mmmavis** [comment]
I can't reproduce the bug on Chrome on iPhone. I'm seeing project image on both the list view and detailed view.

**Comment by youriwims** [comment]
It's only Android _as far as we can tell_ 😬

**Comment by mmmavis** [comment]
Ummm this is gonna be tricky to debug. Some discoveries so far... (will update list as I go)

| Working | OS | Chrome Version | Device  | Type         |   |   |
|---------|----|----------------|---------|--------------|---|---|
| y       | 9  | 69.0.3497.100  | Pixel 2 | emulator     |   |   |
| n       | 9  | 76.0.3809.111  | Pixel 2 | emulator     |   |   |
| y       | 9  | 76.0.3809.111  | Pixel 2 | actual phone |   |   |
| n       | 9  | 76.0.3809.111  | Pixel 3 | emulator     |   |   |

**Comment by mmmavis** [comment]
Spent some time looking up online but couldn't find any relevant that explained why. 

I would say the most straightforward and quickest fix would be removing the ` background-blend-mode: multiply` CSS rule from the project image. This will remove the light grey tint from the images but will fix the issue we are seeing on newer Android Chrome.

@xmatthewx thoughts? Here's a gif to demo what the images look like **with** (currently on prod, images appear slightly darker) and **without** the tint treatment.

![background-blend-off-2](https://user-images.githubusercontent.com/2896608/63453907-8612cf80-c3fe-11e9-9c78-5eada2776a74.gif)

**Comment by xmatthewx** [comment]
Excellent investigation @mmmavis. Wow, what a bug.  I propose that we:

a) file the chrome bug somewhere. or ask a friend in moco to do that. 
b) temporarily disable the blend, but leave it in there and bring it back when bug is fixed. 
c) ask @natalieworth if we should add a temporary super light border.

The blend was added because a lot of thumbs are on white backgrounds and they make the layout less crisp. Here's how that looks: 

<img width="792" alt="image" src="https://user-images.githubusercontent.com/53411/63463694-b1f87a00-c42b-11e9-9f56-9b719d2379d5.png">

**Comment by mmmavis** [comment]
@xmatthewx I filed a bug/report already but I'm not sure how to track it though as it didn't send me a confirmation email of some sort.

> ask @natalieworth if we should add a temporary super light border.

I'll work with Nat on this.

**Comment by mmmavis** [comment]
Googled a bit further and found this [Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=988948&q=background-blend-mode&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) that describes the issue. I'll keep an 👁 on it.

**Comment by mmmavis** [comment]
Talked to @natalieworth - we are gonna add `border: 1px solid #ccc` to project images on list view. I'll file a follow-up PR so we remember to add the grey tint back once Chrome fixes rendering bug.
