### ISSUE TITLE
Entry images are cropped

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#1139]
Images on the entry page, especially ones with text/wordmarks in them seem to be cropped. e.g. https://www.mozillapulse.org/entry/1327

Not sure if it's important to fix.

cc @xmatthewx and @kristinashu

**Comment by xmatthewx** [comment]
@natalieworth - take a look and decide how important this is to address. thanks!

**Comment by natalieworth** [comment]
@gideonthomas cropping is okay, but it seems to be sketching them. Is it possible to crop them without stretching them?

cc @xmatthewx @youriwims

**Comment by mmmavis** [comment]
Maybe this is something to do with the original image file that was uploaded? It looks a bit stretched to me even without any CSS treatments: https://assets.mofoprod.net/network-pulse/images/entries/2019-08-17_002155.3380840000.png

**Comment by natalieworth** [comment]
@mmmavis Yep! You're right. Thanks. Going to close this as I don't think it's an issue with the code/ the images look like they are cropping and not being stretched. I think it was just this one particular image :D
