### ISSUE TITLE
Enhance Homepage by promoting featured items

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1143]
Pulse entries can be "featured" by a moderator. Currently, this gives those items a flag over their thumbnail. To promote featured items further, and offer visitors the best first impression possible, we should put a few featured items at the top of any list view. 

@natalieworth - feel free to add your thoughts. and then hand over to @alanmoo to triage. 

I'm thinking: 
 - for any list view, display 3 featured items at the top. if it's not the home view,  match the query (home, help, tag, search).
 - below, list everything else. don't repeat the 3 items.

**Comment by xmatthewx** [comment]
Assigning to @alanmoo to triage.

**Comment by alanmoo** [comment]
This sounds like an enhancement to the component that renders a set of entries; Presumably something along the lines of running a filter for featured entries and relocating those to the front of the array of results.

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
