### ISSUE TITLE
Update deck based on interviews

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#115]
Update deck with feedback from interviews done in https://github.com/mozilla/network-pulse/issues/48

(Summary deck:
https://docs.google.com/document/d/1IUbYB56ZlwCand-R1TSdMNixatOPw207cQX1D1EBBL8/edit#heading=h.9vgek1udbh8u)

**Comment by acabunoc** [comment]
Let me know if you need me to clarify any of the notes! I know they're not the clearest...

**Comment by kristinashu** [comment]
Made a few minor updates to Value to Program Staff, Stakeholders, and Assets slides.
https://docs.google.com/presentation/d/15rBpuLWnNKJy6jG5PSP2dRkZWGwZ-YR_nuqEwnakRUA/edit#slide=id.gd58133b56_0_69
