### ISSUE TITLE
Add post date to entries in moderation view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#1153]
A request from @acabunoc, our moderator extraordinaire. This helps knowing whether an item is stale and overdue for action in the `pending` or `in progress` bucket.

**Comment by acabunoc** [comment]
thanks for filing this, @xmatthewx!

**Comment by sanchitgupta001** [comment]
Hi @xmatthewx , if anyone else does not work on this issue, can I try?

**Comment by gideonthomas** [comment]
Hi @sanchitgupta001. Unfortunately, this probably needs design first and we aren't ready to take on new contributions of this scale at this time. Sorry for the confusion.

**Comment by xmatthewx** [comment]
Sorry @sanchitgupta001 - I didn't realize that we couldn't support contributions at this time.

**Comment by xmatthewx** [comment]
Since this is just an internal moderation view, it doesn't need design. We can just use an existing paragraph style and stick the date above the description. 

<img width="553" alt="image" src="https://user-images.githubusercontent.com/53411/67099991-e9b24280-f18c-11e9-9e3c-7f7780b519fe.png">

**Comment by gideonthomas** [comment]
@sanchitgupta001 feel free to open a PR, however, as we are a small team, our support will be limited and don't have the capacity to walk through the process of spinning up the project, opening a PR or describing what the solution to the issue could be.

I have also updated our Contributing Guidelines accordingly -- https://github.com/mozilla/network-pulse#contribute

**Comment by mmmavis** [comment]
Hi @sanchitgupta001, is this still something you have interest working on?

**Comment by mmmavis** [comment]
I'm taking this over! 😉

**Comment by mmmavis** [comment]
PR got merged!
