### ISSUE TITLE
Make server error on "Add page" sit own its own line (mobile)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1157]
Follow-up for issue https://github.com/mozilla/network-pulse/issues/1140 and PR #1155

For mobile size screens, make the following change

## FROM

<img src="https://user-images.githubusercontent.com/2896608/68873941-4124cf00-06b5-11ea-86c1-f91c3d20c6ff.png" width=320>

## TO

<img src="https://user-images.githubusercontent.com/2896608/68874106-7f21f300-06b5-11ea-8fe8-2d97b09ce11e.png" width=320>

**Comment by AdityaSrivast** [comment]
@mmmavis I'm willing to work on this. Also there's a similar issue on "/myprofile" route.

![image](https://user-images.githubusercontent.com/31389740/69026714-fdea9900-09f1-11ea-920a-781e5cc13df2.png)

**Comment by Yashs911** [comment]
@mmmavis I would like to work on this issue.
