### ISSUE TITLE
Reduce number of global variables

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#117]

**Comment by xmatthewx** [comment]
@mmmavis – should we move this to the backlog of the current milestone or save it for if and when we do a bigger iteration?

**Comment by mmmavis** [comment]
Moving it to backlog and with no milestone assigned sounds great. Too many global variables problem is likely to go away as we Reactify the app.

**Comment by mmmavis** [comment]
this is totally v1 specific. closinnnnng it now!
