### ISSUE TITLE
Swap `optipng-bin` for `imagemin-optipng`

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1181]
As suggested by @pomax in https://github.com/mozilla/network-pulse/pull/1173#issuecomment-561422672, let's swap `optipng-bin` for `imagemin-optipng`

<img width="789" alt="Screen Shot 2019-12-03 at 4 42 08 PM" src="https://user-images.githubusercontent.com/177243/70102057-df88be00-15eb-11ea-8c94-3492f7b61164.png">

**Comment by Pomax** [comment]
After trying to switch to `imagemin`, it turns out that it cannot preserve dir structure, so I've filed https://github.com/imagemin/imagemin/issues/348 and this work is effectively blocked until they fix that.

**Comment by Pomax** [comment]
shelving until there's some sign that imagemin is actually maintained. We may have to move off of this entirely and go for a cross-platform png optimizer utility instead.

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
