### ISSUE TITLE
Replace `postinstall` with `heroku-postbuild`

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1191]
Follow-up for PR #1165. See [thread](https://github.com/mozilla/network-pulse/pull/1165/files#r351076602) for context.

@patjouk I set up `postinstall: npm run build` years ago when I started this project. I had it mainly for Heroku apps to run the build task so the site can be loaded properly (I guess I couldn't find a better way at the time?). In the PR above I split webpack configs into "production" version and "dev" version & change `postinstall` to `postinstall: npm run build:prod` so my PR doesn't break Heroku apps. However, we don't have devs to accidentally run the app in `production` mode just because they run `npm i` locally. Question: can we get rid of `postinstall` completely and use `heroku-postbuild` (or other heroku script) instead?

**Comment by cadecairos** [comment]
@mmmavis I think it's okay to make this change. In terms of the dev process, we'll need to update the README to include instructions to run `npm run build:dev`, since we want to drop the postinstall script.
