### ISSUE TITLE
Different types of artifacts we collect

### ISSUE THREAD

**Issue by acabunoc** [mozilla/network-pulse#12]
Write up the different types of artifacts (stories, projects, proposals) we collect. See if we can categorize them in a way that make sense considering the existing platforms for collecting projects/stories/etc.

**Comment by hannahkane** [comment]
I suggest we create a template for collecting this information. Template might include info like:
 - description of the kind of data that's collected about this artifact type
 - who are the primary audiences for this artifact type?  
 - what purposes are served by collecting and sharing this artifact? (e.g. finding contributors/collaborators, finding tools to use, fulfilling funder requirements, etc.)

**Comment by acabunoc** [comment]
I started a spreadsheet and am slowly filling it out

**Comment by xmatthewx** [comment]
Nice. Thanks for starting this. I suggest that we be specific rather than abstract. For example, instead of `Projects`, let's list `Open Science Software Projects` and `Hive Portfolio Project`. We can note their similarities and differences in terms of how we gather, where we file it, who looks at it, etc.

**Comment by xmatthewx** [comment]
[This slide](https://docs.google.com/presentation/d/15rBpuLWnNKJy6jG5PSP2dRkZWGwZ-YR_nuqEwnakRUA/edit#slide=id.g15e2ac5656_0_145) has a list of primary and secondary asset types. 

Open question: should we have a DB attribute to mark content type? For labelling or filtering assets? Definitely don't want to add this to the form. In DB, it might be more work than it's worth.

**Comment by xmatthewx** [comment]
Depends on #48.

**Comment by acabunoc** [comment]
closing for now, filled out the sheet quite a bit!
