### ISSUE TITLE
Searchbar searches everything regardless of current state

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#121]

**Comment by mmmavis** [comment]
How search works currently - 

1. get search term from the search bar
2. search through all project cards one by one (e.g,. all `<div class="project">`), if the search term appears in a project's DOM's textContent (ie., `DOMElement.textContent`) do nothing, otherwise hide the project from UI.

**Comment by mmmavis** [comment]
I have 2 approaches in mind:

Since we already have a list of project objects stored in the app, 

Option 1 ) We should search through the objects directly and render matching projects into DOM.
Option 2 ) Load all project cards into DOM. Each card should have a `data-id` attribute. We then search though all project objects, grab the list of matching project IDs,  show/hide project cards according to that list of matching IDs.

Seem like option 2 would be more ideal since we only have to render projects into DOM once. What do you think @cadecairos and @acabunoc ? 🐹

**Comment by acabunoc** [comment]
I'm a bit worried about the efficiency of Option 2, but I don't have enough DOM expertise to be able to definitively say it would be slower. Would you load all projects cards into the DOM before each search? Would this be triggered every time a character is typed in the search bar?

**Comment by mmmavis** [comment]
@acabunoc 

> Would you load all projects cards into the DOM before each search? Would this be triggered every time a character is typed in the search bar?

Yup yup. It's the same for option 1 and 2 since we are doing a "live search". And that's why I can't seem to tell which approach is more efficient. Maybe we should put some constrains on how we want to support live search?

**Comment by mmmavis** [comment]
@acabunoc 

> Would you load all projects cards into the DOM before each search? Would this be triggered every time a character is typed in the search bar?

For option 2 we will only have to load all projects cards into DOM once. Every time a search term is changed we'll just have to toggle the hide/show UI state on the cards.

**Comment by cadecairos** [comment]
> since we are doing a "live search".

Yeah that definitely changes things. Using CSS to apply the search in real time will be much faster. Also, it sound's like it's more of a "live filter" than a search, but it just so happens that the app shows all things by default.

**Comment by acabunoc** [comment]
We can add search constraints when we notice a lag, no need to now I think :)

I *think* that the biggest performance load would be actually writing to the DOM (browser reflow/layout thrashing are words that come to mind), which makes me lean towards option 1 to minimize how much writing we do. 

But I am not an expert! And we probably won't see a performance hit till we have 100s of assets in pulse (which we should plan for). Is anyone else better versed in browser performance than me that can comment?

**Comment by acabunoc** [comment]
Ah, just read @cadecairos's comment -- yeah filtering would be better for live search. But I do think we'll run into some performance issues down the road

**Comment by xmatthewx** [comment]
When we run into performance issues, we will have succeeded enough to justify a move to django. Yay. Until then, let's optimize for what we've got. 

Here's a strawperson proposal to discuss: 
 - pull projects from spreadsheet
 - keep in memory or local storage
 - write to DOM
 - filter DOM when possible (as search was originally setup)
 - rewrite DOM when necessary
 - check spreadsheet for new things (on tab switch)
 - add new things to memory/storage and DOM (rather than rewriting it all)

**Comment by acabunoc** [comment]
This plan sounds god to me! Especially with live search

**Comment by mmmavis** [comment]
Seems like we would like to try option 2 first? @acabunoc @cadecairos If we encounter any performance issue with option 2 we can revisit and find alternatives/fixes.

**Comment by cadecairos** [comment]
No objections from me

**Comment by mmmavis** [comment]
Awesome!

To avoid crazy merge/rebase conflict... I'll wait for the currently open PRs to merge first before I tackle this ticket. 🌻

**Comment by mmmavis** [comment]
I updated the search section on QA checklist

### Search
 As soon as the search bar is in focus / user clicks on search bar:
 - [ ] all projects appear
 - [ ] nav bar is hidden
 - [ ] add new project button is hidden
 - [ ] . (if user is previously on Issues Tab) issues buttons are hidden
 - [ ] cancel search icon appears
 When a user begins typing:
 - [ ] hint text is hidden
 - [ ] only applicable cards are visible
 - [ ] shows "not found" messages if there's no matching project
 - [ ] hitting ESC button returns to the tab/page you were on
 Clicks on the dismiss button
 - [ ] brings you back to the tab/page you were previously on

**Comment by xmatthewx** [comment]
Great stuff.

When user first clicks on search bar, should we hide everything? So it's more obvious they are revealing things if they type a common word? (sometimes you can't see things vanishing down below) This UX probably isn't a critical blocker. cc @kristinashu

**Comment by kristinashu** [comment]
I lean towards showing all the posts and then filtering them out as someone types. I think it's ok if there is no immediate feedback, might actually be less distracting this way. Compared to a blank screen, then a bunch of cards showing up, then just a few card... But agree, neither way is a blocker.

**Comment by mmmavis** [comment]
+1 learning towards showing all posts .

Note that this has landed on staging. We should create a new ticket if we decide to change it another way!
