### ISSUE TITLE
remove `request` dependency

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#1245]
We rely on `request`, at least according to our dependency list, but https://www.npmjs.com/package/request is deprecated and will never be updated ever again. We should find out where we're using it, and replace it with modern code =)

/cc @mmmavis

**Comment by mmmavis** [comment]
This file seems to be the only place we use the `request` package: https://github.com/mozilla/network-pulse/blob/master/js/review-app-slack-webhook.js

**Comment by mmmavis** [comment]
Re-opening as GitHub seemed to have issues at the time I merged my PR. Will close this ticket once I confirm the fix actually got landed.

**Comment by mmmavis** [comment]
Done!
