### ISSUE TITLE
Fira font is not loading

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#126]
Fira is not showing up on my phone.

Comp:
<img width="319" alt="screen shot 2016-08-08 at 3 37 04 pm" src="https://cloud.githubusercontent.com/assets/1068783/17498879/e6a596dc-5d7e-11e6-9d6e-c83fbda4e4dd.png">

Production:
<img width="425" alt="screen shot 2016-08-08 at 3 36 44 pm" src="https://cloud.githubusercontent.com/assets/1068783/17498877/e522474c-5d7e-11e6-91b6-79991c50badd.png">

**Comment by mmmavis** [comment]
Oops didn't realize we are using Fira as the font. I should've paid more attention on the Sketch file.

**Comment by kristinashu** [comment]
Ah much better, thanks!
