### ISSUE TITLE
Can't scroll down google form on mobile

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#128]
When I open the form to add a post on mobile, scrolling moves the close icon around a little but I can not scroll down the form.

Production:
<img width="426" alt="screen shot 2016-08-08 at 4 03 35 pm" src="https://cloud.githubusercontent.com/assets/1068783/17499349/b9f4f8b4-5d81-11e6-9e40-f06d630f2a96.png">

**Comment by xmatthewx** [comment]
What's your device and browser? iPhone & safari? Works as expected on Android 6, Chrome & Firefox Beta.

**Comment by kristinashu** [comment]
I'm on iPhone SE with iOS 9.3.4 and it happens in FF, Safari and Chrome.

**Comment by kristinashu** [comment]
Also happening on Natalie's iPhone 5

**Comment by mmmavis** [comment]
Probably an iOS issue, I'm seeing the same issue on my iPhone 6s. I think it's probably trying to scroll the layer underneath the embedded Google Form.

**Comment by xmatthewx** [comment]
Maybe try hiding the other layer while form is displayed.

**Comment by mmmavis** [comment]
I can't seem to find a way to enable scrollbar on fixed position HTML element. 😦 ummmm

**Comment by xmatthewx** [comment]
Hmm. That stinks. Shouldn't scrollbar be automatic? Does this work on your device @kristinashu: http://codepen.io/okfuture/full/vKvxxq/

**Comment by kristinashu** [comment]
No, it isn't scrolling

**Comment by mmmavis** [comment]
I got a fix... had to change `display` to `absolute` + other tweaks.
