### ISSUE TITLE
Footer links should open in a new tab

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#129]
All 3 links should open in a new browser tab. Please and thank you.

**Comment by mmmavis** [comment]
Opening links in new tabs can be disorienting for people and as a general practice it is probably something we should avoid doing. (see https://www.w3.org/TR/WCAG20-TECHS/G200.html) I would advocate for keeping the footer links open on the same tab. 😁

**Comment by kristinashu** [comment]
Ok, no biggie!
