### ISSUE TITLE
Discuss whether or not to Reactify this app

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#13]
Currently this app is based on ~500 line of vanilla JS code `.js` file. This works good with the prototype features we have & linkage with Google Spreadsheet. As this project involves more features will be added and we might switch to use a real database. Let's discuss whether or not to Reactify this app. And if we are doing it, should we tackle it now or at a later stage.

Some things to take into account:
- route/url structure
- server
- API calls
- database

/cc @cadecairos @acabunoc @xmatthewx

**Comment by cadecairos** [comment]
My first instinct is that If we're going to "reactify" network-pulse, we'll want to do it before building out more features, otherwise we're just making things harder for us in the future.

**Comment by mmmavis** [comment]
@xmatthewx I'm curious to know if we have a roadmap or milestones for this project. Is there any deadline we are trying to meet?

**Comment by xmatthewx** [comment]
I've added milestones to the repo. Let's keep our eye on the deliverables in the kickoff ticket (#5). One of the deliverables is a proposed roadmap.

**Comment by mmmavis** [comment]
Alright, let's make the "whether or not to Reactify" decision after this heartbeat then. I will focus on other deliverables for this milestone for now.

**Comment by mmmavis** [comment]
@xmatthewx @cadecairos @acabunoc @kristinashu 

I'm going to be updating the "Some things to take into account" list in the first comment. Free feel to add more if you think of any!

**Comment by cadecairos** [comment]
> server
If this get wrapped in a server, I'd like it to be an express server!

> database
It'd be cool if we use an ORM that can gracefully fall back on sqlite for local dev

**Comment by mmmavis** [comment]
Closing. This is not something we are going to tackle for this phrase 😜 We'll continue the discussion after we ship the MVP and learn from our users.

**Comment by simonwex** [comment]
@mmmavis could you file a ticket to do this post-mvp?

**Comment by mmmavis** [comment]
@simonwex I created [another ticket](https://github.com/mozilla/network-pulse/issues/98) to discuss about the same matter 2 weeks ago. The decision was to hold off until we learn more from the users & decide whether or not we will be continuing working on this prototype.

**Comment by xmatthewx** [comment]
Worth mentioning @simonwex that @mmmavis has modularized our code to simplify a refactor if we do that later.
