### ISSUE TITLE
Shared post view should be centered 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#130]
Single post should be centered

Comp:
![red-pen-c7f1c6fc-8ca9-4955-c0bc-d95c1920569c](https://cloud.githubusercontent.com/assets/1068783/17499617/6b551f8e-5d83-11e6-963d-08cb6b33d45e.png)

Production:
<img width="1332" alt="screen shot 2016-08-08 at 4 13 14 pm" src="https://cloud.githubusercontent.com/assets/1068783/17499595/359c9584-5d83-11e6-9853-c58efc56ea59.png">

**Comment by mmmavis** [comment]
oops!
