### ISSUE TITLE
No search results remains in view

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#131]
When I see the "Nothing found" message and then close the search, I still see the "Nothing found" message on other screens.

<img width="1089" alt="screen shot 2016-08-08 at 4 22 48 pm" src="https://cloud.githubusercontent.com/assets/1068783/17499779/891a5dda-5d84-11e6-90b2-eee7e7625530.png">

**Comment by mmmavis** [comment]
this should be fixed when PR #118 is pushed live.

**Comment by mmmavis** [comment]
fixed!
