### ISSUE TITLE
styling issue creating a pulse entry

### ISSUE THREAD

**Issue by kaili09** [mozilla/network-pulse#1360]
**Describe the bug**
Drop-down options not working as expected. For Tags, I cannot select the appropriate choice, and for author, I cannot delete the wrong choice. Something strange also happened when I uploaded the image. Can't save (not an option), but refreshed (lost work) and now still seeing the same issue only without text.

<img width="798" alt="Screen Shot 2020-07-02 at 11 52 27 AM" src="https://user-images.githubusercontent.com/50032968/86395250-2e1f3900-bc5d-11ea-8727-cadb01e2ed3e.png">
<img width="854" alt="Screen Shot 2020-07-02 at 12 10 27 PM" src="https://user-images.githubusercontent.com/50032968/86395253-2fe8fc80-bc5d-11ea-9b54-a45a341d5aea.png">
<img width="993" alt="Screen Shot 2020-07-02 at 11 54 51 AM" src="https://user-images.githubusercontent.com/50032968/86395255-30819300-bc5d-11ea-9a4f-4cfa3ffbf7d4.png">
<img width="901" alt="Screen Shot 2020-07-02 at 11 52 33 AM" src="https://user-images.githubusercontent.com/50032968/86395257-30819300-bc5d-11ea-92f4-797f911cd62f.png">

**Expected behavior**
Expected to be able to type and edit in dropdown fields. I also expected a refresh to fix it, but it did not.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.5
 - Firefox 77.0.1 (64-bit)

**Additional context**
I haven't changed anything in my browser settings since I last created a pulse entry (without these complications)

**Comment by mmmavis** [comment]
Related to #1359

**Comment by mmmavis** [comment]
I suspect this has something to do with Bootstrap uplift and the recent`react-tag-autocomplete` uplift.

Adding/removing a tag in the "Tags" field results in JS errors (see screenshot below)
<img width="457" alt="image" src="https://user-images.githubusercontent.com/2896608/86398531-9c163100-bc5a-11ea-8773-641fc92ccc6e.png">
