### ISSUE TITLE
Footer: add copy for CC license

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network-pulse#1379]
Implementation ticket for footer changes.

**Impacted sites:**
[Mozilla Pulse](https://www.mozillapulse.org/)

**Changes:**
1. Removed "License" copy
2. Organized items by alphabetical order (except for "Donate", which should remain the first link)
3. Added "Most content available under a Creative Commons license." Link for [Creative Commons license is here](https://foundation.mozilla.org/about/website-licensing/)
4. Changed Mozilla logo to the most updated one. [Logo here](https://drive.google.com/drive/folders/1S8P67EV-c426se-eEdgS-cUorjqZI7EQ?usp=sharing)
5. Change copy to be consistent with other web properties: "Join our Mozilla News email list to take action and stay updated!"

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/22157921/87988498-4a143e80-ca95-11ea-8b3f-685b5612761f.png">

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket: [#4868](https://github.com/mozilla/foundation.mozilla.org/issues/4868)
- [x] Link to InVision: [link here](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425806734_Footers-Pulse)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included

cc: @TheoChevalier - updates we will be doing to our English Footers

**Comment by Yashs911** [comment]
Hi, @taisdesouzalessa I would like to work on this issue.

**Comment by taisdesouzalessa** [comment]
hey @Yashs911 thank you so much for your contribution 💯. 
Here is the logo from that Google Drive folder: 
[Mozilla-logo-BW-RGB(4).zip](https://github.com/mozilla/network-pulse/files/5342160/Mozilla-logo-BW-RGB.4.zip)

cc: @mmmavis @Pomax

**Comment by Yashs911** [comment]
@taisdesouzalessa there is some problem with .svg version so can I use .png image with proper styling instead

**Comment by taisdesouzalessa** [comment]
@Yashs911 try to use this one here then: https://assets.mofoprod.net/static/_images/mozilla-block-white.8a5ea59a8186.svg

It is the same we're currently using in our Foundation site (footer): https://foundation.mozilla.org/en/

**Comment by Yashs911** [comment]
Still not loading and which image do I have to use the one with black background or white. Because  Foundation site (footer): https://foundation.mozilla.org/en/ and mozillapulse.org footer have same logo I guess.

![1](https://user-images.githubusercontent.com/64412143/95367530-7f8d3300-08f2-11eb-8364-25b9f7ed9702.JPG)

**Comment by taisdesouzalessa** [comment]
The svg from here (https://assets.mofoprod.net/static/_images/mozilla-block-white.8a5ea59a8186.svg) works for me. This is what I see (it seems we have nothing because it is all white but when I change the fill color the logo is there):

![mozilla-logo](https://user-images.githubusercontent.com/22157921/95368892-8fbdf780-088b-11eb-83bb-f215a125a732.gif)

Hopefully it works for you too :)

The logo we are using is the one with white background, the same as we have in the [Mozilla Foundation](https://foundation.mozilla.org/en/) site.

**Comment by Yashs911** [comment]
@taisdesouzalessa I don't know why but the image is not loading
![Capture](https://user-images.githubusercontent.com/64412143/95371208-7fdbfd00-08f7-11eb-8e5c-f17acc9079d4.JPG)

Sorry If I caused any inconvenience

**Comment by Yashs911** [comment]
@taisdesouzalessa Issue solved

**Comment by taisdesouzalessa** [comment]
No need to apologize at all @Yashs911 - glad the issue got solved. Let me know if I can help with anything else. Sorry this svg was trouble!

**Comment by mmmavis** [comment]
PR merged! Thanks, @Yashs911 !
