### ISSUE TITLE
Save to homescreen

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#138]
Building a user habit to check for new projects will increase impact. Prompt users to Add-to-Homescreen with a one time alert. (Try it. Add it to your homescreen. I bet you'll check Pulse a few times you wouldn't otherwise!)

We should also update the color on the favicon. 

Not critical. Adding to backlog for when there's a spare moment.

**Comment by arush0311** [comment]
Are we talking about progressive web apps? https://github.com/cubiq/add-to-homescreen

**Comment by xmatthewx** [comment]
@arush0311 – Yes, and... I don't think we should prioritize this feature right now.
