### ISSUE TITLE
Update font style for into blurb

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/network-pulse#1416]
Update font style for into blurb

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [ ] Design has been finalized
- [ ] Link to original design ticket
- [X] Link to related ticket [#5234]
- [ ] Link to Redpen https://redpen.io/p/yqece0a9215e9c33f1
- [ ] Design changes been merged into the master Sketch file
- [ ] Desktop and mobile mockups are included
- [ ] Assets are included
- [ ] Hover state for elements are designed
- [ ] Other states for elements are designed (e.g., error state for form)

**Comment by jamilasnell** [comment]
Issue moved to [mozilla/foundation.mozilla.org #5248](https://github.com/mozilla/foundation.mozilla.org/issues/5248) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mmmavis** [comment]
Ticket has been moved to `foundation.mozilla.org` repo. Closing this one now 😉
