### ISSUE TITLE
Footer: checkbox and text not aligned

### ISSUE THREAD

**Issue by Yashs911** [mozilla/network-pulse#1438]
### Describe the bug
For width greater than 1200px checkbox in footer is not aligned.
### To Reproduce
1. Go to https://www.mozillapulse.org/
2. Scroll down to footer

### Expected behavior
It should be aligned

### Screenshots
width >1200px
![issue](https://user-images.githubusercontent.com/64412143/96240356-6ead8300-0fbe-11eb-9804-4d6e11cc37da.JPG)

width<1200px
![soln](https://user-images.githubusercontent.com/64412143/96240375-766d2780-0fbe-11eb-8166-3cf87917d4d7.JPG)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by Pomax** [comment]
this got fixed, but the issue never got closed.
