### ISSUE TITLE
Update screencap in README

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#144]

**Comment by mmmavis** [comment]
using this screencap instead sounds okay to you? @xmatthewx @kristinashu 

![network-pulse](https://cloud.githubusercontent.com/assets/2896608/17790072/ce78cc14-6549-11e6-9cb1-1ef37fcaf863.png)

**Comment by kristinashu** [comment]
wfm!

**Comment by mmmavis** [comment]
fixed in https://github.com/mozilla/network-pulse/commit/cee99317527d81d3dfefbea1fb25ffed387b0191 🌞
