### ISSUE TITLE
Lock column title row in spreadsheet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#147]
Let's lock the first row of the spreadsheet to avoid accidental modification to column titles.

**Comment by xmatthewx** [comment]
Good call. Assign to me if you don't have permission.

**Comment by mmmavis** [comment]
Done. 👍

**Comment by mmmavis** [comment]
@xmatthewx I set a warning instead of locking the row. Let me know if we should have it locked instead.
