### ISSUE TITLE
 Faved tab breaks if a faved project is later deleted from spreadsheet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#148]
I can fix this by filtering out those "no longer existed" projects before we render projects into the faved tab. 

Question: Do we also want to add some visual clue/notice so that users know their fav'ed project has been removed from the spreadsheet?

/cc @kristinashu @xmatthewx

**Comment by xmatthewx** [comment]
Good catch. I wouldn't worry about notifying users, as long as things don't break.

**Comment by mmmavis** [comment]
Cool, works for me!

**Comment by mmmavis** [comment]
Instead of generating project `id` on the fly when we process & feed spreadsheet data into the app, we should generate `id` **on** the spreadsheet so that each spreadsheet row has an `id` field.

We can use the [`N` function](https://support.google.com/docs/answer/3093357) that Google provides, along with the [`SUBSTITUTE` function](https://support.google.com/docs/answer/3094215?hl=en) on the `timestamp`

e.g., 

when `timestamp` is `1/26/2016 11:44:22`...

`N(1/26/2016 11:44:22)` returns `42395.48914`
`"p"&SUBSTITUTE(N(B5),".","")` returns `p4239548914` <<< we can use this `id` for the app

@xmatthewx @acabunoc @cadecairos comments? This is still not human readable but so far this is the only way we can find to auto generate an "unique" id on Google Spreadsheet. (there shouldn't be any duplicated `id` unless there are multiple entries submitted at the same time (millisecond precision).

Note that if we agree to make this change projects that have been fav'ed will be reset on users device since we are using a different formula to generate `id`.

**Comment by mmmavis** [comment]
let's move the `id` discussion in https://github.com/mozilla/network-pulse/issues/188 🌞
