### ISSUE TITLE
Hovering on 'X' says "add a project"

### ISSUE THREAD

**Issue by acabunoc** [mozilla/network-pulse#149]
When in adding a project view, hovering over the 'X' still says "add a project" 

![screen shot 2016-08-10 at 11 57 36](https://cloud.githubusercontent.com/assets/617994/17560898/ca4e0b9e-5ef1-11e6-8604-35942fd485b7.png)

**Comment by xmatthewx** [comment]
Ah. Good catch. We should change that and also stop using the word project. 

 - Form (X): "Close Form"
 - Pulse (+): "Add something new"
  - I think this is better than Add an Asset. Thoughts? @acabunoc @kristinashu

**Comment by xmatthewx** [comment]
Also. This can stay in the backlog until we finish more critical things.

**Comment by xmatthewx** [comment]
Estimating this as a 1 in effort. Should I not do that now?

**Comment by kristinashu** [comment]
+1 to "Add something new" (Asset still feels off to me)

**Comment by mmmavis** [comment]
Fixed!
