### ISSUE TITLE
Enable deep linking

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#15]

**Comment by xmatthewx** [comment]
Display URL in the detail view until we have a button for sharing #18

**Comment by mmmavis** [comment]
relates to https://github.com/mozilla/network-pulse/issues/14 (Build detail view)

**Comment by mmmavis** [comment]
Done in PR https://github.com/mozilla/network-pulse/pull/25. It definitely needs some design love but we can file follow-up tickets instead. Just wanted to get the feature in place first. Gonna close this ticket now! 🍻
