### ISSUE TITLE
Explore detail view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#151]

**Comment by kristinashu** [comment]
@xmatthewx here's a quick comp: https://invis.io/7W89NQ03A#/180945702_Featured_With_Detail_View

Initial thumbnail card view includes:
- title
- optional image
- creator
- date added
- 'learn more'
- fav

Detail view includes all of the above. Plus:
- clickable category tag (new feature)
- clickable creator name (new feature)
- extra copy
- optional Get Involved link (now just a text link to follow the 'how to get involved')
- visit external link
- share on twitter and facebook

Lemme know what you think!

**Comment by xmatthewx** [comment]
Added a few comments in invision. All in all, looks great.

**Comment by kristinashu** [comment]
Thanks, I've made those updates.

**Comment by kristinashu** [comment]
I've updated the last few redpen screen to only show the detail view changes (other feature updates will be covered in separate tickets).

Initial thumbnail card changes:
- shortened intro (only the copy that appears on the form under "Description")
- the only buttons are 'Read more' which links to the detail view and Fav icon
- keep optional photo

<img width="175" alt="screen shot 2016-08-17 at 10 57 33 am" src="https://cloud.githubusercontent.com/assets/1068783/17747391/853c142e-6469-11e6-827f-e9f2d191ee0c.png">


Detail view:
- "Back" button which links to thumbnail overview screen
- all copy available in the spreadsheet (in the following order: Description, Interest, Network connection, Origin, Get involved text followed by Get involved URL)
- "Visit" external link and Fav icon
- keep optional photo

<img width="269" alt="screen shot 2016-08-17 at 10 57 16 am" src="https://cloud.githubusercontent.com/assets/1068783/17747396/88b04ae4-6469-11e6-842c-48eb47629f85.png">


Desktop view:
- wider card size than thumbnail view
![desktop - post detail 2x](https://cloud.githubusercontent.com/assets/1068783/17745384/74ef0b3e-6460-11e6-8bb3-6d78762c1f78.png)

@xmatthewx want copy do you think we should show on the detail view? I've listed some above.

**Comment by xmatthewx** [comment]
Cool cool.

I wonder if we should have a header above Network connection in detail view (that could include network connection and origin columns). 

I wonder if we should display tags and program at the bottom. Maybe okay leave out for now.  

Creators: tap to search probably not MVP

**Comment by kristinashu** [comment]
Hacky but since we no longer ask users "Network Connection" or "Origin", maybe we can just manually add "Network Connection:" before that text in the spreadsheet. Could even combine the two into one column since there aren't very many Origin entries?

I see the value in showing tags but worry about bumping the CTAs down too far.

**Comment by xmatthewx** [comment]
Agreed re: Tags. Let's keep them out. 

It should be easy for Mavis to include "Network Connection: ..." and then those two columns as a single paragraph or two. It's also fine for program staff to input that in via the spreadsheet when they have that info, even if it's only on interesting, featured items.

**Comment by kristinashu** [comment]
Sounds good, closing.
