### ISSUE TITLE
Plan rollout and onboarding

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#152]

**Comment by kristinashu** [comment]
[Meeting](https://docs.google.com/document/d/1IUbYB56ZlwCand-R1TSdMNixatOPw207cQX1D1EBBL8/edit#) notes summary:

### Timeline
Aug 19: Release 0.9
Aug - Sep: Staff pilot
Oct: New release 1.0
Mozfest: Test (all attendees? Specific groups?)

### How to share?
- Email from Lotta or Kaitlin?
- Mofo staff meeting Oct 24

### Support
- Monthly highlights [Lotta]
- Help Triage projects
- Help people add images
- Give people access to doc

### Possible Content

#### Description
- Highlights from overview [our deck](https://docs.google.com/presentation/d/15rBpuLWnNKJy6jG5PSP2dRkZWGwZ-YR_nuqEwnakRUA/edit#slide=id.gd58133b56_0_69) 
- Framing (good for new staff, 'This is what we need. Been missing this.', Could reduce pain points, Won’t fit some very specific jobs.)
- Include some images or visuals

#### Request to staff
- Input your stuff (pull 3 things from the past 6 months and then add new things as they come up)
- Cross hubs sharing
- Etherpad with Hub leads every two-weeks
- Do it in a way to communicate back with hubs
- Trickle down to program staff?
- Share to their fellow staff
- Favorite things organic? Call it out in request?
- Search: Use it to gather list/link for some sort of report. 
- Tell us how input and then subsequent gathering of “stuff” went

**Comment by kristinashu** [comment]
Definitely needs some work but here's a rough starting point for our roll out email https://docs.google.com/a/mozilla.com/document/d/1BvSP0PEzYmqN5TSep-rDzkApdIRPmDgQ7RDoyhm97Sk/edit?usp=sharing
Please give it some love @xmatthewx @acabunoc!

**Comment by kristinashu** [comment]
Thanks for adding your thoughts! It's feeling a little long. @hannahkane would you be able to take a look?

**Comment by hannahkane** [comment]
Added a couple notes. Main feedback is to create a really concrete, actionable ask.

**Comment by kristinashu** [comment]
Updated the draft https://docs.google.com/a/mozilla.com/document/d/1BvSP0PEzYmqN5TSep-rDzkApdIRPmDgQ7RDoyhm97Sk/edit?usp=sharing

@xmatthewx is our next step to meet with Kaitlin, brief her then have her send out an email?

**Comment by xmatthewx** [comment]
cc @Lottarao take a look at this thread and the attached doc. Would love your feedback.

**Comment by xmatthewx** [comment]
Plan is ready. Kickoff is scheduled. Yay.
