### ISSUE TITLE
Add search suggestions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#153]
Keeping in backlog for now

**Comment by kristinashu** [comment]
<img width="423" alt="screen shot 2016-08-15 at 9 00 46 am" src="https://cloud.githubusercontent.com/assets/1068783/17670440/cacab8b4-62c6-11e6-917d-0a08464b962d.png">

**Comment by kristinashu** [comment]
Mocked this up while exploring the empty search view https://github.com/mozilla/network-pulse/issues/237

![empty favs copy 8 1x](https://cloud.githubusercontent.com/assets/1068783/20493919/8c49136e-afcf-11e6-8512-4808f96144a3.png)

**Comment by xmatthewx** [comment]
Oh very cool. I really like this as way to highlight various threads we know about, but wouldn't be obvious to others. We'd probably run with Suggested terms initially, until we have enough activity for Popular.

**Comment by kristinashu** [comment]
@xmatthewx any suggestions on what the terms should be?

**Comment by xmatthewx** [comment]
hmm... these return a nice mix of results: 

mozfest
privacy
prototype
community
local
code
game
iot
data

**Comment by arush0311** [comment]
Can I take this?

**Comment by xmatthewx** [comment]
Sure. This isn't as high priority as some of the other tickets you've mentioned, but would be a nice addition. 

We'd want to manage a list of suggested terms in django, since it's too early to generate a good list. So we'll need to create that model, api, and then frontend pieces. 

Phrase before the list: "You might also like..." instead of "popular" etc.

**Comment by himanish-star** [comment]
@xmatthewx , can I take this issue up ?

**Comment by alanmoo** [comment]
Is there enough detail here for you to get started?

**Comment by xmatthewx** [comment]
I think we can start this with a static component on the frontend. A couple months later, if analytics show it to be useful, we can add to backend admin. But for now, a simple static build would be great. 

I propose that links _do not_ populate search. Why? 
 - Platform can't currently search help categories. This is a chance for us to promote this important feature of the platform. /help/promote yields 4 times the results as a search for promote. 
 - As links, we can link to a tag, category, or a search when useful. 

```
[ { label: 'iot', slug: '/search?keyword=iot' },
  { label: 'promote', slug: '/help/promote' }, ...]
```

Requirements: 
 - [ ] component with static, easy to update list suggestions
 - [ ] when input is empty, suggestions component displays
 - [ ] when input is not empty, component does not display (see comp below)
 - [ ] style for component { margin-left: 0.5em; color: #aeaeae; }


### Search input is empty

<img width="359" alt="image" src="https://user-images.githubusercontent.com/53411/35692234-ab9a04c2-072f-11e8-9836-63e40885cbad.png">

### Search input is not empty

<img width="509" alt="image" src="https://user-images.githubusercontent.com/53411/35692621-b59fabec-0730-11e8-85fd-13945d7d8f57.png">

**Comment by mmmavis** [comment]
@arush0311 @himanish-star seems like our team wanna get this out soon. I'll be working on this today/tomorrow. Thanks for offering help!

**Comment by arush0311** [comment]
@mmmavis please go ahead. Sorry I completely forgot about this issue.

**Comment by mmmavis** [comment]
@xmatthewx what are the trending terms/links we wanna show?

**Comment by xmatthewx** [comment]
Let's try this @mmmavis. If it's too much, let's first remove help code. 

```
[{ label: 'mozsprint', slug: '/tags/mozsprint' }, 
{ label: 'artists open web', slug: '/tags/Artists%20Open%20Web' },
{ label: 'inclusion', slug: '/issues/digital-inclusion' }, 
{ label: 'help code', slug: '/help/code' }, 
{ label: 'help with feedback', slug: '/help/test-and-feedback' }]
```

**Comment by mmmavis** [comment]
Done. https://www.mozillapulse.org/search
