### ISSUE TITLE
Format URLs for card links

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#156]
Based on comment in [doc ](https://docs.google.com/document/d/1JroE86P4_BxHh7DPMp5_cLaHQ-AWgdi1BAZqS3v2m-4/edit?disco=AAAAAtShVWE#heading=h.d4xdgyi7ghde)

To make the form as simple and clear as possible we would like to remove the "include http:// or https://" text. Would you be able to add a check for this and for it to add the http:// if it's missing?

Steps:
- [ ] Add check
- [ ] Test it
- [ ] Delete text from the form

**Comment by xmatthewx** [comment]
I believe we have validation on the form itself. So all URLs should be okay. I think I added that help text so users don't see a not-too-helpful validation error. Unsure if google let's you edit error text. Dig around in odd settings menu on that individual item. 

If we don't use form validation, we'll have to check and fix URLs when we render the cards. That's complicated and probably opens the door to dangerous links. So, we might not be able to make this better.

**Comment by mmmavis** [comment]
@kristinashu I don't remember what this ticket was about 😁 Seems like it's for v1. Can we close it?

**Comment by kristinashu** [comment]
Yeah, as long as in v2 someone can put in "mozillafestival.org" and it will link ok (without having to put in "http://mozillafestival.org").

**Comment by xmatthewx** [comment]
http or https is required. says it in the hint on the form.

**Comment by kristinashu** [comment]
So should we leave this open to fix that or do we not care?

**Comment by xmatthewx** [comment]
I care. We'll have to see what things come up from QA. See what's most critical.
