### ISSUE TITLE
Users should be able to edit response after submitting 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#158]
A suggestion in the interviews was to have the ability to edit a response afterwards. For example, I submit a project but forgot to add a contributors name.

Option 1) We could give staff edit access to the spreadsheet but that is not very intuitive

Option 2) It's easy to allow users to edit the form right after they edit. Just need to edit settings
<img width="408" alt="screen shot 2016-08-10 at 2 40 30 pm" src="https://cloud.githubusercontent.com/assets/1068783/17572283/7bf5d73a-5f08-11e6-812c-195bc9116038.png">
so users see this right after clicking submit
<img width="504" alt="screen shot 2016-08-10 at 2 40 43 pm" src="https://cloud.githubusercontent.com/assets/1068783/17572290/807e569c-5f08-11e6-9536-ec60ada1d4b0.png">

Option 3) This would be idea but not sure if it is possible. Is there a way to edit your own response later on? Does it require gApp login?

**Comment by mmmavis** [comment]
One note, we should verify that whether or not editing response will update the `timestamp` meta in the Google Spreadsheet.

**Comment by xmatthewx** [comment]
Bumping to the backlog of the current milestone.

**Comment by xmatthewx** [comment]
I enabled edits via the form, and add basic instructions in the "thanks for submitting" copy. 

It does update the timestamp as @mmmavis wondered (which will break any favs). I think it's okay, since it is most likely that people will use it to fix a typo. Very unlikely people will save the link to edit much later after submitting. 

I'm going to call this good enough for now and close.

**Comment by mmmavis** [comment]
@xmatthewx it will also break direct links to single project view too - this can be problematic if previous links were shared out.

**Comment by xmatthewx** [comment]
oh dang. you're right. i'll turn the feature off and update the thank you message. some combo of github + spreadsheet will have to be good enough for this version!
