### ISSUE TITLE
Add Twitter share button

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#159]
Discuss adding social shares like Twitter and Facebook?

**Comment by kristinashu** [comment]
Once we have a detail page, share could look like this:
<img width="270" alt="screen shot 2016-08-17 at 2 12 53 pm" src="https://cloud.githubusercontent.com/assets/1068783/17753491/e2ad6052-6484-11e6-829d-1143098b36ad.png">

**Comment by kristinashu** [comment]
Now that we have a detail page, we could add social like above ^

cc @xmatthewx

**Comment by xmatthewx** [comment]
👍 We should probably keep link icon as well, for access to shortlink URL for shares via email.

**Comment by kristinashu** [comment]
Here's the card with the link icon, the link will have to show up below the icons.

<img width="320" alt="screen shot 2016-11-21 at 10 01 00 am" src="https://cloud.githubusercontent.com/assets/1068783/20494398/943e97d6-afd1-11e6-83cc-eabe040e99d5.png">

**Comment by mmmavis** [comment]
Can we move this to the following heartbeat since this is not a launch blocker?

**Comment by mmmavis** [comment]
What happens when you click on the Twitter/Facebook icon?

**Comment by kristinashu** [comment]
It opens up a model to share on Twitter/Facebook. Text could include: Title of post and the Pulse URL to that post.

Like on http://www.theverge.com/2017/1/25/14371450/indus-valley-civilization-ancient-seals-symbols-language-algorithms-ai

<img width="1312" alt="screen shot 2017-01-25 at 1 20 26 pm" src="https://cloud.githubusercontent.com/assets/1068783/22309719/434891a2-e301-11e6-9162-639b722ccaed.png">
<img width="1312" alt="screen shot 2017-01-25 at 1 20 36 pm" src="https://cloud.githubusercontent.com/assets/1068783/22309720/434dd5ae-e301-11e6-8580-04b7da14e17d.png">

**Comment by mmmavis** [comment]
Not MVP for launch. I'm gonna remove this from the current milestone.

**Comment by xmatthewx** [comment]
We can move forward twitter and do facebook later.

**Comment by mmmavis** [comment]
Hey @kristinashu It seems like Font Awesome only has social icons in solid colour (no outline version). When you get a chance can you put our custom svgs on Google Drive? 😉

**Comment by xmatthewx** [comment]
is hover state pink outline or solid pink or solid blue?

**Comment by kristinashu** [comment]
Here are the svgs: [icons.zip](https://github.com/mozilla/network-pulse/files/1005250/icons.zip)

Let's make the hover state a pink outline (same as the current link icon).
