### ISSUE TITLE
Review & clean up code

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#16]
I don't think there's much to improve as the code is pretty tidy and straightforward (thanks @xmatthewx !) but I'll still go through it and be nitpicking.

One thing I would like to do is to lint [`js/pulse.js`](https://github.com/mozilla/network-pulse/blob/gh-pages/js/pulse.js). @gvn any suggestion on how to do it? I'm thinking to just save a copy of https://github.com/MozillaFoundation/mofo-style/blob/master/.eslintrc.yaml and rely on my eslint CLI to do the checks and fixing.

/cc @cadecairos @acabunoc

**Comment by gvn** [comment]
You can just include `mofo-style` via npm and point eslint to the RC within node_modules.

See: https://github.com/MozillaFoundation/mofo-style#setup

**Comment by mmmavis** [comment]
@gvn this is not a node project. I guess I'll just `npm install` without the `--save-dev` option then.

**Comment by mmmavis** [comment]
`npm install` doesn't work without `package.json`. i'll do this the manual way then

**Comment by mmmavis** [comment]
accidentally deleted my previous comment so I'm gonna recomment it again...

@gvn this is not a node project though but i guess i can still `npm install` and reference the `.eslintrc.yaml` in `mofo-style` module.

**Comment by gvn** [comment]
Sounds like you've got enough needs to make it into a npm managed project. You'll need a task runner for running the linter and eslint + mofo-style should be devDependencies.

**Comment by xmatthewx** [comment]
@mmmavis – should we close this and file any specific follow up issues?

**Comment by mmmavis** [comment]
Yup. Let's close this one!
