### ISSUE TITLE
Communicate that this is only a prototype

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#160]
Based on interview summary [doc](https://docs.google.com/document/d/1IUbYB56ZlwCand-R1TSdMNixatOPw207cQX1D1EBBL8/edit#).

How do we let users know that this is only a prototype. That means:
- it might not live on
- we are open to feedback and contributors
- reassure them we have a plan for sun-setting
- keeping it in-house initially
- keeping the spreadsheet available even if we don't maintain the tool
- remain committed to making it super useful so we don't deprecate

Some suggestions were:
- prototype label in top corner
- link in the footer
- ...

**Comment by xmatthewx** [comment]
If we bring Pulse to Mozfest, we really should find a way to do this.

**Comment by kristinashu** [comment]
@xmatthewx could the about page cover this? https://github.com/mozilla/network-pulse/issues/234

**Comment by xmatthewx** [comment]
Yes. And... hopefully we'll be exiting prototype stage. But could be interesting to describe Pulse as a living document of our shared knowledge, the footprints of our network activity. That it will evolve not just in content, but in form as well.
