### ISSUE TITLE
How do we feature people, collaborations, connections, relationships?

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#161]
Came up a few times in the [interviews](https://docs.google.com/document/d/1IUbYB56ZlwCand-R1TSdMNixatOPw207cQX1D1EBBL8/edit#), how do we show importance of people and relationships?

We could look at how we display names and maybe have them function like tags, trigger a search by name.

**Comment by xmatthewx** [comment]
cc @liberaliscomputing

**Comment by xmatthewx** [comment]
We should also address the connection between names and date. Currently it displays: `Mark Surman on Sep 4, 2016` It strongly suggests that Mark posted it. This feels succinct and more accurate: 

`By Mark Surman・Added Sep 4, 2016`

**Comment by xmatthewx** [comment]
I'd like to revisit the design of this. See comment above on Sep 9. 

We can display creators on one line and then automatically truncate with ellipses. Or choose character count. 

I'd like to `By` before creators and `Added` before the date. 

Creator list can expand in detail view. Ideally in detail view we would drop the line break and separate with a middot to avoid awkward line lengths when the creators wrap a little bit to the next line. See below.

<img width="334" alt="screenshot 2016-12-12 16 25 10" src="https://cloud.githubusercontent.com/assets/53411/21117440/b061ee42-c087-11e6-8cab-f32379b18f7e.png">

<img width="522" alt="screenshot 2016-12-12 16 29 52" src="https://cloud.githubusercontent.com/assets/53411/21117550/3af4db82-c088-11e6-8d00-2c57cded42fd.png">

**Comment by xmatthewx** [comment]
@kristinashu - any feedback? let's assign to @mmmavis it the plan looks good.

**Comment by kristinashu** [comment]
Works for me.
