### ISSUE TITLE
Update a form field title, spreadsheet and code from "Creator" to "Creators"

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#162]
Super minor but it will help to encourage people to add contributor, partners...

Screen cap of form on production:
<img width="669" alt="screen shot 2016-08-11 at 11 32 42 am" src="https://cloud.githubusercontent.com/assets/1068783/17600249/8030bb76-5fb7-11e6-9460-fcf138f0683e.png">

**Comment by mmmavis** [comment]
@kristinashu @xmatthewx can you grant me edit access to the form?

**Comment by kristinashu** [comment]
Sent you an invite!
