### ISSUE TITLE
Verification emails & Receiving contact form notifications

### ISSUE THREAD

**Issue by acabunoc** [mozilla/network-pulse#1633]
Hi all 👋

I’m still getting email notifications when people fill out the contact form while I’m on parental leave. Does anyone else get these?

Several people haven’t gotten verification  emails in the last day. And Teon wants to consolidate his pulse accounts.

https://docs.google.com/spreadsheets/d/1G4SOJXG_v9OFiL6NV2nOfrGhQ159ZSFfeIQV3nW9zrg/edit?ouid=113263149988286049053

cc @Pomax

**Comment by Pomax** [comment]
@benhohner @jzinner is it possible that this was a zapier integration that we removed?

**Comment by bheasman** [comment]
Closing this - will raise again once we have clarity on Pulse (if needed)
