### ISSUE TITLE
Use mofo-bootstrap

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#166]
Not sure if we should use mofo-bootstrap or not? Building prototypes quickly seems like the perfect use of bootstrap but not sure we're there yet? But could be a good opportunity to test it?

Design elements we could pull from it: fonts, colors, buttons, maybe icons, maybe grid, maybe footer

Is it an issue that pulse is not built in react?

Thoughts? @xmatthewx @mmmavis @gvn

**Comment by gvn** [comment]
Mofo Bootstrap doesn't need React, so I'd definitely recommend using it for every new thing we do!

**Comment by mmmavis** [comment]
I'm in for adding `mofo-bootstrap`! 🌞  Not an MVP but I think we should do this sooner than later. We already have defined quite a bit of our own Network Pulse CSS - some would've be taken care of if we have `mofo-bootstrap` in place (plus we probably shouldn't have too much app specific CSS?).

**Comment by mmmavis** [comment]
Cool! I changed the title to "Use mofo-bootstrap"! 

Not sure if there's anything in the design file you need to change to match "mofo-boostrap" styling @kristinashu .

**Comment by kristinashu** [comment]
Excellent! Colors are from the bootstrap palette so they should work as is. I could possibly make the footer look more like the unified footer but it doesn't look like that is part of bootstrap yet anyways.

**Comment by xmatthewx** [comment]
@mmmavis – should we remove this from current milestones? save it for if and when we do a react refactor?

**Comment by mmmavis** [comment]
Network Pulse is already using Fira so I think we are fine without mofo-bootstrap for now. 

Is @kristinashu back today? If yes I can try adding mofo-boostrap but I will likely need design suggestion after I drop in mofo-bootstrap as tweaks need to be made.

**Comment by kristinashu** [comment]
@mmmavis yeah I'm back
