### ISSUE TITLE
Replace (+) with SVG

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#167]
The plus in the Add New button doesn't center perfectly on all devices. It rotates funky. We should probably create an SVG to replace it.

**Comment by kristinashu** [comment]
Is it not an SVG now? I see what you mean tho, it is off on mobile:

<img width="424" alt="screen shot 2016-08-12 at 2 01 19 pm" src="https://cloud.githubusercontent.com/assets/1068783/17636943/48c859f8-6095-11e6-882c-103c519ef8ca.png">

I've saved out new SVGs to test.
"icon add btn.svg" is the circle with the + cut out and "icon add.svg" is just the + on it's own.
[icon add btn.svg.zip](https://github.com/mozilla/network-pulse/files/416147/icon.add.btn.svg.zip)
[icon add.svg.zip](https://github.com/mozilla/network-pulse/files/416146/icon.add.svg.zip)

**Comment by kristinashu** [comment]
It spins properly in FF but in Chrome the + to x doesn't spin from the center, seems to turn from the top of the + 

The + and x are also slightly off centered within the circle in Chrome (good in FF).
