### ISSUE TITLE
Decide when to push from staging to production

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#168]
@xmatthewx @kristinashu @acabunoc @cadecairos We now have a staging instance: https://network-pulse.mofostaging.net/ (thanks Chris!) and we should decide when / how often we want to push things to production.

**Comment by cadecairos** [comment]
We shouldn't feel like we're constrained to pushing on a schedule. 

I think we should deploy features and fixes that we know work great on staging to production as soon as we know they're stable.

**Comment by xmatthewx** [comment]
Cool. After a review, a feature can move to master. Then flag someone to run the quality checklist, before moving to production.

**Comment by mmmavis** [comment]
👍
