### ISSUE TITLE
Discuss and document workflow

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#17]
Who submits an item? When? Why? What happens after? Let's explore these questions and more.  

I've drafted chart that I hope demonstrates some benefits of a unified filing system. https://docs.google.com/drawings/d/1pCSwZYQrBu1YtYQBgyaTCk3cAs_Ko7U2OYtNhHzF_Nk/edit

Comments and ideas welcome in comments here or the diagram.

**Comment by xmatthewx** [comment]
That is to be determined by us. Let's ideate, test, and discover an optimized solution to the problem: _Mozilla and our Network lack a coordinated means to file, discover, analyze, and share useful things with each other_. 

We currently have two prototypes. One for posting projects. One for sharing potential impact stories. Based on the results (let's discuss), let's plan the next iteration. I have a proposal (let's discuss). We also have a few tasks to help inform this, such as listing the things we already collect and/or share #12.

**Comment by xmatthewx** [comment]
Iterated on [the diagram](https://docs.google.com/drawings/d/1pCSwZYQrBu1YtYQBgyaTCk3cAs_Ko7U2OYtNhHzF_Nk/edit)

**Comment by xmatthewx** [comment]
depends on #48

**Comment by kristinashu** [comment]
@xmatthewx is this good to close?

**Comment by xmatthewx** [comment]
Good enough for now!
