### ISSUE TITLE
Implement detail view

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#175]
Based on https://github.com/mozilla/network-pulse/issues/151

Shown in the last few screens https://redpen.io/p/by8c797c413d39c620

### Initial thumbnail card changes:
- shortened intro (only the copy that appears on the form under "Description")
- the only buttons are 'Read more' which links to the detail view and Fav icon
- keep optional photo

<img width="175" alt="screen shot 2016-08-17 at 10 57 33 am" src="https://cloud.githubusercontent.com/assets/1068783/17747391/853c142e-6469-11e6-827f-e9f2d191ee0c.png">

### Detail view:
- "Back" button which links to thumbnail overview screen
- all copy available in the spreadsheet (in the following order: Description, Interest, Network connection, Origin, Get involved text followed by Get involved URL)
- note about Network Connection and Origin: Please add "Network Connection:" in front of the copy and then those two columns as a single paragraph
- "Visit" external link and Fav icon
- keep optional photo

<img width="269" alt="screen shot 2016-08-17 at 10 57 16 am" src="https://cloud.githubusercontent.com/assets/1068783/17747396/88b04ae4-6469-11e6-842c-48eb47629f85.png">

### Desktop view:
- wider card size than thumbnail view
![desktop - post detail 2x](https://cloud.githubusercontent.com/assets/1068783/17745384/74ef0b3e-6460-11e6-8bb3-6d78762c1f78.png)

**Comment by mmmavis** [comment]
❓ Question about what "back" link should do when

1.  user goes to detail view by clicking "read more" from search result
2. user uses the project link to go to detail view directly

**Comment by kristinashu** [comment]
Generally, the back button should go back to were the user came from (ex. Featured tab, Latest tab, Fav tab or Search results screen). If they're new then they should go to the landing screen (ie Feature Tab). So

1.  user goes to detail view by clicking "read more" from search result: should go back to Search results screen

2.  user uses the project link to go to detail view directly: should go to Featured screen

**Comment by mmmavis** [comment]
@kristinashu thanks for the clarification! 😎

**Comment by mmmavis** [comment]
depends on  https://github.com/mozilla/network-pulse/issues/67

**Comment by mmmavis** [comment]
@kristinashu 

> note about Network Connection and Origin: Please add "Network Connection:" in front of the copy and then those two columns as a single paragraph

Question about how to combine `Network Connection` and `Origin` together. Is each of the fields always in one paragraph? Are we adding `"Network Connection:"` as a header or more like adding "Network Connection:" at the beginning of the `Network Connection` info?

**Comment by kristinashu** [comment]
Yes, please combine the two fields into one paragraph. "Network Connection:" should just be at the beginning of the info (no special header treatment). Thanks!
