### ISSUE TITLE
Use universal footer

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#178]
Consider including: 
- Legal
- GitHub Repo
- About Pulse
- Mozilla logo, description, and link
- Contact email?

**Comment by kristinashu** [comment]
Based on footer in https://github.com/mozilla/mofo-bootstrap/issues/92

Here is a mockup:
<img width="316" alt="screen shot 2016-11-17 at 9 54 43 am" src="https://cloud.githubusercontent.com/assets/1068783/20400997/e7d2ed6c-acab-11e6-87bb-2e15a71f5e8c.png">

Links are:
- GitHub: https://github.com/mozilla/network-pulse
- Chat: https://chat.mozillafoundation.org/mozilla/channels/mozilla-chat-dev
- Email Us: mattheww@mozillafoundation.org
- Legal: https://www.mozilla.org/en-US/about/legal/
- License: https://creativecommons.org/licenses/by/4.0/

@xmatthewx does that work for you?

**Comment by kristinashu** [comment]
Actually, it will also need to have a link to our about page https://github.com/mozilla/network-pulse/issues/234:

<img width="317" alt="screen shot 2016-11-17 at 10 07 03 am" src="https://cloud.githubusercontent.com/assets/1068783/20401451/be437cee-acad-11e6-921a-24c7154ab0cb.png">

**Comment by xmatthewx** [comment]
This is great. 
 - I might be old fashioned, but I think I'd like to avoid spam from my address on the site. We could make a simple google form as contact form. 
 - I like the link to chat. I wonder what channel is best. Town Square? Production? I don't think many of us are in chat dev.  

And, we should mention CC license in the submission for. I'll go note that now...

**Comment by kristinashu** [comment]
Google contact for works for me and Town Square sounds nice and welcoming, I've updated the link above.

**Comment by mmmavis** [comment]
As an interim solution I made footer stayed at bottom of the page and applied background colour to it: https://pulse-mavis.herokuapp.com/favs

If the *new* footer is going to be an universal one (I saw a similar one on the Science site) I think we should probably create a `footer` component on [`mofo-ui`](https://github.com/mozilla/mofo-ui) and pull from it. Thoughts?

/cc @kristinashu @gvn

**Comment by kristinashu** [comment]
Yes, there is a ticket to add the footer as a component https://github.com/mozilla/mofo-bootstrap/issues/92 but not sure when that will actually happen.

**Comment by gvn** [comment]
Yeah, we would like to add the footer to `mofo-ui` but no one has started that work.

Volunteers are welcome! 😉

**Comment by aayushsanghavi** [comment]
Does this require knowledge of React? Is it to be done on the React branch?

**Comment by gvn** [comment]
We actually have someone working on it right now, but we may need help adding the footer to our various sites soon.

**Comment by ryanwarsaw** [comment]
@aayushsanghavi Anything with the ```v2 (upcoming)``` tag means it's for the React version. Issues with the v1 tag mean it's for the current version, which is not the react version.

**Comment by mmmavis** [comment]
Hey @aayushsanghavi 😃  we have been focusing on v2 work since we are aiming to have it out early Feb. After we get your [PR for v1](https://github.com/mozilla/network-pulse/pull/315) merged (I will review it again soon) we probably won't much time to tackle v1 tickets unless it's an urgent thing that needs to be fixed asap.

**Comment by mmmavis** [comment]
@xmatthewx are we still good with having a Google Form for "Email Us" link? Now I think about it I think having GitHub and Chat should be sufficient enough. Thoughts? @kristinashu

**Comment by xmatthewx** [comment]
Github and Chat both require accounts and aren't great if someone has a quick comment. It's not clear who manages our desk.com inbox or that we are prepared to handle that. 

Any reason to not use a simple form to spreadsheet that notifies a few of us? We can always remove it if it gets nutty. I think we can remove chat. I don't think we see network people joining us there, do we?

**Comment by mmmavis** [comment]
@xmatthewx no particular reason 😂 Google forms require accounts as well though most people should have one already. I just thought if it was me I wouldn't use the form since I'm active on Github and Chat.

Ah, and I just thought of something - if a non Mozilla staff user tries to log in to Pulse he/she will see a login failed screen though at that point he/she is logged in into **Google** so when he/she submits the feedback form that person is seen as an authenticated "Google" user (and not **Pulse** user). Not sure if this is a good thing or bad thing (can confuse people) but I just wanna bring it up.

**Comment by xmatthewx** [comment]
Unless I'm mistaken, Google Forms have the option to capture submitters identity, or not. We should keep that off, and not track it. People can just type out their email address and submit.  They should need an account or to be logged in.

**Comment by mmmavis** [comment]
@xmatthewx 

Cool to know! Though I don't use Google Form enough to verify that 😉 Can you create the form and put the link here please? Thanks! I'll add it to the footer so we can test it out along with login.

**Comment by xmatthewx** [comment]
I shared access with you. Shortlink to form: https://mzl.la/pulse-contact

**Comment by mmmavis** [comment]
current status: I'm waiting for [my PR on mofo-ui](https://github.com/mozilla/mofo-ui/pull/51) to be merged and published first.

**Comment by xmatthewx** [comment]
Looks like this has been merged @mmmavis. Not critical for launch, but it'll be sweet to see it there.
