### ISSUE TITLE
Design a share button

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#18]
Users should be able to share a direct link to a single entry's detail view. Design a button the enables copy-paste and share via email and twitter. Note: auto copy-paste requires flash in some browsers. We'll need to benchmark [tech options](https://github.com/zeroclipboard/zeroclipboard/issues/171) and best practices for use on desktop and mobile. 

Depends on #14 #15

**Comment by kristinashu** [comment]
Short term solution in https://github.com/mozilla/network-pulse/issues/39#issuecomment-234328373

Longer term design will eventually be done in #32
