### ISSUE TITLE
Can't un fav a card on mobile

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#183]
On my iPhone in FF, Safari and Chrome. If I Fav something and tap the heart icon again to un favorite it, the icon still looks selected (filled in pink). However, it is removed from my fav list.

**Comment by mmmavis** [comment]
is it on staging or production?

**Comment by kristinashu** [comment]
Production. But I can check staging now.

**Comment by mmmavis** [comment]
i'm guessing it's the lingering hover state that's causing the confusion

**Comment by kristinashu** [comment]
Here's a sprite. There's 1px between the two icon states.

[icon fav sprite.svg.zip](https://github.com/mozilla/network-pulse/files/425929/icon.fav.sprite.svg.zip)

**Comment by kristinashu** [comment]
Or we can use the same icon (font awesome?) as the schedule app, since it seems to work.

**Comment by mmmavis** [comment]
@kristinashu yea font awesome would work, but I wonder if we should load a new css file in just for one icon. Is there other font awesome we can make use of?

**Comment by kristinashu** [comment]
No, I guess we only use a few icons

**Comment by mmmavis** [comment]
haha browsers  ┐(´д`)┌
I will think about whether to use font awesome or JS hacks to solve this mobile specific issue. blah

**Comment by kristinashu** [comment]
Maybe for now we could just not have a hover state? Would that fix it?

**Comment by mmmavis** [comment]
@kristinashu haha yea that is actually the easiest and less hacky fix!

**Comment by mmmavis** [comment]
I think I'm just gonna remove hover state CSS for now! Fix is on its way!

**Comment by kristinashu** [comment]
Cool, thanks!
