### ISSUE TITLE
Update 'categories' to 'tags' in search bar

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#184]
Close search bar icon gets cut off because hint text is too long. Please update 'categories' to 'tags' in search bar to shorten.

<img width="426" alt="screen shot 2016-08-18 at 2 02 28 pm" src="https://cloud.githubusercontent.com/assets/1068783/17790684/78d58146-654c-11e6-8545-16a3b95290fd.png">

**Comment by xmatthewx** [comment]
Let's set the width and clip overflow instead of changing the word. There might be other devices that will have the same problem even if we pick shorter words.

**Comment by xmatthewx** [comment]
Reopening to revisit in a future milestone. See https://github.com/mozilla/network-pulse/issues/184#issuecomment-240865662

**Comment by mmmavis** [comment]
The `::placeholder` pseudo element [works poorly cross browsers](http://caniuse.com/#feat=css-placeholder). With the `text-overflow: ellipsis;` trick only desktop FF works as expected. On other browsers/mobile text gets chopped when it reaches the width we set for the input box.

I can update the "tags" to "categories" and add the `text-overflow: ellipsis;` trick, just a note that it will only work on FF desktop.

**Comment by mmmavis** [comment]
obsolete. closing.
