### ISSUE TITLE
Fav tab link not highlighted

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#187]
On the production site, fav tab link not being highlighted when you are on the Fav tab.

**Comment by mmmavis** [comment]
This works fine if user has no faved project. I think this is related to how Fav Tab is being rendered... not simply a CSS problem. See screencap below for error being thrown when user has fav projects.

<img width="1059" alt="screen shot 2016-08-19 at 12 27 26 pm" src="https://cloud.githubusercontent.com/assets/2896608/17821792/566730c0-6608-11e6-93b1-3d1ec692e308.png">

**Comment by mmmavis** [comment]
This will be fixed when fix for https://github.com/mozilla/network-pulse/issues/148 is in.

**Comment by xmatthewx** [comment]
fixed!
