### ISSUE TITLE
Add id field to spreadsheet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#188]
Instead of generating project `id` [on the fly](https://github.com/mozilla/network-pulse/blob/master/js/pulse.js#L141-L146) when we process & feed spreadsheet data into the app, we should generate `id` **on** the spreadsheet so that each spreadsheet row has an `id` field.

We can use the [`N` function](https://support.google.com/docs/answer/3093357) that Google provides, along with the [`SUBSTITUTE` function](https://support.google.com/docs/answer/3094215?hl=en) on the `timestamp`

e.g., 

when `timestamp` is `1/26/2016 11:44:22`...

`N(1/26/2016 11:44:22)` returns `42395.48914`
`"p"&SUBSTITUTE(N(1/26/2016 11:44:22),".","")` returns `p4239548914` <<< we can use this `id` for the app

@xmatthewx @acabunoc @cadecairos comments? This is still not human readable but so far this is the only way we can find to auto generate an "unique" id on Google Spreadsheet. (there shouldn't be any duplicated `id` unless there are multiple entries submitted at the same time (millisecond precision).

Note that if we agree to make this change, projects that have been fav'ed will be reset on user's device since we are using a different formula to generate `id`.

**Comment by xmatthewx** [comment]
Can the N function work with form submissions? Or will it require copy-paste from admins in the spreadsheet? If editing an entry via the form updates the timestamp, won't it change this field as well? 

What problem does this change solve?

If our pilot test goes well, we can looking into building this on django. I'd rather wait and invest on that, unless there's a critical problem right now.

**Comment by mmmavis** [comment]
It's just generally `id` should be included in the "database" level, not generated on-the-fly in app.

The formula can be used with variable, e.g., `p"&SUBSTITUTE(N(B2),".","")` note that B2 references to cell B2. I can test to verify but I believe and I hope this won't require manual copy and paste every time a new entry is in. My plan is to 1) add a new column `id` to spreadsheet 2) apply the formula`p"&SUBSTITUTE(N(TIMESTAMP_CELL_NUMBER),".","")` to every cell in that column.

If we have plans to move away from Google Spreadsheet after the pilot test (if it goes well 👍 ), I'm fine closing this ticket.

**Comment by mmmavis** [comment]
Google Spreadsheet is acting funky to me now, will tackle this later today.

**Comment by mmmavis** [comment]
What a bummer! My proposed solution didn't work! 😢 

I created a new column `id` in the spreadsheet and applied `=IF(ISBLANK(B2:B),,"p"&SUBSTITUTE(N(B2:B),".",""))` to column B of the all rows. IDs were generated as expected for existing rows... however when new form response came in a new row got inserted to the spreadsheet and our preset formula was overwritten - leaving `id` of the entry blank. 😭 An [online tutorial](https://www.youtube.com/watch?v=bwNJsZ5IrPA) suggested creating a new sheet and utilizing `query` formula as a workaround. This approach adds a ton of complexities to our workflow so it's best to avoid this route.

Conclusion: let's stick with what we have now (generate id on the fly in app)

Blah 😷

**Comment by acabunoc** [comment]
Sad! I've done this before using a trigger: http://webapps.stackexchange.com/a/15452 (not just the formula)

**Comment by cadecairos** [comment]
*mumbles something about using PostreSQL* 😄

**Comment by acabunoc** [comment]
HAhahhaha @cadecairos

**Comment by xmatthewx** [comment]
It'll be ok. The pilot test will rock, and then we can build a real backend with an abundance of confidence.

**Comment by mmmavis** [comment]
Thanks for the link @acabunoc ! I wanted to avoid using script as columns/rows/cells might be shuffled around and it would require us to ensure column/row/cell references in the code are **always** up to date. Another thing with script is I'm worried it's not visible for people (other than us devs) what's happening "in the background", whereas formulae can be easily discovered.

@cadecairos 😂
