### ISSUE TITLE
Gather requirements and set approach for a share button

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#19]
Depends on design #18. Design depends on tech constraints as well. 

We will want to explore options for copy-paste that work across browsers and devices (or display a field for users to manually copy-paste). This should inform design constraints. See utility and discussion here: https://github.com/zeroclipboard/zeroclipboard/issues/171

**Comment by mmmavis** [comment]
First iteration is done. I create a follow-up ticket for enabling preselecting text on mobile devices: https://github.com/mozilla/network-pulse/issues/42
