### ISSUE TITLE
QA and push to production

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#198]
It looks like the gh-pages branch is about 2 weeks behind the master branch. Is there anything specific blocking an updates?

**Comment by mmmavis** [comment]
let's wait for https://github.com/mozilla/network-pulse/pull/197 gets merged first. then we will update the production site.

**Comment by xmatthewx** [comment]
Did QA (and updated list in wiki). Things looking great! 

3 things are unchecked below because i want to file issues. But they aren't actually broken. Nothing critical. 

Let's push to production! 💯 

### Splash screen
 - [x] shows briefly while app loads

### Default view (Featured)
 - [x] `Featured` is displayed and highlighted in menu
 - [x] cards are sorted by most recent at the top
 - [x] cards display in columns to fit browser width responsively
 - [x] cards contain title, name and date, a paragraph or two of text, read more link, fav button

### Item card
 - [x] `Read more` button opens the detail view, hides other cards
 - [x] Fav icon shows selected state when tapped
 - [x] Images appear, fit to the top of some cards

### Detail view
 - [x] Visit button opens a external link in a new tab
 - [x] Get Involved button opens an external link in a new tab
 - [x] Link icon button reveals a URL to share (selected to copy on desktop)
 - [x] Fav icon shows selected state when tapped
 - [x] Fav state persists between detail and gallery view

### Item URL shared. User opens link.
 - [x] single item detail view displayed
 - [x] `back` button appears in nav bar

### Search 
 - [x] search bar appears at top of all views
 - [x] search includes search icon left aligned
 - [x] placeholder text says "Search keywords, people, tags ...

#### Search Active (tap on search bar)
 - [x] all projects disappear
 - [x] nav bar is hidden
 - [x] add new project button is hidden
 - [x] if on Issues Tab, issues buttons are now hidden
 - [ ] clear `X` button appears on right side

#### Search Typing
 - [x] hint text is hidden
 - [x] only relevant cards are visible
 - [x] shows "not found" messages if there's no matching project

#### Search Exit
 - [x] exit search by pressing `esc` or tapping `X` icon on the right
 - [x] nav bar and search placeholder text returns
 - [x] returns to previous tab with nav highlighted
 - [x] URL does not include a search query

#### Search Share Query
 - [x] while searching, press enter or tap outside search bar to update URL with search query
 - [x] load search URL yields search results

### Add Post Icon
 - [x] Opens form
 - [x] Add icon turns to Close icon
 - [x] Form scrolls as expected, close icon doesn't move
 - [x] Tap close icon to return to previous state
 - [x] Item is added to the spreadsheet
 - [ ] Card is added to the site without browser refresh

### Featured view
 - [x] this is default view for a new visitor
 - [x] only featured cards load
 - [x] cards are sorted by most recent at the top

### Recent View
 - [x] all cards load
 - [x] cards are sorted with most recent at the top

### Favs View
 - [x] shows message if no items have been faved
 - [x] shows all faved cards
 - [x] most recent project should appear first in the list
 - [x] fav icon shows selected state
 - [x] clicking on the heart un-favs it 

### Issues view
 - [ ] on landing here users see message about issues
 - [x] tapping on an issue only shows cards related to that issue
 - [x] cards are sorted by most recent at the top
 - [x] only one issue can be displayed at a time (though items can appear in multiple issues)

### 404 screen
 - [x] shows error message for "project not found" URLs (e.g, https://mozilla.github.io/network-pulse/?id=p1111111111_i_do_not_exist)

**Comment by xmatthewx** [comment]
@mmmavis – I think we're good to push this all to production. Yay.

**Comment by mmmavis** [comment]
Awesome. Will do it now.
