### ISSUE TITLE
Enable Short links for search query URLs 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#199]
Short links work for Project IDs but not Search queries. It's not critical, but it would be helpful if it's an easy fix. 

this: https://mzl.la/pulse?id=p1470188181000
points to: https://mozilla.github.io/network-pulse/?id=p1470188181000

This: https://mzl.la/pulse?keyword=inclusion
Doesn't point to: https://network-pulse.mofostaging.net/?keyword=inclusion

cc @mmmavis

**Comment by mmmavis** [comment]
If https://mzl.la/pulse is meant to point to the production site, i.e., https://mozilla.github.io/network-pulse , anything on https://mzl.la/pulse should also point to the production site.

**Comment by xmatthewx** [comment]
🐑 🐐 ugh. my mistake. forgot that search URLs weren't on production yet. please ignore me.

**Comment by mmmavis** [comment]
heh 🍻
