### ISSUE TITLE
Plan for Pulse at Mozfest

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#203]
There's interest in leveraging Pulse to capture awesome things at Mozfest. Let's discuss possibilities and design how they will show up. 

 - I believe that @acabunoc is in conversation with @Saallen about how it fits within facilitator training and shareouts. 
 - @kristinashu – let's discuss how a kiosk could be used for browsing. Let's also discuss how the event app might link to it ... maybe via pathways (link to related search query).
 - We can also connect with @liberaliscomputing to see how this might overlap with [network mapping](https://github.com/liberaliscomputing/network-mapping-js).

**Comment by xmatthewx** [comment]
https://github.com/MozillaFoundation/Mozfest2016_production/issues/156

**Comment by xmatthewx** [comment]
@mmmavis – we plan to have a kiosk for MozFest. We probably don't want attendees to add projects. 

Two options:
 - Add a column for moderation (would slow down new legit items)
 - Fork the code and remove the Plus button for the kiosk. (We can hide the URL and kill the repo after MozFest).

**Comment by mmmavis** [comment]
@xmatthewx questions:

1. will attendees be able to submit entries at the kiosk?
2. other than having a kiosk, how else do we plan to share out Network Pulse at MozFest? (e.g., inform wranglers/session facilitators about this app?, ..etc)

**Comment by mmmavis** [comment]
@xmatthewx we are generating `id` based on `timestamp` of each entry. Does editing in spreadsheet update a row's `timestamp` ?

**Comment by Saallen** [comment]
Can I ask why you wouldn't want ppl to add projects at the festival? Seems
like an easy way to drive traffic to the site...

**Comment by xmatthewx** [comment]
1. No. I think entries via a kiosk will be too unpredictable and likely to include many Test 123 items cluttering up the space. 
 2. ...
   - I will invite Sci fair participants to submit to a clone of the form I created, before fest begins. I will manually copy entries to our db after review. 
   - We could invite facilitators to post session outputs directly to Pulse OR to the cloned form for review by me and wranglers.
   - Anyone who visits Pulse on their own device could post.  I think that's okay. I will just need to monitor activity. I'd rather not lock it down for the weekend, but we could do that, and require entry to form via direct link.

**Comment by mmmavis** [comment]
> No. I think entries via a kiosk will be too unpredictable and likely to include many Test 123 items cluttering up the space. 

@xmatthewx ahahahahahahah how did you know that's exactly what I was concerning about. And "Test 123" is exactly what I would put if I was a MozFest participant checking out Network Pulse. 😂 

To your point 2, let's have a quick chat after the MozFest stand next week?

**Comment by xmatthewx** [comment]
Closing this. Issues filed. Tracking meta for all the issues here: https://github.com/mozilla/network-pulse/issues/225
