### ISSUE TITLE
File Working Open Workshop

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#210]
Add Wow to Pulse. Either the whole thing, or a few of the handout/activities. Or both. http://mozillascience.github.io/working-open-workshop/

**Comment by acabunoc** [comment]
I'd like to file individual lessons. Will do this soon.

**Comment by acabunoc** [comment]
* [x] [Open Project Communication](https://mozilla.github.io/network-pulse/?id=p1474472416000)
* [x] [Introduction to Roadmapping](https://mozilla.github.io/network-pulse/?id=p1474472509000)
* [x] [Wrangling Web Contributions](https://mozilla.github.io/network-pulse/?id=p1474472634000)
* [x] [GitHub for Collaboration on Open Projects](https://mozilla.github.io/network-pulse/?id=p1474472747000)
* [x] [Getting Started with Codes of Conduct](https://mozilla.github.io/network-pulse/?id=p1474472873000)
* [x] [Running Sprints and Community Events](https://mozilla.github.io/network-pulse/?id=p1474472973000)
* [x] [Personas and Pathways](https://mozilla.github.io/network-pulse/?id=p1474473081000)
* [x] [Your Data Can Live Forever: How to Plan for Data Reuse](https://mozilla.github.io/network-pulse/?id=p1474473170000)
