### ISSUE TITLE
Privacy policy and Terms of service

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#214]
Post-pilot, before any public use, we'll need to add links to legal things.

**Comment by kristinashu** [comment]
Is the usual Mozilla Legal stuff ok? https://www.mozilla.org/en-US/about/legal/

This is tied to adding our universal footer https://github.com/mozilla/network-pulse/issues/178

**Comment by xmatthewx** [comment]
The usual website links are good for now. When we start promoting submissions from non-staff, we should chat with Legal about content policy.

**Comment by kristinashu** [comment]
Covered in footer ticket https://github.com/mozilla/network-pulse/issues/178
