### ISSUE TITLE
Bug with link to load single item

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#217]
I shared a link to an individual item with @simonwex. The item did not load. I believe he tried refresh without luck. He searched for the item, then viewed it. I believe he was then able to load via URL. 

Link shared: 
 - first try: https://mzl.la/pulse?id=p1474298299000
 - second try: https://mozilla.github.io/network-pulse/?id=p1474298299000

@simonwex – what browser? any edit or additions to this description?

**Comment by mmmavis** [comment]
@xmatthewx that project you were trying to visit probably doesn't exist anymore. I tried with another project and it worked out fine. Please check links below:

<img width="322" alt="screen shot 2016-10-07 at 12 06 12 pm" src="https://cloud.githubusercontent.com/assets/2896608/19202320/8f50873e-8c86-11e6-9250-a57b74ab588e.png">

https://mozilla.github.io/network-pulse/?id=p1475792358000
https://mzl.la/pulse?id=p1475792358000

**Comment by mmmavis** [comment]
@xmatthewx we are generating `id` based on `timestamp` of each entry. Does editing in spreadsheet update a row's `timestamp` ?

**Comment by xmatthewx** [comment]
That project does still exist and the link works for me on mobile and desktop chrome. Timestamp doesn't update on edit (only edits via form, which we have disabled).

This is a hiccup that might not be easy to repeat. A race condition in loading and routing? Maybe only affects users who don't have site in cache? Just a wild guess.

**Comment by mmmavis** [comment]
@xmatthewx which project is it? let me see if i can reproduce it.

**Comment by xmatthewx** [comment]
Thanks. The links in my first comment.

**Comment by mmmavis** [comment]
@xmatthewx sorry I've been more specific - do you remember what the project is called (e.g., project title)? Neither of your 2 links works for me so I would like to go in to the spreadsheet and see if there's any data format problem.

<img width="1104" alt="screen shot 2016-10-07 at 1 56 45 pm" src="https://cloud.githubusercontent.com/assets/2896608/19205221/f69cca2e-8c95-11e6-9175-3efe33f3e726.png">

**Comment by xmatthewx** [comment]
Brilliant. Well, take notes ... we are in the middle of observing the bug. Search for "Merits of Thimble" and view it. Is your URL the same?

**Comment by mmmavis** [comment]
"Merits of Thimble" is https://mozilla.github.io/network-pulse/?id=p1474309099000 for me (vs your https://mozilla.github.io/network-pulse/?id=p1474298299000 )

**Comment by xmatthewx** [comment]
Well, that's strange. I think we're getting different timestamps from google. Ugh. Couldn't be timezones, could it? Here's the json I get directly from the sheet URL: 
https://gist.github.com/xmatthewx/db8ce54529781dcd6b96786505b029bf

**Comment by mmmavis** [comment]
Thanks for providing that `.json`. Maybe Google shows `timestamp` based on viewer's timezone... ? Interesting... I'll investigate and see if that's true. 🙄

**Comment by mmmavis** [comment]
@xmatthewx I did some research and found out we can set timezone and locale for each Google Spreadsheet: `File -> Spreadsheet setting...`.

(our current setting)
<img width="590" alt="screen shot 2016-10-07 at 2 57 08 pm" src="https://cloud.githubusercontent.com/assets/2896608/19206591/cb4f51bc-8c9e-11e6-8488-4f472ddea0fe.png">

This means the `timestamp` we see shouldn't be different since the spreadsheet is in Eastern Time. 

I'm having some trouble looking for values in the json blob you provided. Can you help verify if this is the `timestamp` you see for `Merits of Thimble`

<img width="276" alt="screen shot 2016-10-07 at 2 58 19 pm" src="https://cloud.githubusercontent.com/assets/2896608/19206613/f07f2d4a-8c9e-11e6-96be-e001706228ca.png">

**Comment by mmmavis** [comment]
I converted the `id` you got (1474298299000) back to `timestamp` and it gave me `2016-09-19T15:18:19.000Z` . 4 hours of difference... how is that possible? Isn't Brooklyn time always 3 hours ahead of Vancouver time? 😨

**Comment by xmatthewx** [comment]
Thanks @mmmavis. 

### Plan A

Fix timestamp madness
 - Let's see when we're converting timestamp to confirm we're both receiving same universal timestamp from sheets
 - If we do, we can just remove non-alphanumeric characters and use the string as ID without converting time format via js
 - If we don't, we can file a grievance with google and move on to plan B....

### Plan B

I propose that we...
 - create a new column for ID
 - only display projects that include an ID
 - as moderator, I will manually assign an ID to approve an item
 - for now, I can just start and end my day with a round of moderation

**Comment by mmmavis** [comment]
(the deprecated though still working) Google API does return `timestamp` exactly the same as what it shows on the spreadsheet, e.g., `9/26/2016 12:59:01`

@xmatthewx  Let me know if turning `timestamp` into `id` looks good to you, e.g., `9/26/2016 12:59:01` --> `p092620161259001`. Note that the precision is to seconds, not miliseconds.

**Comment by mmmavis** [comment]
@xmatthewx fix is on staging site.

Let me know if https://network-pulse.mofostaging.net/?id=p09202016115432 shows you "Open Innovation Toolkit"

**Comment by xmatthewx** [comment]
It worked as expected. 👍 

This link should take you to the Wayback Machine: https://network-pulse.mofostaging.net/?id=p092720161800933

**Comment by mmmavis** [comment]
lovely. let me update production app now!
