### ISSUE TITLE
Discuss Creator Field

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#222]
Hive Chicago posted several interesting assets to Pulse. The assets are great, but the team seemed to hit a challenge with the Creator field. It appears that they have a desire or need to give formal attribution (and links) to funders and partners. 

Let's discuss their challenges and requirements and then explore solutions. 

cc @samueledyson @annmarie123 @kristinashu 

<img width="1015" alt="screenshot 2016-10-18 16 22 43" src="https://cloud.githubusercontent.com/assets/53411/19494963/6adf7802-954f-11e6-8b00-34663e6d1ecb.png">

**Comment by kristinashu** [comment]
We've decided to truncate the creator field and move the additional info to the description field. 

Example https://mozilla.github.io/network-pulse/?id=p10072016153855

**Comment by xmatthewx** [comment]
Let's discuss in a bit more detail. 

We will want to capture people and institutions connected to these projects as discreet data. This will allow us to link to all projects created by Jane Doe, or supported by ABC Foundation, for example. 

I'm not concerned with links out to partners. That's out of scope, and can be handled by each project's own site if needed. People can clutter their descriptions with that info if they want. 

Entering creators/partners/contributors could be a simple input field for one entry with a button below to add another entry. We _could_ ask people to specify if it's an individual or group/institution, but that's complicated and probably not necessary.

**Comment by xmatthewx** [comment]
I think this is resolved and reflected in the new DB development. cc @alanmoo
