### ISSUE TITLE
Prepare kiosk computer for Mozfest

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#224]
We'll have an iMac or mac mini https://github.com/MozillaFoundation/Mozfest2016_production/issues/199

To set up as Kiosk, let's look at Firefox addons, such as: 
- [Custom Style Script](https://addons.mozilla.org/en-US/firefox/addon/custom-style-script/) to hide the Add New button 
- [Reset Kisok](https://addons.mozilla.org/en-US/firefox/addon/reset-kiosk/) to reset homepage after period of inactivity

We'll also need to create a new mac user to optimize desktop and minimize access to other apps. 

Anything else?

**Comment by mmmavis** [comment]
There's also https://addons.mozilla.org/en-US/firefox/addon/mfull/ . I just tried it but it made my Firefox behave buggy. Not sure if it's cuz I have too many tttttaabbbbbs open. 👀 

I'll give [Custom Style Script](https://addons.mozilla.org/en-US/firefox/addon/custom-style-script/) and [Reset Kisok](https://addons.mozilla.org/en-US/firefox/addon/reset-kiosk/) a try now.

**Comment by mmmavis** [comment]
Dumb me... I should've tested these extensions using a guest account. "Reset Kisok" has effectively killed my browser open tabs and windows and Firefox is unable to restore them. 😭 

Anyways, I've found a combo that we can use for our kiosk:

### 🔶 Log in using a guest account on Mac

### 🔶 Set Network Pulse as the default homepage of Firefox

- enter `about:preferences` in Firefox's URL bar
- 'show my home page' when Firefox starts
- set `https://mozilla.github.io/network-pulse/` as the homepage
 
<img width="1005" alt="screen shot 2016-10-24 at 3 14 24 pm" src="https://cloud.githubusercontent.com/assets/2896608/19665961/9936e328-99fc-11e6-80b5-f4a5c23bf84b.png">


### 🔶  [mFull: Full Screen Mode for Firefox](https://addons.mozilla.org/en-US/firefox/addon/mfull/) 

- force full screen mode
- hide bookmark bar
- hide toolbar
- hide sidebar

<img width="575" alt="screen shot 2016-10-24 at 3 02 22 pm" src="https://cloud.githubusercontent.com/assets/2896608/19665832/e4adc124-99fb-11e6-97b1-282291c139d0.png">
<img width="573" alt="screen shot 2016-10-24 at 3 02 39 pm" src="https://cloud.githubusercontent.com/assets/2896608/19665836/e7c01498-99fb-11e6-941e-df03c632bc17.png">
<img width="573" alt="screen shot 2016-10-24 at 3 02 49 pm" src="https://cloud.githubusercontent.com/assets/2896608/19665840/eb1ce18e-99fb-11e6-8f2c-2a53baafd333.png">



### 🔶  [Reset Kiosk](https://addons.mozilla.org/en-US/firefox/addon/reset-kiosk/)

- reset homepage after period of inactivity
- disable context menu

<img width="450" alt="screen shot 2016-10-24 at 3 04 09 pm" src="https://cloud.githubusercontent.com/assets/2896608/19665847/f2508f14-99fb-11e6-9826-de97e2fc427b.png">



### 🔶  [Custom Style Script](https://addons.mozilla.org/en-US/firefox/addon/custom-style-script/)

- add CSS to hide the Add New button 

<img width="1167" alt="screen shot 2016-10-24 at 3 11 09 pm" src="https://cloud.githubusercontent.com/assets/2896608/19665883/238ac270-99fc-11e6-82e0-5f1a5202834d.png">

**Comment by xmatthewx** [comment]
thanks a million for exploring this!!!!! 🚑 🚸  :medal_sports:   :taco: 🍻 🍕

**Comment by xmatthewx** [comment]
@mmmavis – any lessons learned to note before we close this?

**Comment by mmmavis** [comment]
keyboards, mouses, cables, plugs, and power outlets can be very finicky 😉 

thanks for setting up the booth at MozFest @xmatthewx 👍

**Comment by xmatthewx** [comment]
@alanmoo - can you link to your auto-scroll gist here?

**Comment by xmatthewx** [comment]
@mmmavis – no, no. thank you!

**Comment by alanmoo** [comment]
https://gist.github.com/alanmoo/4b47aad61a2e661bdac700ada5884a5a - time variables can be adjusted at the top. There's also a logic bug somewhere that eats time.

**Comment by xmatthewx** [comment]
Yum. Time tastes good. 🍴  🍗
