### ISSUE TITLE
Gather Mozfest Science/Demo projects 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#226]
Gather MozFest Science fair and closing demo projects. 
- [x] draft [message to participants](https://public.etherpad-mozilla.org/p/science-fair-pulse)
- [x] send message Oct 21 & Oct 27 to [sci fair group](https://docs.google.com/spreadsheets/d/1TJ8mMm0K7FYpstGWLLZJLdv8lkbrZbJ4upDf-iloz3I/edit#gid=140327018)
- [x] review & merge submissions
- [x] send  message Sunday to [demos group](https://docs.google.com/spreadsheets/d/1TJ8mMm0K7FYpstGWLLZJLdv8lkbrZbJ4upDf-iloz3I/edit#gid=369053853)
- [x] reivew & merge submissions

**Comment by xmatthewx** [comment]
@acabunoc – there are about 25 projects listed in the science fair doc. If you can review my [message](https://public.etherpad-mozilla.org/p/science-fair-pulse), I'll send it out tomorrow. We can send again next Thurs.

**Comment by acabunoc** [comment]
@xmatthewx  Added a couple notes, looks good 👍

**Comment by xmatthewx** [comment]
done.
