### ISSUE TITLE
Empty Favs view missing helper text

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#227]
Before a user adds an item to their Favs, that view should show helper text in the design below. 

Bug? Enhancement? I believe this was implemented before. Maybe lost in a merge. 
### current view

<img width="340" alt="screenshot 2016-10-26 11 59 16" src="https://cloud.githubusercontent.com/assets/53411/19723564/b80cf094-9b73-11e6-9016-1128f65a4015.png">
### helper text

![pulse-empty-favs](https://cloud.githubusercontent.com/assets/53411/19723591/d4facafa-9b73-11e6-883f-4c34f36402a1.png)

**Comment by mmmavis** [comment]
@xmatthewx do you remember what the steps to reproduce were? It's working for me on https://mozilla.github.io/network-pulse/ . Maybe you fav'ed and unfav'ed something? Let me know so I can debug it!

![screen shot 2016-10-27 at 11 27 12](https://cloud.githubusercontent.com/assets/2896608/19763939/5ae82972-9c38-11e6-94fe-d2aaad9ddfe9.png)

**Comment by xmatthewx** [comment]
You're right. I must have fav'd and unfav'd. It's not ideal that we lose the message, but there's no urgent need to fix this. We can keep it in the backlog. I'll unassign and relabel.

**Comment by mmmavis** [comment]
v1 bug. closing.
