### ISSUE TITLE
Move images to AWS

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#228]
The Pulse prototype uses a temp solution for image storage. It's very speedy, but might not survive a surge in traffic. We should move this to AWS in the not too distant future. 
- [x] Create storage bucket https://github.com/MozillaFoundation/mofo-devops/issues/430
- [x] Download all the current images
- [x] Resize anything unnecessarily large
- [x] Update source URLs in spreadsheet

**Comment by xmatthewx** [comment]
@alanmoo @cadecairos – we should probably do this first. (Look how good I was, filing this in the thick of MozFest installation!)

**Comment by alanmoo** [comment]
Where are the current images being stored?

**Comment by cadecairos** [comment]
I think we're hot linking many of them

**Comment by alanmoo** [comment]
Yeah, I wrote a script to pull them all with helpful file names, I'll optimize them tomorrow to prep for AWS

**Comment by xmatthewx** [comment]
Thanks @alanmoo. Can you also drop a zip archive on gdrive? Later, we designers might want crop items for uniform height, at least for featured items. But we can worry about that later. 

> I think we're hot linking many of them

There's nothing to see here. Move right along. :dark_sunglasses:

**Comment by alanmoo** [comment]
https://drive.google.com/open?id=0B1Vhh4IAm7XXQVIxdVF4RlU1ZzA

**Comment by mmmavis** [comment]
I've updated image URLs in the spreadsheet. See list of new URLs: https://github.com/MozillaFoundation/mofo-devops/issues/430#issuecomment-262837943. Note that original URLs are in a spreasheet column called "Backup Thumbnail URL". Feel free to remove it if it's no longer needed.

**Comment by xmatthewx** [comment]
thanks @mmmavis ! 👍 💯 

I think we can close this issue. Work to wire up django can be filed when ready.
