### ISSUE TITLE
Create an overview deck

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#23]
From https://github.com/mozilla/network-pulse/issues/5

Deliverable: Small slide deck that... 
 - Synthesizes and simplifies the research and recommendations in [this doc](https://docs.google.com/document/d/1SAAuPgOaVqpQorrbD0vZSnf8wHHYjddPyYrkrFj72kQ/edit#heading=h.g9fpre8yvc04).
 - Proposes an H2 roadmap (e.g. UX iteration w/ Issue integration; Program process plan for input; Mozfest kiosk test; EOY review, report and recommendations)
 - Goal: Make it easy to communicate with all staff this project’s what, why, when, and how (big picture, 6-10 slides)

**Comment by kristinashu** [comment]
WIP https://docs.google.com/presentation/d/15rBpuLWnNKJy6jG5PSP2dRkZWGwZ-YR_nuqEwnakRUA/edit#slide=id.gd58133b56_0_69

**Comment by xmatthewx** [comment]
v1 one is done. will update as needed.
