### ISSUE TITLE
Define Thumbnail proportions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#230]
Currently, item thumbnails are a wild variety of sizes and shapes. We should choose ideal proportions. 

For resizing large file sizes with @alanmoo, I suggested we cap things at 1200 x 630, the recommended size for an image that accompanies a Facebook link.  We can try that proportion and then adjust to suite our specific design.

**Comment by kristinashu** [comment]
1200 x 630 seems very large considering we only need about half that size for the Pulse feed. What if instead we had a more general Pulse image we would use for all shares (rather than a different image depending on the project)?

**Comment by alanmoo** [comment]
I like the idea of a single image for all pulse shares, but don't forget about high res displays- 1200 then becomes exactly what we need.

**Comment by xmatthewx** [comment]
We don't need to change how big we display image. Just storing a little extra resolution for display on 2x screens or if we change individual item layout later.

**Comment by xmatthewx** [comment]
this is done
