### ISSUE TITLE
Links to detail view

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#231]
Currently, clicking on the "read more" links to the detail view. We should expand this so clicking on the card image, title or read more links to the detail view.

**Comment by mmmavis** [comment]
I removed the `v1` tag as I'd like to focus on getting v2 done than adding enhancement to v1. I will get this implemented for v2.

**Comment by mmmavis** [comment]
Done! https://pulse-react.herokuapp.com
