### ISSUE TITLE
Spin up back end repo

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#232]
Create a django project with basic schema.

Presumably this should be a separate repo- thoughts @Pomax?

**Comment by Pomax** [comment]
We can either set up a new repo, or we can use this repo but start life in a different branch. I see the following steps here:

- [ ] set up a new repo or dedicate a branch on this repo to the django work
- [ ] "install" Django 1.10.x
- [ ] define minimal models on the Django instance for testing: I recommend a metadata model along the lines of `{title, description, content-url, thumbnail-url, tags}`
- [ ] set up a view that lets us push data into Django for this model
- [ ] set up a view that lists all data for this model gallery style
- [ ] set up an administrative view that lets us curate
- [ ] tie the repo or branch to heroku deployment for "live" testing.

This should be a reasonable number of first steps that we should be able to get up and running this week.

/cc @simonwex @cadecairos further thoughts?

**Comment by xmatthewx** [comment]
There is useful conversation and history in this repo. Code-wise is a blank slate easier to manage during the refactor? I will let you all and @mmmavis be the judge of that.

**Comment by Pomax** [comment]
also /cc @gideonthomas who might have a Django docker compose file already!

**Comment by alanmoo** [comment]
Regarding the repo, my question was more about the back end living in this repo vs another repo. I agree that the front end should continue to live here; it should be on a branch to start and then get merged to master when ready.

**Comment by Pomax** [comment]
this feels like a naming conflict - are we considering the front end to be a product on its own, and the backend a separate API? It feels like that's what we mean in which case I'll vote for a different repo to make the separation of concerns explicit

**Comment by mmmavis** [comment]
Agree. I will create a branch on this repo for the reactifcation work. 

Is https://github.com/mozilla/network-pulse-api the repo for the API work? If so I guess we can close this ticket. 😉

**Comment by Pomax** [comment]
It is, but there are still open checkboxes on this ticket so I'd like to keep it open for now.

**Comment by mmmavis** [comment]
> It is, but there are still open checkboxes on this ticket so I'd like to keep it open for now.

oh right I missed those! 😉

**Comment by mmmavis** [comment]
@Pomax @alanmoo feel like we can close this ticket? :clinking_glasses: 🍾
