### ISSUE TITLE
Add an about page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#234]
To link from the footer https://github.com/mozilla/network-pulse/issues/178

**Comment by kristinashu** [comment]
@xmatthewx could you write the copy for this?

**Comment by xmatthewx** [comment]
Probably. 😁   We can move other current footer stuff (github, sign-up) to this page. About content will be short (What it is, Why it's useful, How you can leverage and contribute). Wouldn't hurt to have some sort of graphic that is Networky+Pulsy. Clipart, stock imagery, or napkin doodle. 😀 😬

**Comment by xmatthewx** [comment]
Could be interesting to describe Pulse as a living document of our shared knowledge, the footprints of our network activity. That it this fledgling tool is likely to evolve not just in content, but in form as well.

**Comment by mmmavis** [comment]
I'm gonna remove this ticket from the current heartbeat since this is still in discussion.

**Comment by xmatthewx** [comment]
Closing. Tracking in https://github.com/mozilla/network-pulse/issues/488
