### ISSUE TITLE
Add a load more button

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#235]

**Comment by xmatthewx** [comment]
We currently fetch all items when a user visits. The Latest view, displays all of them. That was okay for the first couple hundred items, but we're reaching the limit, for both bandwidth and user experience.   

We should load items in batches, and give the user a load more button.

For engineers, we'll need to chose a number. 24? If it's divisible by 2 and 3, I believe it'll give us even rows on different screen sizes.

**Comment by kristinashu** [comment]
I don't think this needs to be mocked up. It should be a blue outline button, centered, and say 'View more.'

**Comment by kristinashu** [comment]
It's mocked up https://redpen.io/p/nzcd35d57dd04ad6dc

**Comment by mmmavis** [comment]
24 sounds good!

**Comment by mmmavis** [comment]
done! https://pulse-react.herokuapp.com/latest

**Comment by kristinashu** [comment]
Nice!
