### ISSUE TITLE
Improve empty search view

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#237]

**Comment by xmatthewx** [comment]
@Pomax @mmmavis – it'd be nice if we could have a table of suggested terms. In the future we could generate them based on activity+curation. Until then, would be nice to set them seasonally.

**Comment by kristinashu** [comment]
This ticket is very closely related to - Explore search suggestions #153

**Comment by xmatthewx** [comment]
Added suggested search terms to https://github.com/mozilla/network-pulse/issues/153#issuecomment-267432438

**Comment by xmatthewx** [comment]
closing. tracking in #153
