### ISSUE TITLE
Aspirational features

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#238]
Here is a list of potential future features (based on [this doc](https://docs.google.com/document/d/1nfPzoKSjN25vNVAP-K8WmYB1M2R9Qof5UQ8x5-JJNXM/edit?pli=1#heading=h.aij4j5cfgp6f)):

- Timeline view #55
- Data view #81
- Web app (mobile optimizations)
  - https://docs.google.com/document/d/13gbx52eUkjo0HsdOyW0gj7FSNiT_uOFXqFe3AUgU3xE/edit
  - Save to homescreen prompt #138
  - Notifications #247
    - Have a twitter account so that Pulse can post new submissions (HN style)
    - Notify in chat
    - Mobile notifications
- Add to home screen #138
- Public submissions
- Distributed submissions
- FTU - first time use (nice to have)
- Integrated Input (Applications (mozfest, global sprint, ...) >> feed into Pulse)
- Pulse feed embeds (e.g. on Mozfest site, Mozilla.org) #246

**Comment by kristinashu** [comment]
Prioritizing these in this exercise https://docs.google.com/a/mozilla.com/presentation/d/1CByrAFq8rQWKe1pHi_HtvUz0drEBbrkdr8M6XQQ7epA/edit?usp=sharing

**Comment by kristinashu** [comment]
From the slides, we've prioritized:

- Share Search UI - https://github.com/mozilla/network-pulse/issues/159
- Pulse Embeds - [need ticket]
- Data View - https://github.com/mozilla/network-pulse/issues/81
- Tweet/Chat Notify - [need ticket]

<img width="949" alt="screen shot 2016-11-17 at 1 11 08 pm" src="https://cloud.githubusercontent.com/assets/1068783/20408030/9b65c6a8-acc8-11e6-8333-19337b2faf29.png">

**Comment by xmatthewx** [comment]
Thanks for capturing that. 

A new idea also emerged: Prompt users to tweet after they add a new item. Or redirect to their item (if they have permission to publish directly) where they can access the feature to tweet.

Below is a brief explanations of other items on the list. 

<img width="1101" alt="screenshot 2016-11-17 18 17 06" src="https://cloud.githubusercontent.com/assets/53411/20412002/252a53a8-acf2-11e6-80de-de6726adc290.png">

**Comment by kristinashu** [comment]
@xmatthewx could you open tickets for Pulse Embeds and Tweet/Chat Notify? Just want to make sure I know what you have in mind.
