### ISSUE TITLE
Define API

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#239]
Let's discuss requirements and routes, fun things such as `/item/id` and `/item/id/image` and `issues/[issuename]` and `/search`. We can start by capturing what @mmmavis bravely implemented with JS and duct tape to help us quickly ship the prototype. (Thanks Mavis!!)

@Pomax @alanmoo @cadecairos – who wants to draft a strawperson proposal for us to jumpstart discussion?

discussion on data: https://github.com/mozilla/network-pulse/issues/236#issuecomment-260736581

**Comment by xmatthewx** [comment]
https://github.com/mozilla/network-pulse-api

**Comment by mmmavis** [comment]
This seems to be the initial ticket that we created for spinning up the backend repo. I think we can mark this completed now. #success ✨
