### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#241]
Pulse has a [green favicon](https://github.com/mozilla/network-pulse/blob/master/icon.png). We should update the color. Maybe the design too, though that's probably not too important.

**Comment by kristinashu** [comment]
Here's a pink pulse line at 196x196px on both a white background and a transparent background.

![icon-fav-white](https://cloud.githubusercontent.com/assets/1068783/21363551/e5864a62-c6a1-11e6-9b54-f0915b9aab62.png)
![icon-fav](https://cloud.githubusercontent.com/assets/1068783/21363550/e5832044-c6a1-11e6-9141-7e69154e6d73.png)

**Comment by mmmavis** [comment]
hey @kristinashu can you export @ 2x ones too plz? Thanks! :clinking_glasses:

**Comment by kristinashu** [comment]
Yup yup, here you go!

<img width="196" alt="icon-fav-white 2x" src="https://cloud.githubusercontent.com/assets/1068783/21459170/d2f43c50-c8f0-11e6-82ae-57591e89c8df.png">
<img width="196" alt="icon-fav 2x" src="https://cloud.githubusercontent.com/assets/1068783/21459171/d2f748fa-c8f0-11e6-875a-aea773487705.png">

**Comment by mmmavis** [comment]
Done!
