### ISSUE TITLE
Design improved empty fav's screen

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#243]

**Comment by kristinashu** [comment]
@xmatthewx here's possible empty screen. Added the heart icon and action item (button linking to the Feature page).

![empty favs copy 9 1x](https://cloud.githubusercontent.com/assets/1068783/20493706/bb82939a-afce-11e6-8552-45d2b8824f16.png)

**Comment by xmatthewx** [comment]
This is perfect. 

I wonder about the word Posts. I've avoided Posts and Projects, but Items and Assets are dull. What if it said `Explore featured`?

**Comment by kristinashu** [comment]
Ah right that's better.

![empty favs copy 9 1x](https://cloud.githubusercontent.com/assets/1068783/20494461/e6830ed2-afd1-11e6-8d7d-73a2483c93fe.png)

**Comment by mmmavis** [comment]
https://pulse-mavis.herokuapp.com/favs done! fixing footer and spacing now.
