### ISSUE TITLE
Set card height

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#244]
@xmatthewx @mmmavis to move away from masonry layout, we could make the cards all the same height. Here is a mockup where the cards are all the same, if text is short then there is white space, if it is long then it fades off:

Desktop
![red-pen-313333e7-5739-47ca-ac16-d42c80401851](https://cloud.githubusercontent.com/assets/1068783/20582317/f91ad8d0-b194-11e6-93ab-081b191f5d84.png)

Mobile
<img width="318" alt="screen shot 2016-11-23 at 3 54 21 pm" src="https://cloud.githubusercontent.com/assets/1068783/20582334/2e143f04-b195-11e6-8817-7a4ad301ea56.png">
<img width="319" alt="screen shot 2016-11-23 at 3 54 40 pm" src="https://cloud.githubusercontent.com/assets/1068783/20582333/2e122994-b195-11e6-91ba-d4bb1756f212.png">

**Comment by xmatthewx** [comment]
i dig it

**Comment by mmmavis** [comment]
lovely. this should work well!

**Comment by mmmavis** [comment]
@kristinashu should we also restrict the height of the thumbnail image?

**Comment by kristinashu** [comment]
@mmmavis yes, that should be covered in https://github.com/mozilla/network-pulse/issues/230

**Comment by kristinashu** [comment]
We're going with 1200x630px ratio.

**Comment by xmatthewx** [comment]
@mmmavis – let us know if we need to do a batch update of existing images. They aren't consistent, and some might be small. Alternatively, you could crop overflow and give a gray background color for any that are too short. Some might look funky, but we could manually fix the featured items, ignore the rest. I welcome your advice on whatever's easiest. I'm kicking myself for not being more careful from the start. 😢 🐐

**Comment by mmmavis** [comment]
@xmatthewx Oh no worries at all! Thanks for curating SO MANY images this far!

@kristinashu 
This is what I have so far using CSS - basically there will be an 1200:630 ratio image container in every "entry" card and the thumbnail is scaled down to fit (without cropping or changing the image dimension ratio). Note that image is positioned at center top... I tried to make it vertically centered but failed to find an easy approach. Let me know if this looks okay or we prefer another treatment (e.g., scale the image to fill the entire image container etc)

![fireshot capture 4 - mozilla network pulse - http___localhost_3000_latest](https://cloud.githubusercontent.com/assets/2896608/21247242/e754f6c6-c2e2-11e6-8ec9-70f6c5f1069e.png)

**Comment by xmatthewx** [comment]
Thanks Mavis! 

Images should always be full width. The white sidebars are disruptive. 

Let's crop overflow and add a background color to fill in space for short images. That will create more visual consistency. Center top position is great. I can go in and fix thumbnails on important projects that get cropped poorly by this approach. 

Here's a demo: 

<img width="1041" alt="screenshot 2016-12-16 12 17 02" src="https://cloud.githubusercontent.com/assets/53411/21271591/9154509e-c389-11e6-8487-3fcb04aa82f4.png">

**Comment by mmmavis** [comment]
Done! https://pulse-mavis.herokuapp.com/featured

Note that once I've fixed those obvious bugs (e.g., image assets not loading problems etc) I'll move the code to `mozilla` (it currently lives on https://github.com/mmmavis/network-pulse/tree/react).

**Comment by mmmavis** [comment]
oh and I didn't apply the grey background as suggested - the page looked a bit blocky to me 😉

**Comment by kristinashu** [comment]
So much better! Thanks @mmmavis :clap:
