### ISSUE TITLE
Pulse posting party

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#245]
Let's schedule a brief, 20 minute sprint with program staff. Post things pre-All Hands.  

We can
 - Post things to Pulse socially.
 - Chat about challenges and opportunities to build into our routines. 

We can also build a list with the group of things to post, to capture missing bits: https://public.etherpad-mozilla.org/p/pulse-to-post

Could include Vanessa, Aurelia, Amira, Laura, various Hive & Gigabit staff, maybe Martin from IoT. 

Thoughts @acabunoc?

**Comment by mmmavis** [comment]
I believe this is done? If so let's close this ticket! @xmatthewx 👍

**Comment by xmatthewx** [comment]
Done!
