### ISSUE TITLE
Pulse feeds on other sites

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#246]
Pulse items could appear on other sites. Let's explore the ways this could be awesome. At this stage, emphasis is on possibilities, not practicalities. 

Let's explore format
 - Full cards VS simpler, smaller list of links
 - Featured item(s) on a landing page VS a dedicated page
 - Other features: Search box? Button to Pulse? Teaser to full experience?

Some sites where this could appear for mockups
 - mozilla.org
 - mozilla.org/technology
 - MozFest.org
 - Mozilla blogs
 - Science site

**Comment by kristinashu** [comment]
@xmatthewx here are a few ideas https://redpen.io/p/rpecf7b01471ba014f 
I don't think any of them are there yet but some feedback would be great.

**Comment by xmatthewx** [comment]
Some great explorations. Comments added to redpen.

**Comment by xmatthewx** [comment]
Let's definitely do mockups on other sites, including mozilla dot org home (we can get new design mocks) and the /technology page. The goal of this work is to demo the possibility to teams across Mozilla. If we build interest, we can dig into the specific UI details later.

**Comment by kristinashu** [comment]
@xmatthewx sorry for misunderstanding, I'll chose the simplest UI and place it on mozilla dot org home and the /technology page. How do I get the new mozilla design?

**Comment by kristinashu** [comment]
@xmatthewx I've added the /technology mockup, let me know if that is more what you had in mind.

**Comment by xmatthewx** [comment]
> sorry for misunderstanding

Not at all. My original ticket asked for you to explore this stuff. Your UI is great, and will be useful. I was just realizing that it'll be a while before we're ready to implement those things. And that the other half of this ticket will be more useful in the short term.

**Comment by kristinashu** [comment]
https://redpen.io/p/rpecf7b01471ba014f

I've put the feed into:
- mozilla.org ([current design](https://www.mozilla.org/en-US/))(waiting for new design)
- [mozilla.org/technology](http://mozilla.org/technology)
- [mozfest.org/projects](https://mozillafestival.org/projects)
- [blog.mozilla.org](https://blog.mozilla.org/)
- [women & weblit ](https://mozilla.github.io/womenandweb/)

You also mentioned the Science site, would this replace it's current [projects page](https://science.mozilla.org/projects)? Any other sites you can think of?

**Comment by xmatthewx** [comment]
This is a good range. No need for the science site. Thanks!

**Comment by kristinashu** [comment]
@xmatthewx need anything else for this?

**Comment by xmatthewx** [comment]
No, I think these give us all the help we need.
