### ISSUE TITLE
Change LICENSE

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#249]
I just realized this project is [under MIT license](https://github.com/mozilla/network-pulse/blob/master/package.json#L14). Should we change it to MPL-2.0 so it becomes more mofo standard?

/cc @xmatthewx @cadecairos since we are [the only 3 contributors on this project](https://github.com/mozilla/network-pulse/graphs/contributors)

**Comment by cadecairos** [comment]
Fine by me!

**Comment by mmmavis** [comment]
@xmatthewx u okay with this?

**Comment by xmatthewx** [comment]
👍
