### ISSUE TITLE
Build new search page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#252]
I'm almost done reactifying the [existing Pulse](https://mozilla.github.io/network-pulse/). I'm getting some help from others to set up a Heroku instance so we can all see my progress.

...in the meanwhile, I will start getting the new dedicated search page in place

- /search
  - https://redpen.io/cm583a3b66f8b6343f (no suggested terms for now)
  - https://redpen.io/bk7fcefb87aceeab12
  - https://redpen.io/cee8b85a5ebd67f028

/cc @kristinashu @xmatthewx  (ping me if you'd like to see my progress. I can tunnel my localhost for you to take a peek 😉 )

**Comment by alanmoo** [comment]
Keep in mind you'll be able to hit the `/tags` api endpoint to get a list of suggested tags if that's useful. Maybe it would be useful for that response to be sorted by popularity (and then when you search, they can be sorted alphabetically)

**Comment by xmatthewx** [comment]
Longterm, we could have a mix of strategic and popular tags. Until we have data, we can run with these: https://github.com/mozilla/network-pulse/issues/153#issuecomment-267432438

**Comment by mmmavis** [comment]
Closing this ticket now as the dedicated search page has been build. See my WIP app: https://pulse-mavis.herokuapp.com/featured

Let's create new tickets for features we have not yet tackled!

**Comment by xmatthewx** [comment]
Hi. Things are coming along nicely. 

Trying this out now, I wonder if we don't want to stick with card view for search results. Titles alone aren't very helpful for browsing a topic. cc @kristinashu 

Want a new ticket to discuss this @mmmavis ?

**Comment by kristinashu** [comment]
Some discussion in redpen https://redpen.io/bk7fcefb87aceeab12

**Comment by xmatthewx** [comment]
Mobile or not, I still think that titles alone aren't super useful. (They work for favs since those are familiar)

On the new build, searching is likely to blink the display of projects as it pings the DB, so it should feel like something is happening, even if the card in front of you doesn't change. If that's not enough, we could solve the problem with a loading spinner.
