### ISSUE TITLE
Hover state for bikeshed-magenta(#e14164) links

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#253]
@kristinashu do we apply a color change or?

**Comment by kristinashu** [comment]
I should change to the darker tint of bikeshed-magenta.

**Comment by mmmavis** [comment]
@kristinashu cool! Do you have the color code or you know how dark (%?) it should be?

**Comment by kristinashu** [comment]
Should be lightness -15% or darkened 15% https://mozilla.github.io/mofo-bootstrap/demo/

**Comment by mmmavis** [comment]
Awesome. Thanks!
