### ISSUE TITLE
Review results of network survey 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#26]
Reach out to Rafi Santo to gather results from our survey of network members. In particular, review incentives of participation, sharing, etc.

**Comment by xmatthewx** [comment]
@samanthaburton – is there somewhere we can see a summary of results from the network survey that involved Adam/Rafi etc? We are seeking info that could inform our design/features for network pulse (e.g. Motivators that drive member participation).

[Network mapping research doc](https://docs.google.com/document/d/1AA731KG6FB5lKnQi0hjUWwPoLk8kXnIFwhJ3bIYKNXs/edit#)

**Comment by chrislarry33** [comment]
Do you all have this: https://docs.google.com/document/d/1oVD_uJ-bgq9LUWhlI9O9vqRbxhm1pGzPf21FhIjosXw/edit#heading=h.8abuig1ku66r

Thats the key doc

**Comment by xmatthewx** [comment]
Thanks @chrislarry33. If we get some traction with pulse, we can start to think about how we extract [insights like those](https://docs.google.com/document/d/17NQKl7QdlpxdAaDkm36Gtlxla6WHTu1Qn1OJ0xktMYo/edit) organically, in tandem with future surveys. 

I'm calling this issue done enough for now.
