### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#261]
@kristinashu @xmatthewx 

Do we still need a splash page for Pulse v2? Now that we've included "Mozilla Network Pulse" in the navbar (plus adding an About page is on the roadmap too?) I feel it's a bit redundant to have a splash page mentioning the same thing.

Pulse v1: https://mozilla.github.io/network-pulse/
Pulse v2(WIP): https://pulse-react.herokuapp.com/latest

**Comment by kristinashu** [comment]
I think we could still have it for the tag line but let's see what @xmatthewx says. There is also a ticket to make the splash screen last longer https://github.com/mozilla/network-pulse/issues/205

**Comment by mmmavis** [comment]
Done! https://pulse-react.herokuapp.com
