### ISSUE TITLE
Share link URL feature isn't working

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#266]
@mmmavis the share link feature is not working on the react site, it should function the same as on the production site.

- React version is showing the URL before I click on the icon (URL should be hidden until I click it).
- Clicking on the link icon isn't copying the URL (clicking should copy the URL).
- Hover state is a blue box (should be a pink icon).

<img width="585" alt="screen shot 2016-12-23 at 8 34 49 am" src="https://cloud.githubusercontent.com/assets/1068783/21459264/b4d0029e-c8f1-11e6-9d6a-eaa5f97e2862.png">

**Comment by mmmavis** [comment]
oh yea I haven't implemented that part yet 😁

**Comment by mmmavis** [comment]
done! https://pulse-react.herokuapp.com/
