### ISSUE TITLE
Nav item spacing

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#267]
@mmmavis the menu items look very close together, please space them out a little more to increase legibility. They might need to be close together narrow screens but could be more spread out on wider screens.

Comp:

<img width="316" alt="screen shot 2016-12-23 at 9 34 42 am" src="https://cloud.githubusercontent.com/assets/1068783/21459457/2d2e5f78-c8f3-11e6-89bf-2021d7221a7b.png">

<img width="1190" alt="screen shot 2016-12-23 at 9 34 58 am" src="https://cloud.githubusercontent.com/assets/1068783/21459458/2fb49442-c8f3-11e6-97cb-39ea73c7922e.png">

Staging:

<img width="329" alt="screen shot 2016-12-23 at 9 35 23 am" src="https://cloud.githubusercontent.com/assets/1068783/21459460/358062a2-c8f3-11e6-92ce-4e5179df1016.png">

<img width="1309" alt="screen shot 2016-12-23 at 9 35 11 am" src="https://cloud.githubusercontent.com/assets/1068783/21459459/32fbcb34-c8f3-11e6-99fc-5e55dc1aa1ca.png">

**Comment by mmmavis** [comment]
done! https://pulse-react.herokuapp.com/featured

**Comment by kristinashu** [comment]
Perfect, thanks!
