### ISSUE TITLE
Can't hide keyboard on search screen (iPhone)

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#269]
@mmmavis even after clicking 'return' or the close 'x' icon on the keyboard, the keyboard is always visible. The keyboard should be hidden after a user clicks 'return' or the close keyboard icon.

On iPhone 6s iOS 10.2 in Chrome

<img width="402" alt="screen shot 2016-12-23 at 1 23 55 pm" src="https://cloud.githubusercontent.com/assets/1068783/21462635/24bdbb16-c913-11e6-9063-038998f1edd5.png">

**Comment by mmmavis** [comment]
Fixed! https://pulse-react.herokuapp.com/search
