### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#27]
It won't be too useful yet but once we have deep linking and more people using the site it will help inform which type of artifacts are the most popular, help inform us on which features to expand on or kill, if a specific promotion brought in more users...

**Comment by xmatthewx** [comment]
Thanks for adding. It would be useful to put the Item URL behind a button so we can track that intent to share as an event (#19).

**Comment by xmatthewx** [comment]
@mmmavis – let's figure out if we need to add a mozilla domain to add analytics, or if we can [set a cookie](https://support.google.com/analytics/answer/6205202?hl=en#subDirectoriesShareCookies) to our repo's path.

Or maybe we should go ahead and get a domain such as `pulse.mozillafoundation.org`. What do you think? Pros & cons?

**Comment by kristinashu** [comment]
Started domain talk in https://github.com/mozilla/network-pulse/issues/31

**Comment by mmmavis** [comment]
I will spend today reading GA docs as currently I don't know much about it. 😁

**Comment by mmmavis** [comment]
I did some experiments with my personal account + Github pages under my Github account 

<img width="849" alt="screen shot 2016-07-20 at 5 23 10 pm" src="https://cloud.githubusercontent.com/assets/2896608/17007604/fc00027c-4e9e-11e6-9055-db3623378f59.png">

Seems like we are able to track page views on GitHub pages:
<img width="1424" alt="screen shot 2016-07-20 at 4 49 59 pm" src="https://cloud.githubusercontent.com/assets/2896608/17007636/3f473c12-4e9f-11e6-947a-9beef346fd6f.png">

As well as [custom events](https://developers.google.com/analytics/devguides/collection/analyticsjs/events):

<img width="1418" alt="screen shot 2016-07-20 at 4 50 38 pm" src="https://cloud.githubusercontent.com/assets/2896608/17007645/4ff18b80-4e9f-11e6-9724-f2decbafd404.png">

**One thing to note is that**, no matter what you put as the property URL (in my experiment I put http://mmmavis.github.io/network-pulse), GA seems to ignore the paths and track **everything** on http://mmmavis.github.io/. So if I'm using the same tracking ID on another repo (eg., https://mmmavis.github.io/test-ga-gh-pages/). Activities on that site will show up on the same dashboard
<img width="1359" alt="screen shot 2016-07-20 at 5 35 25 pm" src="https://cloud.githubusercontent.com/assets/2896608/17007799/62987748-4ea0-11e6-990f-e5a7db00b50a.png">

**Comment by mmmavis** [comment]
I guess we can create a tracking ID for network-pulse and make sure we don't use the same tracking ID on other repos/GitHub pages on mozilla?

Any concerns here @cadecairos ?

**Comment by xmatthewx** [comment]
These is a great investigation @mmmavis. I read a bit about GA and using paths so that you can have separate tracking on a single subdomain like mozilla.github.io. It is mentioned in [this analytics post](https://support.google.com/analytics/answer/6205202?hl=en#subDirectoriesShareCookies). Maybe there's a workable solution?

**Comment by cadecairos** [comment]
If we use an existing tracking ID we can try create a view under the propery that filters for specific paths (i.e. `/network-pulse`)

Otherwise, we should be creating a new property under GA for this.

Note that we should only use the mozilla GA account for production analytics

**Comment by mmmavis** [comment]
I specified the `cookieDomain` as suggested by [Google](https://support.google.com/analytics/answer/6205202?hl=en#subDirectoriesShareCookies)
```js
ga('create', 'UA-81121503-1', {
  'cookieName': 'gaCookie',
  'cookieDomain': 'mmmavis.github.io/network-pulse',
  'cookieExpires': 60 * 60 * 24 * 28  // Time in seconds.
});
ga('send', 'pageview');
```
But GA stopped tracking my mmmavis.github.io/network-pulse... I guess this is the cause: (found on https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id)

<img width="796" alt="screen shot 2016-07-21 at 5 45 16 pm" src="https://cloud.githubusercontent.com/assets/2896608/17043381/f117578a-4f6a-11e6-99d1-1bbfe30404fe.png">

**Comment by mmmavis** [comment]
Anyways, I think ^ even the cookie domain trick works it won't solve the shared `UA` id problem. Another site under my mmmavis.github.io can still use the same UA ID without specifying the `cookieDomain` (which means data coming from that site will still get aggregated under the same GA property?)

**Comment by xmatthewx** [comment]
So: 
 - long-term solution: add a mozilla URL 
 - short-term solution: can we use a property on your GA account? are you able to share access to just that property?

**Comment by mmmavis** [comment]
@cadecairos 

I'm seeing 2 Mozilla GA accounts (one for small websites, one for additional websites). Do you think we can use one of the accounts and create a new property for `mozilla.github.io` and a view for `mozilla.github.io/network-pulse`?

**Comment by xmatthewx** [comment]
@cadecairos – any thoughts on this?

**Comment by xmatthewx** [comment]
@mmmavis - let's discuss on today's stand so that we can unblock at least a temporary solution.

**Comment by cadecairos** [comment]
@mmmavis I've set up a new GA property for network pulse, here's the tracking code: UA-49796218-43

**Comment by cadecairos** [comment]
@mmmavis I've also added you as a user on the property, you should be able to see it

**Comment by xmatthewx** [comment]
Awesome. Thanks @cadecairos. Can I bug you to give me and the rest of the group privileges too?

**Comment by cadecairos** [comment]
certainly you can

**Comment by cadecairos** [comment]
@hannahkane @kristinashu @acabunoc @xmatthewx

You should all be able to access the network pulse GA stats now. (pending set up)

**Comment by kristinashu** [comment]
@cadecairos got it, thanks!

**Comment by mmmavis** [comment]
ＹＥＡＨ 🍻 thanks @cadecairos

**Comment by xmatthewx** [comment]
See events in #69

**Comment by mmmavis** [comment]
List copied from #69 

🌞 🌞 🌞 🌞 🌞 

### High Value

Item action
 - [ ] Share Intent – User taps `Link button` to reveal URL
 - [ ] Visit – User taps `Visit button` and exits
 - [ ] Get Involved – User taps `Get Involved` and exits
 - [ ] Fav – User taps `Heart button` to Fav a project (Don't worry about un-Favs right now. We need to track activity, not an accurate count.)

Nav action
 - [ ] Views – Track as page views (Featured, Recent, Favs, Categories)
 - [ ] Item view – Track detail views as page views (Ex: .../network-pulse/?id=p1470188181000)
 - [ ] Issues – Track as page views (Ex: .../network-pulse/privacy or  .../network-pulse/?cat=privacy)

Search
 - [ ] Search – User puts focus on the search field 
 - [ ] Found – User visits a search link shared by someone else. Track as page views. (Ex: .../network-pulse/?q=foo)

### Other

 - Add new intent – Someone taps big plus button
 - Sign-up intent – Someone taps footer sign-up link
 - Search – Search terms. Not MVP. Maybe not ever. 
 - Un-Fav – Eh. useful? We see people managing their Fav list.

**Comment by mmmavis** [comment]
Problem with tracking links that open on a new tab is that we need to interfere the default behaviour of `target="_blank"` links (e.g., by calling `event.preventDefault();` plus `window.open()` in the click handler)

for example, 

```js
var getInvolvedBtnClickHandler = function(event) {
  event.preventDefault();

  var $projectCard = $(this).parents(".project");
  ga('send', {
    hitType: 'event',
    eventCategory: 'Get Involved Button',
    eventAction: 'click',
    eventLabel: $projectCard.attr("id"),
    hitCallback: function() {
      window.open($(this).attr("href"),"_blank");
    }
  });
};
```

Depends on your browser setting, `window.open(some_url,"_blank");` might throw up a warning like the screencap below... which is not good

<img width="1199" alt="screen shot 2016-08-17 at 3 21 03 pm" src="https://cloud.githubusercontent.com/assets/2896608/17755620/c4eb6018-648f-11e6-9f00-67fba844cb5f.png">

Three options we can consider

1. open those links in the same tab instead - we can easily track those without any browser warnings
2. open those links in a new tab - this throws warning
3. open those links in a new tab & do not track those events

@xmatthewx @kristinashu @acabunoc @cadecairos thoughts?

**Comment by cadecairos** [comment]
I know little about these things, but if we're opening the link in a new tab, does the click event running the GA fumction need to prevent the default behaviour of clicking an anchor with a new tab as the target? The window won't close and ja should continue executing.

**Comment by mmmavis** [comment]
@cadecairos I tried it without `event.preventDefault();` and with the option `transport` set to `beacon` (see [docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/events#outbound_link_and_form_tracking)) and everything worked out fine! 😀 Weird, I thought that was what I tried initially. Thanks for prompting me to double check again. 🍸 

@xmatthewx @kristinashu @acabunoc - problem solved!

**Comment by cadecairos** [comment]
That's awesome!

**Comment by mmmavis** [comment]
These are the event tracking that I added. (will be pushed to production soon)

 - [x] Share Intent – User taps `Link button` to reveal URL
 - [x] Visit – User taps `Visit button` and exits
 - [x] Get Involved – User taps `Get Involved` and exits
 - [x] Fav – User taps `Heart button` to Fav a project
 - [x] Unfav – User taps `Heart button` to unfav a project
 - [x] Item view – Track detail views as page views (Ex: .../network-pulse/?id=p1470188181000)
 - [x] Search – User puts focus on the search field 
 - [x] Add new intent – Someone taps big plus button
 - [x] Sign-up intent – Someone taps footer sign-up link
