### ISSUE TITLE
Footer blocks content on issues screen (iPhone)

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#270]
@mmmavis footer is at the bottom on the screen and blocks page content, can't scroll down to see the content. 

On iPhone 6s iOS 10.2 in Chrome

<img width="400" alt="screen shot 2016-12-23 at 1 24 17 pm" src="https://cloud.githubusercontent.com/assets/1068783/21462672/985c2f26-c913-11e6-82ef-4df71e2d2f2b.png">

**Comment by mmmavis** [comment]
should be fixed now https://pulse-react.herokuapp.com/issues
