### ISSUE TITLE
Typo on favs view placeholder

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#290]
Things are looking awesome on the new build. Noticed a small typo: 

"Expore" instead of "Explore" on the button.

<img width="336" alt="screenshot 2017-01-06 07 59 35" src="https://cloud.githubusercontent.com/assets/53411/21718546/2d28201a-d3e6-11e6-8cfe-ac09ea5dac9d.png">

**Comment by mmmavis** [comment]
Ha nice catch!

**Comment by mmmavis** [comment]
Done!
