### ISSUE TITLE
Search - show Cards rather than List

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#291]
There was some discussion in redpen and in https://github.com/mozilla/network-pulse/issues/252#issuecomment-268315616, but ..... I neglected to reopen the ticket. Whoopsie. 

Let's use cards for Search. 

Compare the browsing experience:

<img width="1152" alt="screenshot 2017-01-06 08 10 26" src="https://cloud.githubusercontent.com/assets/53411/21718779/a670b4ae-d3e7-11e6-8609-cc240ba8f67e.png">

<img width="1177" alt="screenshot 2017-01-06 08 10 02" src="https://cloud.githubusercontent.com/assets/53411/21718778/a670c138-d3e7-11e6-9fc0-9c2de61479e1.png">
 
For Favs, a list is great because I'm familiar with the projects. For Search, a user needs thumbnails and descriptions to browse effectively.

**Comment by mmmavis** [comment]
Done! https://pulse-react.herokuapp.com/search
