### ISSUE TITLE
Pulse v2 launch meta

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#294]
Hi team. We are on the final stretch to launch our new build. We will need this ready for the network launch. Let's aim for Jan 31 to production, so we have time to QA and squash bugs. The work seems manageable, but there's risk from conflicting priorities.

Meta tasks below. Tried to order them logically. I'm on mobile. Can someone link relevant issues?

1. [Finish tests](https://github.com/mozilla/network-pulse-api/pull/9)

1. [Prep and import data](https://github.com/mozilla/network-pulse/issues/295)

1. [Connect frontend to backend.](https://github.com/mozilla/network-pulse/issues/296) How many dev days do we expect?

1. [Build Form](https://github.com/mozilla/network-pulse/issues/257) - design spec done, but there is error handling to wrangle. Expect this to take non-trivial time.

1. [Confirm quality analytics](https://github.com/mozilla/network-pulse/issues/325) [issue clarified]

1. [Favs - persist for users with auth.](https://github.com/mozilla/network-pulse-api/issues/12) This feature shouldn't block launch. We can bump.

Anything missing from this list?

Later: 

1. [Revisit back button](https://github.com/mozilla/network-pulse/issues/250)

**Comment by xmatthewx** [comment]
CC @kristinashu @mmmavis @pomax @alanmoo =:-)

**Comment by alanmoo** [comment]
Edited original comment with links

**Comment by xmatthewx** [comment]
@pomax – we all chatted on Friday. Anything on your plate missing from this list?

**Comment by Pomax** [comment]
@xmatthewx I don't think so, I'm working with Alan on the testing and thinking out loud with him about the favouriting mechanism, and don't see anything missing from the above list.

**Comment by xmatthewx** [comment]
Let's all peek at this meta ticket as we prep for work next week before people travel and shift to other projects. @kristinashu @mmmavis @Pomax @alanmoo 

Any big revisions, concerns, new items we've identified as mvp work?

**Comment by alanmoo** [comment]
@xmatthewx We reviewed the milestone today with @simonwex, so those are up to date

**Comment by xmatthewx** [comment]
Closing this. Final tasks are filed and tracking just fine without this overhead.
