### ISSUE TITLE
Connect React front end to Django back end

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#296]
A staging server is propped up at http://network-pulse-api-staging.herokuapp.com/. It needs to be reviewed and redeployed at some point soon, but at least it's something to start working with.

Work includes:

- [x] migrate data from Google Spreadsheet to real database https://github.com/mozilla/network-pulse/issues/295
- [x] use Pulse API to fetch data https://github.com/mozilla/network-pulse/issues/308
- [x] have login system implemented on the front end side
- [x] submission form

**Comment by mmmavis** [comment]
Work includes:

- switching from Google Spreadsheet to real database
- have login system implemented on the front end side
- submission form

**Comment by simonwex** [comment]
@mmmavis @Pomax could you update this ticket to represent this week's work and create one with leftovers into the next milestone?

**Comment by mmmavis** [comment]
I believe we can close this now! 🍾
