### ISSUE TITLE
Sign in and Logout design

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#299]
I will mock up where the Sign in and the Log out button/link will go. 

@xmatthewx @mmmavis @alanmoo @Pomax can you clarify the flow? User clicks Sign in, is redirected to google's sign in page, once they are verified they will be redirected back to Pulse (same screen as they were on before they signed in). 

There won't be Sign up link.

**Comment by Pomax** [comment]
That's literally the flow, although there is an intermediate step that hopefully goes by "too fast":

- user clicks "sign in" link, which is a url that includes a url argument with the URL they are on now
- google does the entire sign in process and redirects the user to the API server's callback URL. This is always the same URL
- the API server's callback records the login and then (hopefully) immediately redirects the user back to the URL that was found in that url argument when they initially clicked to log in.

**Comment by kristinashu** [comment]
Ok great, so I'll I need to mock up is the link to Sign in or Log out.

The layout works well easily on mobile but it's a little trickier on desktop because of the + icon. I had to move the icon up, make it white and slightly smaller. 

https://redpen.io/p/nzcd35d57dd04ad6dc

@xmatthewx let me know if that works or if you have any other ideas.

<img width="1198" alt="screen shot 2017-01-13 at 10 10 39 am" src="https://cloud.githubusercontent.com/assets/1068783/21940338/bb425964-d978-11e6-96ef-835e6c7a09a0.png">

<img width="319" alt="screen shot 2017-01-13 at 10 10 57 am" src="https://cloud.githubusercontent.com/assets/1068783/21940337/bb3ce092-d978-11e6-82db-85264007caf8.png">

**Comment by Pomax** [comment]
Should the view also tell you who you're logged in as?

**Comment by kristinashu** [comment]
It would be ideal to have a name and then 'Log out' after it but I don't think it will fit, especially long names.

**Comment by Pomax** [comment]
for the mobile view would it make sense to put the "logged in as ....... [logout]" in the "grey bar"? I know it's the background, but making it a content div with the logged in user info might work. (Might mean that "log in" and "log out" are not in the place, but for a service where you don't log in and out all the time but just log in and then in most use cases leave it that way, I don't know if that's a problem)

**Comment by xmatthewx** [comment]
@kristinashu – your login mockup looks good. 

For logout, it seems like too much prominence. Like @Pomax says, there's isn't much need to logout. We could put it on light gray above the cards. Or in the footer. Is that weird? Or hide it in the Favs view, with a user's other stuff? 

Could this all be hidden on the Favs view? Login as well? We could prompt when someone taps to Add or Favs for the first time. Most visitors don't really need it. I think the account stuff needs some holistic UX. We can land this as good enough, and then revisit.

**Comment by alanmoo** [comment]
Another ✚𝟏 for putting `log out` at the bottom somewhere.

**Comment by Pomax** [comment]
It might also be fine to tie logout to the user's name rather than having it as a dedicated option. Which could be done through a "a profile page" (with certainly for now extremely minimal information) with a logout option that can be navigated to by tapping one's name, or with a small modal with a "you are logged in as abcdefgh - [logout] [dismiss]" when tapping one's name, etc.

**Comment by kristinashu** [comment]
If we remove Sign in from nav and put it into Favs, it could look like:

<img width="702" alt="screen shot 2017-01-17 at 3 08 40 pm" src="https://cloud.githubusercontent.com/assets/1068783/22043938/e789f88c-dcc6-11e6-94d9-f3e1dd753929.png">

Log out might be too prominent here but I do think it needs to be in the same location as Sign in, for consistency. Any suggestions for better wording?

Clicking on Add Post icon would also trigger the Sign in.

**Comment by alanmoo** [comment]
"Not {name}?" which is a link that logs you out?

**Comment by kristinashu** [comment]
Maybe just:
<img width="644" alt="screen shot 2017-01-18 at 4 15 03 pm" src="https://cloud.githubusercontent.com/assets/1068783/22088507/516d2ea4-dd99-11e6-8077-101c0f493198.png">

@xmatthewx are you good with having the Sign in on the Favs sceen?

**Comment by xmatthewx** [comment]
I really like this treatment. Will it be right aligned on desktop?

Placement on Favs view is a bit quirky (my suggestion), but we can always promote it to other views as we build out user accounts more fully. Does it feel alright to you @kristinashu?

**Comment by kristinashu** [comment]
Great, thanks!

I've moved the text to the left side so it works on both desktop and mobile (without getting in the way of the + icon).

<img width="693" alt="screen shot 2017-01-19 at 10 50 53 am" src="https://cloud.githubusercontent.com/assets/1068783/22120663/8e8585ec-de35-11e6-96b7-85533916a23b.png">
<img width="944" alt="screen shot 2017-01-19 at 10 51 58 am" src="https://cloud.githubusercontent.com/assets/1068783/22120662/8e7c1b06-de35-11e6-9eb8-0137346ed09e.png">

Closing this ticket and opened implementation - Add Sign in and Logout link to favs screen #318
