### ISSUE TITLE
Implement 404 page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#303]
Design: https://redpen.io/da82b5b7fb334ccf79

@kristinashu can you help export the broken link icon? I can't find it in Google Drive 😁

**Comment by kristinashu** [comment]
Yup, here you go!
[icon 404.svg.zip](https://github.com/mozilla/network-pulse/files/694950/icon.404.svg.zip)

**Comment by mmmavis** [comment]
Where should "let us know" link to? To https://github.com/mozilla/network-pulse/issues ?

**Comment by kristinashu** [comment]
It can link to https://github.com/mozilla/network-pulse/issues/new

**Comment by mmmavis** [comment]
Done! https://pulse-react.herokuapp.com/hello2017
