### ISSUE TITLE
Add server side data fetching

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#307]
Let's add server side data fetching to make Pulse more SEO friendly. This can also reduce app's initial loading time.

**Comment by mmmavis** [comment]
Hey @alanmoo @gvn It seems like science.mozilla.org loads data on client side only. Other than the tight launch deadline / lack of development time, are there other reasons or findings I should be aware of?

**Comment by alanmoo** [comment]
Heh, this is still open - https://github.com/mozilla/science.mozilla.org/pull/512/files

But yeah, the key thing is that the server side method you use (React.RenderToString? Or maybe RenderToDOMString?) will not wait for async API calls to complete. As soon as react does its magic, the data-less site gets passed to the front end. I believe one approach is to use Flux/Redux to maintain state from server to client, but there are probably other ways. The above PR is so old I don't remember what I did...

**Comment by alanmoo** [comment]
(That being said, I completely agree that the data should be there on first load.)

**Comment by mmmavis** [comment]
Guess I'll learn and give Redux a try! I will definitely need someone to review my PR once it's ready (I'm looking at you @Pomax and @alanmoo ) heh

**Comment by mmmavis** [comment]
After reading some docs, it seems like Redux won't help with the thing we are trying to accomplish here @alanmoo . Especially the docs suggests fetching data on server side, storing it as a `window` var, including it in `<script></script>` in the HTML server serves: http://redux.js.org/docs/recipes/ServerRendering.html#the-client-side 🙄
Originally I was hoping by having server side data fetching would 
1. help SEO (since "project cards" will be included as part of the DOM)
2. speed up initial loading time

But it seems like search engines are Google can crawl JavaScript pretty well nowadays (thanks @Pomax for mentioning it).

Regarding the initial loading time, there are other ways of doing it. Here's one way that @Pomax suggested
> 10:51 AM 
as an alternative, you could make the bundle generate itself every X hours maybe, with a little script that pulls the latest stuff, turns it into a js file, which the bundle then requires in
10:52 AM
like, make a file generate-initial-state.js that writes another file initial-state.js that is required by your app so that everytime you rebundle, you do generate-initial-state && webpack .... and then the bundle will just "have" the initial data baked in without any need for window dangermouses 

I haven't decided on what approach we should take but now it seems like adapting Redux feels like a overkill as Pulse is just a simple site that displays entries in the Pulse database. Other than navigating pages, fav'ing/unfav'ing entries, and submitting new entries there aren't much users can do -- we shouldn't have any data flow craziness that Redux is designed to help.

What do you think @alanmoo @Pomax ?

**Comment by alanmoo** [comment]
Agreed, Redux feels like overkill for this. I do feel like the performance wins are worth it once we've got the site itself working. For future reference, [this may be helpful](http://redux.js.org/docs/recipes/ServerRendering.html#async-state-fetching)
