### ISSUE TITLE
Sign in failed message

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#313]
Need to design a screen or modal if a user tries to Sign in and can not.

**Comment by kristinashu** [comment]
Users attempt Sign in by clicking on:
- Add post icon
- Sign in on Favs screen

Sign in fails if:
- Don't have a mozilla email
- Mess up mozilla email password?

Here are a two options: Modal vs page

<img width="700" alt="screen shot 2017-01-17 at 3 48 55 pm" src="https://cloud.githubusercontent.com/assets/1068783/22044981/843bb800-dccc-11e6-948a-be00a784c843.png">

cc @xmatthewx @mmmavis

**Comment by xmatthewx** [comment]
Design is great. Should we add something like "Check back soon!" ? 

If it takes a while to expand accounts beyond staff, we should add a field to gather email for a notice when it's ready. No need to trouble with that now.

**Comment by kristinashu** [comment]
@mmmavis @xmatthewx any preference between Modal vs Page?

Is "Back" possible (will we know what screen the user was on before they clicked Sign in)?

**Comment by xmatthewx** [comment]
How about.... "Only Mozilla staff can login now as we test this new platform. Check back soon!"

I don't have a strong preference design-wise. Since we don't have other modals, and this won't affect most users, it might be easier to just do this as a page.

**Comment by mmmavis** [comment]
@Pomax just wanna double check to see if I understand the flow correctly

### for non-Mozilla staff

1. User clicks on "Sign In" on Pulse
2. Sends user to the `/login?original_url=<url>` Pulse API endpoint (`original_url` is the URL to redirect user back after the auth process)
3. User is redirected to Google's Log In page
4. User enters emails/password
5. User is logged in on Google
7. User grants Pulse API access to his/her Google account info
8. User is sent back to Pulse to the `original_url` (from Step 2) with url query argument `loggedin=False`.

Pulse checks the loggedin result from the `loggedin` query param, since in this case it is `False`, we show a "failed to log in" notice.

**Comment by Pomax** [comment]
@mmmavis small corrections:

### For every user

1. User clicks on "Sign In" on Pulse
2. Sends user to the `/login?original_url=<url>` Pulse API endpoint (`original_url` is the URL for the page they are on right now (they will be redirected to this URL after the auth process)
3. User is redirected to Google's OAuth page
4. User picks the google account they want to authenticate with. This may require the user to "log into google" first as part of the process.
5. User grants Pulse API access to his/her Google account info
6. User is redirected to the network pulse api auth callback, which activates the user's authenticated session
7. User is redirected to the `original_url` that was passed in step 2 with an additional `loggedin=True` or `loggedin=False` depending on whether authentication succeeded or not

### for users without a mozilla domain login

While "Google" authentication succeeds, the network pulse API will reject the user in step 6, and the redirection back to the pulse client will always be `loggedin=False`

**Comment by kristinashu** [comment]
Updated comp for failed login:

<img width="401" alt="screen shot 2017-01-19 at 10 58 37 am" src="https://cloud.githubusercontent.com/assets/1068783/22120876/6fbbcc24-de36-11e6-8b10-d6067ab2ba3f.png">

Closing this ticket and opened one for implementation - Implement Sign in failed screen #317
