### ISSUE TITLE
Add Sign in and Logout link on favs screen

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#318]
Based on design in - Sign in and Logout #299 

<img width="693" alt="screen shot 2017-01-19 at 10 50 53 am" src="https://cloud.githubusercontent.com/assets/1068783/22120715/c01330d2-de35-11e6-835d-ed3bcacde00e.png">
<img width="944" alt="screen shot 2017-01-19 at 10 51 58 am" src="https://cloud.githubusercontent.com/assets/1068783/22120716/c031b610-de35-11e6-8492-20667f939c71.png">

**Comment by mmmavis** [comment]
Sorry I'm confused - so the "Are you Mozilla Staff? Sign In" / "Hi username! Log out" text **only** appears on the favs page???

**Comment by kristinashu** [comment]
That's right. I know it's odd but people felt it should be kinda hidden.

**Comment by xmatthewx** [comment]
@mmmavis – we could promote it to other views later. Right now, it's just not useful for most visitors, just staff. Feels weird to have it front and center and then say _sorry, you can't login_.

**Comment by mmmavis** [comment]
This is done, though you can't see it on https://pulse-react.herokuapp.com until we fix the deployment issue 😢
