### ISSUE TITLE
Plan a "trending" dashboard 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#320]
We're collecting some data that can help us understand what items on Pulse are interesting to users. A dashboard would help us gather insights and then feature items for easier discovery.

We will have data on [Favs](https://github.com/mozilla/network-pulse/issues/251#issuecomment-273901850) (aka bookmarks). Data on views will only be in google analytics for now (is that true @alanmoo?). Both can help us see what's interesting lately.

This ticket is for some time post launch. To gather requirements, possibilities, and begin design. 

Initially dashboard can be raw for staff or admin only. In the future, it'd be nice to surface to the public.

**Comment by alanmoo** [comment]
Yup, only in analytics. The easy to wrap in stuff captures way too much data and isn't extremely useful.
