### ISSUE TITLE
Plan transition for staff submissions pre- and post-migration

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#321]
At some point this month, we'll want to nudge staff to make sure the best of 2016 has been filed in Pulse. We should time that with migration to our new DB in mind. 

 - At what point should we shutdown the v1 google form? Has migration started already? 
 - At what point can they start using the new form? (I think beta staging with some quirks is okay)
 - Will there be a few days of lockdown in between?

@alanmoo – can you take the lead on this plan? Loop in the team as needed?

During the transition, we could have staff continue to use the v1 google form and then have one program staff person help us manually repost to new DB. 

cc @ldecoursy

**Comment by alanmoo** [comment]
I'm aiming to migrate to a staging db tomorrow. Depending on how that goes, we'll either need to manually move over new items after I grab existing ones tomorrow, or I'll figure out a way to make it pretty easy to do a final migration when v2 is live.

**Comment by ldecoursy** [comment]
Checking back on this. 

I wonder if it makes sense to use the small group discussions as an opportunity to ask folks to add stuff to pulse. @xmatthewx what do you think?

**Comment by xmatthewx** [comment]
Thanks @ldecoursy. I will add reminder to the notes doc. 

@alanmoo – for now, is it still cool if we add things via the v1 form? You and I can test v2 when you return next week.

**Comment by alanmoo** [comment]
Yeah add to the existing spreadsheet, just try and make sure things that are required/format-specific (like URLs) in v2 are respected so we can hopefully avoid migration glitches.

**Comment by alanmoo** [comment]
Follow up described in #358
