### ISSUE TITLE
Confirm google analytics are optimal 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#325]
@mmmavis – have the google analytics on the prototype been migrated to new implementation?

If so, awesome. I assume our views (recent, issues, etc) will show up now that we have proper routing. True?

An improvements I think we need: 
 - make sure that project titles show up in Behavior > Site content > Content drilldown. It currently just shows IDs in the URL, making it hard to analyze trends. 

Links:
 - implementation on prototype: https://github.com/mozilla/network-pulse/issues/27#issuecomment-240581646
 - o.g. checklist of priority things to track: https://github.com/mozilla/network-pulse/issues/69
 - long discussion on in app metrics (now limited to Favs): https://github.com/mozilla/network-pulse/issues/251

**Comment by mmmavis** [comment]
I forgot about GA so I haven't dealt with it for v2 yet. There's `react-ga` node package we can use so I think it won't be hard to bind GA events in. We should figure out [staging and production URLs](https://github.com/mozilla/network-pulse/issues/330) soon so I can ask DevOps to help create GA property for Pulse.

**Comment by mmmavis** [comment]
@xmatthewx 

> make sure that project titles show up in Behavior > Site content > Content drilldown. It currently just shows IDs in the URL, making it hard to analyze trends.

Do we wanna show both the id and title of the entry OR just the title? One note is that title can change but id won't.

**Comment by xmatthewx** [comment]
Let's show both if we can. Titles are very helpful for viewing browsing trends, even if they change once in a while.

**Comment by xmatthewx** [comment]
@mmmavis – this isn't critical pre-launch. but let's land this before we move onto other projects and forget.

**Comment by mmmavis** [comment]
GA event code has been reviewed and merged into the codebase. We just need to replace the [GA UA code](https://github.com/mozilla/network-pulse/issues/368) when we do get one. I think we can close this ticket now.
