### ISSUE TITLE
Rename favorites to bookmarks for developer clarity

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#326]
https://github.com/mozilla/network-pulse-api/issues/30

network-pulse-api :handshake: network-pulse

**Comment by Pomax** [comment]
update on this ticket: we probably want to update the client code so that it uses "bookmarks" in the code, only exposing this functionality as "favorites" when presenting labels to the user.

**Comment by mmmavis** [comment]
yay done!
