### ISSUE TITLE
Determine tags

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#33]
Based on the types of artifacts, issues, and hubs we identify, we will choose which tags/categories/filters we will need to have.

Possible artifacts are being identified in https://github.com/mozilla/network-pulse/issues/12

Issues: 
- Online Privacy & Security
- Open Innovation
- Decentralization
- Web Literacy
- Digital Inclusion 

Hubs:
- Learning
- Science
- Internet Policy & Advocacy
- Women & Web Literacy
- Internet of Things

**Comment by xmatthewx** [comment]
- Some things we should capture as fixed categories (our 5 issues), others could be user defined tags #ftw. 
 - Some things we should offer to the user on input, others we can leave to our staff archivists (program managers).

**Comment by kristinashu** [comment]
I'm reluctant to add user defined tags. Until we have thousands of entries, I think a lot of the tag searches will turn up with only a single post. I'd rather start with more focused categories and tags and then possibly add user defined tags in the future if required.

**Comment by xmatthewx** [comment]
Agreed. That's a good concern. 

We could have a single field on the backend for comma separated tags, so staff could add useful info for free text searches. We don't need to display the tags. Use case: someone posts flexbox froggy, with a good description. But, we discover that our Learning community is searching words like STEM, STEAM, school, web literacy, programming ... words that aren't in the description. We could add those keywords, keep 'em hidden, but leverage them for search.

**Comment by kristinashu** [comment]
You can see categories insitu here https://redpen.io/gn430826daeacf242d

There seems to be a lot of overlap between Issues and Hubs (ex Web Literacy and Learning). Do you think we could just show the Issues? It might be a good way to make sure all the categories have lots of posts (vs having lots of categories with only a few posts in each one).

**Comment by hannahkane** [comment]
+1 to Issues-only for the reason you mentioned, and because the issues are what we want to resonate with people.

**Comment by xmatthewx** [comment]
I recommend adding Issues to the spreadsheet before we commit to displaying them to users. It might be tricky to add issues to all the assets. You can add a spreadsheet column without breaking anything.

Programs could be added by staff in the backend, leveraged for search, but not displayed to user. So a user could search "science" and see relevant things.

**Comment by kristinashu** [comment]
Excellent, I'll start adding them to the spreadsheet https://docs.google.com/spreadsheets/d/1vmYQjQ9f6CR8Hs5JH3GGJ6F9fqWfLSW0S4dz-t2KTF4/edit?ts=5797bfdd#gid=922457769

**Comment by kristinashu** [comment]
@xmatthewx I added issues and hubs to the spreadsheet. Could you give it a quick glance and add/remove any you think fit/don't fit?

Once this is done, I'll open up an implementation ticket for @mmmavis to add this feature.

**Comment by xmatthewx** [comment]
Excellent. I took a look. Added a couple, but otherwise trusted your assessment.

@acabunoc – whether we include our 5 issues on the input form or not, our workflow will need program people to triage projects and apply the best issues. In your interviews, it'd be good ask if program people are starting think about how to apply issues to their program activity.
