### ISSUE TITLE
Staging and Production URLs

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#330]
@xmatthewx @kristinashu 

We should decide on the staging and production URLs for Pulse v2 (and going forward).

I've been using a personal Heroku instance https://pulse-react.herokuapp.com/ to make the WIP v2 app available for people to check out. When we are ready to push v2 to production, I can move the Heroku app to `mozilla` and rename it to something like https://pulse-staging.herokuapp.com/. We can use this instance as the real staging site going forward. We should also remove the v1 staging instance https://network-pulse.mofostaging.net/ (v2 app has a server)

For production, we should decide what URL we wanna use. The jQuery version (Pulse v1) uses GitHub page as the production site solution - we can't continue using it for v2.

/cc @cadecairos

**Comment by xmatthewx** [comment]
Thanks @mmmavis, this all makes sense. My preferred domain would be pulse.mozilla.org if available. If not, mozillapulse.org? 

Any pros/cons @cadecairos @kristinashu? How many challenges come with a subdomain?

**Comment by kristinashu** [comment]
pulse.mozilla.org would be great since it follows the same format as our other domains (science.mozilla.org, teach.mozilla.org, advocacy.mozilla.org...)

**Comment by cadecairos** [comment]
We can do pulse.m.o, but let's shoot for an A+ on the HTTP Observatory (observatory.mozilla.org)

**Comment by mmmavis** [comment]
Hey @cadecairos one thing that's related to this - Can we create a new property on Mozilla GA for `pulse.mozilla.org`? I'm working on https://github.com/mozilla/network-pulse/issues/325 with a UA code that I created with my personal testing account just for testing purpose. At some point we should replace it with the real UA code. I will create a DevOps ticket now.

@xmatthewx after v2 is out, should we keep or remove the current `network-pulse` property on GA?

**Comment by xmatthewx** [comment]
@cadecairos – just a reminder that we'll want to run a check on http observatory. I'm guessing we'll need a security review as well. Could we buy mozillapulse.org as a fallback plan?

**Comment by cadecairos** [comment]
We'll want to asap now, so a domain squatter doesn't take it!

**Comment by xmatthewx** [comment]
Ack. I can't believe I posted domain in plain text. Sorry team.

**Comment by mmmavis** [comment]
@cadecairos what's the minimum score we have to get on observatory? I have a `helmet` PR that's waiting to be merged. That should boost up our score a bit.

**Comment by cadecairos** [comment]
If I can weigh in on the URL - Since this app is displaying user supplied data, it will vastly speed up the process of going live if we don't use a mozilla.org URL.

Should we choose to go with mozilla.org, I'll have to get an rapid risk assessment done, and I'm confident that they'll recommend a security review of the code and a security scan for vulnerabilities. Timing for all these depend on the Sec teams availability.

**Comment by cadecairos** [comment]
> what's the minimum score we have to get on observatory?

At a minimum we'll want a B+. because we have to allow all images, and unsafe-inline in a few places we'll basically be capped at an A- or B+

**Comment by xmatthewx** [comment]
> if we don't use a mozilla.org URL...

Let's proceed with the URL I proposed before. We can explore a subdomain later if we want.

**Comment by xmatthewx** [comment]
@Pomax and @cadecairos to discuss a Thursday launch.

**Comment by mmmavis** [comment]
@cadecairos I believe we have the production URL we want, correct? 😃  If so I guess we can close this ticket and [the DevOps one](https://github.com/MozillaFoundation/mofo-devops/issues/452). I can create a separate ticket for creating a new GA property on DevOps repo if there isn't one already. Let me know!

**Comment by Pomax** [comment]
that sounds reasonable - the prod domain is up now.

**Comment by mmmavis** [comment]
Closing this one now. I will update the existing DevOps ticket: https://github.com/MozillaFoundation/mofo-devops/issues/452
