### ISSUE TITLE
show the splash page on first use, suppress on subsequent loads

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#331]
As the splash page comes with a forced waiting period, it'll be a good idea to show it on first-time-use, but then suppress it on subsequent loads by using a localStorage variable like `suppressSplashScreen=true`.

If the localStorage config does not contain the var, or it's not `true`, show the splash screen, and set `suppressSplashScreen=true` at the same time, so that a next load will bypass the splash.

**Comment by mmmavis** [comment]
Done!

**Comment by Pomax** [comment]
💯
