### ISSUE TITLE
Make sure Pulse API data is correctly passed to corresponding <ProjectCard> props

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#332]
... since field names are in snake_case and props names are in camelCase.

**Comment by Pomax** [comment]
As long as the names match, except for the casing, the XHR functions can run the results through something like this as a post `JSON.parse` step:
```
function snakeToCamel(obj) {
  let out = {};
  Object.keys(obj).forEach(key => {
    let rekey = key.replace(/_(\w)/, (a,b) => b.toUpperCase());
    out[rekey] = obj[key];
  })
  return out;
}
```

**Comment by mmmavis** [comment]
Done. I added a [`utility.js`](https://github.com/mozilla/network-pulse/blob/react/js/utility.js). The `snakeToCamel` function is declared separately as a function variable. I did it this way to make `snakeToCamel` look more like a helper function.
