### ISSUE TITLE
"featured" seems to poll the same list as "favs"

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#333]
If I load the client, fave three entries, and visit `/favs` I see those three entires. Clicking back to `featured` however then still only shows those three entires. It seems that `featured` is using the same list that `favs` is using?

**Comment by mmmavis** [comment]
I wonder if that's because every page uses the `<ProjectList>` component and React is caching it somehow?

**Comment by Pomax** [comment]
is the `<ProjectList>` data getting reset to the base entry list when you switch to `featured`?

**Comment by mmmavis** [comment]
Ah, I think I know why. Remember the `let combinedParams = Object.assign(defaultParams, params);` line in `js/service.js`? I think we are mutating `defaultParams` itself so over time `defaultParams` builds up and so does `combinedParams`.

I guess we can fix this by having something like

```js
let combinedParams = Object.assign(Object.assign({}, defaultParams), params);
```

OR 

```js
let clonedDefaultParams = Object.assign({}, defaultParams);
let combinedParams = Object.assign(clonedDefaultParams, params);
```

👀

**Comment by Pomax** [comment]
this PR was not quite complete, filed https://github.com/mozilla/network-pulse/issues/340 as follow-up but this issue should not close until that one's fixed =)

**Comment by mmmavis** [comment]
follow-up ticket has been fixed. Closing this one nowww.
