### ISSUE TITLE
Failed to deploy app properly on Heroku

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#335]
@Pomax can you lend a hand here please? I can't figure this out.

I tried to [deploy Pulse on Heroku](https://dashboard.heroku.com/apps/pulse-react/settings) and got error messages about `PORT` not being set. I don't remember having to set PORT explicitly for  Heroku apps that I've worked on before. (I believe Heroku sets `PORT` automatically?). I guess we are hitting errors now because for Pulse we are reading env vars from a `.json` file that's generated in [a build step](https://github.com/mozilla/network-pulse/blob/react/package.json#L10) instead?

In https://github.com/mozilla/network-pulse/blob/react/js/build-env-config.js
```
habitat.load(`.env`);
```
Question: does habitat load the `PORT` env var (assuming automatically) set by Heroku? It doesn't say much on https://www.npmjs.com/package/habitat#habitatload-pathtoenvfile- . I've always assumed it would but now it seems like I've been wrong. If that's the case does that mean we have to check the existence of `process.env` vars in `build-env-config.js` as well?

/cc @cadecairos (since you are a Heroku guru as well 😃 )

**Comment by Pomax** [comment]
Let's first fix this and then figure out what's going wrong: I updated the https://pulse-react.herokuapp.com instance so it has a PORT=80 binding, and we can figure out what's wrong during work hours tomorrow.

**Comment by Pomax** [comment]
Looking in the build log I see this:
```
       ERROR in ./config/env.generated.json
       Module build failed: SyntaxError: Unexpected token U in JSON at position 0
       at Object.parse (native)
       at Object.module.exports (/tmp/build_f697c7cbf890e3d95a972a317930cde9/mozilla-network-pulse-233ccc7/node_modules/json-loader/index.js:7:48)
       @ ./pages/bookmarks.jsx 31:20-59
       
       > network-pulse@2.0.0 build-client:scss /tmp/build_f697c7cbf890e3d95a972a317930cde9/mozilla-network-pulse-233ccc7
       > node-sass scss/main.scss dist/css/main.css
```

which would certainly be a problem.

**Comment by Pomax** [comment]
This might actually be Node 6.9 not supporting an ES6 feature...

**Comment by Pomax** [comment]
No matter what I do I don't see `env.generated.json` EVER having anything resembling what we're making the build script output so something is going incredibly wrong there. We'll have to figure this out tomorrow.

**Comment by cadecairos** [comment]
Is this file being created at runtime or build time?

Also, it's bad practice to use files for configuration on Heroku - due to the ephemeral nature of the containers running the apps.

**Comment by Pomax** [comment]
yeah, it's supposed to get generated as part of npm install.

**Comment by Pomax** [comment]
I literally don't understand what is going on here. I rewrote the env writer to use the following code:
```
const HOST = habitat.get(`HOST`);
const PORT = habitat.get(`PORT`);
const ORIGIN = HOST + (PORT ? `:${PORT}` : ``);

const config = JSON.stringify({
  HOST: HOST,
  PORT: PORT,
  ORIGIN: ORIGIN,
  PULSE_API: habitat.get(`PULSE_API`)
}, false, 2);

const opos = process.argv.indexOf(`-o`);
const outfile = process.argv[opos + 1];

var fs = require(`fs`);
console.log(`Writing config`, config);
fs.writeFileSync(outfile, config, { encoding: `utf8` });
```
and invoke it as
```
"build:config": "node js/build-env-config.js -o config/env.generated.json",
```
and yet the heroku log shows this as build output:
```
       > network-pulse@2.0.0 build:config /tmp/build_7de09986e1fa1d8fd71732cca66d831d/mozilla-network-pulse-ebae8b2
       > node js/build-env-config.js -o config/env.generated.json
       
       Writing config {
       "HOST": "https://pulse-react.herokuapp.com",
       "ORIGIN": "https://pulse-react.herokuapp.com",
       "PULSE_API": "https://network-pulse-api-staging.herokuapp.com"
       }
```

Where is `PORT`? Why is that key not even there??

**Comment by Pomax** [comment]
Filed https://github.com/mozilla/network-pulse/issues/338 to solve this properly

**Comment by cadecairos** [comment]
I don't think PORT is known until runtime. Builds happen in separate boxes.

**Comment by gideonthomas** [comment]
Yeah and looks like you can't change that

**Comment by Pomax** [comment]
Updates to make things work on Heroku for now:  https://github.com/mozilla/network-pulse/blob/react/server.js#L10-L18

Further work will happen in #338
