### ISSUE TITLE
Don't use a pregenerated config for env values

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#338]
Due to how heroku works, we cannot use a config pregenerator that stores values in an `env.generated.json` (or any other file) because the environment where the code is compiled is not guaranteed the environment where the code will actually run.

As such, it is necessary to make sure the server, at runtime, can supply these values either on a dedicated route that the webpage can load (either as independent script, or as an xhr by the bundle) or to have the server inject those values into the correct spot in the bundle when users request the .js file for it.

**Comment by mmmavis** [comment]
Found the doc that you created few months ago @Pomax . I'm gonna put it here as a reference: https://docs.google.com/document/d/1fF9jPHDpJ1xfJCLJ0oJgPw0HahszuPdZBKbny7ii_0M/edit?ts=57c5f369#heading=h.yxl0o26zatdx 👍
