### ISSUE TITLE
Revise form fields

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#34]
We need to identify necessary fields based on the identified artifacts (related to tagging https://github.com/mozilla/network-pulse/issues/33).

Fields need to be flexible enough to fit all artifacts and should be low friction in order to encourage upload (no image upload requirement).

**Comment by xmatthewx** [comment]
We can have three types of fields:
 - input form - required for input (should be zero or almost zero – we can delete broken submissions)
 - input form - optional input
 - db triage - fields used by staff

Staff can add info to refine entries to reduce burden on user input and increase reliability of data. This could include things like issue areas, value to network, etc. 

Link to [Current form](https://docs.google.com/a/mozillafoundation.org/forms/d/e/1FAIpQLSd59CbzEheXsCydzJSqez3vB-zzacbf_wXC3c5DhAjWKExlTQ/viewform)

**Comment by xmatthewx** [comment]
depends on #48

**Comment by xmatthewx** [comment]
We should also examine how the form frames what types of things seem to fit / not fit. Based on feedback from Amira via Abby.

**Comment by kristinashu** [comment]
@xmatthewx I've put the questions into a gdoc so we can comment and update. I'm mostly suggesting we remove some questions to make the form shorter and work more broadly for different types of assets. Let me know what you think. I'm sure the questions will change over time as we discovery what the pulse can become!

https://docs.google.com/a/mozilla.com/document/d/1JroE86P4_BxHh7DPMp5_cLaHQ-AWgdi1BAZqS3v2m-4/edit?usp=sharing

**Comment by xmatthewx** [comment]
Lots of progress today with @kristinashu. Changing this to implementation.

**Comment by kristinashu** [comment]
I've updated the form. Here is a summary of non-copy related updates. (Based on comment in https://docs.google.com/document/d/1JroE86P4_BxHh7DPMp5_cLaHQ-AWgdi1BAZqS3v2m-4/edit#heading=h.d4xdgyi7ghde)

- Removed "Status" question from the form
- Added an Issues question to the form. I need to copy over the issues we had manually added into the new column. Only problem is the form adds each issue as a new column. Is that ok?
- Swapped order of "Get involved" and "Get involved URL"
- Removed "Helpful Info" section that included "Network connection" and "Origin"

Note: even though we removed some questions, we still want to keep the column and info we have already collected around these questions.

Still need to do:
- [ ] Write and add intro text to form
- [ ] Add http:// or https:// test so we can remove that text https://github.com/mozilla/network-pulse/issues/156
- [ ] Update "Creator" to title to "Creators"

I've added a test project and it was added without any problems. Now what's the best way to delete it?

@xmatthewx @mmmavis can you please take a look and see if anything in the spreadsheet seems ok or needs to be updated?

**Comment by kristinashu** [comment]
For reference, here is a screen cap of the old form ![old form](https://cloud.githubusercontent.com/assets/1068783/17567427/277d465c-5ef4-11e6-9294-386a54dc91d7.png)

**Comment by kristinashu** [comment]
Opened tickets for:
- Add http:// or https:// test so we can remove that text #156
- Update "Creator" to title to "Creators" #162

Only remaining piece for this ticket is to write and add intro text. @xmatthewx I've wrote something rough but would love you take on it
https://docs.google.com/a/mozilla.com/document/d/1JroE86P4_BxHh7DPMp5_cLaHQ-AWgdi1BAZqS3v2m-4/edit?usp=sharing

**Comment by kristinashu** [comment]
Intro copy was revised and added to the form.
