### ISSUE TITLE
add "user.verify" to componentWillUnmount

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#343]
This will allow things like "failedLogin" to reset between different pages.

**Comment by mmmavis** [comment]
Hey @Pomax I wonder if this is something related to Pulse API instead. I added 
```
componentWillUnmount() {
    user.verify(this.props.router.location);
  }
```
back in and it seemed like `user.verify` did get kicked in when component got unmounted.

So I
1. Went to the /add page on Pulse front end
2. Used my Mozilla Account to log in
3. Got redirected back to /add as the authenticated user
4. Opened another tab to log my Mozilla/Google account out
5. Visited http://test.example.com:8000/userstatus and realized I was still being seen as a loggedin user.

**Comment by Pomax** [comment]
what did step 4 look like? where/how did you log out?

**Comment by mmmavis** [comment]
@Pomax 

> what did step 4 look like? where/how did you log out?

I went to https://myaccount.google.com/permissions?pli=1, clicked on the little circle at top right, and chose "sign out". Google logged me out. And then I got redirected to the following url.

https://sso.mozilla.com/signout.html
<img width="965" alt="screen shot 2017-01-30 at 10 07 13 pm" src="https://cloud.githubusercontent.com/assets/2896608/22454116/82845712-e738-11e6-8b0b-a8f16e98a7c1.png">

I then went to http://google.ca/ just to confirm that I wasn't logged in anymore.

<img width="957" alt="screen shot 2017-01-30 at 10 14 23 pm" src="https://cloud.githubusercontent.com/assets/2896608/22454290/846fcd1c-e739-11e6-9bc0-3ed6993eb8df.png">

**Comment by mmmavis** [comment]
Uh oh. Is it something to do with Mozilla's SSO? So after I visited google.ca I went to http://sso.mozilla.com/ to triple check 😂 . However, I was still seen as "Mavis" there.

**Comment by Pomax** [comment]
If you don't log out through the app, the app won't know you've been logged out. This isn't OKTA/SSO, it's gmail auth so as long as you aren't logged out of *google* you'll still be logged in as far as the app is concerned

**Comment by mmmavis** [comment]
> If you don't log out through the app, the app won't know you've been logged out. This isn't OKTA/SSO, it's gmail auth so as long as you aren't logged out of google you'll still be logged in as far as the app is concerned (as long as there is a google session anywhere, you'll still be logged in)

Ah I see.

@Pomax even when we have the following snippet on `add.jsx` and `bookmark.jsx`
```jsx
componentWillUnmount() {
  user.verify(this.props.router.location);
}
```
Unmount doesn't wait for the verification process to finish so we can't guarantee `user` gets properly reset *before* new page gets rendered (e.g., if you are going from /add page to /featured page). 

I don't how often we should have user re-verified.  In `componentDidMount` and `componentWillUnmount` lifecycle methods of **all** page level components?

**Comment by Pomax** [comment]
One thing we can do is register components as listeners to the `user` object, so that any listening object is sent a notification when a user action occurs, In principle:

```
class User {
  constructor() {
    this.listeners = [];
  }

  // register listeners
  addListener(o) {
    this.listeners.push(o);
  }

  // unregister listeners
  removeListener(o) {
    this.listeners.splice(this.listeners.indexOf(o),1);
  }

  // notify all listeners of a change for this user
  notifyListeners(evtName) {
    this.listeners.forEach( listener => {
      if (listener.updateUser) {
        listener.updateUser(this)
      }
    });
  }

  // do a thing. Rather than using a "passed" callback, things register
  // as listeners during their componentWillMount and then the user
  // functions simply blindly inform all registered listeners of changes
  // in the user state. Each registered component can then decide
  // whether or not to act that state change (if unmounted, not, for instance)
  doAThing() {
    doAnAsyncThing( (evt) => {
      this.notifyListeners(evt.name, this);
    });
  }
  ...
}
```

**Comment by xmatthewx** [comment]
@pomax Are we still working on this? Critical for launch? Should we push to next milestone or move to the backlog?

**Comment by Pomax** [comment]
@mmmavis will be better able to answer that.

**Comment by mmmavis** [comment]
I'd say move it to next milestone. I'm aiming to get the "add new entry" form in place first (hopefully by this week).
