### ISSUE TITLE
Implement a Notice component

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#344]
A few places we display a text notice to users (like failed login). Not urgent, but it would be good to design a reusable component for this. 

cc @mmmavis

**Comment by mmmavis** [comment]
@xmatthewx did you mean something like

<img width="529" alt="screen shot 2017-01-31 at 12 40 33 pm" src="https://cloud.githubusercontent.com/assets/2896608/22483565/a04a5ca4-e7b2-11e6-8a2c-674d058ac823.png">

If that's the case we have a `<HintMessage>` component already: https://github.com/mozilla/network-pulse/tree/react/components/hint-message

**Comment by xmatthewx** [comment]
There's a notice that appears in this scenario that's different: https://github.com/mozilla/network-pulse/issues/317#issuecomment-276096992

**Comment by kristinashu** [comment]
Feels a little messy on this screen because there is a lot going on but how about something like this? 

![screen shot 2017-05-03 at 10 13 04 am](https://cloud.githubusercontent.com/assets/1068783/25672599/1edd5aa2-2fe9-11e7-8023-611564031345.png)

**Comment by mmmavis** [comment]
@xmatthewx @kristinashu I heard that we are going to allow non-staff to log in soon. If that's the case do we still need this Notice component? What are the other use cases?

**Comment by xmatthewx** [comment]
not a priority to update this now, but there will be other use cases. for example, staff items get posted immediately, non-staff will be held for moderation. we'll want to let people know.

**Comment by mmmavis** [comment]
Obsolete ticket. Closing.
