### ISSUE TITLE
Update logo to align with new brand

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#351]
We should update name/logo to align with the new brand. I recommend we call it Mozilla Pulse, dropping the word Network. What do you think @kristinashu? We can go horizontal or stacked.

Examples for reference: https://mozilla.ninja/gallery/

**Comment by xmatthewx** [comment]
@kristinashu – Should we bump this to the next heartbeat?

**Comment by kristinashu** [comment]
Sure, seems low priority.

**Comment by xmatthewx** [comment]
Just thinking... it will be a little odd to promote the new release with staff and not have the new logo. Maybe @sabrinang can help knock one out quickly since she's done it twice already?

**Comment by sabrinang** [comment]
Exported .png and .svg in gdrive:
https://drive.google.com/drive/folders/0B4Q8pzCpDS_ebUpHeVRGN0loNUE?usp=sharing
<img width="1173" alt="screen shot 2017-02-16 at 4 34 41 pm" src="https://cloud.githubusercontent.com/assets/2492510/23047632/ea9bcf76-f465-11e6-8470-91cdee240b69.png">

.ai file is there too (to edit in the future with Zilla typeface)

**Comment by kristinashu** [comment]
Thank you Sabrina!

**Comment by kristinashu** [comment]
This only shows up on the splash screen, I think stacked will work well.

**Comment by kristinashu** [comment]
Oh my gosh! I'm so distracted from Pulse I forgot v2 does use the logo on every screen. I think the horizontal is actually better for this at 204 x 34 px (for both the nav bar and the splash screen).

[mozilla-pulse_wordmark-interim-horizontal.svg.zip](https://github.com/mozilla/network-pulse/files/794338/mozilla-pulse_wordmark-interim-horizontal.svg.zip)

<img width="1200" alt="screen shot 2017-02-22 at 9 44 23 am" src="https://cloud.githubusercontent.com/assets/1068783/23224567/c3099736-f8e3-11e6-9df2-20e524393dad.png">
<img width="319" alt="screen shot 2017-02-22 at 9 46 04 am" src="https://cloud.githubusercontent.com/assets/1068783/23224568/c30b71f0-f8e3-11e6-90af-7e8e764b756f.png">

I think we should eventually make all the dark grey elements black to match the logo but I'll open up a new ticket for that.

Should be ready for you now @mmmavis!
