### ISSUE TITLE
Gather images to feature MozFest talks

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#354]
The MozFest dialogues and debates are freshly cut and posted to Pulse by @KevZawacki.  It would be great to find an image or video frame for a few of them, so we can add them to the featured tab. 

@KevZawacki – can you identify 3-4 best candidates? Can you work with @kristinashu to grab a screenshot?

**Comment by KevZawacki** [comment]
@xmatthewx Certainly.

Three best candidates are Zeynep Tufekci, Chris Soghoian, and Sahar Aziz. Screenshots below -- let me know how I can help further.

![chris](https://cloud.githubusercontent.com/assets/11045250/22796932/6ab4e9aa-eeca-11e6-90ed-d2dcf66d2e77.png)
![sahar](https://cloud.githubusercontent.com/assets/11045250/22796934/6ad8138a-eeca-11e6-8f29-6141be393119.png)
![zeynep](https://cloud.githubusercontent.com/assets/11045250/22796935/6ae0f4fa-eeca-11e6-9691-5a2fb0cb3334.png)

**Comment by xmatthewx** [comment]
Cool. We should add Katherine Maher MozFest talk if we want to feature that on the network site as listed here: https://docs.google.com/spreadsheets/d/1MVOTTxNH4FvyoiBIR--F8HqZYhBvlL2LSKi4XDa1LKo/edit#gid=2088995141

**Comment by KevZawacki** [comment]
Here's a screengrab of Katherine's talk:

![screen shot 2017-02-13 at 4 17 56 pm](https://cloud.githubusercontent.com/assets/11045250/22903755/bf60b368-f207-11e6-9cce-ec57704b9a71.png)

**Comment by kristinashu** [comment]
Here are the cropped images, they should be ready to be uploaded. @alanmoo can you please upload them?

![01](https://cloud.githubusercontent.com/assets/1068783/22946790/57dc5160-f2ad-11e6-8d69-d48c8606f080.jpg)
![02](https://cloud.githubusercontent.com/assets/1068783/22946791/57dee704-f2ad-11e6-85d1-7cd33b9c907b.jpg)
![03](https://cloud.githubusercontent.com/assets/1068783/22946789/57d95b7c-f2ad-11e6-8d89-1d30de5f671e.jpg)
![04](https://cloud.githubusercontent.com/assets/1068783/22946792/57ea894c-f2ad-11e6-8c4d-005b3c590c16.jpg)

**Comment by alanmoo** [comment]
I don't actually have access to the S3 bucket, @cadecairos or @gideonthomas can you help out with this? They should end up at `https://d27v9tuhdmbcr4.cloudfront.net/network-pulse/`

**Comment by gideonthomas** [comment]
Are they already linked in the front-end? If that's the case, what are the names for these images? Or can we just assign them names and paste them here?

**Comment by alanmoo** [comment]
Nope, not on there yet, just post the names here.

**Comment by gideonthomas** [comment]
https://d27v9tuhdmbcr4.cloudfront.net/network-pulse/mozfest-katherine.jpg
https://d27v9tuhdmbcr4.cloudfront.net/network-pulse/mozfest-sahar-aziz.jpg
https://d27v9tuhdmbcr4.cloudfront.net/network-pulse/mozfest-zeynep-tufekci.jpg
https://d27v9tuhdmbcr4.cloudfront.net/network-pulse/mozfest-chris-soghoian.jpg

**Comment by gideonthomas** [comment]
Let me know if anything else needs to be done here!

**Comment by alanmoo** [comment]
These have been added to the Google Sheet for v1 of Pulse. When we launch v2, they'll get carried over in the final migration.
