### ISSUE TITLE
Featured items – custom sort order

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#357]
Admins will want to set the order on featured items. Top 3 shouldn't necessarily be the 3 most recent.

Option A
 - Provide admins with a new view that lists all featured items. Enable them to drag-n-drop to specify order.

Option B
 - On individual entry edit view, provide admins a field to enter a sort value. 
 - Enforcing a strict sort would be very cumbersome. So, we could offer Featured Group A, Featured Group B, and allow no value on the rest. We would then sort by feature group and timestamp. Admins could then use these flexibly for something like top 3, top 9, other.  

What do you think @Pomax @alanmoo ?

**Comment by Pomax** [comment]
With an eye to the future, I'd also like to put the idea of automated ranking on the table similar to how imgur, hackernews, reddit, etc (and to a degree, google) present "top hits" based on a mix between age (negative ranking) and popularity (positive ranking). If this project becomes popular enough to be one of those sites mozillians hit up first thing in the morning for a quick surfin' then manual intervention becomes an intractable proposition.

Of course we're nowhere near that point yet, but planning for "when this needs to be automated" early can make it much easier to switch later on.

In terms of the suggested options, both feel like they'll probably break down really fast, both options become near-impossible with more than a handful of entries in the list (a human being would need to sit there and compare n² pairings to do a "fair" sorting), so perhaps an option C would be a combination of the automated concept mentioned above, and a human intervention in the form of a button that sets an age override for feature purposes, such that for the purpose of feature ranking it counts as having just been posted again". 

And in whatever case we end up implementing, we may also want to consider a "sticky" flag for featured posts, to bypass (automated or manual alike) rankings and simply have an entry show up at the top of the feature list for a while (or until the sticky flag is turned off)

**Comment by alanmoo** [comment]
Yeah, maybe a "most recent featured time" property on the model that we sort by, which maps to a "make this the top featured item" button? So you're just..."playing Jenga" is the best metaphor I can come up with right now. But hopefully without the bit where everything collapses.

**Comment by xmatthewx** [comment]
For Option A, if we can provide admin list of all featured items (just titles), it shouldn't be too tricky to sort. I'd give that view a way to remove things from featured so the list could always be 2-3 dozen entries max. 

I'm also interested in having some automated ways to highlight [entries](https://github.com/mozilla/network-pulse/issues/251) and [trends](https://github.com/mozilla/network-pulse/issues/320). This is different. Staff will need to say: these 3 things belong on the homepage of the network site. And, these 24 belong on the project page, because they align with our upcoming focus on such-and-such topic.

**Comment by alanmoo** [comment]
Yes, that wouldn't be too difficult from an administration standpoint but I'm concerned about the effort to implement an interface like that vs its usefulness; at first mention it feels like it would be a significant effort to build properly.

I'm not sure I follow your second paragraph @xmatthewx. You're saying 3 items belong on the homepage of the upcoming network site? We might want to do some more thinking about how best to do that. And by "project page", what are you referring to?

**Comment by Pomax** [comment]
Given Option A's discussion do we want to give admin'd users a direct "checkmark" UI that lets them flag and unflag things as featured without having to hit the admin interface, in that case? Or would the fact that every logged in (staff) member is treated as an admin at the moment make that inconvenient?

**Comment by xmatthewx** [comment]
Sorry for the lack of context. We need to pull items from Pulse into the network site. These need to be carefully curated. If the network is focused on a topic like Encryption one month, we'll feature a mix of things that include a bunch of encryption. Three entries will appear on the homepage, a dozen or two on the [project page](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/217251312). 

Somewhere, we need to give an admin a way to rank those items. I'm totally flexible in how that happens, but we'll need more control than just feature-flag + timestamp.

**Comment by xmatthewx** [comment]
We can launch without this, but we'll need to figure something out in the near future.

**Comment by Pomax** [comment]
I'm getting a bit confused - we have two repos, "network-pulse" (the client) and "network-pulse-API" (the server). I don't understand talking about "the network" and "pulse" as two different things, can you elaborate what you mean with these terms when used on their own rather than as a single thing referring to the same system?

**Comment by alanmoo** [comment]
I believe network site = MLN site that's being built by others in the MoFo Production team

**Comment by xmatthewx** [comment]
Oops. Sorry. Yes, Pulse entries will be pulled into the new site for the Network website as mocked up here: https://projects.invisionapp.com/share/ZJ9YTAGEA

**Comment by alanmoo** [comment]
Will those be a different set than the top x entries on the featured page of the main pulse site?

**Comment by xmatthewx** [comment]
Same set. 

Sorry for the lengthiness of this issue. Might have been better if I initiated this while meeting over video.

**Comment by xmatthewx** [comment]
Closing. Starting again in #423.
