### ISSUE TITLE
At V2 launch: Migrate newest data and shut down existing capture form

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#358]
Blocked by launch, but data since February 8 will need to be migrated and the existing form capture should be shut down/redirected

**Comment by xmatthewx** [comment]
@alanmoo – maybe schedule a specific time for this? thursday before? friday after?

if we migrate before launch, we should:
  - [ ] make sure nothing snuck into the old pulse in the small window during launch

**Comment by alanmoo** [comment]
The "proper" way to do this would involve simultaneous writes to both databases for a while. Fortunately, we're low traffic enough that I'm fine doing this right before launch.

**Comment by xmatthewx** [comment]
@alanmoo - pulse is live and looking beautiful. Thanks!! I'll start to share with Kevin and Chris and others after we do one last migration.

**Comment by alanmoo** [comment]
Ok so I should go ahead and do this?

**Comment by mmmavis** [comment]
@alanmoo This is done? 😃😃😃😃😃

**Comment by alanmoo** [comment]
👍🏼
