### ISSUE TITLE
Prep for v2 staging

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#360]
`master` branch is currently being used as v1 staging. Since we are not developing on v1 anymore, to move us a step forward towards GitHub flow and prep us for v2 launch I think we should 

- [x] get rid of v1 staging: https://network-pulse.mofostaging.net/ (@alanmoo created a [DevOps ticket](https://github.com/MozillaFoundation/mofo-devops/issues/460))
- [x] push code in `react` to `master` 
- [x] get rid of the `react` branch 
- [ ] ~~create a Heroku staging instance that's based off of `master` (I have one currently http://pulse-react.herokuapp.com/ that's based off of `react`. I can rename it to `pulse-staging` and move it under Mozilla on Heroku)~~ no longer applies since we have an official v2 staging instance set up: http://network-pulse-staging.herokuapp.com/
- [x] make sure v2 staging is linked to `master`

If there's any update that we absolutely need to make to [v1 prod](https://mozilla.github.io/network-pulse/), we can do it by submitting&merge PR against the `gh-pages`.

@xmatthewx if you are okay with this I wanna tackle this todo list ASAP. 😄 Having too many branches and staging/production sites can be quite confusing (at least to me 😉 ).

**Comment by xmatthewx** [comment]
Works for me. Any conflicts @cadecairos @alanmoo? 

Loosely related to final migration: https://github.com/mozilla/network-pulse/issues/358

**Comment by alanmoo** [comment]
Devops ticket filed for point 1, except it was to redirect the staging url to heroku.

**Comment by alanmoo** [comment]
I've created a [pipeline](https://dashboard.heroku.com/pipelines/602785db-1ca6-43e4-9a35-e546dab127a4) and stood up the pulse staging and production instances. Note that the pipeline can't *actually* be used to promote because the env var for API server is baked in at build time, but this at least links them together.

**Comment by mmmavis** [comment]
DONEEEEE 🎉 🎉 🎉 

Thanks for the help @alanmoo 🍻
