### ISSUE TITLE
Allow image uploading for Pulse entries

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#363]
based on https://github.com/MozillaFoundation/mofo-devops/issues/430#issuecomment-279779017 we should look at how we can best get images submitted along with forms.

Given that I don't see a way to make S3 publishing for images work securely in the client, a possible flow would be:

- user posts data to API
- API pushes data into model
- API uploads image to S3 -> gets a URL back
- API updates model with S3 url as thumbnail image url
=> API confirms to user that their POST was processed successfully

**Comment by xmatthewx** [comment]
Are you thinking of this happening via frontend form by users? Or via backend by admins? I think admin-only is okay for a first pass on this, if that saves a bit of energy.

**Comment by Pomax** [comment]
I would think the user sends the form with an image in it, and then the API server takes care of the rest, so as far as the user is concerned they simply get a normal "drag/drop image or browser your computer for one or give us a URL!" and if it's not a URL, we make the API server do the S3 magic. S3 is fast, so it wouldn't block the form submission during normal operation.

**Comment by xmatthewx** [comment]
Cool. I think we will need to give admins the ability to add and change images (manually download and crop is totally fine) ....to ensure quality on featured items. Will that be difficult to add to django admin? Wondering if we should prioritize image handling via Admin first, and then follow with the form for Users. Curious what you think.

**Comment by Pomax** [comment]
I would push back on that and say admins shouldn't ever be on the hook for that: offer the user the controls for that. When they add an image to their entry, fetch the image, present it to them with a crop overlay, and warn them for low res images, with a hard "no you cannot use this image" for way-too-low-res images.

**Comment by xmatthewx** [comment]
I'm not saying we shouldn't give the User the ability to upload, crop, and post their own images. We should work toward that. Can we realistically implement that in the next 2 weeks along with all the other things on our plate?

In addition to that, I think it's a requirement that Admins/Curators be able to add and update images. Consider this scenario: 

A fellow or MozFest participant posts something amazing (themself or via a staff person). Kevin loves it, and wants to promote it as a feature to coincide with an upcoming advocacy campaign. But the image is of terrible quality. We're stuck. We ask the person to repost with a new image, but they email us a new image instead. Communication across timezones with a remote village has devoured a week. The press inquiries are starting to roll in, but we still can't feature the project. The image the person sent is better, but we can't edit the image easily via Django. We consider reposting but notice the project already has 99 favs. We file a devops ticket to manually add image to AWS and edit entry in the DB. The work gets done, but we've missed the window. Articles have been posted, but opportunity is missed. 

If implementing that on django for Admins is faster than implementing it for users on the frontend, I wonder if we should start there. We could create a temporary Image URL field for the frontend form for Users.

**Comment by Pomax** [comment]
No that's fair, I commented under an assumption that is probably not grounded: Django admins can already do *anything*. If they need to create or delete an entry, they have that power already, and if they need to update a single field in an entry, like replacing an image URL, they have that power already, too. 

In this case, the server would upload the user-specified image (Cropped properly) to S3 and get a URL back; the admin view will let any admin trivially change that URL to any other image needed. So that's the base case. If we need something "fancy" that lets admins view the image, and edit it in place, then that goes beyond basic powers and requires either a dedicated dashboard that lets them do that out-of-admin, or requires hacking on the admin view for entry models to include an image editor. Both are a fair bit of work, and not something we'll have ready as soon as we have images-to-S3 ready, but admins *will* already be able to curate images on a case-by-case basis.

**Comment by mmmavis** [comment]
(I'm moving this ticket out of the current milestone since we don't have enough enough to finish it. Gonna put it in the next milestone for now.)

**Comment by xmatthewx** [comment]
Thanks @Pomax. I recognize the scenario is slightly extreme. If we do our jobs well with the new network site, top featured stuff on Pulse will have a lot of eyes on it.  Items outside of the featured space can be imperfect with good-to-okay images. So, low volume, but high value curation and admin.

 - If admins can upload a new image via django, that's great. Image editing not necessary. 
 - If image uploads via django admin would be a _harder_, not _easier_ than via our frontend form, than we can skip that. In that case, could we give admins a frontend form for adding images only to the bucket that returns URL for copy-pasta into admin interface? Not to edit an entry, just upload an image.

**Comment by Pomax** [comment]
if it's just uploading a new image (pre-cropped to the correct aspect), it's probably easier to keep that in the admin view.

**Comment by xmatthewx** [comment]
Okay. Simon suggested we do a quick estimate. Maybe team up with @gideonthomas since this is useful for other django projects coming up?

@Pomax is the list below an accurate summary?

Requirements in order of importance: 
 - Add image uploads to the API `mvp`
 - Add upload field to frontend form `mvp`
 - Add upload functionality to Admin entry view `needed soon`
 - Enable frontend Users to preview and adjust image crop `needed eventually`

**Comment by Pomax** [comment]
What's the actual MVP date? The order looks right to me, not sure if the first two can make it into MVP depending on the dates.

**Comment by xmatthewx** [comment]
I don't think this blocks launch. So, we can launch during heartbeat that starts Monday and continue this as required. Let's estimate the first 3 items and then make a plan based on that. For crop functionality, it would be good to have a notion of the work required, but I don't think we need to consider it as closely.

**Comment by Pomax** [comment]
crop functionality needs a bit of research because there are premade solutions out there already, the tricky part (which always messes up time estimats) is finding one we can easily drop into our codebase(s). In terms of image uploading, I'd estimate a day to implement it, a day to realise it doesn't work in the slightest, and a day of mandatory "your engineers underestimated the time needed". The only tricky bit is making Django do the S3 posting, the rest is already handled.

**Comment by xmatthewx** [comment]
@Pomax will let us know soon-ish whether we can/should land this before we launch on Thursday, or after.

**Comment by Pomax** [comment]
This looks like something that can be done "easily", but given a Thursday launch, not with enough days to have both @alanmoo and myself around to both implement and then test before launch. Candidates for tackling this issue are https://github.com/boto/boto and https://github.com/bradleyg/django-s3direct (between the two, most likely bobo... I know, it's a horrible name) both of which should involved a small-to-moderate amount of programming, but enough to if we do it wrong set us back half a day to a day which would basically put us at "still working on it when launch is supposed to happen".

**Comment by xmatthewx** [comment]
Alrighty. It _is_ a curious name.

**Comment by xmatthewx** [comment]
@Pomax are you still working on this or is it on hold? Do we need a corresponding ticket in the api repo?

**Comment by Pomax** [comment]
this was put on hold when we decided image upload would not be necessary for launch, and we've been sorting out some launch issues in the mean time. @gideonthomas and @cadecairos have [implemented image upload on the network-api side](https://github.com/mozilla/network-api/commit/d692ad329ab95d36028d3d7ebb122fbe9505d83b) that we can probably use as well.

**Comment by xmatthewx** [comment]
Got it. To clarify, I didn't want it to block the launch of Pulse. So we could start QA and get Kevin on board. I do think it's required for launch of the Network site. Pulse featured prominently there and we have lots of pulse content to polish up and add. Sorry if that was ambiguous.

**Comment by Pomax** [comment]
Associated issue on the network-pulse-api repo (with PR) https://github.com/mozilla/network-pulse-api/issues/98

**Comment by xmatthewx** [comment]
Closing this discussion. Tracking frontend in https://github.com/mozilla/network-pulse/issues/424 and API in  https://github.com/mozilla/network-pulse-api/issues/98
