### ISSUE TITLE
Prepare Quality testing scripts

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#367]
@kristinashu – can you help us prepare a checklist for quality testing. Checklist is a script for people to follow and confirm stuff happens as it should. We can follow [a pattern](https://github.com/mozilla/webmaker-core/wiki/Webmaker-Quality-Testing) we used before. We won't need so many lists. This way, we can get some people other than us testing on Mobile, Windows, other browsers  etc. cc @alanmoo if you want to get in on the fun.

**Comment by kristinashu** [comment]
Here's a start...

### Things to test:
- [ ] Add a post (need to write script)
- [ ] Search (need to write script)
- [ ] Content loads in main nav items (Featured, Latest, Issues, Favs)
- [ ] Fav and unfav works
- [ ] Copy link works

### Where to test:
Mac desktop
- [ ] safari
- [ ] FF
- [ ] chrome

iphone
- [ ] safari
- [ ] FF
- [ ] chrome

Windows desktop
- [ ] FF
- [ ] chrome
- [ ] IE???

Android
- [ ] FF
- [ ] chrome
- [ ] ?

**Comment by alanmoo** [comment]
iOS uses the same rendering engine across all 3 browsers, so I'm not super concerned about multi-browser testing there. More like screen size confirmation (iPhone, iPhone+ , iPad portrait, iPad landscape)

**Comment by xmatthewx** [comment]
looks like i actually created some scripts last fall. they could use a quick update based on revised design since then. but we probably don't need this until we're preparing to land a big change or release to general public. https://github.com/mozilla/network-pulse/wiki/Quality-Tests
