### ISSUE TITLE
Update GA UA code

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#368]
When we have an official GA property set up, we should update the temporary testing UA code with a real one.
https://github.com/mozilla/network-pulse/blob/master/main.jsx#L8-L11

And Make sure things mentioned in this list still work as expected: https://github.com/mozilla/network-pulse/pull/349/#issue-205747713

**Comment by xmatthewx** [comment]
Nice. Is there a devops ticket for this?

**Comment by mmmavis** [comment]
Yes: https://github.com/MozillaFoundation/mofo-devops/issues/452#issuecomment-280438064
