### ISSUE TITLE
Include "interest" field in "add new enry" form?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#371]
@xmatthewx 

Not sure if it was by design -  I just realized the form mockup didn't include the field "interest": https://redpen.io/nvd9c7a75f06c79e35

/cc @kristinashu

**Comment by xmatthewx** [comment]
Thanks @mmmavis. I added a comment on Redpen with slightly adjusted phrase you can use for the form.

**Comment by mmmavis** [comment]
kk I've included it in the 'add new entry' PR: https://github.com/mozilla/network-pulse/pull/372

**Comment by kristinashu** [comment]
Do we really need that field? If so, @xmatthewx what do you want to hint text to be?

**Comment by xmatthewx** [comment]
I worry about people hastily posting stuff without thinking about what it means to the others. We could look in the spreadsheet to see if the field has been used well or is redundant. I'm open to removing it, but I'd like to keep it unless we've found it to be no useful. Nobody has said to us they struggle to figure out what to put there.

**Comment by kristinashu** [comment]
Ok, what should the hint text say?
