### ISSUE TITLE
Redirect short URL

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#373]
Wherever this ends up living, at launch we should redirect mzl.la/pulse to the new URL.

@xmatthewx is that done via a bugzilla ticket or something?

**Comment by ryanwarsaw** [comment]
@alanmoo If you file an issue in the ```mofo-devops``` repository, I'm sure cade or gideon could make the redirection changes, perhaps something to add in MozillaFoundation/mofo-devops/issues#452?

**Comment by alanmoo** [comment]
Cool. I'll do that once the site is live, we don't have anywhere to direct people to yet.

**Comment by xmatthewx** [comment]
I got this one. It's a bit.ly account that our communications people use.

**Comment by mmmavis** [comment]
Seems like this is already done. https://mzl.la/pulse now goes to https://www.mozillapulse.org/ 👏
