### ISSUE TITLE
Form styling QA

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#374]
Few styling things but none of them are blockers. Here's the [redpen link](Redpen https://redpen.io/nvd9c7a75f06c79e35) for reference.

- [ ] vertical spacing: generally needs a little more space above titles (example: above "Basic Info" and "Optional Details", and above each field like "Title of the project" and "URL")
- [ ] width for content is too wide: should be using only 8 columns instead of all 12
- [ ] fira isn't loading in the form field and button
- [ ] needs a little more space after check boxes, before the text

Screen cap of comp next to staging:
<img width="1020" alt="screen shot 2017-02-22 at 10 10 45 am" src="https://cloud.githubusercontent.com/assets/1068783/23225784/00922254-f8e8-11e6-96e6-3c5adfeb13ff.png">

Column grid for content width:
<img width="1197" alt="screen shot 2017-02-22 at 10 15 04 am" src="https://cloud.githubusercontent.com/assets/1068783/23225790/0319f0b0-f8e8-11e6-8509-6e8d5b475483.png">

Check boxes too close to text:
<img width="451" alt="screen shot 2017-02-22 at 9 29 28 am" src="https://cloud.githubusercontent.com/assets/1068783/23225800/0c23a2dc-f8e8-11e6-857f-f4ae6b6d8bca.png">

**Comment by xmatthewx** [comment]
Thanks for the close look at this @kristinashu. I agree that none of these should block launch. Better to launch, test, and then address things like this all at once.  

I was about to add Pomax to my test entry when I noticed the link/input overlap:
 
<img width="972" alt="screen shot 2017-02-22 at 6 51 25 pm" src="https://cloud.githubusercontent.com/assets/53411/23238457/07e5a326-f930-11e6-8929-ebefa1036502.png">

**Comment by mmmavis** [comment]
checkbox spacing will be tackled as a followup ticket: https://github.com/mozilla/network-pulse/issues/391
