### ISSUE TITLE
Confirmation message after successful form submission

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#376]
Brought up by @Pomax in https://github.com/mozilla/network-pulse/pull/372#issuecomment-281497076

> @mmmavis @kristinashu it feels like the submission process here is "too fast", in that there is no post confirmation? You're taken to the issue you just posted, which I remember we wanted to have happen, but it might be a good idea review this from a usability perspective. It feels like once you submit the entry, the view of your just-posted entry should have some kind of "thanks for submitting, here's the thing you posted, all live and everything!"

Currently after a successful form submission user gets sent to the entry page of the entry he/she just submitted. As a temporary solution / placeholder I included a line `Thanks for submitting! Here's the entry you just posted.` on the page. Message looks a little buried to me and I'm not sure if this message sounds user friendly enough. Suggestions? @kristinashu 

![fireshot capture 4 - mozilla network pulse - http___network-pulse-staging herokuapp com_entry_155](https://cloud.githubusercontent.com/assets/2896608/23229228/59cfd346-f8f4-11e6-90c9-2148abe413ba.png)

**Comment by kristinashu** [comment]
Cool! You could probably just say "Thanks for submitting!"
