### ISSUE TITLE
"Creator" fields on "add new entry" form

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#377]
Brought up by @Pomax in https://github.com/mozilla/network-pulse/pull/372#issuecomment-281495418

> Additional names don't end up below each other, so the "add more" button moves right to left to right to left the more creators you add. Is that intentional? (it feels like it makes the UI unpredictable)

> ![screenshot 168](https://cloud.githubusercontent.com/assets/177243/23186970/e36aebca-f83d-11e6-8138-b9f56b97590c.png)

(ignore the misalignment issue in the screencap, I will soon fix it in another PR)

@kristinashu for your reference, I *think* this is what @Pomax has in mind: [example on react-formbuilder library](https://pomax.github.io/react-formbuilder/example/). I like having the ability to both remove/add fields. What do you think @kristinashu ?

**Comment by Pomax** [comment]
Yeah, I meant that as a user I expect clicking an "add more" button to add another field without changing the relative positionings of any of the UI elements

**Comment by kristinashu** [comment]
I think it works as is and isn't a blocker for launch. Let's keep this open as an "enhancement"?

**Comment by mmmavis** [comment]
Ummmm we should decide soon if we wanna use hashtag or just tag first. Hashtag can only be one word while tags can be multi-word. This will affect how our search functionality works too as searching for `#webliteracy` and `web literacy` are not the same thing. UI/UX improvements can be post-launch enhancement but we should really decide what we like things to be stored in the database so that we don't run into problem after launch.

/cc @xmatthewx @alanmoo

**Comment by mmmavis** [comment]
oops omg ignored my previous comment hahaha that was referring to another ticket 😂

**Comment by xmatthewx** [comment]
This feels very usable to me. I'm going to close. Please comment if you disagree and see this as pretty important.
