### ISSUE TITLE
Discuss hashtags

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#383]
Currently, we gather tags from users in a tags field. Team has discussed merits of #hashtags vs comma separated phrases. #375 

Let's discuss: should we drop the tags input field in favor of hashtags in the description fields? Merging existing tags would take a bit of work, but shouldn't be a blocker. 

### hashtags in description

 - **Pro hashtags**: This is defacto approach on social platforms today. They're quick and simplify user's task.
 - **Con hashtags**: Requires a bit of engineering to parse, likely with risk of edge case bugs

### tags+commas in distinct field

 - **Pro comma separated phrases**: This might yield more tags, useful for this platform as an archive or knowledge base. They will likely encourage staff to consider how people will find things. Also allows for phrases that can be _hardtoread_ otherwise. 
 - **Con comma**: A bit more labor intensive for users. Probably increase inconsistent tagging (e.g "mozfest, 2016, iot" vs "mozfest 2016, iot").

**Comment by kristinashu** [comment]
Let's stick with tags, we can open a new ticket if we decide to change.
