### ISSUE TITLE
Improve the form-post-failing notice

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#385]
Right now the notice reads "Sorry! We're unable to submit entry to server at this time.", we might want to rephrase that to "Sorry! We are unable to submit this entry right now" and possibly with the added information that comes out of the API server about why there is a 403 (if there is any information of course)

**Comment by xmatthewx** [comment]
If things fail, can we display their content? Even in a rough format? Stinks to lose your writing.

**Comment by Pomax** [comment]
As is you get the notice next the form you're trying to submit so in that sense the information isn't lost, but it's not super helpful in figuring out how to fix your form so that posting will succeed (if you even can!)

**Comment by mmmavis** [comment]
@Pomax What kind of detail error message do we wanna show? What are the status codes that would be helpful for users to know?

**Comment by Pomax** [comment]
Many of the errors are actually concerns for use, more than the user, so the user typically should be informed that something went wrong and really we should be notified of that. I don't know what the best way to do that is.

Possible errors the user could run into while trying to post:

403: the user isn't *actually* logged in, which might happen if they somehow invalidate their session between logging in and submitting the form (say in a different tab). We could mitigate by prompting the user to log in again, but we'd need to make sure we track the path there: if the 403 is generated for a different reasing, then telling the user to log in over and over again is not useful.
409: some of the data is not being sent over to the API server in a form that the API server understands. This should never be possible, our form submission should already prevalidate and only send data in a payload that can be parsed.
404: this should even be possible, something is running on the API server that is *not* the API server. That should be a cause for concern on our side.
500: there is a serious problem with the API server that's causing it to generate internal errors. That should also be a cause for concern on our side.

I think the notice that "you can't submit right now" is the right conclusion that we should draw, but the messaging around it needs a tactical rewrite so the user doesn't feel frustrated by it.

**Comment by gideonthomas** [comment]
will reopen if it becomes an issue
