### ISSUE TITLE
network-pulse-staging app is not calling /nonce ... ?

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#386]
if I look at the network traffic, the app on network-pulse-staging at no point calls the `/nonce` route on the API server to ensure it has a csrf token and a nonce value for posting.... that would explain why we're getting a 403, @mavis do you know where to confirm that this isn't happening?

**Comment by mmmavis** [comment]
I'm not able to reproduce this. Is this still happening? What's the STR?

**Comment by Pomax** [comment]
weird http nonsense.. closing with the https-PR landing.
