### ISSUE TITLE
improve load time by restricting page_size for `entries` to 24

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#387]
Right now page_size is set to 996 which makes the request transfer the entire database of entries on every call. Let's cut this down to 24 instead, so it doesn't take a really long time to do a network fetch.

**Comment by xmatthewx** [comment]
This was discussed before with @alanmoo and @mmmavis. I believe there was a concern about slow loads on Load More. Or repeat searches queries. 

How big approximately is a blobby blob of json per 100 entries? What's a reasonable amount of kb to transfer?

**Comment by Pomax** [comment]
you don't really wan to transfer more than 1kb. I'm going to be pragmatic here and say "just load what you need to show the user what they're supposed to see". If the screen fits 24 items, load 24 items, at mot prefetch the next 24, and keep network activity lean.

**Comment by xmatthewx** [comment]
That sounds reasonable. 

Is there a way I can do a throttled test on my end by viewing /latest?page_size=24 manually? It seems to be fetching all still with that parameter. Site is slow on 3G, but Load More seems instant.

**Comment by Pomax** [comment]
yeah if you want to check the difference, try these two links:

- full: https://network-pulse-api-staging.herokuapp.com/entries/?format=json
- limited: https://network-pulse-api-staging.herokuapp.com/entries/?format=json&page_size=12&page=3

And then you can play with the "page size" value to see the difference

**Comment by mmmavis** [comment]
Fixed in https://github.com/mozilla/network-pulse/pull/410
