### ISSUE TITLE
First iteration on Share + Detail View 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#39]
It'll take a little time to develop good UX for the connections between project card, share button, detail view, and external links. 

Let's create a quick spec to so we can wrap this heartbeat or start the next with the sharing feature enabled and behaving "good enough".

 - add a Share button that reveals URL
 - change or remove trigger on detail view
 - clean up content in detail view

This might mean moving the "open" button to the detail view. Or, only displaying the detail view when viewed via link. 

Or – attempts at an easy fix might be too hard to justify. I hope not, but might be true.

**Comment by kristinashu** [comment]
I like what we talked about earlier:
- Remove detail view (since there is no valuable extra info to show)
- Instead, add a Share button (next to Open and Get Involved) which reveals a unique URL users can copy
- Someone who clicks on the copied URL will go to a lightbox page (like Mavis just added) but content would be the same content as in the thumbnail card but shown in a lightbox.

@mmmavis what do you think? Does that make sense? Is it easy to execute?

**Comment by mmmavis** [comment]
@kristinashu yea this works fine with me and should be simple to implement. I'm not sure if the Clipboard API [works across all major browsers though](http://caniuse.com/#feat=clipboard). So after users click on the "share" button we might need to display a text box for them to manually copy the url.

**Comment by kristinashu** [comment]
Great! Text box works for me.

**Comment by kristinashu** [comment]
This is related to https://github.com/mozilla/network-pulse/issues/18 which I will close.

Longer term design will eventually be done in https://github.com/mozilla/network-pulse/issues/32

**Comment by xmatthewx** [comment]
Excellent. It could be good to use a input with text pre-selected for easy copying. 

Here's a quick mockup for something adequate. @kristinashu feel free suggest changes.  

<img width="479" alt="screenshot 2016-07-21 14 13 27" src="https://cloud.githubusercontent.com/assets/53411/17033698/5911986e-4f4d-11e6-8911-82fe2d0b0f2b.png">

**Comment by kristinashu** [comment]
Pre-selected sounds good. 

Instead of overtop, could it show up below (close button wouldn't be necessary)?
<img width="458" alt="screen shot 2016-07-21 at 11 26 54 am" src="https://cloud.githubusercontent.com/assets/1068783/17034112/0f291d60-4f36-11e6-965b-7e0560997731.png">

**Comment by xmatthewx** [comment]
👍 even simpler

**Comment by mmmavis** [comment]
Share button has been added. The preselect trick doesn't work on mobile... I'll file a separate ticket to follow up. Note that I didn't change anything for the detail view itself. Please free feel to create tickets for detail view adjustment 😉

**Comment by kristinashu** [comment]
Cool! I like the share button and link. 

But when I copy and paste the link in I see this:
<img width="1239" alt="screen shot 2016-07-22 at 10 25 15 am" src="https://cloud.githubusercontent.com/assets/1068783/17065461/c53f6724-4ff6-11e6-8949-c5eda037c502.png">

**Comment by xmatthewx** [comment]
Bug filed #43
