### ISSUE TITLE
Add spacing after checkbox

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#391]
<img width="445" alt="screen shot 2017-02-23 at 2 17 24 pm" src="https://cloud.githubusercontent.com/assets/2896608/23281616/e40a5d2c-f9d2-11e6-9ee5-9dd077c4eb64.png">

**Comment by mmmavis** [comment]
@Pomax is it something we can tweak on the `react-formbuilder` side? Basically we need a way to assign Bootstrap class like `.form-control` **directly** to `input` and `label` in `checkboxGroup` and `optionGroup`. We can do this already to other component type so I hope we can do this too on `checkboxGroup` and `optionGroup`. If this doesn't sound like a good idea I can always write CSS rules for element of our choice to replicate stylings that come with Bootstrap classes.

**Comment by Pomax** [comment]
That makes no sense. We use less/sass, we can tack any class anywhere we like through things like
```
.react-formbuilder .checkbox-group {
  input {
    .bootstrap-class-we-need
  }
}
``
