### ISSUE TITLE
Missing date info

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#394]
Staging appears to missing date info on entries as seen in mockup here: https://github.com/mozilla/network-pulse/issues/161#issuecomment-266558692 and below.

<img width="334" alt="screenshot 2016-12-12 16 25 10" src="https://cloud.githubusercontent.com/assets/53411/21117440/b061ee42-c087-11e6-8cab-f32379b18f7e.png">

<img width="522" alt="screenshot 2016-12-12 16 29 52" src="https://cloud.githubusercontent.com/assets/53411/21117550/3af4db82-c088-11e6-8d00-2c57cded42fd.png">

 - Ideally in detail view we would drop the line break and separate with a middot to avoid awkward line lengths when the creators wrap a little bit to the next line. See below.

**Comment by xmatthewx** [comment]
cc @mmmavis

**Comment by mmmavis** [comment]
Might be a Pulse API issue - I don't see any "timestamp" field being stored (at least I'm not seeing on the the Django dashboard). @Pomax @alanmoo ?

**Comment by alanmoo** [comment]
It's called `created`.

**Comment by mmmavis** [comment]
kk now I see it in /entries response. I will take care of this ticket.

**Comment by mmmavis** [comment]
@xmatthewx 

> Ideally in detail view we would drop the line break and separate with a middot to avoid awkward line lengths when the creators wrap a little bit to the next line. See below.

On detail view, since we can't predict how long the [creator] text is gonna be, there could be cases like 
<img width="546" alt="screen shot 2017-02-23 at 9 25 10 pm" src="https://cloud.githubusercontent.com/assets/2896608/23291641/ae382ca6-fa0e-11e6-8837-187bbbb6d10a.png">

I wonder if we should make it consistent so that [creator] and [date posted] each occupies a line, regardless of which view it is on (list view or detail view).

**Comment by alanmoo** [comment]
You can avoid the awkward line breaks by using the `.col-auto` class. [Example](http://codepen.io/alanmoo/pen/QpwWLL)

**Comment by mmmavis** [comment]
@alanmoo cool! Is there an easy way to make sure a middot is there when [creator][date posted] fit in one line?

**Comment by Pomax** [comment]
fitting content based on available space? @flukeout has opinions here and they're all "javascript" =P

**Comment by mmmavis** [comment]
Yea that's why I'd suggest that we stick with 
```
[creator]
[data posted]
```
(each starts a new line)
on every view.

Are you good with this? @xmatthewx

**Comment by alanmoo** [comment]
@mmmavis not off the top of my head. Without something like element queries being a thing, it seems like it would be significantly trickier if at all possible.

**Comment by xmatthewx** [comment]
Can't we just wrap the dot, add a class, use a whatever media-queries you have in place for screen size?

Or, don't worry about it. We have some bigger responsive wrinkles to address post-launch.

**Comment by alanmoo** [comment]
It's more dynamic than just screen size. I'd say nix the dot, and maybe just change the font style/weight/something between creators and date. Or go with the new line approach.

**Comment by mmmavis** [comment]
> Can't we just wrap the dot, add a class, use a whatever media-queries you have in place for screen size?

Still, we have no way (without JS) to tell how long each string is gonna be. And [creators] vary entry by entry. The middot treatment can fix the awkward line break issue for some entries, but def not all of them.

**Comment by Pomax** [comment]
wrap each creator name in a `white-space: nowrap` span, and insert `<wbr>` elements between each name.

**Comment by mmmavis** [comment]
I don't want design decision to block us from fixing "missing date info" issue. Here's [the PR](https://github.com/mozilla/network-pulse/pull/400) to add that date info back

list view, clip with ellipsis
<img width="369" alt="screen shot 2017-02-24 at 4 25 04 pm" src="https://cloud.githubusercontent.com/assets/2896608/23326058/1b6280e2-faaf-11e6-97c2-518d73e16810.png">

detail view, show full text
<img width="553" alt="screen shot 2017-02-24 at 4 24 41 pm" src="https://cloud.githubusercontent.com/assets/2896608/23326056/18e8c2a4-faaf-11e6-99b9-90c3af9219ef.png">

We can create a new ticket to discuss how we want [creator] and [date posted] meta to show on the page.
