### ISSUE TITLE
Export to CSV/JSON feature

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#40]
This just came up my mind during the stand. Once we have the tags feature in place, we should have page that lists out all projects/artifects fall under the same tag. And we should probably have an export feature for people to easily download the metadata of those projects/artifects.

Any thoughts?

**Comment by xmatthewx** [comment]
For now, find by search will probably serve us well enough. In the future, an export or api by category could be useful, but we aren't near that yet.  We're likely to have fixed categories (5 issues, hubs). Tags are likely be to be defined by user (or staff during triage).

**Comment by mmmavis** [comment]
obsolete. closing. 😉
