### ISSUE TITLE
Project title on detail view shouldn't be hyperlinked

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#416]

**Comment by mmmavis** [comment]
@kristinashu do we want the plain text project title on detail view to stay as pink (`#e14164`) or make it the same color as body text grey (`#2f2f31`)?

<img width="530" alt="screen shot 2017-03-23 at 3 42 18 pm" src="https://cloud.githubusercontent.com/assets/2896608/24273405/6c324346-0fdf-11e7-92da-7de7162a5c96.png">

<img width="529" alt="screen shot 2017-03-23 at 3 41 49 pm" src="https://cloud.githubusercontent.com/assets/2896608/24273402/68223450-0fdf-11e7-8887-9496c7aeb17c.png">

**Comment by kristinashu** [comment]
Let's go with black. It will help differentiate from the other screen and it will fit in well with the our new branding (with uses a lot more black).
