### ISSUE TITLE
Hover effect for heart icon (for favorating/bookmarking)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#417]
The heart icon in a project card doesn't have any hover effect. See example below: 
<img width="374" alt="screen shot 2017-03-14 at 10 28 23 pm" src="https://cloud.githubusercontent.com/assets/2896608/23934892/935f87b6-0905-11e7-901f-c64b9e913c4c.png">

@kristinashu can you suggest how the heart icon should look on hover?

- a hollow heart on hover (for project that is currently not favourited/bookmarked)
- a filled heart on hover  (for project that is currently favourited/bookmarked)

**Comment by Sudip7** [comment]
@mmmavis : little more description would help to understand the issue!!!

**Comment by mmmavis** [comment]
@Sudip7 kk I just updated the ticket description above.

**Comment by kristinashu** [comment]
How about the heart turns into a filled in grey heart (same grey as the outline text for hollow hearts). This would work for both states (hollow + filled in). Does that make sense?

**Comment by mmmavis** [comment]
@kristinashu 

I'm thinking maybe the 2 hearts (hollow + filled) should not use the same hover style. If I hover on a hollow heart, I see it turn filled grey, I click on it without moving my cursor away after, I still see a grey filled heart since that's the hover state for red filled heart as well. This could be confusing to users since it look as if nothing has happened. Same thing would occur if we started the flow from a filled red heart in the beginning.

Maybe having some sort of animation would help? ummm...

**Comment by kristinashu** [comment]
To be honest I don't think we even need a hover state for the heart (Twitter and others don't have one). A little animation would be nice tho, I like the one we used in the schedule app.

**Comment by mmmavis** [comment]
Yea I'm fine with not having hover effect. Someone mentioned about this issue initially  so I created this ticket.

[MozFest schedule app](https://app.mozillafestival.org/#_show-friday) doesn't have hover effect for the heart. The animation happens when you click on the heart. Is that what we wanna use here (but for on hover)?

**Comment by kristinashu** [comment]
Yeah, animate on the click (would be too distracting to have it on every hover).

**Comment by mmmavis** [comment]
kk I'll create a new ticket for it. Closing this one now.
