### ISSUE TITLE
Preselect share link on mobile devices

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#42]
On desktop, direct link to a project is preselected once users click on the share button (shown in screencap below). Implementation wise this trick doesn't work on mobile. I'll look up to see how this can be done for mobile devices.

<img width="571" alt="screen shot 2016-07-22 at 10 25 16 am" src="https://cloud.githubusercontent.com/assets/2896608/17065438/a76e28ac-4ff6-11e6-88ea-7818d12eff36.png">

**Comment by xmatthewx** [comment]
Nice to have, but not critical

**Comment by kristinashu** [comment]
No longer relevant now that we have the detail view.
