### ISSUE TITLE
Input guidelines

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#422]
Let's revise the helper text on the input form based on wisdom from @KevZawacki in these [WIP edits](https://docs.google.com/document/d/1Rp08kMV4qZ_xUadW9SftsGGeZc9t3ZASTCxGrSeR2fE/edit). 

We can wait for Kevin to say things are good to go.

**Comment by xmatthewx** [comment]
cc @hannahkane

**Comment by xmatthewx** [comment]
Do we want a word or two to deter entries that are written as ads or recaps, rather than more [wikipedia-styled](https://en.wikipedia.org/wiki/Wikipedia:Contributing_to_Wikipedia#Wikipedia.27s_purpose) references? Or do we need to address that with staff directly?

**Comment by KevZawacki** [comment]
@xmatthewx 

To prevent ads/recaps, I've added this language to our document: "Remember: This is a brief summary, not an advertisement or changelog."

Re: character limits, what are your thoughts on:

title = max_length=50
description = max_length=500
get_involved = max_length=300

(We can grandfather in older entries.)

**Comment by hannahkane** [comment]
@xmatthewx - can you explain why an event recap wouldn't be appropriate. Not sure I follow.

**Comment by xmatthewx** [comment]
> can you explain why an event recap wouldn't be appropriate. Not sure I follow.

The platform is for assets or resources. It's not a blog or twitter. If a recap is framed as: "lessons learned from xyz hackathon" then it's a best practice that could fit in well. But if it's a just a story of what someone did, it's not a resource for others. I don't think we need to prohibit things like that in a gray area, but I don't want people to start using this like twitter or to put their unstructured notes from a community call that aren't useful to others.

**Comment by xmatthewx** [comment]
@KevZawacki suggests (and i agree) the form could include a statement like "Submissions may be lightly edited by our Network Site curator for spelling, grammar and style consistency..."

We'll want that for featured items. I wonder if legal would suggest we reach out to individuals in the case to request permission.

**Comment by xmatthewx** [comment]
Thanks. Closing. Suggestions have been filed for implementation.
