### ISSUE TITLE
Rank/sort Featured Items

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#423]
Pulse enables an Admin to flag an entry as featured, to appear on the featured tab. We also pull this featured list into the Mozilla Network site. 

Going further, an admin should be able to specify the rank or order of featured items, so that we can highlight things that align with our editorial calendar, so the top three items on the network site match the topic of other news and features.

@gideonthomas implemented something like this for a different content type on the network site. Let's discuss what it would take to port it to here. cc @Pomax

**Comment by Pomax** [comment]
when you say "rank featured", are you thinking "within the set of featured items, there is a fluid ranking similar to a numerical score" or "within the set of featured items, some items have an additional should-be-on-top checkbox"?

**Comment by xmatthewx** [comment]
Adding @KevZawacki for input. 

Interesting: I actually think that an additional `this-should-be-on-top checkbox` would be more useful. That way, we don't ever need to un-feature a thing or worry about the rank of many dozens of things (which loses valuable info). Instead, we just need to manage the tippy-top shortlist items. My gut says that's an easier way to solve the job we need to do for the network site. Could also be useful for promoting a thing or two to the top of an issue view.

Sorry I posted this here instead of the api repo.

**Comment by xmatthewx** [comment]
@Pomax - how are featured entries currently ordered? Post date? Or, by date featured? Reverse or forward? If it's featured date, we could maybe hack that to set tippy-top in the interim.

**Comment by KevZawacki** [comment]
So whenever I newly click `this-should-be-on-top checkbox` on an item, it would jump to the first spot? And the previous `this-should-be-on-top checkbox` item would be pushed to the second spot? And so forth?

That works for me. But if we're planning to highlight a whole new crop of content at the start of each week, it seem like `within the set of featured items, there is a fluid ranking similar to a numerical score` would be most efficient, no?

**Comment by xmatthewx** [comment]
@KevZawacki – I think we should huddle up on this over vidyo if you have time. So we can tackle this case and related curation in Pulse itself.

Some thoughts below. @Pomax – feel free to mute this until we get a bit more clear. 

Idea 1: So from an Admin perspective, it sounds like we are proposing:
 - `Featured` – a true/false flag on many good things (maybe 10% of all entries). once true, likely remains true. 
 - `Curated/Highlighted` (better word?) – a flag and input on a few editorial things (maybe 9 at a given time). Highlights are ranked for display order. Likely removed after a period of time. (Note: Gideon has a drag-n-drop sort feature on Net site that could work for this)

I'd like to throw in a different perspective:

This is an Admin feature for Pulse items pulled _elsewhere_. We should maybe administer this _elsewhere_ by requesting specific entries by ID... unless it is also useful within Pulse. My gut says no. I think Pulse works best when it updates more often.

Lastly we're also considering a redesign of the Projects page on the Network site that might obviate this. (Did I use obviate properly? What a word!) The new approach would be to pick 3-4 issues/topics and show 2-3 projects within each ... giving much context to visitors.

**Comment by Pomax** [comment]
That is the correct use of obviate =)

Right now `featured` is a simply a flag toggle ([true/false in the code](https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/entries/models.py#L47)), so a "put this up top and push everything else down one spot" can be done, it does run into that question of "how many is too many" so on a screen with only 9 or 12 results, more than three "sticky-featured" entries might be too many already because it would make a large part of the page look the same.

But I think matthew's onto something: "stickies" are more something that you want to control per consuming application, so maybe putting that in the network pulse api itself is the wrong place, or the network pulse api needs to be made aware of all the clients it can have and how they want to handle "stickies" on a per client basis, but that'll be substantially more work.

**Comment by xmatthewx** [comment]
I don't think is relevant anymore as relationship with network site has evolved.
