### ISSUE TITLE
Add image upload to Input form

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#424]
This should be tip top priority, before other QA. 

@Pomax has a PR open to enable image upload in the API. https://github.com/mozilla/network-pulse-api/issues/99

We need to hook this up to the existing input form. We will drop the current URL field from the form.  

I'm unsure if this is work for @mmmavis @Pomax or @alanmoo.

**Comment by Pomax** [comment]
landing the functionality into the database is work for me and @alanmoo, updating the client form is a job for @mmmavis and probably me (I suspect the form builder might not have an "image" field, which we'll need to add if we want to use it in our form definition for the client)

**Comment by mmmavis** [comment]
@Pomax yes could you please help add an "image" field to the already-awesome react-formbuilder? 😄 One question regarding the Django dashboard  - am I supposed to see a "thumbnail" field there? I can't remember where exactly I saw it but I remember you mentioned something about having both "thumbnail" and "thumbnail url" in the backend.

**Comment by Pomax** [comment]
you will now only see a "thumbnail" field in the admin view, with an image preview if there is an image to preview

**Comment by Pomax** [comment]
![image](https://cloud.githubusercontent.com/assets/177243/24061218/c2f742f6-0b13-11e7-8c67-3d3ba6df41b2.png)

**Comment by mmmavis** [comment]
blocked by https://github.com/mozilla/network-pulse-api/issues/103
