### ISSUE TITLE
"Load more" button should not stay in focus/active state

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#427]
originally mentioned in https://github.com/mozilla/network-pulse/issues/419#issue-212218068 by @xmatthewx 

> Action: Tap "load more" in list view. Scroll down to bottom. 
Result: Button retains focus/active state from before.

**Comment by mmmavis** [comment]
This should be fixed on staging now: https://network-pulse-staging.herokuapp.com/latest

@xmatthewx can you verify?

**Comment by xmatthewx** [comment]
Still seems to happen on Android, both Chrome and FF beta. Do you have an Android in the office?

**Comment by mmmavis** [comment]
Ah, right. Might be a mobile thing. It works on desktop Chrome/FF/Safari but not iOS ones (and Android ones I guess)

**Comment by mmmavis** [comment]
@alanmoo @gvn I searched online a bit and seems like this is the default behaviour for mobile (that the button stayed "focused/active" after touched. Any suggestion on how to reset them back to the default state? I hope we can do it without involving JS.

**Comment by alanmoo** [comment]
Nothing non-JS jumps to mind for me, unfortunately. Can't you access the button from the event handler and defocus it at the end of that function?

**Comment by mmmavis** [comment]
@alanmoo 

> Nothing non-JS jumps to mind for me, unfortunately. Can't you access the button from the event handler and defocus it at the end of that function?

yea probably but does it mean that we'll have to do this for all buttons we currently on the site (and remember to do so for any future buttons we are gonna add)... 👀

**Comment by alanmoo** [comment]
Then that sounds like a prime candidate for a React component so that we can keep it DRY, no?

**Comment by mmmavis** [comment]
Yup we can definitely create a React component for this. I'm just thinking... if what we are seeing on mobile (which is the default behavior for any <button> on any site on mobile) doesn't introduce a huge UX concern, should we bother "fixing" it? We can easily create a React component to force `.blur()` but that sounds a bit like a hacky-patch to me since it's more like an enhancement for mobile **only**. Another concern I have is this kind of custom components don't often get used afterwards. It's not intuitive enough for devs to remember to use it compared to just using `<button>`. New devs on this project probably won't even notice we have this custom component. In a few months (or even weeks) time I can see myself forgetting about this custom button component. I've seen this kind of inconsistency happened in other projects so I'm a bit hesitated now. 😦

**Comment by xmatthewx** [comment]
This isn't a critical, stop-everything-else, kind of bug. And, it definitely is not an enhancement. With it, Pulse feels broken, not like a polished app ready for primetime. 

We don't need to put this before other work, but we also can't not do it. I don't have an opinion on how, but this must be a fairly common problem for single page apps.

**Comment by mmmavis** [comment]
This is not a common single page app "problem". Touchscreen devices mimic "hover" by making it "sticky" and this is the default behavior for "hoverable" HTML elements. So yea, from UX/UI point of view this can be seen as a bug but dev/tech wise it's not. 😉 

Bootstrap has some workaround suggestion: https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#sticky-hoverfocus-on-mobile Should we enable `$enable-hover-media-query` on `mofo-bootstrap`? @gvn @alanmoo

**Comment by gvn** [comment]
Yes, let's do that.

**Comment by mmmavis** [comment]
k will file ticket & PR on mofo-bootstrap.

**Comment by mmmavis** [comment]
Seems like `$enable-hover-media-query` isn't ready for use yet. We'll have to find another way to solve the sticky hover issue before Bootstrap enable the `$enable-hover-media-query` flag again.
