### ISSUE TITLE
Remember list scroll position 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#428]
originally mentioned in https://github.com/mozilla/network-pulse/issues/419#issue-212218068 by @xmatthewx 

> Action: Go back from an entry to a list view. 
Result: list reloads. Expected: show me where I was before

expected behaviour as described in https://github.com/mozilla/network-pulse/pull/445#issuecomment-291942575

> We only need and want to remember scroll position for one specific scenario, when a user goes from List to Detail and back to List. It would likely feel weird in other scenarios. 
> * `Remember position` – Scenario: User opens a Detail view from somewhere in List view, then User triggers browser back from Detail to List view. >>List view displays with prior scroll position. 
 > * `Everything else` – Scenario: User taps Tab (regardless of current and prior position) >> Tab loads from the top

**Comment by xmatthewx** [comment]
works beautifully!! thanks.
