### ISSUE TITLE
iOS Safari: detail view not showing project card

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#430]
Not sure if it's just me - 

On iOS Safari, detail view is not showing the project card. For example, this is what it looks like when visiting https://www.mozillapulse.org/entry/153

<img src="https://cloud.githubusercontent.com/assets/2896608/23935698/878b9056-090a-11e7-9212-35983293196c.PNG" width=480>

(Note that it seems fine on iOS Chrome and Firefox)

**Comment by kristinashu** [comment]
@mmmavis seems fine to me? The post shows up.

**Comment by taisdesouzalessa** [comment]
@mmmavis it works for me too. Here is the screenshot:
![img_5162](https://cloud.githubusercontent.com/assets/22157921/24012817/966961ce-0a3c-11e7-818b-97b8f8876a2c.PNG)

**Comment by hannahkane** [comment]
I can't reproduce either.

**Comment by mmmavis** [comment]
@Pomax @alanmoo 

Ah it's something to do with my iOS Safari's privacy and security settings

Originally I had **Do Not Track turned on** and **Block Cookies set to "Allow from Websites I Visit"**

<img width="1001" alt="screen shot 2017-03-16 at 12 12 40 pm" src="https://cloud.githubusercontent.com/assets/2896608/24015166/d8e787b2-0a44-11e7-89ec-6351e23d5e49.png">

After turning DNT off I got

<img width="1131" alt="screen shot 2017-03-16 at 12 26 46 pm" src="https://cloud.githubusercontent.com/assets/2896608/24015184/e70087c2-0a44-11e7-8fe8-3fd540a20a4a.png">

And after I set my "Block cookies" setting to "Always Allow" I was finally able to see project card showing up on detail view.

So here's the question - why is it only the detail view (uses https://api.mozillapulse.org/entries/project_ID/ to fetch data ) that's affected by my browser settings? 😦  I was able to view other pages (list view ones) on Pulse just fine.

**Comment by mmmavis** [comment]
@taisdesouzalessa was able to reproduce the bug just now  (with "Do Not Track" turned on and "Block Cookies" set to "Allow from Websites I Visit")

**Comment by Pomax** [comment]
Another question is *why do we need cookies at all*, that should not affect data responses... Is there a way to see the full raw request headers for "with no cookies" turned on and with it turned off? Maybe we can see a difference.

**Comment by mmmavis** [comment]
I tested it earlier today and it didn't seem to relate to Safari's privacy and security settings anymore O_o However, I found out there were 2 XHRs being sent on detail view (filed #436) and the fix to it (PR #437) seems to resolve this weird iOS Safari issue too. I think we are safe to close this ticket now. Phew!
