### ISSUE TITLE
Tell users about image size in form

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#433]
The form should tell users that  "Images should be 1200 x 630px."

cc @kristinashu

**Comment by xmatthewx** [comment]
@kristinashu – I wonder if we should add a help link that connects with some quick pointers. Maybe we recommend an easy online editor for cropping and exporting photos. We could put that help info in a wikipage in this repo.

**Comment by mmmavis** [comment]
for ref, this is what the form looks like

![fireshot capture 10 - mozilla network pulse - http___localhost_3000_add](https://cloud.githubusercontent.com/assets/2896608/24166241/ddb48968-0e2f-11e7-924f-5740473a42f5.png)

**Comment by hannahkane** [comment]
Suggested copy: "Images look best at 1200 X 630px"

**Comment by xmatthewx** [comment]
While we make this change, can I squeeze in another?? I'd like something other than "code" for the support field placeholder text.

**Comment by xmatthewx** [comment]
How about: "Help us test the prototype and then plan some local events!"

**Comment by xmatthewx** [comment]
We can also change button label to "Select Image" ... dropping the click here....

**Comment by xmatthewx** [comment]
To summarize: 

 - [ ] Image field: Project Image (look best at 1200 x 630px)
 - [ ] Image button: Select Image
 - [ ] Support placeholder: Help us test the prototype and then plan some local events

**Comment by mmmavis** [comment]
@xmatthewx 

>  - [ ] Support placeholder: Help us test the prototype and then plan some local events

This is the "get_involved" field. I'm not the best person to suggest copy. But can we tweak the line a bit? This placeholder sounds a bit unclear to me as a user. Should we change the line to something like `Help us test the prototype, plan some local events, contribute to the codebase, ...`?

**Comment by xmatthewx** [comment]
That works
