### ISSUE TITLE
Gather requirements for moderation

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#438]
Pulse currently allows users with Mozilla LDAP to login and add new entries in Pulse. In the near future, we will want to enable a small circle of network members to add entries. This will require an MVP moderation feature. 

### Two use cases
 - A fellow: highly trusted individual with direct relationship to staff. Moderation is useful for program manager mentoring new fellows. 
 - Global sprint participant: these individuals may be newer to the network. They relationship and activity centers around a proposed project. Moderation will be important for quality control and mentorship. 

### MVP plan
 - edit: ~~a true/false checkbox in django admin for staff to approve entries by non-staff~~
 - edit: an entry moderation flag [waiting, approved, denied] 
 - should default to ~~true~~ approved for staff entries
 - non-staff should have a message on frontend making process clear
 - if staff curators encourage a specific tag for their program, would be nice if admins could browse entries by tag (see https://github.com/mozilla/network-pulse-api/issues/90)

### Nice to have
 - a frontend view of pending entries for admins. so they can see and read in full color. 
   - edit: should not block landing basic moderation functionality

@acabunoc @auremoser – what do you think about this?

**Comment by acabunoc** [comment]
👍

**Comment by auremoser** [comment]
> should default to true for staff entries

Would be great to define the process specifically mentioned in the MVP plan. Might seem tacit, but whoever is assigned this issue will probably want it spelled out.

* Community entries will be flagged to the community lead for Network Pulse (whoever is the product owner, for triage to "specialized" owners (for the Global Sprint) that can be myself or @acabunoc 
* Entries will be under review thereafter, set for approval a week after submission
* If changes are required, PO or specialized owner will reach out with changes requested
* Project will be matched with an appropriate thumbnail and final project once posted will be send to the submitter (not sure this one is necessary but it's nice to have)

We could also just delete the 2nd and 3rd bullets, and just include a disclaimer with the submit button that says "Mozilla reserves the right to make minor typo and submission edits to ensure quality and alignment with other network pulse projects. Our community is thriving, and it's important that we curate a great user experience for all Pulse visitors. Any changes the submitter deems disruptive to submission content, we can negotiate." or something more concise. 

Thank you @xmatthewx !

**Comment by xmatthewx** [comment]
@Pomax @simonwex – let's poke at this async and then find time to discuss. 

Note: I have reviewed this with Abigail (legal) already and have messages for input form.

**Comment by Pomax** [comment]
It sounds a little like the app would need a new tab, "pending", visible only to users with the `is staff` or even `is admin` flag set, where they can do entry administration (rather than using the django admin backend).

**Comment by xmatthewx** [comment]
A frontend view for moderation would be good longterm, but Django is preferred for a first build to simplify. If Django isn't complicated for mvp, let's pursue that so we don't do add design and extend the api. 

We will use tags like `global sprint` or `club/region name` to enable community leads to find "their" items to moderate. We don't have the design/build capacity right now to prep a way to flag people, assign or own things.

**Comment by Pomax** [comment]
I'm actually recommending a new panel in the client because it's by fair easier to rapid prototype it client-side compared to adding in all the features in django. That is in part my familiarity with JS vs. Python, so perhaps @gideonthomas has opinions here, too.

**Comment by gideonthomas** [comment]
Hmm I think it depends on how much we want to customize the workflow. If we can get away with a sort of barebones approval process, can't we just add a field ("status") to all the models that you can set a default for in the admin view based on the role of the person logged in and make that field non-editable for non-staff? Then, staff can filter the list view by "pending" entries and just change the status field accordingly? I don't think it'll be too hard to do and will probably not require any design work, just workflow documentation for staff.

**Comment by xmatthewx** [comment]
It would require a lot of design to create a client side panel. 

examples: the queue ui with status indicator. change of status ui (from list or detail view?). after changing status, what's ux... redirect to queue with confirmation messages and link to live item? accidentally declined? how do i recover? declined by someone else? who? and can i change that? 

so if django is fairly easy, even if clunky, it's probably the safer approach at this stage.

**Comment by xmatthewx** [comment]
Closing. Track work in #524
