### ISSUE TITLE
More friendly form errors (not visible from below)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#441]
While posting a new entry today, Submit didn't work and it wasn't clear why. 

As you'll see in the screenshot below, the button is enabled, but a click yields no action. I assumed there was a bug. I scrolled up to take a screenshot, and only then noticed the Error message on one of the fields. 

To make this more friendly, we should do something. Maybe scroll up to error on submit attempt. Maybe show an error by button that has a generic message to correct an error up above. 

<img width="1116" alt="screen shot 2017-03-22 at 11 52 57 am" src="https://cloud.githubusercontent.com/assets/53411/24207159/95c35b4e-0ef6-11e7-864b-49c578961faf.png">

**Comment by mmmavis** [comment]
@xmatthewx Did you fill out the required fields(title and url)? There could be inline error messages that you have missed. But yea I agree we can have a more friendly UX here.

**Comment by xmatthewx** [comment]
Yep. It's not a form bug. I had too many characters on a field up above. I found it because I knew that might be the case. Many users could give up. 

I recommend that we keep Submit gray and disabled when errors are present. Add helper text next to it. Something like so...

<img width="562" alt="screen shot 2017-03-24 at 12 43 50 pm" src="https://cloud.githubusercontent.com/assets/53411/24304413/9e3bde78-108f-11e7-9719-8b46ee4e3259.png">

**Comment by kristinashu** [comment]
Can we do inline validation for required fields?

**Comment by kristinashu** [comment]
Opened a ticket for the title word count error https://github.com/mozilla/network-pulse/issues/493

**Comment by xmatthewx** [comment]
Another user impacted by this. We need to fix this. At least adding at a simple message near button telling people to make corrections above. 

cc @alanmoo

**Comment by alanmoo** [comment]
I've filed the above PR as a quick low-hanging fruit fix. The error message appears, but I didn't change any behavior of the button, as that would have required deeper investigation of the event propagation/validation checking.

**Comment by mmmavis** [comment]
Alan's fix is on production now: https://www.mozillapulse.org/add

**Comment by xmatthewx** [comment]
good enough!
