### ISSUE TITLE
deprecate `thumbnail_url`

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#442]
Both staging and production network-pulse-api databases have been uplifted to use the new S3 based image hosting for thumbnails, using the `thumbnail` field instead of the `thumbnail_url` field.

We should remove `thumbnail_url` from the client code, since `thumbnail` does the same thing now and new entries won't receive data for `thumbnail_url` anymore. Once that has been done, we can drop the `thumbnail_url` column from the database schema entirely on the network-pulse-api side.

**Comment by mmmavis** [comment]
Seems like a good intro bug - `help wanted` label applied.

**Comment by Pomax** [comment]
The work involved here is cleaning up the project-card.jsx file, to remove mention of `thumbnailUrl` in the two places it's still listed.

**Comment by Sudip7** [comment]
Thanks, @Pomax, that would suffice to complete the ticket.

**Comment by Sudip7** [comment]
@mmmavis, @Pomax already raised a pull request. Could u guys please verify and approve/comment for any modifications​???

**Comment by Pomax** [comment]
hi @Sudip7 mavis commented on your PR 7 days ago asking for some fixes before we can land it, did you see her request?
