### ISSUE TITLE
Optimize ordering of creators

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#443]
Currently, supporting orgs like Mozilla as the first creator, before the people who drive the projects. Tracking this in the api repo: https://github.com/mozilla/network-pulse-api/issues/109

**Comment by xmatthewx** [comment]
@Pomax – we discussed this issue before. See link in original comment. Do you think this is feasible this heartbeat? Or should we bump it?

**Comment by Pomax** [comment]
The PR for this is over on https://github.com/mozilla/network-pulse-api/pull/135

**Comment by mmmavis** [comment]
The PR @Pomax linked was merged on Jun 23. @xmatthewx @Pomax Is there anything left to do for this ticket?

**Comment by xmatthewx** [comment]
I believe those PRs were closed, not merged. I pretty sure it's still work to be done.

**Comment by mmmavis** [comment]
@xmatthewx oh yea you are right!
