### ISSUE TITLE
Add a route for tags

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#444]
The API can serve up entries by Tag. As far as I can tell, we don't have a route for that right now. Let's add that. 

It's useful for program staff to have links to their stuff /tags/mozfest or /tags/global-sprint, even though we don't (yet) surface those tags in the cards.

**Comment by xmatthewx** [comment]
this isn't urgent, but curious: is it a lot or a little bit of work? @alanmoo @mmmavis

the question is just about routes. no changes to cards or navigation. just the ability to hit a URL like mozillapulse.org/tags/foo and load a list of projects with that tag

**Comment by mmmavis** [comment]
Pulse API already has the `tags` meta. I think it will take me an hour to enable tags pages on Pulse front end.

**Comment by mmmavis** [comment]
I'll try to get a PR in today/tomorrow.

**Comment by mmmavis** [comment]
@xmatthewx what do we wanna show on `/tags` page?

**Comment by mmmavis** [comment]
As a quick solution, I'm thinking to add this `Tag: tag name` header to `/tag/tagname` page. Let me know if it looks okay or requires any tweaks.

<img width="1168" alt="screen shot 2017-04-10 at 1 54 06 pm" src="https://cloud.githubusercontent.com/assets/2896608/24882243/3bc7268a-1df5-11e7-8fb4-e2c770a91a43.png">

**Comment by xmatthewx** [comment]
looks great. thanks!

**Comment by mmmavis** [comment]
@xmatthewx what do we wanna show on `/tags` page? Any suggestion?

**Comment by xmatthewx** [comment]
For now – Can we redirect to `Latest` view?? 

If that's easy, let's do it!! Stop reading this comment. If that's difficult, ... we could display a simple list of tags. There are currently 400 tags, so this will require a bit of design. Question: What does the api return? How are they sorted? Recently created? Recently used? Most used? Alphabetical?

**Comment by mmmavis** [comment]
cool, let's just redirect /tags/ to /latest for now!

**Comment by alanmoo** [comment]
For the record, https://api.mozillapulse.org/tags/.

I feel like we should get an autocomplete field working for tags sooner rather than later so that doesn't become an infinitely long list.

**Comment by xmatthewx** [comment]
whippeee!

autocomplete filed: https://github.com/mozilla/network-pulse/issues/482
