### ISSUE TITLE
Style and add content to shared detail view

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#45]
Follow up from https://github.com/mozilla/network-pulse/issues/39

When someone ~~clicks on the~~ _follows a_ shared URL the card/thumbnail should show in lightbox.

**Comment by xmatthewx** [comment]
@mmmavis – what's the status of this? Just waiting for PR review? Let's nudge it along.

**Comment by mmmavis** [comment]
Yea PRs are up. They are just waiting for review.
