### ISSUE TITLE
Different message on Favs tab

### ISSUE THREAD

**Issue by Sudip7** [mozilla/network-pulse#454]
Hi team,

I am not sure whether it's really a issue or not but I have noticed this more than one time during development. I also don't know precisely how to mock/reproduce this issue. I tried few way but none is working. For your reference adding a screen shot.

The piece of code this message belongs to present in bookmarks.jsx. But there was no error in the terminal , I forgot to test browser terminal though. 

`getFailurePrompt() {
    return (<p>Only Mozilla staff can login now as we test this new platform. Meanwhile, your favorited projects can still be remembered on this device.</p>);
  }`

Please look into it. 

![favfirsttime](https://cloud.githubusercontent.com/assets/6715793/24588473/b88566f6-177d-11e7-80c1-76ad1f016340.jpeg)

@mmmavis @Pomax  any ideas!!!

**Comment by mmmavis** [comment]
@Sudip7 you mentioned you have been seeing different messages when visiting the Favs tab. The Screencap counts as one, what about other messages you have seen? Do you remember what they were?

**Comment by mmmavis** [comment]
Messages on that Favs tab varies when your login state changes. There are 3 cases:

## Before a user attempts to log in

<img width="1126" alt="screen shot 2017-04-03 at 1 37 22 pm" src="https://cloud.githubusercontent.com/assets/2896608/24630772/c77d4e76-1872-11e7-8fa3-e390c7417b06.png">

## User has successfully logged in (currently only Mozilla Staff can log in)
<img width="1432" alt="screen shot 2017-04-03 at 1 39 22 pm" src="https://cloud.githubusercontent.com/assets/2896608/24630831/fadcd5e8-1872-11e7-9eba-ea994e40d1cc.png">

## User is not allowed to log in (when non Mozilla Staff tries to log in)
As seen in your screencap

**Comment by Sudip7** [comment]
@mmmavis: the other screen is the regular one, that contains the sign in link. I believe this is the default behaviour. Btw how u distinguish Mozilla and non-mozilla users???

I found this particular screen few times so thought to enquire about it.

**Comment by xmatthewx** [comment]
I believe this message should only appear on the Favs screen. Login is currently limited to staff, based on the domain of the email address user submits to login.

Is there a bug? Or are you just asking about this behavior? We plan to gradually open this up to more users after we have a chance to test and build a bit more.

**Comment by mmmavis** [comment]
@Sudip7 @xmatthewx now that we allow anyone with Google account to log in, is this still an issue? If not let's close this ticket ✨

**Comment by xmatthewx** [comment]
Yep! Closing.
