### ISSUE TITLE
"please sign in" icon is not getting styled

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#456]
when prompted to sign in, this is the view:

![screenshot 205](https://cloud.githubusercontent.com/assets/177243/24664277/1a4ae04a-190f-11e7-90ca-027103ad1792.png)

The font required by the SVG icon is not getting used - we probably just want to use the actual outline in the SVG file itself, not rely on a webfont for this.

**Comment by mmmavis** [comment]
@Pomax I just removed font-awesome from my local system and was able to reproduce this issue. Nice catch!

@kristinashu can you update the .svg file? Looking at the source code it seems like the svg relies on font-awesome font. If user's system doesn't have font-awesome font installed the icon won't load.

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="18px" height="20px" viewBox="0 0 18 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 41.2 (35397) - http://www.bohemiancoding.com/sketch -->
    <title></title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Pulse" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" font-size="22" font-family="FontAwesome" font-weight="normal">
        <g id="Sign-in-failed" transform="translate(-152.000000, -157.000000)" fill="#E14164">
            <text id="">
                <tspan x="152.357143" y="175"></tspan>
            </text>
        </g>
    </g>
</svg>
```

**Comment by mmmavis** [comment]
We can also just use font-awesome icon directly (like [this](http://fontawesome.io/icon/user/)) instead of loading the svg.

**Comment by Pomax** [comment]
either is fine - if we already load fontawesome then using the icon directly makes sense. If we don't, then putting the icon outline in the SVG will be much smaller than relying on  a full fontawesome

**Comment by mmmavis** [comment]
cool let's go with using font-awesome directly then.
