### ISSUE TITLE
update logo for homescreens

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#461]
transparent logo doesn't work on all backgrounds. needs an outline or a circle/rounded rectangle around.

**Comment by mmmavis** [comment]
Hey @xmatthewx are you referring to the icon that shows up after you "save to homescreen" on mobile?

Here are the files that are being used: https://github.com/mozilla/network-pulse/tree/master/assets/favicons I just realize there are some inconsistancy there - one icon has transparent background and others are on white.

**Comment by xmatthewx** [comment]
Yes. The logo that appears when saved to homescreen. Probably better on white. Does it have rounded corners? That'd be better than a square.

**Comment by mmmavis** [comment]
I don't have an Android device with me but I think homescreen icons get cropped/shown as square with rounded corners.

**Comment by mmmavis** [comment]
@Pomax can you correct me if my assumption was wrong? ^

**Comment by xmatthewx** [comment]
![screenshot_20170417-180329](https://cloud.githubusercontent.com/assets/53411/25106700/ee5cdfa8-2398-11e7-81f0-f01ee1179250.png)

**Comment by mmmavis** [comment]
I just realize I need some image editing help. @kristinashu can you help create an icon with Pulse icon on white rounded corner rectangle? This is the icon that will be used on Android devices when someone "save this site to homescreen".

**Comment by kristinashu** [comment]
Can you please try this?

![icon-fav-white-rounded 2x](https://cloud.githubusercontent.com/assets/1068783/26080555/f5eb661a-397b-11e7-8338-265b999ae117.png)

**Comment by mmmavis** [comment]
@xmatthewx @kristinashu  version ccc works good to me!

![screenshot_2017-05-15-15-50-20](https://cloud.githubusercontent.com/assets/2896608/26082726/3a99f9de-3986-11e7-9d1a-1e53f0b6334e.png)

**Comment by kristinashu** [comment]
Here's the updated size. I also made it so the red lines don't go all the way to the edge of the square.

![icon-fav-white-rounded 2x](https://cloud.githubusercontent.com/assets/1068783/26083678/08a91e5e-398c-11e7-9b8e-52994830c501.png)

**Comment by mmmavis** [comment]
![screenshot_2017-05-15-18-50-40](https://cloud.githubusercontent.com/assets/2896608/26086441/779f2a5c-399f-11e7-9740-c1252dc9c5c1.png)

**Comment by mmmavis** [comment]
@xmatthewx ping me when you get a chance to help test this. I'll ngrok my localhost!
