### ISSUE TITLE
manifest.json apparently fails to load

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#462]
It looks like our manifest is blocked as unsafe, at least in Chrome. Or am I mistaken? It worked previously and there haven't been any big [changes to the manifest](https://github.com/mozilla/network-pulse/blame/master/manifest.json). Maybe something happened when we went to our new domain? 

<img width="445" alt="screen shot 2017-04-05 at 2 53 44 pm" src="https://cloud.githubusercontent.com/assets/53411/24721967/eeefe150-1a0f-11e7-867f-a5931e35911c.png">

As a result, when a user saves Pulse to device home screen, then opens it, web app doesn't load the start url and it doesn't load fullscreen without browser chrome.

Any insight @cadecairos @Pomax @alanmoo @mmmavis ?

**Comment by cadecairos** [comment]
How do I test this?

**Comment by mmmavis** [comment]
could be something to do with our security header setting? https://github.com/mozilla/network-pulse/blob/master/js/security-headers.js

**Comment by xmatthewx** [comment]
Chrome reports 

> Refused to load manifest from 'https://www.mozillapulse.org/manifest.json' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'manifest-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by cadecairos** [comment]
@xmatthewx thanks, that error message helps a lot!

@mmmavis yea, it looks like we need to add:

```
manifestSrc: [
  `'self'`
]
```

to that configuration.

**Comment by flukeout** [comment]
@xmatthewx - Web Sherlock Award 👍 👍

**Comment by Pomax** [comment]
omg there is a `manifestSrc` too? @_@

**Comment by mmmavis** [comment]
✨
