### ISSUE TITLE
Enable users to edit their own entries

### ISSUE THREAD

**Issue by chadsansing** [mozilla/network-pulse#472]
For example, today I noticed that I mis-typed Nicky Case's name in the credit line of a Pulse entry I made (https://www.mozillapulse.org/entry/190). I should be able to go back and edit the entries I have made as a contributor to take care of minor issues like that without needing the dev team to do that for me.

**Comment by kristinashu** [comment]
Matthew, I'm going to remove the ```enhancement``` label. I think this is an important feature to have.

**Comment by xmatthewx** [comment]
@kristinashu – let's briefly discuss. I agree this is important. It's also oddly complicated. 

I see 3 reasons to edit an entry: 
 - correct a mistake
 - add additional info (add contributor, update the get involved/help info)
 - evolve an entry based on pivots in a project

I think the first two are useful, and currently a pain to have moderators execute on behalf of users. The third reason is debatably better as a new entry in the stream. Users could make that choice: keep your link and user's who fav'd it, or appear higher in search etc. I guess we don't need to worry about that too much.

All of this brings some risk: Someone could swap in totally inappropriate content. 
 1. Does an edited entry disappear and go back into moderation? 
 1. We could offer a "request an edit" form where the user makes the changes, entry remains live as-is, until a moderator approves changes to replace original. This won't be trivial to engineer.
 1.  We could offer a request an edit form that just files an issue with a request for manual changes by us. Nice for user, sucky for us, but better than current scenario.

Lastly, who sees the edit link? Just the person who submitted the item. Or, creators too? I guess both would be best and hopefully not too tricky to engineer.

**Comment by kristinashu** [comment]
Yes, more complicated than appears!

> I see 3 reasons to edit an entry: 
>  - correct a mistake

Correct a mistake is the biggest issue and I expect most users notice the mistake right after they post it. I can see how filling out the form and then seeing the actual post right after is when users notice this.

> I think the first two are useful, and currently a pain to have moderators execute on behalf of users. 

This is also a pain and poor user experience for the user. I personally would be much more nervous to post something knowing it can never be updated or deleted.

> All of this brings some risk: Someone could swap in totally inappropriate content. 

Seems like a long time away that we would need to worry about this kind of behavior.
>  1. Does an edited entry disappear and go back into moderation? 

Seems excessive. For someone to signup, go to the effort to add a good post, get it approved and to then go back and update it to something inappropriate would be very rare.
>  1. We could offer a "request an edit" form where the user makes the changes, entry remains live as-is, until a moderator approves changes to replace original. This won't be trivial to engineer.
>  1.  We could offer a request an edit form that just files an issue with a request for manual changes by us. Nice for user, sucky for us, but better than current scenario.

Sounds like a good solution for now.

> Lastly, who sees the edit link? Just the person who submitted the item. Or, creators too? I guess both would be best and hopefully not too tricky to engineer. 

I'd say only the creator can edit since it is there name is as the creator.

**Comment by xmatthewx** [comment]
> Correct a mistake is the biggest issue and I expect most users notice the mistake right after they post it.

True! We could maybe solve this by showing a preview with a final submit button. With back arrow back to the form.  

I'll respond more fully tomorrow.

**Comment by kristinashu** [comment]
Oooh I like that!

**Comment by xmatthewx** [comment]
Okay. Thanks for all the input. One question and summary:

 - [ ] Design an edit link
   -  Should we use the [corrections link](https://github.com/mozilla/network-pulse/issues/485) available to everyone, capture email and name to see if it is the orig author? But let others flag errors too?
 - [ ] Prep a google form for edit requests. Trigger new issues if easy.
 - [ ] Engineer the link.
 - [ ] File an issue to discuss Preview before Submit for new entries

**Comment by xmatthewx** [comment]
We have added a "corrections" link below each entry so users can contact us with new info. I've also filed a ticket to enable people to preview their thing before submitting. 

For now, we'll close this request to edit entries and see if these other two things do the trick.
