### ISSUE TITLE
Expand User accounts beyond LDAP

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#474]
Long-term, we will want a large set of network members to post to Pulse. Soon, we will want to start adding a few trusted users who don't have LDAP (manual whitelist or account creation). In between, we will want to align with Network site for user management. 

Let's discuss! @Pomax @simonwex @cadecairos @alanmoo 

Note:
 - this is for submission of entries only, not admin. 
 - this depends on moderation https://github.com/mozilla/network-pulse/issues/438

**Comment by alanmoo** [comment]
I believe the approve list for domains is hard-coded into the codebase. Does Django support some sort of invite system in conjunction with Google OAuth? Or do we just create local accounts for non-staff users to start? @xmatthewx am I correct in assuming that this will be low enough volume that some sort of manual process per user is acceptable?

**Comment by Pomax** [comment]
Right now it's a hardcoded post-final-auth check over on https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L210-L227

We can make that a utility function that does something more elaborate than https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L229-L243, such as making sure the permissions are managed based on mozilla address vs. whitelisted trusted user vs. generic google login without any special rights other than "submit into the queue that we review before clearing for public viewing"

**Comment by xmatthewx** [comment]
> @xmatthewx am I correct in assuming that this will be low enough volume that some sort of manual process per user is acceptable?

Yes. My theory is that manually adding a dozen people can reduce pressure on us to open the door for hundreds. Buy a little more time. 

If it is significant work to engineer an interim solution, then my idea is a bad idea, and we should focus on the longterm plan.

**Comment by Pomax** [comment]
whitelisting a small set of addresses should be relatively little work (we can do that out-of-admin, with an environment variable that set for the staging/prod servers). Although of course that is not a "sustainable" solution so if we need this to work asap, perfectly doable.

**Comment by Pomax** [comment]
The work involved here:

- migrate "network pulse API" into the network API to take advantage of its social auth and consolidate login, with permissions set based on groups rather than based on "each user, individually"
  - [ ] move pulse api app into network api repo (preserve routes)
  - [ ] change code to actually work
  - [ ] update tests to reflect the updated code
- [ ] update pulse client to use the new domain

**Comment by xmatthewx** [comment]
Tested on production. Works like a charm. @Pomax - do you want to file any follow up tickets related this, migration, updating tests??

Filed a ticket to update help text for users. #547
