### ISSUE TITLE
Migrate React Components to ES6 syntax

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#477]
`React.createClass` is being deprecated. Migrate React Components to ES6 syntax so we don't run into `react` upgrading problem in the future.

Relevant links:
- https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html
- https://toddmotto.com/react-create-class-versus-component/

**Comment by Sudip7** [comment]
@mmmavis  would like to offer some contribution. May not be the complex one but smaller portions of some files.

**Comment by mmmavis** [comment]
@Sudip7 cool, you can pick the ones you are comfortable tackling. Just make sure your PR references this ticket! 😃

**Comment by mmmavis** [comment]
Hey @kamos1 😃 Thanks for offering help. Feel free to pick any bits you'd like to help with ES6ing. In your PR please mention this issue number. One note is that we are currently working on a new feature on a feature branch. This feature branch will likely be merged to `master` (our primary branch on this repo) soon so do expect a ton of code changes in the next few weeks.

**Comment by kamos1** [comment]
Hey @mmmavis, as components are ES6'd should I be using proptypes? I've seen them used in other ES6'd components

**Comment by mmmavis** [comment]
THIS IS DONE!!! Thanks everyone who contributed! 🍰 ☕️ 🍵 🍺 🍫 :shallow_pan_of_food:
