### ISSUE TITLE
Survey program leads

### ISSUE THREAD

**Issue by acabunoc** [mozilla/network-pulse#48]
How can we integrate pulse into their workflow?

**Comment by xmatthewx** [comment]
Here are a few topics we might to dig into: 
 - Identify their existing practices to track network assets, big and small (probably helpful to probe by mention types of assets they might capture) 
 - Identify pain points. 
 - Get their reaction to value of shared space for tracking assets, benefit of networkification, capacity to scale. 

We should hit each of the hubs and bigger programs.

**Comment by acabunoc** [comment]
People to reach out to:

Hubs:
* Women & Web Literacy: Amira (Maker Party)
* IoT: Michelle
* Learning: Meghan
* Science: Steph
* Advocacy: Sara, OWF - Melissa


Hive - Robert/Sam/Hana
Gigabit - Lindsay? Katie?
Clubs - Julia
MozFest - Erika or Sarah

**Comment by xmatthewx** [comment]
@acabunoc – If you're able to see team's current tools/practices, it'd be useful to gather a list of metadata for assets. This is less important than your higher level conversation topics, but useful.

**Comment by xmatthewx** [comment]
I found it useful to end my interviews with the request: "Please post a project to Pulse in the next few days. Let us know how it went."

**Comment by acabunoc** [comment]
Summary (still filling this out)
https://docs.google.com/document/d/1IUbYB56ZlwCand-R1TSdMNixatOPw207cQX1D1EBBL8/edit#

**Comment by acabunoc** [comment]
Notes are summary should be all up to date! closing since we finished the interviews

**Comment by xmatthewx** [comment]
cc @Lottarao see thread and doc for a peek on this work.
