### ISSUE TITLE
multiple entries

### ISSUE THREAD

**Issue by anmechung** [mozilla/network-pulse#480]
Can you delete multiple entries for "What Web Literacy Skills for Missing from Learning Standards?"  and leave one the most recent one with image?  FYI - When I hit submit, the error message I received several times was something like, "unable to connect to the server ..."

**Comment by xmatthewx** [comment]
I deleted the duplicated. Closing this but cc'ing @alanmoo to see if we need to file a new ticket to deal with the error.

**Comment by alanmoo** [comment]
Not sure. @anmechung if it happens again, take a screenshot?
