### ISSUE TITLE
Add autocomplete for tags on input form

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#482]
Autocomplete can help users avoid typos and use consistent tags, so that people who `games` can also find a good `game`. 

Note: We should convert to lowercase

Step 1 – a designer and dev should collaborate to define requirements, gather benchmarks, and scope the simplest useful solution. Interaction will deeply intertwine both disciplines.

Step 2 – I recommend we prototype rather than comp-then-dev.

**Comment by alanmoo** [comment]
There's gotta be a react based autocomplete package we can pull in pretty easily...

**Comment by kristinashu** [comment]
I won't design this, just let me know what is possible.

If you have options, Medium is a good example to follow.
1) Before.
<img width="338" alt="screen shot 2017-05-02 at 11 39 26 am" src="https://cloud.githubusercontent.com/assets/1068783/25633570/6dfe6f30-2f2c-11e7-8d2f-1d737c1cc3e6.png">

2) After typing the second letter, a few options are suggested (bonus: it shows how many posts are already using that tag).
<img width="399" alt="screen shot 2017-05-02 at 11 40 05 am" src="https://cloud.githubusercontent.com/assets/1068783/25633574/728011b2-2f2c-11e7-9579-21b02815bba6.png">

3) As soon as I've added a comma or clicked on one of the suggested terms, the tag becomes boxed in with an X to remove.
<img width="367" alt="screen shot 2017-05-02 at 11 40 17 am" src="https://cloud.githubusercontent.com/assets/1068783/25633579/76bb8036-2f2c-11e7-8790-2e3253134187.png">

4) And repeat...
<img width="334" alt="screen shot 2017-05-02 at 11 40 34 am" src="https://cloud.githubusercontent.com/assets/1068783/25633587/7c848166-2f2c-11e7-8724-3ccd1feb0fec.png">
<img width="343" alt="screen shot 2017-05-02 at 11 40 48 am" src="https://cloud.githubusercontent.com/assets/1068783/25633588/7c862fac-2f2c-11e7-9daa-59d8179779fb.png">

**Comment by alanmoo** [comment]
Yeah, that's what I was thinking. The official react autocomplete package doesn't support multiple items, but something like http://i-like-robots.github.io/react-tags/ looks like a possible option.

**Comment by kristinashu** [comment]
Ok nice. That example doesn't seem to let me add new tags, but otherwise looks good.

**Comment by alanmoo** [comment]
Ah right, we'll have to see if it supports that/can be added.

**Comment by mmmavis** [comment]
@Pomax agree that this is something we should add to `react-formbuilder`? We can add a new field type (`list-values`? `autosuggestion`? ...?) and let it take an `options` property which we can pass `tags` fetched from API as the value?

**Comment by Pomax** [comment]
@mavis this feels like something we could add to the form builder but then we need to be pretty careful how and where we do that, since the form builder knows nothing about "tags". Can you explain what you were thinking of in more detail?

**Comment by mmmavis** [comment]
I was thinking we could have a field `tagGroups` (please suggest a better name!) which takes similar properties as `checkboxGroup`

```js
tags: {
    type: `tagGroup`,
    label: `Tags`,
    options: arrayOfTags,
    colCount: 1
  },
```

I was thinking during build step we can pull tags from Pulse API and generate [detail-info-fields.js](https://github.com/mozilla/network-pulse/blob/master/pages/add/form/detail-info-fields.js) with `arrayOfTags` being the actual Pulse tags. But now I think of it this means `arrayOfTags` can easily be out-of-sync since we don't rebuild on production periodically. Suggestions? @Pomax ?

**Comment by Pomax** [comment]
that gets more specific than a generic form builder should probably be. However, the form builder lets us use components as field types, so if there's a good autocompleting tag component already out there, then all we need to do is wrap that in a component that takes whatever props we need to throw at it, with a function that the form-builder can use to get the data back out, and we should be good to go

**Comment by mmmavis** [comment]
hey @Pomax I haven't dived into `react-formbuilder`'s codebase yet. But I followed the README and tried adding a component as a field... it didn't work for me. 

```jsx
var Test = React.createClass({
  getInitialState: function() {
    return {
      value: null
    };
  },
  onChange: function(event) {
    console.log('hi test onChange', event.target.value);
    this.setState({value: event.target.value});
  },
  render: function() {
    return (<input onChange={this.onChange} />);
  }
});

module.exports = {
  ...
  test: {
    type: Test,
    label: `test test test`,
    fieldClassname: `form-control`,
    placeholder: `hi im the placeholder`
  },
  ...
}
```

When I typed something in the input box I did see `console.log('hi test onChange', event.target.value);` got printed but the form didn't seem to know there was value changes. Did I pass anything wrong?

**Comment by xmatthewx** [comment]
Amazing! This functions beautifully on staging. Well done. Question: how are suggestions ordered?

**Comment by kristinashu** [comment]
Agree! This is excellent!

**Comment by mmmavis** [comment]
🎉 

@xmatthewx I think it's just based on what the API returns: https://network-pulse-api-staging.herokuapp.com/tags/ I'm guessing the list is sorted based on the time a tag was created? (oldest -> newest) /cc @Pomax @alanmoo

**Comment by xmatthewx** [comment]
Ok. If so, let's file a follow up for API to return tags sorted by most-to-least used. Not critical today, but will make for a smoother experience. Also useful elsewhere on the site (empty search suggestions, trending view).
