### ISSUE TITLE
Add entry title to html head

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#483]
For SEO and user's browser history, we should include the entry title in html head. "Foo bears – Mozilla Network Pulse"

**Comment by mmmavis** [comment]
@xmatthewx How about non-entry pages? Just follow the same format `[page name] - Mozilla Network Pulse`? e.g., `Featured - Mozilla Network Pulse`, `Digital Inclusion - Mozilla Network Pulse`, `Add - Mozilla Network Pulse`?

See https://github.com/mozilla/network-pulse/blob/master/routes.jsx#L94-L111 for list of routes we currently have.

**Comment by xmatthewx** [comment]
Good question. Yes, that pattern is fairly standard. For Issues and Tags we can keep it simple:

Yes: Issues – Mozilla...
Yes: Decentralization – Mozilla...
No: Decentralization – Issues – Mozilla

**Comment by mmmavis** [comment]
@xmatthewx for search is using the same format e.g., `web literacy - Mozilla...` good?

**Comment by xmatthewx** [comment]
That works. Do you update browser history? If yes, cool. If not, you could just say `Search – Mozilla...`

Other sites handle this pretty differently:  
 - Test - Wikipedia
 - NY Times Search
 - Search for "test" - Google Developers

**Comment by mmmavis** [comment]
Seems to be working!

<img width="332" alt="screen shot 2017-04-17 at 2 25 49 pm" src="https://cloud.githubusercontent.com/assets/2896608/25105536/d98b2040-2379-11e7-8fd5-d850cddf05a9.png">

**Comment by xmatthewx** [comment]
huzzah 🥇

**Comment by mmmavis** [comment]
:man_dancing: 
:woman_cartwheeling:
