### ISSUE TITLE
Form language

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#484]
Two statements to add to the form. 

 1. Above "Submit" button – "By submitting your entry, you agree to be bound by the [Mozilla Terms of Service](https://www.mozilla.org/about/legal/terms/mozilla/), and you agree that your entry may be edited lightly for clarity and style."  
 1. Image  – "Only submit images that you have permission to use in this context."

Maybe something like this: 

<img width="807" alt="screen shot 2017-04-13 at 5 57 00 pm" src="https://cloud.githubusercontent.com/assets/53411/25026027/a5c3bd3a-2072-11e7-9b57-2c05161c3889.png">

**Comment by xmatthewx** [comment]
Let's update a few other bits of copy as well, with some feedback from Kevin. 

### Intro 

Do you have something to share? If it might be useful to someone in our network, share it here! Pulse includes links to products and software tools, research reports and findings, think pieces, white papers, interviews, and curricula. If it might be useful, share it… at any stage or fidelity.

Please keep your language simple and useful for a broad audience. No jargon. Submissions may be lightly edited by our curators for spelling, grammar and style consistency.

### Basic info

 - Title (Required: Keep it simple. Name it, don't describe it.)
 - Description (Simple, brief language works best. No jargon.)

**Comment by xmatthewx** [comment]
see also #529 for some copy

**Comment by mmmavis** [comment]
@xmatthewx which "required" label styling do we wanna go with?

current:
<img width="300" alt="screen shot 2017-05-10 at 3 52 44 pm" src="https://cloud.githubusercontent.com/assets/2896608/25924664/cc95a852-3598-11e7-98e2-6173154e26ab.png">

from your comment above:
<img width="436" alt="screen shot 2017-05-10 at 3 52 33 pm" src="https://cloud.githubusercontent.com/assets/2896608/25924665/ce5ba4c0-3598-11e7-98a9-fa834a2b752b.png">

**Comment by xmatthewx** [comment]
I wonder what @kristinashu thinks. Should we add a style, separate title from explanation?

**Input Name** (required)
_Help text info info info_

**Title** (required)
_Keep it simple. Name it, don't describe it._

**Description**
_Simple, brief language works best. No jargon._

**Comment by kristinashu** [comment]
Could add a style or to keep it simple and reduce height, we could do something like this:

Title: Keep it simple. Name it, don't describe it. _(Required)_

**Comment by xmatthewx** [comment]
"Look best..." in mockup could be a different presentation. We just need some hierarchy for all this hint text.

**Comment by mmmavis** [comment]
> "Look best..." in mockup could be a different presentation. We just need some hierarchy for all this hint text. 

No worries. I have a PR up for that: https://github.com/Pomax/react-formbuilder/pull/28

**Comment by mmmavis** [comment]
Finalized changes:

//////

- Above "Submit" button – "By submitting your entry, you agree to be bound by the [Mozilla Terms of Service](https://www.mozilla.org/about/legal/terms/mozilla/), and you agree that your entry may be edited lightly for clarity and style."  
- Image  – "Only submit images that you have permission to use in this context."

<img width="807" alt="screen shot 2017-04-13 at 5 57 00 pm" src="https://cloud.githubusercontent.com/assets/53411/25026027/a5c3bd3a-2072-11e7-9b57-2c05161c3889.png">

### Intro 

Do you have something to share? If it might be useful to someone in our network, share it here! Pulse includes links to products and software tools, research reports and findings, think pieces, white papers, interviews, and curricula. If it might be useful, share it… at any stage or fidelity.

Please keep your language simple and useful for a broad audience. No jargon. Submissions may be lightly edited by our curators for spelling, grammar and style consistency.

### Basic info

 - Title: Keep it simple. Name it, don't describe it. *(required)*
 - Description: Simple, brief language works best. No jargon.

**Comment by mmmavis** [comment]
Done!
