### ISSUE TITLE
Detail view corrections link

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#485]
Since some things will be posted on behalf of others, would be good to give people the means to correct stuff. We have contact in the footer. This is a bit more accessible. 

<img width="687" alt="screen shot 2017-04-13 at 6 03 49 pm" src="https://cloud.githubusercontent.com/assets/53411/25026272/c1e669e4-2073-11e7-91b3-cec0aa5afb34.png">

Should be unobtrusive. This comp uses half opacity.

**Comment by kristinashu** [comment]
This looks good. What would clicking Contact Us do (email us, a form, open issue...)? 

This area is also where people could flag a post.

**Comment by xmatthewx** [comment]
Yes. We have a contact link in the footer that goes to a google form.

**Comment by mmmavis** [comment]
Do we still wanna add this? @kristinashu @xmatthewx this should be a quick fix.

**Comment by kristinashu** [comment]
I think so!

(slightly related to Enable users to edit their own entries #472)

**Comment by xmatthewx** [comment]
Yes. We'll have to think through the form, but could just start with the generic contact form in the footer.

**Comment by mmmavis** [comment]
> Yes. We'll have to think through the form, but could just start with the generic contact form in the footer.

Cool, I'll have a PR for this today.

**Comment by mmmavis** [comment]
Question is where to add the link on the new 2-column layout? https://network-pulse-staging.herokuapp.com/entry/334

**Comment by kristinashu** [comment]
Good questions... how about we add a diving line then have the text just under it?

![screencapture-network-pulse-staging-herokuapp-entry-334-1502313850315](https://user-images.githubusercontent.com/1068783/29144759-fe29a6da-7d0e-11e7-93c5-3027272c33ef.jpg)

**Comment by mmmavis** [comment]
Live on production!
