### ISSUE TITLE
Clarify attribution and author

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#486]
Attribution is a bit ambiguous right now. Might be read that entry was posted by the people listed as creators. 

Putting their names in red helps to attach creators to the title. 

<img width="422" alt="pulse-attribution-ui" src="https://cloud.githubusercontent.com/assets/53411/25026352/139f3fae-2074-11e7-878c-362a275c2030.png">

Curious what you think @kristinashu

**Comment by kristinashu** [comment]
I worry about there being too much pink and push body content down too much (because of the added gap). How about we remove the _date added_ and _posted by_ info from these thumbnail cards, only show it in the detail view. I think this will generally help prioritize and clean up the card view. This way we can keep the attribution grey and it will stand out more.

**Comment by kristinashu** [comment]
Here it is mocked up, so only the creators are visible on the overview screen:

![desktop 2x](https://cloud.githubusercontent.com/assets/1068783/25633041/a19fce94-2f2a-11e7-94e4-df81d5586fff.png)

And then creators, date added and added by are at the bottom (with tags).

![desktop - detail 2x](https://cloud.githubusercontent.com/assets/1068783/25633042/a357ec30-2f2a-11e7-87cb-4dd8fc5f5ac7.png)

**Comment by kristinashu** [comment]
@alanmoo @Pomax do we currently show who added the post? If we are, it seems like it is grouped with the project creators. Can we add the post author and/or have it separate from the project creators?

**Comment by Pomax** [comment]
Looking at https://github.com/mozilla/network-pulse/blob/master/components/project-card/project-card.jsx#L214-L232 we only show creator information, and the date-time the entry was posted, but not the "who posted it" information

**Comment by kristinashu** [comment]
Ok thanks Pomax. 

@xmatthewx if you're happy with the comps then I'll open a ticket for implementations. 

Steps would be:
- surface post author to users
- update thumbnail cards to only show the creators (remove data posted)
- update detail view to show date added and the creator at the bottom
- bonus: make the author name clickable and show all their posts (similar to tag view e.g. https://www.mozillapulse.org/tags/mozfest)

**Comment by xmatthewx** [comment]
Thanks @kristinashu. This is great. Sorry for so many notes. 

 - I wonder if we should remove "by" before creators since it could be read as posted by. Or, mabe spell out _project by_? Attribution can be a very sensitive topic.
 - As I mentioned elsewhere, some projects have a lot of tags. And the metadata feels a little funny in the middle, before the primary action button. Could we try these as a card footer? Or jump to your new layout with sidebar?

Whoever engineers this: Feel free to file the bonus (clickable author names) as a separate ticket to do after. That could also include clickable creator names. The DB is ready for both, but we'll need to add to API. So the work is a little different.

**Comment by kristinashu** [comment]
Let's keep this ticket small, we can focus on tags #523 and layout in a new ticket.

"Project by" would get very repetitive on the overview page but have removed "by":

![desktop 2x](https://cloud.githubusercontent.com/assets/1068783/25860935/f0b289b4-3497-11e7-81d7-c05b55bdd2c0.png)

![desktop - detail copy 3 2x](https://cloud.githubusercontent.com/assets/1068783/25860939/f498ecb2-3497-11e7-8882-07e8c888ac25.png)

**Comment by xmatthewx** [comment]
👍 feel free to file a new ticket to implement moving the data and removing "by". this ticket got looooong.

**Comment by kristinashu** [comment]
Opened implementation ticket https://github.com/mozilla/network-pulse/issues/528
