### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#487]
Add/remove/update links:
 - Remove “Chat” link as Mattermost is being deprecated
 - Add "Privacy" link to https://www.mozilla.org/privacy/websites/
 - "Legal” in footer should link to https://www.mozilla.org/about/legal/terms/mozilla/

**Comment by Sudip7** [comment]
Please assist to find the Privacy icon. Was not able to locate it in repo. @xmatthewx @mmmavis

**Comment by Sudip7** [comment]
I found these two links while searching for privacy icon. Not sure how to implement them. 

http://bigthink.com/design-for-good/mozillas-privacy-icons-a-visual-language-for-data-rights
https://www.fastcodesign.com/1662961/mozillas-privacy-icons-tell-you-how-sites-use-your-personal-data

**Comment by mmmavis** [comment]
@Sudip7 

In `footer.jsx`, update `const Footer` to what @xmatthewx suggested in this ticket. Here is the list of icons that we can pull from [`mofo-bootstrap`](https://mozilla.github.io/mofo-bootstrap/demo/) (via `mofo-ui` package): https://github.com/mozilla/mofo-ui/blob/master/src/components/mofo-footer/mofo-footer.jsx#L6

To to add privacy icon to footer, add the following to `Footer`

```jsx
{
    iconType: `privacy`,
    link: `https://www.mozilla.org/privacy/websites/`,
    text: `Privacy`
 }
```

**Comment by Sudip7** [comment]
@mmmavis, please confirm the order of icons should be in the order : Github, Contact Us, Legal, Licence, Privacy.

**Comment by mmmavis** [comment]
Looks good to me. @xmatthewx agree? ^

**Comment by xmatthewx** [comment]
Looks good. Let's put Contact Us as the last item. Make it easier to find. Thanks so much!!

**Comment by mmmavis** [comment]
@Sudip7 

- GitHub
- Legal
- License
- Privacy
- Contact Us

**Comment by Sudip7** [comment]
Thanks @mmmavis @xmatthewx , will send the PR soon

**Comment by Sudip7** [comment]
PR request sent, please review

**Comment by mmmavis** [comment]
Hey @Sudip7 I reviewed your PR this morning (PDT time): https://github.com/mozilla/network-pulse/pull/496 Are you able to see my comments there?

**Comment by mmmavis** [comment]
Live on https://www.mozillapulse.org ✨ Thanks @Sudip7 !

Don't forget to check our PR reviews comments **in the PR itself** next time 😉 That's normally where you look for review updates (rather than on the issue ticket page) 🤓 .
