### ISSUE TITLE
Reduce title size and length 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#489]
Some titles are long: (screen cap from production)
<img width="1433" alt="screen shot 2017-04-17 at 8 44 47 am" src="https://cloud.githubusercontent.com/assets/1068783/25094252/2312f49c-234b-11e7-948d-d22c0aeaa272.png">

We should reduce font size slightly (from 30px to 26px).

@xmatthewx do you think we need to add a character count to the title?

**Comment by xmatthewx** [comment]
oye. i think there is a character count, but maybe it should be even shorter. smaller type might help. 

there is an issue to update some copy on the form for legal. i added a comment about titles, but it'll only help so much. https://github.com/mozilla/network-pulse/issues/484#issuecomment-294195199

we reserve the right to edit entries. i think if we do a round of cleanup, people will hopefully write titles  similar to what they see. 

or... maybe we should move away from titles. maybe titles are a relic of the past. i'm an old person so i'm not sure. should we let people tweet, merging title and description?

**Comment by kristinashu** [comment]
Whaaat?!? Long live titles! 

Things to do:
- [ ] reduce font size in title
- [ ] manually clean up existing titles
- [ ] reduce character count from 140 to 80
- [ ] update language - #484 
- [ ] inform users about character count - #493

**Comment by kristinashu** [comment]
@xmatthewx can we put this one into our next heartbeat?
