### ISSUE TITLE
Make cards more responsive

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#491]
from QA ticket https://github.com/mozilla/network-pulse/issues/419

### Action
View pulse at different screen widths

#### 1) Thumbnail grid view
- Cards are squished very thin when they don't need to be (see screen cap from product)
- we should switch to 2-per-row below ~992px
- recommend a minimum card width ~320px
<img width="786" alt="screen shot 2017-04-17 at 9 37 35 am" src="https://cloud.githubusercontent.com/assets/1068783/25095669/8a8072d4-2351-11e7-9b2a-935556945ffd.png">

#### 2) Detail view
- Individual card has tons of margin at browser widths below 992px  (see screen cap from product)
- cards should keep the wider style for longer
<img width="772" alt="screen shot 2017-04-17 at 9 40 51 am" src="https://cloud.githubusercontent.com/assets/1068783/25095759/f968a7e8-2351-11e7-95e1-2d49dafe8ef5.png">

**Comment by mmmavis** [comment]
I have a PR up for this.

**Comment by kristinashu** [comment]
Looks good!
