### ISSUE TITLE
Remove gh-pages?

### ISSUE THREAD

**Issue by gvn** [mozilla/network-pulse#497]
This is coming up in Google search results:

https://mozilla.github.io/network-pulse/

cc: @xmatthewx

**Comment by xmatthewx** [comment]
I removed link from gh and readme a week or so ago, but yes, probably a good idea.

**Comment by mmmavis** [comment]
yea let's do that

**Comment by mmmavis** [comment]
I'm gonna remove `gh-pages` now. There's also a `v1` branch if we ever wanna check out the v1/jQuery based code.

**Comment by mmmavis** [comment]
Done!
