### ISSUE TITLE
Update Leadership Series & Fix Redirect

### ISSUE THREAD

**Issue by NDuma** [mozilla/network-pulse#498]
Link from [Leadership series](https://github.com/mozilla/open-leadership-training-series/tree/gh-pages/_articles) directs to https://mozilla.github.io/network-pulse/ {I don't recall which section to reference (it's before: https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/ )}
- [X] Lookup section
  *  [search Result](https://github.com/mozilla/open-leadership-training-series/search?utf8=%E2%9C%93&q=https%3A%2F%2Fmozilla.github.io%2Fnetwork-pulse%2F+&type=)
- [ ] cite link in-line
- [x] Make PR to fix Leadership Link to "Graduated site".
- [ ] Make PR to update to "Graduated" site.

["Add" button]```//*[@id="toggle-form-button"]``` makes [notification](http://prntscr.com/eyluaj) of redirect  yet clicking [https://www.mozillapulse.org/](https://www.google.com/url?q=https://www.mozillapulse.org/&sa=D&ust=1492680178651000&usg=AFQjCNHW7bWgDbAU3csIXjW3XOXjrpQGJQ) 
Redirect fails
___
Version 60.0.3072.1 canary SyzyASan

**Comment by xmatthewx** [comment]
Looks like this is done. Closing.
