### ISSUE TITLE
We should enable and RSS feed or another form of subscription

### ISSUE THREAD

**Issue by chadsansing** [mozilla/network-pulse#499]
A community member asked for RSS in order to keep up with Pulse. @Pomax cited this article on Slack which explains how to help Django create the feed.

https://docs.djangoproject.com/en/1.11/ref/contrib/syndication/#publishing-atom-and-rss-feeds-in-tandem

Can we implement?

**Comment by Pomax** [comment]
on the api side I've filed https://github.com/mozilla/network-pulse-api/issues/112

@xmatthewx ?

**Comment by xmatthewx** [comment]
I'm keen to get notices into twitter and slack. Is RSS a means to that end? Or are there easier ways? That will serve many people well.

**Comment by xmatthewx** [comment]
And if Django makes RSS easy to add, by all means.

**Comment by Pomax** [comment]
There's always IFTTT as a way to to turn feeds into "anything", which might be worth looking at.

**Comment by phillipadsmith** [comment]
@Pomax FYI, I've added a simple Zapier integration that posts the latest Pulse entries to channel #mofo-pulse-latest on the Mozilla Slack instance.

I've also added two Zapier RSS feeds: one for latest, and one for featured. I'm not 100% sure they're working as expected, so I'll need to take another look once another Pulse entry is added. 

https://zapier.com/engine/rss/268207/mozilla-pulse-featured/
https://zapier.com/engine/rss/268207/mozilla-pulse-latest/

Not a perfect solution, but a solution for now! :grimacing:

Pinging mozilla/network-pulse-api#112 also.

**Comment by alanmoo** [comment]
It would be cool if we could create a JSON Feed. It's a new thing that's picking up steam, and easier than a proper XML based RSS feed. https://jsonfeed.org/

**Comment by Pomax** [comment]
@alanmoo I don't know if you purposely phrased it that way, but damn son.

**Comment by alanmoo** [comment]
Hey, it's a spec and not a new Javascript framework ;) (But also not necessary, just a thought I wanted to throw out there in case someone feels like playing around with something. Probably a good "help wanted" item.)

**Comment by gideonthomas** [comment]
DOne
