### ISSUE TITLE
How do I see items I've added to Pulse?

### ISSUE THREAD

**Issue by jvallera** [mozilla/network-pulse#502]
I've added two or three projects to pulse, but cannot find them. They are not showing up under the categories or through search.

**Comment by xmatthewx** [comment]
Odd. I will investigate. Your submissions should appear in Latest and via search, no moderation required.

**Comment by jvallera** [comment]
Thanks! One is called Privacy Brigade, another is Ada Lovelace day curriculum Jam (or something like that)...I forgot what the third one was.

**Comment by xmatthewx** [comment]
All looks good here. 

I see Ada here: https://www.mozillapulse.org/entry/193
And here: https://www.mozillapulse.org/search?keyword=ada

Brigade here: https://www.mozillapulse.org/search?keyword=privacy
Here: https://www.mozillapulse.org/entry/236
And here: https://www.mozillapulse.org/latest

Ping me on Slack if you still can't see things.

**Comment by jvallera** [comment]
Perfect! Thanks. My bad, I was looking in the old version of Pulse. https://mozilla.github.io/network-pulse/

**Comment by xmatthewx** [comment]
Yep. We fixed the shortlink to point to the new Pulse. Have a bug filed to pull down the old prototype. 

Nice posts by the way!
