### ISSUE TITLE
Update submission approval message

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#504]
Soon all users will be able to submit an entry. We should update the submission text so that if they're not an approved user, they see a message that says something like "thanks for your submission, we've added it to the review queue and if all goes well it'll show up in the public feed soon"

On submitting, users are redirected to a url like `http://localhost:3000/entry/17?justPostedByUser=true` If the GET request for an entry fails, we should check for that query param. If it is true, then display that message, perhaps on the homepage?

This is required before moderation lands 

@xmatthewx

**Comment by Pomax** [comment]
I don't understand why we would need to do this:
- user posts an entry in the client
- client changes the view to "thanks, it'll be reviewed soon!" if the post succeeds, by loading a component that's associated with the react-router URL `/submitted` or something

**Comment by xmatthewx** [comment]
And... I see now he's talking about something else

**Comment by xmatthewx** [comment]
Whoops. Wrong channel. This ^^^ makes sense, even if I don't.
