### ISSUE TITLE
Need to fix a typo in an Pulse entry for Global Sprint

### ISSUE THREAD

**Issue by chadsansing** [mozilla/network-pulse#505]
I imagine travel kept Matthew from helping with this yesterday, but the title of

https://www.mozillapulse.org/entry/253

Needs to be changed from 'Library Caprentry' to 'Library Carpentry' asap for the Global Sprint.

**Comment by kristinashu** [comment]
Should be fixed now!

**Comment by chadsansing** [comment]
Thanks, @kristinashu!
