### ISSUE TITLE
Remove splash screen

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#511]
In Firefox 53.0 for mac.

When I am on https://www.mozillapulse.org/featured and then click on a post, I see the pink splash screen for a fraction of a second before seeing the post's detail page. This splash screen should only be visible if the first time a users loads Pulse.

**Comment by kristinashu** [comment]
Once https://github.com/mozilla/network-pulse/issues/488 is done, we might be able to completely remove the splash page.

**Comment by xmatthewx** [comment]
Remove the splash screen. As Kristina pointed out, it's no longer needed.

**Comment by mmmavis** [comment]
@kristinashu now that #488 is done, can we remove splash page altogether?

**Comment by mmmavis** [comment]
PR filed!

**Comment by kristinashu** [comment]
Awesome!
