### ISSUE TITLE
optimize bookmarks.jsx

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#514]
Currently bookmarks.js in its `componentDidMount` function gets the list of user bookmarks, updates the state with that, then checks if there is a bookmarks cache and if so, overrides the just-set list of bookmarks. This feels a little inefficient, is the code clean enough that we can instead follow this flow instead?

- check for shouldRestore
- if shouldRestore, setState with cached values
- if no shouldRestore, setState by calling `getBookmarks`

**Comment by mmmavis** [comment]
Most of the bookmark related code has been rewritten/modified in PR https://github.com/mozilla/network-pulse/pull/610 . I think we can close this ticket now.
