### ISSUE TITLE
Allow users to attempt sign in after a sign in fail

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#515]
Follow up based on - Implement Sign in failed screen #317

**Currently we have:** 
Prompt to sign in
<img width="386" alt="screen shot 2017-05-02 at 2 48 48 pm" src="https://cloud.githubusercontent.com/assets/1068783/25641336/68a981d4-2f48-11e7-9c2f-ccca9a222956.png">

Message if sign in failed
<img width="427" alt="screen shot 2017-05-02 at 2 39 37 pm" src="https://cloud.githubusercontent.com/assets/1068783/25641340/69f691c6-2f48-11e7-8799-5c4aedd871e0.png">

**Can we add the sign in link so people can try again if the need to?**
<img width="516" alt="screen shot 2017-05-02 at 3 06 53 pm" src="https://cloud.githubusercontent.com/assets/1068783/25641460/07d3399e-2f49-11e7-82ee-c2df1d4e605e.png">

**Comment by alanmoo** [comment]
The "login failed" screen will become significantly less visible soon, as we're going to enable log-in for anyone with a Google account. How does that affect this ticket?

**Comment by kristinashu** [comment]
True. Could there be any other reason for a failed login? If non-mozilla account is the only reason then we can close this.

**Comment by alanmoo** [comment]
I don't believe any other error screen would return to a page we build...@pomax, am I missing anything?

**Comment by Pomax** [comment]
the only thing I can think of would be "google auth was misconfigured" and then login will fail for everybody, not any particular subset. I think we can close this issue given the migration we'll be doing.
