### ISSUE TITLE
Remember list scroll position – Part 2

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#518]
Follow up on - Remember list scroll position #428 

This is working well for me in FF for Mac and Chrome iOS but not on Chrome 58.0.3029.96 for Mac In Chrome for Mac it is reloading the page when I hit the my back arrow, it should remember my scroll position.

**Comment by xmatthewx** [comment]
For me, this seems to work, unless I have hit the View More button. When I go back, I need to hit View More again. Scroll position isn't preserved since the entry isn't visible.

**Comment by kristinashu** [comment]
Weird, I just did a straight forward scroll down, click on post, click browser back button once on the post detail page. The page reloaded for me. Also just tried on Luke's computer where it also reloaded. 

@mmmavis can you please try?

**Comment by mmmavis** [comment]
Um this is weird, it works for me still and I don't have to hit "view more" button again.

@kristinashu @xmatthewx which device / browser are you on?

**Comment by kristinashu** [comment]
Works everywhere for me except for Chrome 58.0.3029.96 for MacOS Sierra 10.12.4

**Comment by xmatthewx** [comment]
My test: 
 - open featured
 - tap view more
 - view flexbox froggy details
 - hit back button

Safari OS X - works
Firefox OS X - works
Chrome OS X - reloads (v57.0.2987.133)

Firefox Android - goes to bottom of view, showing view more button, but not the froggy (v53.0.2)
Chrome Android - reloads (v58.0.3029.83)

**Comment by Pomax** [comment]
This seems to have been fixed since, certainly on OSX for Chrome (tested with v60, no reload occurs)

**Comment by Pomax** [comment]
Also fixed for Firefox on Android

**Comment by Pomax** [comment]
Also fixed for Chrome on Android.

**Comment by Pomax** [comment]
Closing as this bug seems to have been fixed.
