### ISSUE TITLE
Disable image link on detail view

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#519]
Steps to repeat:
- go to a post detail page e.g. https://www.mozillapulse.org/entry/251
- click on the image and the page will reload

Expected result:
- clicking on image should not reload the page

**Comment by Sudip7** [comment]
I would like to work on it.

**Comment by xmatthewx** [comment]
thanks @Sudip7 !!

**Comment by mmmavis** [comment]
Hey @Sudip7 just checking if you are or still have the interests to work on this. If not that's totally fine. Just let us know and I will take care of it. 😉

**Comment by Sudip7** [comment]
hey @mmmavis , I was out of town and away from network. I really enjoy working with the team. Will look into it soon.

**Comment by mmmavis** [comment]
Hey @Sudip7 no worries at all. There's no rush or pressure here. I just wanted to make sure ticket doesn't get stale that's all! :)

**Comment by mmmavis** [comment]
PR https://github.com/mozilla/network-pulse/pull/575 fixed this issue. I will close this ticket once the fix is live on production.

**Comment by hannahkane** [comment]
@mmmavis says to close, so closing :)
