### ISSUE TITLE
Explore an expanded Get Involved section

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#521]
Notes based on chat with Matthew:
- what might it look like if people can flag the kind of support they needed? 
- description + link + maybe a few checkboxes or tags? 
- challenge would be to have a shortlist of meaningful categories that work for most scenarios (e.g. design, code, feedback, test, take action, fundraising...)
- could be a great way for people to filter
- will motivate people to post more and make it less of a passive experience for users
- keep it light and flexible
- will encourage people to post more works in progress

**Comment by kristinashu** [comment]
As we add more info, it might be nice to move the detail view away from the card view which looks very similar to the thumbnail overview cards. This will give us room for more content and possible more features like commenting... Just experimenting and trying different things out, not saying we should necessary do this.

https://redpen.io/sb1db0043c3844f70a

![desktop - detail with get involved copy 2 2x](https://cloud.githubusercontent.com/assets/1068783/25727827/4623d76a-30e0-11e7-8970-4cdbaed9f614.png)

**Comment by xmatthewx** [comment]
I love this design.

What if tags, social, date & name were added to this sidebar? Or below it? Think about small screens too, order of the elements.

**Comment by xmatthewx** [comment]
I really like the hierarchy and layout of title, thumb, heart, view, sidebar. Order and alignment is super.

**Comment by xmatthewx** [comment]
I think this Get Involved + Help approach works very well. 

We'll need a technical discussion about how we want to handle help tags. I think we treat them like issue categories, just labeling on frontend as designed. 

Question: the original suggestion was to allow a sentence on the different categories of help, instead of paragraph + tags as we have here. My instinct: this approach is simple, flexible, and less overwhelming to a submitter. True?

**Comment by kristinashu** [comment]
I'm not completely clear on what you have in mind but is this more what you had in mind?

![desktop details 2 column copy 2x](https://cloud.githubusercontent.com/assets/1068783/25925885/60a885d0-35a0-11e7-91aa-97b6761993f3.png)

**Comment by xmatthewx** [comment]
Yes, I think that was the suggestion. To clarify, my instinct was like yours, and I think your previous design is stronger than this new mockup. 

It's good to have this mockup as a reference though, if someone else thinks we should consider it. It's too many words, too much visual noise. 

Let's proceed with your [previous design above](https://github.com/mozilla/network-pulse/issues/521#issuecomment-299329820).

**Comment by kristinashu** [comment]
Okay, here's the slightly updated version from #527

![desktop - 2 column detail copy 4 2x](https://cloud.githubusercontent.com/assets/1068783/25911310/352c64a4-3568-11e7-9371-12b63af58c3a.png)

<img width="190" alt="screen shot 2017-05-10 at 10 04 05 am" src="https://cloud.githubusercontent.com/assets/1068783/25911343/52ca8ebe-3568-11e7-8dca-5bcfe69b33df.png">

Opened a new ticket for what the form updates #533

**Comment by kristinashu** [comment]
Ticket filed for implementation https://github.com/mozilla/network-pulse/issues/537
