### ISSUE TITLE
Implement tags and issues on Detail view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#523]
Tags are awesome. The help users find related things.

 - This ticket covers adding tags to frontend of an entries detail view. 
 - Related work tracked in #500.

Note: we should present both Issues and Tags to users on entry detail view.

**Comment by xmatthewx** [comment]
### Assumption: Issues + Tags

We should display Issues and Tags. For users, a single visual treatment is probably best, but always putting Issues first.

###

@mmmavis there are few design things to resolve. 

Some projects have a lot of tags. And the metadata feels a little funny in the middle, before the primary action button. Could we try it as a card footer? Fifty entries and have 6 TO 9 tags. @kristinashu I really like your tag style on the newer get involved design. Button/box rather than link.

**Comment by mmmavis** [comment]
@kristinashu could you give me a ping when design is finalized and ready for implementation? Thanks! 🍸 🍸

**Comment by kristinashu** [comment]
@xmatthewx like this?

![desktop - detail copy 3 2x](https://cloud.githubusercontent.com/assets/1068783/25859919/d89b382e-3494-11e7-8dbc-0f1ab907f004.png)

**Comment by xmatthewx** [comment]
This looks good, and ready to hand over to Mavis. 

And... I really like the 2-column layout you tried with for get involved. Feel free to continue looking at how the whole card works in concert in those other tickets.

**Comment by mmmavis** [comment]
@kristinashu I see that we are splitting `[creator]` and `[time posted]` lines here (detail view). Where do we wanna show this info on the list view?

**Comment by mmmavis** [comment]
@kristinashu what's the hover state for those tag buttons?

@xmatthewx @kristinashu do we wanna show the tags as they are or turn them into all lower cases?

**Comment by kristinashu** [comment]
@mmmavis the creator and time posted work is in this ticket https://github.com/mozilla/network-pulse/issues/528

For tags, please make the hover state one mofo-bootstrap shade of grey darker.

@xmatthewx what do you think about lower case? For consistency, I like the idea of forcing all of them to be lower case.

**Comment by xmatthewx** [comment]
Good catch @mmmavis. We should make tags lowercase when they are entered before they end up in the database. I will file a bug. Right now, DIY and diy are treated as if they are different tags.

**Comment by xmatthewx** [comment]
@mmmavis – just a note that these tags should include any 5 issues on the item too. Issues first. Presented to the user as the same thing. Tapping an issue tag should go to /issue/name

**Comment by mmmavis** [comment]
kk to keep things simple I'll just make tags visible on the detail view in this PR. :+1
