### ISSUE TITLE
Clean up tags on existing projects

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#525]
Will be very useful after we land tags on frontend and auto-complete in submission form.

 - [ ] de-dupe mixed case
 - [ ] remove Issue-as-tag after confirming issue-as-category is used
 - [ ] de-dupe near misses

I've gathered all the tags and dropped them into a [spreadsheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/14VrDqX_qlthS8_SeHcvfkw2vXcxJy891PpjSi8ZUFaE/edit?usp=sharing). Marked action required.

**Comment by xmatthewx** [comment]
Here's a review of 4 types of changes we can make with most impact. I tried stuff within each type by impact as well. 

https://public.etherpad-mozilla.org/p/network-pulse-tagz-merge

**Comment by mmmavis** [comment]
@Pomax I'm not very confident running db query on production db but I help with the manual updates part (if any).

**Comment by xmatthewx** [comment]
@acabunoc might be able to lend a hand. she has an interest in cleaning up the mozsprint stuff.

**Comment by acabunoc** [comment]
Is there a db schema I can look at? I ❤️ SQL
@Pomax

**Comment by Pomax** [comment]
@acabunoc it's a pretty basic schema, with a Django definition over in https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/tags/migrations/0001_initial.py: it's just an `id`, and a `name` field that is a Django `charfield with max length 150` (we're using postgres as our dbms)

**Comment by acabunoc** [comment]
started thinking about lowercasing them all:
https://gist.github.com/acabunoc/692e07d7420db33567f3d09595ce5319

Not sure this will be helpful!

**Comment by xmatthewx** [comment]
Brilliant. I'm not the most qualified to review the syntax, but the logic looks sound to me! 

cc @cadecairos

**Comment by Pomax** [comment]
@xmatthewx, @acabunoc I'm not a fan of just blanket-lowercasing tags. There are plenty of acronyms and words where capitalisation makes an appreciable difference. and lowercasing them as a tech solution actually makes the content less "right".

I would prefer a solution where we "don't insert a new tag if case-insensitive compare tells us the tag already exists", so rather than forcing everything to lowercase in this PR, look at what the lowest id is for tag sets with same-word-different-case, and then throwing away everything except that first instance, so that spelling "wins".

**Comment by xmatthewx** [comment]
@Pomax, alrighty. We can continue to allow users to create mixed-case tags, and rely on autocomplete to avoid unintentional differences in the future, ... if we clean up the existing mess. It'll disrupt discovery and a tracking/revealing trends too much. 

I don't understand your suggestion. Probably because it's late on Friday. 

Also... currently, our url paths .../tags/DIY and .../tags/diy reveal the same 13 projects. We'd need to change that to utilize case-sensitive tags.

So... I propose that we:
 1. look at current tags for any meaningful case differences
 2. merge and lowercase all the rest
 3. manually edit IoT and a few others back to mixed case via django (I can volunteer for that)
 4. continue to allow mixed case by users, rely on autocomplete and monitor for trouble
 5. make our paths case-sensitive

Does this seem reasonable?

**Comment by Pomax** [comment]
That sounds like a reasonable approach except for point 5. In terms of usability you want to be able to show tags with the correct casing, but *match* tags on any case. As an example, if I visit `.....?tags=IoT` then that should yield the same results as `.....?tags=iot` or `.....?tags=IOT`.

Building on that list, I see the following tasks here:

- [ ] api side: compile a list of tags where case makes a difference based on the tags we currently have
- [ ] api side: lowercase all tags using a Django migration (rather than pure SQL - the tag ids are used as foreign keys, which a Django migration can "cleanly" take care of for us)
- [ ] api side: edit the list of tags from task 1 to have the correct casing
- [ ] client side: update our tag autosuggestion so that if a user types a known tag that only differs in case, we auto-replace their tag with the one the system already knows
- [ ] api side: make filtering/searching by tag case insensitive in the query (but *not* in the result, those should show the exact case used in the database)

**Comment by xmatthewx** [comment]
Glad to hear that a django migration can make this simpler. 

I believe we can check off those last two items of yours. That seems to be the current behavior. 
 
@Pomax – can you take a look at current list, see if we have any meaningful case differences? 

How should we prepare for django migration? How can @acabunoc or I help prep [the tags](https://public.etherpad-mozilla.org/p/network-pulse-tagz-merge)?

**Comment by xmatthewx** [comment]
@Pomax – if you can create a model migration script or two, the rest of the team can help prep specific cases. 

We have 3 types generally (details in [pad](https://public.etherpad-mozilla.org/p/network-pulse-tagz-merge)): 
 1. [ ] merge mixed-case tags to single lowercase tag 
 2. [ ] remove issue-as-tag. add issue-as-category if not already there (ex: `decentralization`) 
 3. [ ] merge variations into single tag (ex: `game`, `games`)

**Comment by xmatthewx** [comment]
Ping @Pomax – let's try and unlock this clean and merging of tags. Happy to help with legwork, just need some guidance from you or @gideonthomas if we're going to do this as django migration rather than with sql.

**Comment by xmatthewx** [comment]
I've simplified things. Gathered all the tags again and dropped them into a [spreadsheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/14VrDqX_qlthS8_SeHcvfkw2vXcxJy891PpjSi8ZUFaE/edit?usp=sharing) with action required. Fewer items to migrate overall.

**Comment by alanmoo** [comment]
This thread has become a bit confusing. To sum up, the current ask is for:

A series of migrations in Django to
 * merge mixed-case tags to single lowercase tag
 * remove issue-as-tag. add issue-as-category if not already there (ex: decentralization)
 * merge variations into single tag (ex: game, games) as indicated [here](https://docs.google.com/spreadsheets/d/14VrDqX_qlthS8_SeHcvfkw2vXcxJy891PpjSi8ZUFaE/edit#gid=0)

Is this right @xmatthewx?

**Comment by xmatthewx** [comment]
yes! that's correct!

**Comment by gideonthomas** [comment]
I think in general you should be able to write a django migration that does all of the above and might be a bit easier than writing PL/SQL (but this really depends on what you're comfortable with). What you're looking for is a data migration - https://docs.djangoproject.com/en/1.11/topics/migrations/#data-migrations.

> merge mixed-case tags to single lowercase tag

I think you can pretty much adapt @acabunoc's sql script above into django code:
```py
for tag in Tags.objects.all():
    if tag.name.islower():
        continue
    for mixed_case_tag in Tags.objects.filter(Q(name__iexact=tag.name), ~Q(pk=tag.pk)):
        mixed_case_tag_entries = mixed_case_tag.entries
        tag.entries.add(*mixed_case_tag_entries)
        mixed_case_tag.delete()
```
<br>

> remove issue-as-tag. add issue-as-category if not already there (ex: decentralization)

There seem to be some cases here where the tag's text does not match the issue's text. In this case, it might just be easier to hardcode the tag ids from the spreadsheet and update accordingly
```py
issue = Issues.objects.get(name__iexact="digital inclusion")

for tag in Tags.objects.filter(pk__in=[ <hardcode the tag ids for the specific issue for e.g. digital inclusion from the spreadsheet here>]):
    entry_issues = tag.entries.issues.all()
    if issue not in entry_issues:
        tag.entries.issues.add(issue)
    tag.delete()
```
and repeat for each issue
<br>

> merge variations into single tag (ex: game, games)
Here too I think it might just be easier to hardcode the ids and update accordingly
```py
final_tag, created = Tags.objects.get_or_create(name__exact="games")
for tag in Tags.objects.filter(pk__in=[ <hardcode the tag ids that need to be transformed for a single transformation for e.g. games> ]):
    entries = tag.entries
    final_tag.entries.add(*entries)
    tag.delete()
```
and repeat for each migrated tag

Hopefully that is helpful, let me know if you need any more info or if I didn't fully answer the question.

**Comment by alanmoo** [comment]
Thanks @gideonthomas- do you, @acabunoc, or @cadecairos have the bandwidth/desire to open a PR for this? Even if it's not a complete one (all tags that need transforming), getting the scaffolding of it together would be helpful.

**Comment by gideonthomas** [comment]
I unfortunately don't at the moment, sorry.

**Comment by xmatthewx** [comment]
@acabunoc do you have the know-how to do this django-wise? 

Note: the spreadsheet includes a count of how many times a tag is used. We can land lowercasing and then start with big wins, quit when payoff drops too low.

**Comment by Pomax** [comment]
I've setup a PR for this on https://github.com/mozilla/network-pulse-api/pull/167, which does a two-pass clean up.

The first pass removes duplicates, preserving "whatever the first instance's case", rebinding which tag an entry links to in the process, with the second pass then forcing all tags left from this to lower case. 

After this lands and is applied, we can go in and do manual curation.

**Comment by xmatthewx** [comment]
I think part of this is ready to merge to production. When it's done, let's do a quick review of [spreadsheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/14VrDqX_qlthS8_SeHcvfkw2vXcxJy891PpjSi8ZUFaE/edit?usp=sharing) to mark what's done and what remains. We can file new follow up.

**Comment by Pomax** [comment]
After the initial collapse, there are a fair number of tags that have commas, so I'm going to write an additional utility function that does "the right thing" when it sees tags with commas:
- split on comma,
- trim resulting tag(s)
- collapse duplicates

**Comment by xmatthewx** [comment]
Excellent @Pomax. Should we close this issue an open a new one for a clean slate?

**Comment by Pomax** [comment]
sure. Filing #177 for this work
