### ISSUE TITLE
Implement two column layout for detail view

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#527]

**Comment by kristinashu** [comment]
Tried a few different layout but think something along these lines is working best:

![desktop - 2 column detail copy 4 2x](https://cloud.githubusercontent.com/assets/1068783/25911310/352c64a4-3568-11e7-9371-12b63af58c3a.png)

<img width="190" alt="screen shot 2017-05-10 at 10 04 05 am" src="https://cloud.githubusercontent.com/assets/1068783/25911343/52ca8ebe-3568-11e7-8dca-5bcfe69b33df.png">

cc @xmatthewx

**Comment by xmatthewx** [comment]
I think this is all great. 

We can talk with Mavis after she lands tags and form stuff about the order we want tackle this. It seems like layout is useful even before we have API in place for clickable creators, help tags, etc. But worth a discussion.

**Comment by xmatthewx** [comment]
This will mean more when we start to have a broader audience with network site launch, but 42% of new users are on mobile.
 
<img width="515" alt="screen shot 2017-05-10 at 7 37 56 pm" src="https://cloud.githubusercontent.com/assets/53411/25925733/7fea7616-35b8-11e7-9b54-a2ad1d3de592.png">

**Comment by kristinashu** [comment]
Related to https://github.com/mozilla/network-pulse/issues/533
