### ISSUE TITLE
Implement clarify attribution and author 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#528]
Based on design in #486 

**Update to thumbnail overview page:**
- [x] remove the word "by"
- [x] remove date added info

**Post detail view:**
- [x] remove the word "by"
- [x] move the date added to the bottom
- [x] surface post author to users and show it at the bottom after the date
- [ ] bonus: make the author name clickable and show all their posts (similar to tag view e.g. https://www.mozillapulse.org/tags/mozfest)

Comps:
![desktop 2x](https://cloud.githubusercontent.com/assets/1068783/25860935/f0b289b4-3497-11e7-81d7-c05b55bdd2c0.png)

![desktop - detail copy 3 2x](https://cloud.githubusercontent.com/assets/1068783/25860939/f498ecb2-3497-11e7-8882-07e8c888ac25.png)

**Comment by mmmavis** [comment]
It seems like the "published by" meta is not exposed by the API.  @Pomax can you confirm?

**Comment by mmmavis** [comment]
I suggest that we tackle 
> bonus: make the author name clickable and show all their posts (similar to tag view e.g. https://www.mozillapulse.org/tags/mozfest)

in a followup ticket.

**Comment by mmmavis** [comment]
@Pomax @alanmoo 

> It seems like the "published by" meta is not exposed by the API. @Pomax can you confirm?

Since I wanna learn Django and this seems like a good starter ticket to tackle... I'm gonna file a ticket on pulse api and assign it to myself!
