### ISSUE TITLE
Update footer repo link

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#53]
@mmmavis please update the footer link to https://github.com/mozilla/network-pulse instead of Matthews repo

<img width="482" alt="screen shot 2016-07-27 at 8 53 55 am" src="https://cloud.githubusercontent.com/assets/1068783/17182291/d5cdbfe8-53d7-11e6-91f1-ff207f374651.png">

**Comment by xmatthewx** [comment]
The footer I made is terrible and fugly. 🐶

**Comment by kristinashu** [comment]
Aww poor footer. I changed it slightly in the new comps https://redpen.io/p/by8c797c413d39c620
