### ISSUE TITLE
Routes for issues page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#530]
(this is somewhat related to but not blocking https://github.com/mozilla/network-pulse/issues/523#issuecomment-300523022)

When I first implemented routes for the issue pages, I wanted the urls to be more human readable so I didn't use the handy `encodeURIComponent` method to generate the path... instead I went with a mapping object that I created:

from https://github.com/mozilla/network-pulse/blob/master/pages/issue.jsx#L6-L12
```jsx
const issueMapping = {
  "online-privacy-and-security": `Online Privacy & Security`,
  "open-innovation": `Open Innovation`,
  "decentralization": `Decentralization`,
  "web-literacy": `Web Literacy`,
  "digital-inclusion": `Digital Inclusion`
};
```

For example, url for the "Online Privacy & Security" issue page is currently 
`https://www.mozillapulse.org/issues/online-privacy-and-security` instead of `https://www.mozillapulse.org/issues/online%20privacy%20%26%20security` (<- generated using `encodeURIComponent()` method).

Since we are using `encodeURIComponent()` to generate urls for the `/tags/imatag` pages and for consistency reasons I wonder if we should start doing the same for the `issues/imanissue` page? We can redirect the current routes so they don't become 404s.

Thoughts? @xmatthewx @Pomax @alanmoo

**Comment by alanmoo** [comment]
The hyphenated project URLs have value to users of the site. They link to fixed, specific content in an easily readable way. URI encoded strings are definitely not as easy to read (though Firefox makes them readable), but (to me, at least) they're also a hint that it's "generated" content. So I'd say let's keep things the way they are.

**Comment by alanmoo** [comment]
Wait, we're not talking about project URLs here. Links like `https://www.mozillapulse.org/issues/online-privacy-and-security` could go either way; I don't see a particular benefit to changing things though.

**Comment by xmatthewx** [comment]
> They link to fixed, specific content in an easily readable way.

I think this holds true for Issues.

**Comment by alanmoo** [comment]
Mostly; The content varies but it's very useful to have the issue grokable from the URL.

**Comment by xmatthewx** [comment]
And... the Issue URLs are likely to be used as links often.

**Comment by mmmavis** [comment]
Seems like this ticket is closable?

**Comment by xmatthewx** [comment]
totally. closing.
