### ISSUE TITLE
Define categories for expanded Get Involved Help section

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#533]
Based on design of detail view in #521 we will need to:
- [ ] determine which tags/checkboxes we want (e.g. design, code, feedback, test, take action, fundraising...)
- [ ] add check boxes to form
- [ ] reconsider copy

**Comment by xmatthewx** [comment]
Excellent. Let's make our best guess on the categories of help (code, design, test, feedback, take action, funding, ... ? ). Then we should get feedback from a cross-section of people (maybe Abby, Lindsey, Chad, Vanessa, Amira, Michelle, Robert, ...)

**Comment by xmatthewx** [comment]
bumping to next heartbeat. let's collaborate on categories.

**Comment by xmatthewx** [comment]
I've created a [spreadsheet](https://docs.google.com/spreadsheets/d/17nzi7TPFXrog3-lALBrrqCXyuiOiF27hc4vRmh7ELqw/edit#gid=0) with all 'get involved' text on current entries. i've started identifying common categories. several are obvious, a few are fuzzy. i'd welcome input from @kristinashu @taisdesouzalessa @hannahkane on this. 

In the end, we'll probably want 6 or so (12 max) categories a creator can choose. More than that could overwhelm submitters and visitors. So... we don't need to identify everything possible, just the most common.

**Comment by hannahkane** [comment]
Nice. I added some comments/questions to the first sheet, and started a second sheet to offer a possible configuration of suggested categories. Would love to see others' proposals.

**Comment by xmatthewx** [comment]
After dissecting things in the spreadsheet, we're reviewing options in [this doc](https://docs.google.com/document/d/1fRYs5YZMaEgX36eIOLTu-j2THtqlRWry_loZryvL0cI/edit#)

**Comment by xmatthewx** [comment]
We have a solid draft list. A few questions on the bottom three items. 

Any gaps? Ambiguous terms?

 - Code
 - Design
 - Test & feedback
 - Promote
 - Mentor
 - Localize & translate
 - Fundraise
 - Write (content, copywriting, & documentation)
 - Attend (best for global and online events accessible to anyone, especially events that repeat)
 - Plan & organize
   - Too vague a term? It could be opportunity to organize a local event or organize people around a cause. 
 - Take Action
   - Would this be confusing when most entries aren’t campaign-like? Might get applied by people in odd ways, interpreted as Get Involved
   - “Join campaign” better?
   - Endorse & Sign petition - too specific

**Comment by taisdesouzalessa** [comment]
Yay, this is pretty cool, Matthew! I think it covers the majority of cases we had. I just have 2 observations:
1. Localize and translate seem super close to me as terms (I can't differentiate them). Maybe it makes sense to the audience but not to me?
2. In the last bullet point, I think "Join Campaign" works better because "Take Action" is very broad (one could say that "Plan and Organize" is also taking action, or "Promoting", or "Attending").

**Comment by xmatthewx** [comment]
> Localize and translate seem super close to me

I just worry that people [might not be familiar](https://trends.google.com/trends/explore?q=localize,translate) with the word Localize. I didn't know it pre-Mozilla even though I had localized a museum's website! This list is gonna eat up a lot of space regardless.

> I think "Join Campaign" works better

Agreed

**Comment by xmatthewx** [comment]
UX-wise, I'm thinking we could do this as active/inactive buttons, instead of checkboxes, to save space. 

`Attend`  `Code`  `Design`  `Fundraise`  `Localize & translate`  `Mentor`  `Plan & organize`  `Promote`  `Take Action`  `Test & feedback`  `Write & document`

**Comment by hannahkane** [comment]
I think a meaningful difference between "localize" and "translate" is that localize might refer to not a direct translation of content, but actually changing the content itself (e.g. activities, images, cultural references) to make it locally relevant. It might fit better under something that essentially means "create content" (though I don't think the current iteration of "Write" entirely captures it.)

**Comment by kristinashu** [comment]
All sounds good! I also like the idea of using active/inactive buttons for the tags.

**Comment by xmatthewx** [comment]
@taisdesouzalessa suggests `Create content` instead of `Write`. I believe @hannahkane agrees. And, since that's a creative task, she also suggests we keep `Document` separate. Makes sense to me. 

I wish Documentation was a verb. Is `Create documentation` better than `Document`?

**Comment by taisdesouzalessa** [comment]
I think that we should either use "Document" or "Write documentation" (not sure "Write documentation" is the best term though...any other ideas?). The reason being we are already using "Create" in "Create Content" and having another label starting with the same verb can work against scannability.

**Comment by xmatthewx** [comment]
`Attend`  `Create content` `Code`  `Design`  `Fundraise`  `Localize & translate`  `Mentor`  `Plan & organize`  `Promote`  `Take Action`  `Test & feedback`  `Write documentation`

**Comment by acabunoc** [comment]
@xmatthewx this list looks good to me!

This might fit under 'Test & feedback' but have you considered 'Discuss'? A lot of times people just want to talk about ideas that still kind of vague.

**Comment by xmatthewx** [comment]
Interesting. It's similar to feedback but maybe we need something like `Join community`.

**Comment by xmatthewx** [comment]
@amirad @chadsansing @omnignorant – in Pulse, we plan to give authors a checklist of categories of Help to go along with the Get Involved text and link. That way, people can more easily discover code opportunities etc. We teamed up to write the list below, based on what people have submitted so far. 

I thought you three and @acabunoc would have good insight on whether this list aligns with what you've seen in your program work. Would you add any categories to this list? Any confusing terms below? 

`Attend`  `Create content` `Code`  `Design`  `Fundraise`  `Join community` `Localize & translate`  `Mentor`  `Plan & organize`  `Promote`  `Take Action`  `Test & feedback`  `Write documentation`

Quick impressions are fine. No need to repeat our effort. (Note: we aim to educate users on opportunities, not create the most rationale taxonomy.)

<img width="332" alt="screen shot 2017-07-07 at 1 52 42 pm" src="https://user-images.githubusercontent.com/53411/27970114-9a36c098-631b-11e7-9ec7-886e19e828fc.png">

**Comment by chadsansing** [comment]
@xmatthewx, first response is to consider things like, "help to design," and "help to improve."

I will chime back in if other ideas arrive :)

**Comment by xmatthewx** [comment]
thanks. closing. tracking form design for implementation here: #601
