### ISSUE TITLE
update the pulse api URLs

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#535]
tracked as https://github.com/mozilla/network-api/issues/197 on the network-api side.

Going forward, the pulse api will be namespaced to `.../api/pulse/...` so routes that are currently `/nonce` will become `/api/pulse/nonce` etc.

**Comment by Pomax** [comment]
looks like the client hasn't switched quite yet. Once it does, we'll track removing the old routes over in https://github.com/mozilla/network-pulse-api/issues/144

**Comment by xmatthewx** [comment]
can this ticket be closed? or is it still relevant?

**Comment by Pomax** [comment]
this can be closed, the staging pulse client now uses `/api/pulse`
