### ISSUE TITLE
Implement Help categories on Frontend

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#537]
Based on design in https://github.com/mozilla/network-pulse/issues/521 relies on form updates in #533 and post detail page layout https://github.com/mozilla/network-pulse/issues/520

Content includes:
- "Get Involved" title
- all "Get Involved" body copy
- a link URL
- tags

https://redpen.io/p/of380006b3156e2c51
![desktop details latest 2x](https://user-images.githubusercontent.com/1068783/28633006-2f798918-71e7-11e7-900b-7de98caf519e.png)

**Comment by xmatthewx** [comment]
Tracking updates to form here: #601

**Comment by xmatthewx** [comment]
mvp is tags with current layout

**Comment by mmmavis** [comment]
@xmatthewx @kristinashu where does the help label take you? to a page on `/help-types/typeofhelp` ?

**Comment by kristinashu** [comment]
I'd say either `/getinvolved/typeofhelp` or `/help/typeofhelp`?

**Comment by xmatthewx** [comment]
Yep, I think `mozillapulse.org/help/code` is simple, clear, and easy to remember.

**Comment by mmmavis** [comment]
Cool, I just created a ticket on API repo for the API to allow filtering entries by help type: https://github.com/mozilla/network-pulse-api/issues/165

**Comment by xmatthewx** [comment]
@mmmavis - is this ready for review on staging?

**Comment by mmmavis** [comment]
> @mmmavis - is this ready for review on staging?

Not yet. PR is still in review.
