### ISSUE TITLE
Build moderation front-end

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#541]
Moderating many projects would benefit from a frontend view.

Why not just use Django? 
 - it's unfamiliar. and we'll want many moderators with minimal training required
 - Django doesn't currently provide a way to browse by moderation state
 - Django doesn't currently make it easy to read a project. See below. 

<img width="823" alt="screen shot 2017-05-17 at 1 12 20 pm" src="https://cloud.githubusercontent.com/assets/53411/26166738/87560d58-3b02-11e7-867e-83cb258fb7d9.png">

### Frontend specs

 - List view MVP
   - show non-approved projects at /pending/ or similar
   - indicate state on each card (pending, in-review, declined)
 - Detail view MVP
   - a drop-down to change moderation state (see #522)

### Nice to have (not likely for first build) 
 - List view
   - way to filter state (pending, in-review)
   - a way to filter by tag or search (e.g. see all global sprint)

Any other requirements?
@hannahkane @kristinashu

**Comment by hannahkane** [comment]
Questions, not requirements:

 * Would /pending/ show just pending projects or also in-review and declined projects? If all non-approved states, it would be good to be able to filter on state.
 * For "in-review", I wonder if it will be important to know which staff person is working on it. Maybe not.
 * If project submissions come in at a slow trickle, it may become important to build in some notifications, whether that's a visual indicator on the homepage (for auth'ed moderators) or even email notifications. Sorry, I probably just made @pomax headdesk.

**Comment by xmatthewx** [comment]
Good questions. 

 - You made me realize we should indicate state on each card in list view. A way to switch view between states would be good, maybe not essential, but probably not a big lift. (updating list in orig comment)
 - Eventually, we might want to assign or claim in-review, but let's worry about that after we get the basics landed. 
 - If moderators get a menu item, we could include a count of pending. We can also worry about this after we get basics landed.

**Comment by xmatthewx** [comment]
Quick mockups

### List view 

<img width="1194" alt="screen shot 2017-05-19 at 11 15 41 am" src="https://cloud.githubusercontent.com/assets/53411/26254549/f6ed3b22-3c84-11e7-9aa2-d28e36066396.png">

### Detail view

<img width="775" alt="screen shot 2017-05-19 at 11 18 40 am" src="https://cloud.githubusercontent.com/assets/53411/26254550/f6ef8aee-3c84-11e7-9ed0-aff9b1def62a.png">

<img width="779" alt="screen shot 2017-05-19 at 11 20 26 am" src="https://cloud.githubusercontent.com/assets/53411/26254618/31e49568-3c85-11e7-9ce4-70698d851920.png">

**Comment by xmatthewx** [comment]
to file: 
 - [ ] We need user staff status from API (estimate: 1)
 - [ ] API endpoints moderation state (estimate: 3)

**Comment by xmatthewx** [comment]
@kristinashu - feel free to design UI here. I did quick mockups assuming you're busy with Internet Health things. No strong opinions here and I'm sure you'll could make this much nicer.

**Comment by mmmavis** [comment]
I will create a feature branch and start building UIs first. But we still need to decide whom we are showing the moderation controls to. To all staff? To people who have admin access to Django? Or?

/cc @xmatthewx @Pomax @alanmoo

**Comment by alanmoo** [comment]
I'd say anyone with a MoFo email address. If they can post, they should be able to approve too. (That doesn't apply to non-staff, of course)

**Comment by xmatthewx** [comment]
Aha. I was thinking this UI would only be visible at a route like /moderate/pending. But... I could see value in having the UI appear everyone. In that case, I should consider it a bit more closely.

**Comment by alanmoo** [comment]
I believe that's pretty much it, with the addition of the link to that route being visible in the top nav for moderation-capable users.

**Comment by mmmavis** [comment]
+1 Now I think about it I think we should have new routes for moderation purposes. Otherwise the entries displayed on each page are gonna be different for public(only **approved** entries will be shown) and for staff/admins(**all** submitted entries). This can get quite confusing to staff especially - for example, I ,as staff, shared a link like https://www.mozillapulse.org/search?keyword=web+literacy to my community. I saw 100 entries there but I was not aware none of those entries was approved. This means that link I shared will lead people to a page that has no entries listed.

I see that now each entry has [4 possible states](https://github.com/mozilla/network-pulse-api/blob/7c489e888a86b10a842fe3fee211c52558636b2b/pulseapi/entries/migrations/0008_moderationstate_defaults.py#L14-L17) - Pending, In Review, Approved, and Declined. Are we adding 4 new routes to Pulse front end, one for each state (e.g., `/pending` will show all pending entries)? 

Another question - I totally understand we want to avoid leaving all the moderation work to just a few people. But having 90+ MoFo staff all as moderators sounds a bit too much to me. Is the idea so that MoFo staff can self approve their own entries? If we do wanna have 90+ moderators I think it's important to indicate which staff is working on which "in-review" entry (just like what @hannahkane has suggested) so that "in-review" entries don't slip through the cracks.

**Comment by alanmoo** [comment]
I know we discussed some of this last sprint while building out the API, @Pomax can you clarify what the endpoints are and what you had in mind for client-side implementation?

**Comment by xmatthewx** [comment]
I this we'll want about a half dozen moderators. Not 90. Our plan for user roles includes this, but we shouldn't wait for that. We can use routes to keep things hidden. I'm not worried about rogue staff messing with things. We can use slack and the internal notes field to manage "in review".

**Comment by xmatthewx** [comment]
It seems we agree – let's build moderation as separate from public views ... as long as you can reuse components for streamlined maintenance. 

 1. Top of list view can have simple nav/filter to show only one state at a time, so we can keep the moderation-state label off of cards in list view if that helps simplify components. 
 2. We could have a single route for /moderation/ and use query strings to filter state. Or, we could have multiple routes. Whatever seems easier and little brittle to you.

Do you want to set up a call to discuss @mmmavis? Might be quicker and easier.

**Comment by mmmavis** [comment]
@xmatthewx @Pomax sure we can chat after the daily stand today if that works. /cc @alanmoo 

I think the simpler way to do this is to
1. have one route `/moderation`
2. have controls on that page for moderators to filter entries by their approval state
3. when a moderator changes an entry's state, we simply update the state of that entry and nothing else (i.e., don't move it out from the current filtered view as it can get complicated and requires more time to implement)

Endpoint related pieces:
1. a way to get a entry's approval state (☑️ I think this is done already)
2. a way to determine whether the current logged in user has moderation rights
3. (probably not needed, a way to get a filtered list of entries by their approval states)

**Comment by xmatthewx** [comment]
Agreed on your first list of 1,2,3. 

Endpoint things:
 1. cool
 2. we can use is_staff for now
 3. if I understand this correctly, and we don't use a param for filtered list, we should probably return 100+ entries. Approved will eat up that count, and it'll be hard to find an old Declined. You'll hit more many times.

**Comment by xmatthewx** [comment]
No need to match my styles below. After you do a first pass, share a screenshot and we can clean up as needed. Only a few people will see this. 

### List view 

We can ignore search for now, unless it's easy. if not, follow up with that later.

<img width="537" alt="screen shot 2017-06-08 at 1 41 06 pm" src="https://user-images.githubusercontent.com/53411/26942462-2660991e-4c50-11e7-9b10-9a22bc84e508.png">

### Detail view

Match states to backend. Use "Pending" not needs moderation. 

<img width="775" alt="screen shot 2017-05-19 at 11 18 40 am" src="https://cloud.githubusercontent.com/assets/53411/26254550/f6ef8aee-3c84-11e7-9ed0-aff9b1def62a.png">

<img width="779" alt="screen shot 2017-05-19 at 11 20 26 am" src="https://cloud.githubusercontent.com/assets/53411/26254618/31e49568-3c85-11e7-9ce4-70698d851920.png">

**Comment by xmatthewx** [comment]
Updated Moderation UI on list view and detail view above. This isn't going to win any awards – would welcome any input from @kristinashu.

**Comment by xmatthewx** [comment]
Updated screenshot above didn't save for some reason. Trying again.

**Comment by kristinashu** [comment]
Dropdowns work for me but the additional Search seems over complicated.

**Comment by alanmoo** [comment]
The search makes sense to me if you're trying to find a specific item to feature/unfeature and the moderation functionality is showing up only at a specific route. Even with Matthew's design suggestion, it's a little difficult to spot an entry and then feature it, as you'd have to relocate the entry in the "moderate" view, which is only slightly easier than jumping into the admin site.

If we went the "moderation per item always shows up on every card for moderators" approach, then the search might be unnecessary.

**Comment by kristinashu** [comment]
Oh ok, I thought those dropdowns were always visible to moderators (haven't been following too closely).

**Comment by mmmavis** [comment]
@xmatthewx 

Question: If the list view for moderation is on `/moderation`  what the route should be for detail view (on moderation mode)?

**Comment by xmatthewx** [comment]
@mmmavis – Totally up to you. We could use /moderation/123 or a parameter on /moderation?id=123. 

We could also show all the entry content and moderation UI on the list view. Not necessary, but if it's simpler for you overall, that would be worth discussing.

**Comment by mmmavis** [comment]
> We could also show all the entry content and moderation UI on the list view. Not necessary, but if it's simpler for you overall, that would be worth discussing.

@xmatthewx I like this idea and I think it'll save moderators' time from navigating between views. I *think* this is easier to implement than introducing another view so I'm gonna go with the direction until I hit obstacles in the way.

**Comment by alanmoo** [comment]
I think this is the way to go too, now that there's a `moderator` key in the user info file that the API returns. The moderation can be baked into the normal components/views and only show up for a few moderators, as opposed to all staff. We should still have a `/moderation?state=` card view though, so moderators can find items that need approval.

**Comment by xmatthewx** [comment]
Woohoo! Thanks @mmmavis. Thanks all. This looks great.  🥇
