### ISSUE TITLE
Correct Sign In messages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#547]
Now that we've opened things to non-staff with google login, we should tweak our help text.

 - [ ] Remove "Are you Mozilla Staff?" from Favs view
 - [ ] Remove "Please note, only Mozilla..." from "Add" view

"Add" view says sign in, which can be slightly confusing if I don't already have an account. Seems like "Sign in with Google" is the most clear and accurate button label. Do you agree @kristinashu? 

 - [ ] Change button to "Sign in with Google"

**Comment by kristinashu** [comment]
Yes, sounds good!

**Comment by alanmoo** [comment]
I updated some of the wording and it's on staging, but since we've got actual directive another PR would be useful

**Comment by xmatthewx** [comment]
@hannahkane can you check in on this tomorrow?

**Comment by alanmoo** [comment]
Closed by #553
