### ISSUE TITLE
Add redirect for admin

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#548]
Add a redirect from `mozillapulse.org/admin/` to `api.mozillapulse.org/admin/` to make life just a little easier.

**Comment by Sudip7** [comment]
@xmatthewx , could you be little more descriptive

**Comment by xmatthewx** [comment]
Admin her manage users must remember and go to this URL:  `api.mozillapulse.org/admin/`. I would like to setup a simple redirect from `mozillapulse.org/admin/`, because it's much easier to remember. 

@mmmavis can share how these are setup. I'm unsure if it's handled on the frontend or server side.

**Comment by mmmavis** [comment]
@Pomax @alanmoo how are these usually done? We can add a `onEnter` handler (to the to-be-add `<Route path="admin" ... />`) that redirects /admin to `api.mozillapulse.org/admin/` or we can ask DevOps's help to configure a webpage redirect. Suggestions?

**Comment by alanmoo** [comment]
@cadecairos does it make sense to do the same thing you've been doing on the network site for consistency?

**Comment by cadecairos** [comment]
@alanmoo Are you proposing we have the Django admin site accessible from `mozillapulse.org/admin` rather than worry about a redirect?

Aren't we consolidating the two backends into one project? If so, then I'd prefer to hold until that's completed before messing around with proxying the existing admin site through Cloudfront.

**Comment by alanmoo** [comment]
Good point. Would a temporary redirect on the front end be safe?

**Comment by xmatthewx** [comment]
I believe this is now unblocked. Backends are now joined. True @alanmoo?

**Comment by alanmoo** [comment]
Not yet, data is still going in to api.mozillapulse.org. Once the data's been migrated, we can point `mozillapulse.org/admin` at `network.mofoprod.net/admin/pulse` (or whatever that second path ends up being)

**Comment by Pomax** [comment]
given the changes that have been happening around pulse migrations, and the decision not to migrate for now, I would recommend we put up a simple redirect such that people who hit up `mozillapulse.org/admin` are sent over, with a URL change, to `api.mozillapulse.org/admin` instead.

**Comment by xmatthewx** [comment]
tracking in #938
