### ISSUE TITLE
Explore a timeline or current events like feed

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#55]
Follow on @xmatthewx redpen comment: After we settle on MVP details, I’d love to briefly explore what a timeline could be like. As a separate view … or maybe there are just a few cards between the items to call out big moments (Mozfest, Net neutrality vote, etc.).

**Comment by xmatthewx** [comment]
one shape this could take: http://mollywhite.net/wikimedia-timeline/

**Comment by xmatthewx** [comment]
another mofo specific thing: https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1aypWtbAW4Z8v_PfHPx9JuJL4rJxBoz49Ry0mnFIHSxM&font=Default&lang=en&initial_zoom=2&height=650

**Comment by mmmavis** [comment]
@kristinashu is this v1 specific? If so that's close it 😉

**Comment by kristinashu** [comment]
We should keep this, it's a potential feature in the future.

**Comment by kristinashu** [comment]
I think now we can close this, @xmatthewx?

**Comment by xmatthewx** [comment]
Issue moved to [mozilla/network #601](https://github.com/mozilla/network/issues/601) via [**ZenHub**](https://www.zenhub.com/)
