### ISSUE TITLE
Change main page hero copy

### ISSUE THREAD

**Issue by jessevondoom** [mozilla/network-pulse#550]
**Issue**
We introduce the phrase “healthy internet” on the main page but don’t define Internet health or tie back to the Internet Health Report. Defining the network in terms of Internet health is a main goal of the organization in 2017 so we need to make more of an explicit connection going forward. 

**Suggested solution**
This will be a central theme as we design for the next major iteration of the site but for now I think we can make a lot of impact with a pretty minor copy change in the Network site main page hero:

_Current:_
“We are a global network keeping the internet open and accessible to all.”

_Change to:_
“The Internet is an ecosystem billions depend on. [https://internethealthreport.org/v01/about/](It’s health influences everyone it touches.) We are a global network keeping the Internet open, healthy, and accessible to all.”

**Comment by jessevondoom** [comment]
Borrowed the new copy (edited down) from the Internet Health Report site about page for consistency.

**Comment by hannahkane** [comment]
Re-filed here: https://github.com/mozilla/network/issues/449
