### ISSUE TITLE
"member preview" panel and survey preamble tweaks

### ISSUE THREAD

**Issue by jessevondoom** [mozilla/network-pulse#551]
**Issue**
There’s concern that we need to do more to communicate the iterative/collaborative nature of the Network site. Right now we’re framing that as the site being “in progress” or a preview. We’ll move away from that framing as the network starts to feel more ownership of the site, but for now there are some ways we can make the the in-progress/feedback process more obvious.

**Suggested solution**
There’s a three-step fix that hopefully doesn’t require a ton of work:

1. The feedback panel on the top of the site (“Welcome to our member preview. We look forward to your feedback.”) is fairly subtle. If we make it stand out more we hopefully remind people that this is a collaborative building process and invite more feedback. 
2. Can we change the text in the feedback panel to: “Welcome to our member preview. It’s a work in progress and we invite your feedback.”
3. Lastly, let’s reiterate that message before the survey form: “Mozilla is a part of a movement to keep the Internet healthy and wants to help it grow. This site is part of our effort to do that. It’s a work in progress, and your feedback makes a real difference. We look forward to hearing your perspective.”

**Comment by hannahkane** [comment]
Re-filed here: https://github.com/MozillaFoundation/Network/issues/19

**Comment by hannahkane** [comment]
lol, which is also the wrong place. Here we go: https://github.com/mozilla/network/issues/448

**Comment by jessevondoom** [comment]
We should really post this one to every repo, just to be safe.
