### ISSUE TITLE
Ensure that there is a page for people to see when JS is blocked

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#555]
Plenty of people run privacy addons like NoScript which prevent JS from running until cleared. Running mozillapulse in this setting gives an initial landing page that looks like this:

![screenshot 60](https://cloud.githubusercontent.com/assets/177243/26376328/fcad13e0-3fc0-11e7-8e6b-bdae6bf116dc.png)

That is not okay, we need to have something there that tells users why they have to turn on JS just to use our site (part of server-generated pages is that there is a page even when JS is disabled, which the react bundle then hooks back into, I'm a bit surprised that functionality is not working...)

**Comment by jamilasnell** [comment]
It is a personal pet peeve of Pomax's and YET we are closing this until we decide to work on pulse again
