### ISSUE TITLE
Need to fix image size for a Global Sprint entry

### ISSUE THREAD

**Issue by Melechuga** [mozilla/network-pulse#557]
The image size for entry #308 (https://www.mozillapulse.org/entry/308) is 839 x 630 but for some reason it doesn't capture the full image. Can someone please fix it? Thanks!

Original image:
![global sprint image](https://cloud.githubusercontent.com/assets/5815317/26468128/2fb928d4-414a-11e7-8148-3c402f3c08cc.jpg)

**Comment by alanmoo** [comment]
This is because images get cropped in the styles so they take up the full width of the entry. Easiest solution is to use a wider image, closer to the 1200x630 suggested by the submission form.

**Comment by xmatthewx** [comment]
Done. Sorry for the delay on this one.
