### ISSUE TITLE
Form validation UX needs improvement

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#558]
From @Melechuga:

> “Description” [field had more than 600 characters]. The little red warning letters pop up, but when I’m at the bottom of the page clicking “submit” I can’t see the warning.

**Comment by kristinashu** [comment]
I believe design is done, just waiting for implementation in https://github.com/mozilla/network-pulse/issues/493 and https://github.com/mozilla/network-pulse/issues/441

**Comment by alanmoo** [comment]
Ah, great.
