### ISSUE TITLE
Analytics seem to be down

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#559]
There are 0 sessions since last Wednesday. Did we make any changes that could have impacted this? cc @mmmavis @alanmoo @cadecairos

**Comment by cadecairos** [comment]
Shoot - This was my bad. I tweaked the view with a filter for  "mozillapulse.org" but the app is served from "www.mozillapulse.org"

I have corrected the filter.

**Comment by cadecairos** [comment]
I've confirmed data is now showing on the view.

**Comment by xmatthewx** [comment]
fixed. closing.
