### ISSUE TITLE
Add category & tags to detail view

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#56]
Mocked this up but will hold off on adding to MVP.

![mobile - featured with category tag 2x](https://cloud.githubusercontent.com/assets/1068783/17191619/8b2fdd7c-53ff-11e6-94e0-d686de2403d5.png)

**Comment by mmmavis** [comment]
@kristinashu is this v1 specific? If so let's close it 😉

**Comment by kristinashu** [comment]
Lets keep this, I still think it's something we should eventually add in.

**Comment by xmatthewx** [comment]
I think tags can unlock a lot of potential and should be the next feature we consider adding. 

Let's update this design based on revised design. Tags & issues should probably appear just on the detail view.

**Comment by xmatthewx** [comment]
depends on #444

**Comment by mmmavis** [comment]
Unblocked. #444 is live on prod now: e.g., https://www.mozillapulse.org/tags/mozfest 🎉

**Comment by kristinashu** [comment]
Continuing in https://github.com/mozilla/network-pulse/issues/500
