### ISSUE TITLE
New tags aren't added to an entry

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#562]
Noticed this on staging, haven't confirmed on production but not sure why it would differ:

1. Create a new entry (entry name, link) and fill in an autocompleted tag.
2. After the tag appears in its grey box, type in something else, which should become a new tag for the entry. 
3. Click save
4. Notice that the text entered after the existing tag isn't attached to the entry. It disappeared.

**Comment by mmmavis** [comment]
I can't reproduce this. My "mavistesting" tag shows up fine on staging.

<img width="1133" alt="screen shot 2017-06-01 at 3 11 11 pm" src="https://cloud.githubusercontent.com/assets/2896608/26703038/99da8446-46dc-11e7-9dcd-1edbe9797f1a.png">

**Comment by alanmoo** [comment]
Were you pressing "enter" after typing in the new tag? If you do that it works properly, but it was definitely not obvious to me.

**Comment by mmmavis** [comment]
@alanmoo right, I did press the "enter" key. To me using "enter" as delimiter has been pretty intuitive but as you said it might not be obvious to other people.
