### ISSUE TITLE
Form: identify if submitter is creator

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#564]
Let's add a field to the form for submitters to identify whether they own the thing or not.

**Comment by Sudip7** [comment]
@xmatthewx, please provide some more description and sample template.

**Comment by xmatthewx** [comment]
@Sudip7 - This ticket requires design and planning first. When it's ready, I will label it as `help wanted`. Thanks!

**Comment by xmatthewx** [comment]
The simple solution would be to add an checkbox.

<img width="377" alt="screen shot 2017-06-07 at 3 00 08 pm" src="https://user-images.githubusercontent.com/53411/26896231-0ab1c7ce-4b92-11e7-975c-923d767f696e.png">

Linking user account to the creator id sounds hard. Should we land a simpler mvp version first? Or should we dig in? @alanmoo

**Comment by alanmoo** [comment]
The creator model on the back end already links to a user model, but none of the creators that have been added yet actually make that connection. That is to say the creator data looks something like this for all creators currently:
```
{
  name: "Someone's Name"
  user: null
}
```

I'm not sure there's a clear path to linking new creators to existing users yet, but for the submitter something like that checkbox could work, as we can have the front end pass the userdata back to the server as a creator. This UI does leave open the question of "where in the list of creators does this person show up?" (See also: #443).

**Comment by xmatthewx** [comment]
Oh right, one of you anticipated this need.  

Checkbox can work as you suggest as a first step. 

Agreed that there won't be an easy way to merge "confirmed" creators with string-only creators. It's a fun puzzle that gets silly complicated fast. Let's table that for now.

We can add self as a disabled input. So people don't also manually enter their name. 

<img width="389" alt="screen shot 2017-06-08 at 11 49 47 am" src="https://user-images.githubusercontent.com/53411/26937908-b8749ad6-4c40-11e7-8a35-1f5837ad300e.png">

**Comment by xmatthewx** [comment]
cc @kristinashu for UX/UI input

**Comment by kristinashu** [comment]
That looks great!

**Comment by xmatthewx** [comment]
Design is good. Implementation continues in #573

**Comment by xmatthewx** [comment]
@kristinashu - do we have a checkbox style for pulse? something with decent size for mobile? could also be a toggle on/off.

**Comment by kristinashu** [comment]
Only check boxes we use are the ones for issues (in the form). They are just the default ones, which are small but far enough apart from each other that it seems fine.
