### ISSUE TITLE
Add site search to GA

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#567]
If we turn on Site Search and identify "keyword" as our query parameter, we'll get nice reports on user searches. 

@cadecairos can I have more privileges in Analytics to manage this stuff? 

In GA > Admin > View > View settings > Site search tracking

"keyword" is our query parameter. Note: don't include equal sign ~~"keyword="~~

https://support.google.com/analytics/answer/1012264

**Comment by cadecairos** [comment]
@xmatthewx I granted you edit permissions for the production view of the mozillapulse.org GA property

**Comment by xmatthewx** [comment]
@cadecairos – I don't seem to have access to Production View Settings. Can I have more global admin access to GA? I can help manage staff access and I promise I want abuse the numbers 😉.

**Comment by cadecairos** [comment]
@xmatthewx done!

**Comment by xmatthewx** [comment]
rad. thanks @cadecairos. i updated the query, waiting to see if it actually works.

**Comment by xmatthewx** [comment]
There were 86 searches on Friday. Feature is live and well.
