### ISSUE TITLE
remove the "delimit on comma" hack

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#568]
We introduced a workaround for `react-tags` in https://github.com/mozilla/network-pulse/pull/565 that we should be removing again as early as possible, contingent on https://github.com/i-like-robots/react-tags/pull/80 landing.

Once it has, we can update our  version of `react-tags` and use the new `delimiters` property to pass in the keyCode for comma (`delimiters={[13, 44]}`)

**Comment by Pomax** [comment]
The PR for react-tag has landed, so we should just able to revert to using `<ReactTag ... delimiters={[8, 13, 44]} .../>` so that in additiona to tab and entery, "comma" also turns strings into tags.

**Comment by Pomax** [comment]
A new version was released so we should be able to switch over to the new version and take out our "hack".

**Comment by mmmavis** [comment]
I'm afraid the "new version" hasn't been published yet. 

https://www.npmjs.com/package/react-tag-autocomplete
<img width="357" alt="screen shot 2017-06-20 at 11 24 37 am" src="https://user-images.githubusercontent.com/2896608/27349102-16663f6e-55ab-11e7-98c8-1696e65b7a0c.png">

**Comment by mmmavis** [comment]
nvm I my previous comment that back 😉 PR on the way!
