### ISSUE TITLE
Add GA event to form's submit button

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#569]
- when submit button is clicked
- how many times the submit button is clicked before the entry is successfully submitted
  - this will help us understand UX wise if we need to improve how we present form errors

/cc @xmatthewx @Pomax

**Comment by Pomax** [comment]
this feels right. We could also do the "counting" using GA's reporting but generating an event that says "submit button clicked: Xth time on this page" will be less work to get immediate insight.

**Comment by xmatthewx** [comment]
👍 appending the "label" with "2nd try" etc will give us a ton of easy to see info.

**Comment by mmmavis** [comment]
@xmatthewx any suggestion on what GA `category`, `action`, and `label` we should be using here?
