### ISSUE TITLE
Implement optional image

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#57]
Users should be able to add an optional image either in the form or in the spreadsheet.

See example in comps https://redpen.io/p/by8c797c413d39c620

We might need to add some image guidelines (ex file size not too big and too small, dimensions...) or we might need to manually crop and save for web.

@mmmavis is this doable using google forms and spreadsheets?

**Comment by kristinashu** [comment]
Hmmm ok thanks @mmmavis. We might need to hold off on this then since we aren't really planning to add a detail view (only for shared links - like how it is now) and I think images are most useful in the thumbnail view.

What if I added images manually to a few 'special' projects? Could github host them?

**Comment by mmmavis** [comment]
> What if I added images manually to a few 'special' projects? Could github host them?

yes if we add them to this repo

**Comment by kristinashu** [comment]
Awesome! Lets to that for now as a quick fix. This way we can test if having an image increases click rates or not.

**Comment by mmmavis** [comment]
🎉

**Comment by xmatthewx** [comment]
:+1: to adding images to a few special projects. (Let's avoid the option/instructions/friction in the form.) 

At some point (not now), we'll want to include a `Load more` button, and display projects incrementally. Not necessary at this point, but later could help with loading and bandwidth issues.
