### ISSUE TITLE
Sort Entries in Admin in reverse chronological

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#570]
We had this before. Maybe got lost in migration. 

Goal: make it easy for admins to find recent entries for featuring and corrections. 

Assign for notification purposes. Feel free to un-assign yourself.

**Comment by alanmoo** [comment]
The code for this is about to land as part of the network-api integration.

**Comment by Pomax** [comment]
that said we can also land that `ordering = ( ... )` line independently on the pulse-api side

**Comment by Pomax** [comment]
PR open as https://github.com/mozilla/network-pulse-api/issues/134
