### ISSUE TITLE
Add Pulse Admin filter for featured projects 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#571]
Pulse admin now has a filter for moderation state. Would be great to add similar for Featured. Not critical, but useful if it's easy.

**Comment by Sudip7** [comment]
@xmatthewsx : would u please provide some ideas on how the filter works for admin?

**Comment by xmatthewx** [comment]
While viewing Entries on the backend, the right side box allows us to filter by `Moderation state`. It would be great to add a similar box to show entries that have `Featured` set as true. 

@pomax could confirm, but I believe [Line 59 in admin.py](https://github.com/mozilla/network-pulse-api/blob/7c489e888a86b10a842fe3fee211c52558636b2b/pulseapi/entries/admin.py#L59) is where the magic happens.

<img width="962" alt="screen shot 2017-06-09 at 1 39 26 pm" src="https://user-images.githubusercontent.com/53411/26987311-1ca36108-4d19-11e7-8c1d-b73fda6546e7.png">

**Comment by Pomax** [comment]
you are correct, @xmatthewx

**Comment by alanmoo** [comment]
@arush0311

**Comment by alanmoo** [comment]
@Sudip7 were you still looking to help out with this? If not, @arush0311 do you want to take it?

**Comment by arush0311** [comment]
I would love to!
