### ISSUE TITLE
Add API endpoint to toggle Featured state

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#572]
@Pomax – 
 - Feel free to add details. or file this in a more sensible repo.
 - I'll put in this milestone's backlog as a stretch goal. is that okay?
 - Wanna estimate with @alanmoo?

**Comment by Pomax** [comment]
- can do
- yep, sounds good
- if we tie it to is_staff, on the back end this is very little work, on the client it would need some UI design to add the toggle for people who should be able to toggle this, without being able to accidentally feature something.

**Comment by alanmoo** [comment]
Agreed, this is more front-end than back-end. I assume it would only show up when viewing an entry from the `/moderate/` route (or whatever we use client-side), just like the approval state?

**Comment by xmatthewx** [comment]
Yes. That was the idea. But worth discussing a bit more. cc @mmmavis 

I see 3 options: 

A: Moderation UI only appears in `/moderation/`, `/moderation?state=pending`, `/moderation?entry=234`

B: Moderation UI appears in `/moderation/` and on standard detail view for all entries `/entry/345/`

C: Moderation UI only appears in `/moderation/`. This view displays full cards with all details, so there's no need to navigate into detail view.

**Comment by alanmoo** [comment]
@arush0311 this may be something you can work on, let's discuss and clarify the needs

**Comment by mmmavis** [comment]
Update: We went with option C mentioned in https://github.com/mozilla/network-pulse/issues/572#issuecomment-307244475
> C: Moderation & Feature UI only appears in /moderation/. This view displays full cards with all details, so there's no need to navigate into detail view.

**Comment by xmatthewx** [comment]
Yes... @arush0311 this would be very useful. It would really help our moderators easily keep the featured tab fresh ... and that also feeds the network site features as well...

**Comment by arush0311** [comment]
just some questions regarding 
-

**Comment by arush0311** [comment]
Just some question regarding @Pomax 's comment
> if we tie it to is_staff, on the back end this is very little work, on the client it would need some UI design to add the toggle for people who should be able to toggle this, without being able to accidentally feature something.
If we create a toggle we can accidently feature something cant we? Am i missing something?

**Comment by xmatthewx** [comment]
Thanks @arush0311 – for this ticket, you can just worry about the api endpoint. We'll do some frontend design to figure out how to prevent accidents. I'll go file that ticket now...
