### ISSUE TITLE
Implement 'Submitter is Creator' feature 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#573]
When someone adds an entry to Pulse, they are likely a creator. Let's allow people to identify this fact and link their user to creator. Model already allows for this relationship.

Requires Form(form + react-formbuilder) and API work

Design in #564

**Comment by xmatthewx** [comment]
If user submitting a new entry is also a creator, they check a box. We pull their name from user account. On submission we add creator and link to user. 

<img width="389" alt="screen shot 2017-06-08 at 11 49 47 am" src="https://user-images.githubusercontent.com/53411/26937908-b8749ad6-4c40-11e7-8a35-1f5837ad300e.png">

**Comment by hannahkane** [comment]
Might be a UX change - e.g. @Pomax's suggestion to use a button instead of a checkbox
Will need to modify library
Form builder needs to know the username

estimate is for front end and back end

**Comment by xmatthewx** [comment]
Brought design question back to the design ticket.

**Comment by Pomax** [comment]
This is implemented on the API side through https://github.com/mozilla/network-pulse-api/pull/222, client updating should no longer be blocked.

**Comment by Pomax** [comment]
both the API and client sides of this has landed, as per the "revised let's just do this for now" spec: do we want to keep this open, or do we want to file new issues (more granular) for the styling refinement?

**Comment by xmatthewx** [comment]
rad! I'll file a follow up for refinement. that can sit in the backlog for now.
