### ISSUE TITLE
Clean up Analytics Event labels

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#574]
@mmmavis pointed out some room for improvement in how we categorize and label Events in Pulse.  

Let's step back and revise.

**Comment by xmatthewx** [comment]
@vojtechmzl - can you take a quick peek at [proposed](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=1060389854) Event labels for Pulse (second tab)?

I have to confess, I'm still not totally confident on how to best use Categories, or how verbose to be with Actions and Labels.

**Comment by mmmavis** [comment]
I also have question about the weird lettercasing/capitalization that GA applies to `label` etc. Is there a way to turn that off?

**Comment by vojtechmzl** [comment]
Hey @xmatthewx , sorry I didn't get to this earlier.

I think the proposed syntax makes sense. If we are particularly interested in the user journey on /add, then I would suggest adding an additional event for when someone successfully logs in. That would enable us to track attrition between the following steps:
User clicks/lands on /add -> User successfully logs in -> User encounters issues with the form -> User successfully submits the form

@mmmavis I am not sure what's causing the capitailzation of the navlink labels in GA. At least there seems to be consistency, so it won't impact the analysis. 

Let me know how I can support.

**Comment by mmmavis** [comment]
@xmatthewx we have "sign in" link on both the `/add` page and `/favs` page. Can you add these 2 to the spreadsheet and their corresponding GA category/action/label? Thanks!

**Comment by xmatthewx** [comment]
Thanks @mmmavis. Added comments. Let me know if you want to discuss.

**Comment by xmatthewx** [comment]
This is working great!! Very interesting info. Two things. 

 1. there's a typo (this splits Category tracking): 
   - correct: Bro**ws**e (about learn more) 
   - typo: Bro**sw**e (view more tap)
 2. Nav Link Category and Clicked Action are legacy (not a problem. we can file and remove later)

![image](https://user-images.githubusercontent.com/53411/31395169-1dcf5bd6-adae-11e7-8501-3e5b683e41ab.png)

**Comment by mmmavis** [comment]
@xmatthewx plz verify on staging and close this ticket if the typo no longer exists. I don't know what we can do for legacy things but I think it's probably not something we can do in this codebase.

**Comment by xmatthewx** [comment]
👍
