### ISSUE TITLE
Add more metadata to Project

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#58]
Based on https://github.com/mozilla/network-pulse/issues/33 and comps https://redpen.io/p/by8c797c413d39c620

When a user clicks on "Issues" the 5 Issue tags (Online Privacy & Security, Open Innovation, Decentralization, Web Literacy, Digital Inclusion) appear below with some intro text.

If a user clicks on one of the tags, then only posts with that specific tag are visible.

Only one tag can be selected at a time.

I've added a column to the spreadsheet (https://docs.google.com/spreadsheets/d/1vmYQjQ9f6CR8Hs5JH3GGJ6F9fqWfLSW0S4dz-t2KTF4/edit#gid=922457769) and assigned Issues to each project. Some don't have an issue assigned and some have multiple issues (separated by commas).

We will hold off on adding this field to the form.

@mmmavis let me know if you have any questions/comments

**Comment by xmatthewx** [comment]
@mmmavis – this is metadata we will include in the card, but not display. A data attribute might work, though a hidden element might more quickly integrate with the search feature. There might be other info like this as well. Lastly, this is info we could display in the detail view, depending on final design.

**Comment by xmatthewx** [comment]
Let's include, but not display `tags` `issues` `program` `type` as tag/category like metadata.

**Comment by kristinashu** [comment]
If I enter a search term, I should be able to copy that url and send it to someone so they go straight to a page with those search results (and any new ones that my have been posted during fitting the criteria). This is something that came up in an interview today and would be very useful.

**Comment by kristinashu** [comment]
Sorry, comment above was related to search but the same should happen for categories. If I have selected a category, the url should be specific to that category.

**Comment by mmmavis** [comment]
relates to https://github.com/mozilla/network-pulse/issues/99 (Search functionality)

**Comment by xmatthewx** [comment]
@mmmavis - have any questions on this issue or [my comment above](https://github.com/mozilla/network-pulse/issues/58#issuecomment-235935083) to estimate this work?

**Comment by mmmavis** [comment]
Estimate set to 2. I got a PR open for this.

**Comment by xmatthewx** [comment]
Yay. Search is more awesome now!!!!!! 💯
