### ISSUE TITLE
Create a deck to show vision for Pulse v3

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#580]
@xmatthewx started [this deck](https://docs.google.com/a/mozilla.com/presentation/d/14dLEg1UagoIwQkTGV4VRc6QN3UxraGyHFSqNJlRR9nQ/edit?usp=sharing) and we will continue to add to it.

**Comment by xmatthewx** [comment]
@kristinashu – a diagram could help us explain the next phase of Pulse and how it will reveal connections, help us build new ones. Would also be useful for the Affinities session I'm planning with Jesse for all hands. 

If we could work at a whiteboard together! But we can't. So I took a brief stab at it. It's not great. I dropped the Sketch file in drive. Want to try something different?

It's trying to say few things, not quite succeeding: 
 - people and projects are gathered around shared affinities (some we know, some we don't)
 - people's connections cut across our circles (leaders, activists, action takers, supporters). seeing these helps us facilitate new, high impact relationships
 - there could be another layer/version of this that indicates the help categories as doorways.

![pulse-network](https://user-images.githubusercontent.com/53411/27408977-2a319ff4-56ad-11e7-84ed-5bdd35efbc10.png)

**Comment by kristinashu** [comment]
Based on the deck, these are my next steps in order of priority:
- [ ] Expanded profile page: quote, affiliation ...
- [ ] Expanded profile page: Surface a person's top tags based on their associated projects
- [ ] Expanded profile page: Link to [Story Engine](https://storyengine.io/) interview
- [ ] Quick Explore: Search, Tags, Discover people ...
- [ ] Deck: User stories
- [ ] Deck: Network diagram
- [ ] Form for profile: Create profile view, when to prompt, available for story engine interview checkbox, Story Corp ...
- [ ] Expanded profile page: Interview view (info from Story Engine)

**Comment by xmatthewx** [comment]
Done enough. Did the job.
