### ISSUE TITLE
Add ATXH4C tag to projects

### ISSUE THREAD

**Issue by omnignorant** [mozilla/network-pulse#588]
Can we please add the ATXH4C tag to the following projects [389, 347, 224, 218]:
* https://www.mozillapulse.org/entry/347
* https://www.mozillapulse.org/entry/389
* https://www.mozillapulse.org/entry/224
* https://www.mozillapulse.org/entry/218

**Comment by xmatthewx** [comment]
@omnignorant – We can add that tag for you. Or, we could add `hack for change` so it's meaningful to the unacquainted, and so that people have a chance to discover that stuff from other places. I'm betting you already have `austin` on these.

**Comment by omnignorant** [comment]
Hi @xmatthewx good suggestion! Can we keep both the `hack for change` and the `atxh4c` tags (because I've already linked to it). Can we also add the `hack for change` tag to these projects?
* https://www.mozillapulse.org/entry/387
* https://www.mozillapulse.org/entry/388

**Comment by hannahkane** [comment]
Added all these tags.
