### ISSUE TITLE
Implement UI and feature updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#59]
@mmmavis design isn't totally final but I'm creating this epic ticket to help scope the upcoming work. Maybe we can chat in more detail about functionality, concerns, open individual tickets...

Based on design in #32 

Comps: https://redpen.io/p/by8c797c413d39c620

Sketch file: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLcGxBUWV0SDU0UEE/view?usp=sharing

Exported Assets: https://drive.google.com/open?id=0B2irLVDJivhLWmZlZ0stNEd1a2c

**Main pages**

Search:
- styling only

Nav:
- styling
- move Featured, Latest, and Favs to a menu and make them separate screens
- add Issues Category Tags https://github.com/mozilla/network-pulse/issues/58
- upload post icon is just styling

Cards: #84 
- styling
- add date
- add image https://github.com/mozilla/network-pulse/issues/57

Footer:
- styling only

**Search page:**
- styling
- add 'no search results' found page

**Share post screen**
- add nav bar and footer to post

**404 Page**
- styling

**Comment by kristinashu** [comment]
@mmmavis please not that the design has been updated since yesterday https://redpen.io/p/by8c797c413d39c620

**Comment by kristinashu** [comment]
Made a few copy updates but design should be all done now.

**Comment by xmatthewx** [comment]
:)
