### ISSUE TITLE
Add link on form for info on 5 issues

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#599]
refiled from https://github.com/mozilla/network/issues/547

When people submit an entry to Pulse, we offer 5 issue categories. Would be useful to link to more info on Internet Health and the 5 issues. 

> Check any key [Internet Health issue](https://network.mofoprod.net/about/) that relates to your project.

Link: https://network.mofoprod.net/about#internet-health

Note: anchor needs to be added to the site's page

<img width="604" alt="screen shot 2017-07-06 at 2 34 37 pm" src="https://user-images.githubusercontent.com/53411/27927033-6a3876a2-6258-11e7-9d11-c6ff85f5513d.png">

cc @hannahkane

**Comment by Pomax** [comment]
This will need a design pass for the presentation of the link. @kristinashu do you have ideas for this?

**Comment by kristinashu** [comment]
We can just make "Key Internet Issues" a blue link (e.g. same blue and then underline treatment as "Get Involved" https://www.mozillapulse.org/entry/392). Is that what you had in mind @Pomax?

**Comment by Pomax** [comment]
That sounds good - so rather than link each individual issue to its own description, we link to the main overview `mozillapulse.org/issues` page?

**Comment by kristinashu** [comment]
Yes, perfect!

**Comment by Pomax** [comment]
@Sudip7 is this something you would be interested in tackling?

**Comment by arush0311** [comment]
Can i take this?

**Comment by xmatthewx** [comment]
👍 thanks @arush0311

**Comment by Pomax** [comment]
This issue seems to have fallen off the cart, do we want to keep it open with specifics on what needs to be done, or should we close it?

**Comment by xmatthewx** [comment]
Looks good on staging. Closing this and we can push to production.
