### ISSUE TITLE
Add Open Graph tags across site

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#600]
The site should have Open Graph tags attached to each of its pages to describe the content, so that this can be picked up when posting links to social media like facebook or twitter.

We can start by ensuring that entries emit their title and description using Open Graph `<meta>` tags.

**Comment by Sudip7** [comment]
@Pomax , I made some changes and posted them to mattermost before raising a PR, please have a look and suggest any modification.

**Comment by alanmoo** [comment]
@sudip7 I checked Mattermost the other day and didn't see anything- it would be helpful if you can comment here for all to see.

**Comment by Sudip7** [comment]
@alanmoo , this is just for demo, based on your suggestions will update the code.
![ogmeta](https://user-images.githubusercontent.com/6715793/28880538-072126d8-77c3-11e7-9189-45646c34c4be.jpg)
![image pasted at 2017-7-27 05-07](https://user-images.githubusercontent.com/6715793/28880560-1541682c-77c3-11e7-8122-c0a427a4b727.png)


Although @Pomax suggested some services I was not able to verify code over it due to the connectivity problem. So above screenshot is from my localhost.

**Comment by alanmoo** [comment]
I think we want to use OG tags similar to those on https://network.mozilla.org.

@gvn I recall you having knowledge of these tags and what we should use, do you have anything to add?

**Comment by gvn** [comment]
Not really, just be sure to have `og:url`, `og:title`, `og:description`, and `og:image` per [this guide](https://developers.facebook.com/docs/sharing/webmasters).

**Comment by Sudip7** [comment]
hey @alanmoo , @gvn those tags are for twitter cards which are similar to fb open graphs. I found some examples just like https://www.koozai.com/blog/social-media/social-markup/ or https://www.magentocommerce.com/magento-connect/social-meta-tags-for-facebook-and-twitter.htmlmj

Even found something similar in one of the mozilla partner sites.
![ogcards](https://user-images.githubusercontent.com/6715793/28949675-f0edb77c-78db-11e7-86bb-e27df95fa278.jpg)


Few things I am not sure though
1. fb:app_id and it's use. 
2. How to use dynamic URL and description which I think so.

**Comment by alanmoo** [comment]
1. Don't worry about `fb:app_id`. As mentioned in the link Gavin shared above, it's for analytics on facebook which we're not concerned about at this point in time.
2. I believe that's the crux of this ticket, we need the meta tags for each page dynamically generated. You're welcome to bounce suggestions off us in the comments.

**Comment by Sudip7** [comment]
I tried something like this

` <Helmet>
      <meta property="og:title" content= "{ `${this.state.entry.title}` }" />
      <meta property="og:description"  content="{ `${this.state.entry.description}` }" />    
      </Helmet>;`

But still not able to figure it out how the dynamic content should work inside the "" of content. 
Any suggestions.

**Comment by mmmavis** [comment]
@Sudip7 it would be helpful if you could submit a PR (and mark it as "WIP") so we can see your working in progress code and make suggestion for it. 😉

**Comment by mmmavis** [comment]
Hey @Sudip7 , haven't heard back from you for a while now. I'm gonna re-assign this ticket to myself as I would like to get this shipped soon 😃 Thanks for offering your help!

**Comment by mmmavis** [comment]
@xmatthewx can you help provide copy for the site `title` and `description` (or point me to the person I should talk to for this)? For og image I think we can probably just use https://assets.mofoprod.net/network/images/mozilla-og-image-min.original.jpg (this is what Foundation site uses)

**Comment by xmatthewx** [comment]
Great. I will draft some copy soon.

**Comment by xmatthewx** [comment]
Thanks Mavis. Will we use the same thing for every page? Or, can we have projects and profiles be unique?

For the site, I think we could use: 
 - title: 'Mozilla Pulse'
 - description: 'Discover & collaborate on projects for a healthy internet.'
 - image: logo

If we can vary for other views, ideas below. Any feedback you've got is welcome. 

Projects
 - title: title
 - description: 'Discover and collaborate on Mozilla Pulse'
 - image: project image

Profiles
 - title: name +  ' – Mozilla Pulse'
 - description: bio
 - image: avatar

Tag view
 - title: tag + ' – Mozilla Pulse'
 - description: 'Discover & collaborate on projects for a healthy internet.'
 - image: logo

**Comment by mmmavis** [comment]
Adding universal og tags to all pages on Pulse should be easy. I will look into having customized meta for different route types.

(Bumping the estimate up to 3)

**Comment by mmmavis** [comment]
@xmatthewx 

> Projects
> - title: title
> - description: 'Discover and collaborate on Mozilla Pulse'
> - image: project image

Wondering for `title` if it should also include `– Mozilla Pulse` for consistency?

**Comment by xmatthewx** [comment]
Probably yes. My concern was that some titles are loooong. But maybe browser UI can handle that okay. Try it. You can decide what's best.

**Comment by mmmavis** [comment]
I have a PR that updates OG tags dynamically client side based on what page/route user is on. However, Facebook OG tag crawler doesn't seem to grab those updated values. Without a drastic codebase rewrite I think the best we can do is to add site wide OG tag 😢 I'll open a new PR for that.

**Comment by xmatthewx** [comment]
😭 Does Twitter or other services accept the client side update? If so, maybe put in a site wide default for FB and then update?

**Comment by mmmavis** [comment]
Unfortunately, I think it's the same case with Twitter card. You can try the [review app](https://github.com/mozilla/network-pulse/pull/1274#event-3201025779) with [Twitter card validator](https://cards-dev.twitter.com/validator) (requires Twitter login).

**Comment by xmatthewx** [comment]
Ok thanks for putting in the effort!
