### ISSUE TITLE
Update form with Help categories 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#601]
@kristinashu – can we mock up the form so we can begin implementation next week? Filing as new ticket so we can close #533. 

We might want a Get Help section, splitting up Optional Details. This would include current description and link, and new help tags (as buttons you can toggle on/off).

Categories: `Attend`  `Create content` `Code`  `Design`  `Fundraise`  `Join community` `Localize & translate`  `Mentor`  `Plan & organize`  `Promote`  `Take Action`  `Test & feedback`  `Write documentation`

Front end display on entries here: https://github.com/mozilla/network-pulse/issues/537

**Comment by Pomax** [comment]
Some things:
1. form: if help categories are chosen, the "link to get involved" cannot be blank.
2. site: do we need a way to show "all entries with needs-help-on-xyz"?

**Comment by xmatthewx** [comment]
For this sprint, MVP is just checkboxes. 

Do we require get involved link if help categories are checked?

**Comment by xmatthewx** [comment]
Mockup below. Note: 
 - I moved image field up to add a new section header
 - No need to actually limit to people to 3 categories. Nobody will get injured if we don't validate that. Let's discover that we actually need it before we put in the work. 

<img width="704" alt="screen shot 2017-07-20 at 10 56 31 am" src="https://user-images.githubusercontent.com/53411/28423871-320d7236-6d3a-11e7-9ca5-aac1c51cd993.png">

**Comment by kristinashu** [comment]
Looks good to me!

**Comment by Pomax** [comment]
Working on the PR for this atm, do we have short summary descriptions to go with each of those help types?

**Comment by xmatthewx** [comment]
> do we have short summary descriptions to go with each of those help types?

We don't, but that's a good idea. It would take a little exploration to figure out where and how we'd display that. Probably best as a follow up item.

**Comment by Pomax** [comment]
yeah, we'll define the model with a placeholder for descriptions but just set them to the string `...` for now and then we can always update and expose them later.
