### ISSUE TITLE
Design moderator Feature toggle

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#602]
Pulse now allows moderators to approve pending entries. It'd be great if they could also Feature an item for display on the Feature tab. 

Note: ability to feature should only appear on approved entries. 

While we design the toggle/checkbox, we should also consider how we visually confirm that the change was made, both for this and pending state change. Right now, it's unclear if anything happened. A blink of color, a notice, or something.   

Related API endpoint in #572

**Comment by kristinashu** [comment]
Would this work?

When a user is in Approved drop down, they see a check box. If they check it then that post will be featured.
<img width="363" alt="screen shot 2017-07-26 at 9 56 45 am" src="https://user-images.githubusercontent.com/1068783/28633465-c165aad6-71e8-11e7-825c-ac4e2b87d793.png">


We could also add "Featured" to this v drop down so users only see what is featured there.

<img width="356" alt="screen shot 2017-07-26 at 9 56 02 am" src="https://user-images.githubusercontent.com/1068783/28633538-fa04985c-71e8-11e7-97e7-b9ea302144b3.png">

**Comment by xmatthewx** [comment]
+1 on both things. Looks like the API work is now done, so we should be ready to implement.

@kristinashu give moderation a try on the site. I think we need a way to indicate that a change succeeded. It feels unsure when you change a drop-down. Doesn't need to be complicated. It could be a blink of border color.  Or maybe the text color changes while pending and then finalized by server.

**Comment by kristinashu** [comment]
I did try updating the status of a post and it seemed pretty clear to me that it worked. The text in the dropdown changes from e.g. "Approved" to "Pending" which seems good. Are you getting a delay? It was pretty instant for me.

**Comment by xmatthewx** [comment]
I think that @hannahkane also said she felt unsure if the change actually went through. True? If so, this will matter more if/when we pull in more moderators. Again, we don't need to worry about this to move the feature checkbox and filter to engineering.

**Comment by kristinashu** [comment]
I've opened - Implement moderator Feature toggle #616

**Comment by kristinashu** [comment]
I'm going to close this ticket but please open a new one if needed (to indicate successful status change).
