### ISSUE TITLE
Prevent commas in tags

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#603]
Tag ID 524 ends `Cyberbullying,`. Let's strip commas. Or, should we limit to alphanumeric characters?

I checked DB and it seems like this only happened once. Might be a weird edge case bug.

**Comment by Pomax** [comment]
This might be a bug, commas should trigger a tag finalization.

**Comment by Pomax** [comment]
You can no longer do this by typing a comma, but you *can* make this happen by pasting a string of tags... the tag handler only looks at what is typed and currently lacks the sophistication to check inside a string that got pasted in.

**Comment by Pomax** [comment]
I've filed https://github.com/i-like-robots/react-tags/issues/84 to see if this is something that can be addressed in the tag component we're using.

**Comment by xmatthewx** [comment]
Should we mark this as blocked for now?

**Comment by Pomax** [comment]
we should. I also found one instance of what is probably a pasted "tag, tag, tag, ..." instance, which we'll have to fix manually.

**Comment by xmatthewx** [comment]
bumping to next milestone

**Comment by Pomax** [comment]
there's some good headway being made on this over on the react-tags repo, hopefully there's a new version to pull soon for this.

**Comment by Pomax** [comment]
One thing left is to make sure that the Tag model itself does not allow commas, probably along with a change to Entry so that if we do see a tag with commas, we split it before entry saving.

**Comment by Pomax** [comment]
filed https://github.com/mozilla/network-pulse-api/issues/180 as followup to this work.

**Comment by Pomax** [comment]
closing as the original work was done, follow-up to take care of the rest.
