### ISSUE TITLE
Sync User Favs

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#608]
Adding this as an epic so we have an epic for all main areas of focus.

**Comment by mmmavis** [comment]
@xmatthewx @hannahkane @kristinashu @Pomax @alanmoo 

This is on [staging](https://network-pulse-staging.herokuapp.com/favs) now. Please help with testing so we know if it's good to push to production.

## For logged in users
**Import `localStorage` favs to backend**

If you have previously fav'ed any entries, when you go to the Fav tab you will see the import prompt like

<img width="998" alt="screen shot 2017-07-25 at 3 04 10 pm" src="https://user-images.githubusercontent.com/2896608/28595912-ed1f0a44-714a-11e7-82e5-7695e4365221.png">

screen after things have been imported...

<img width="977" alt="screen shot 2017-07-25 at 3 04 31 pm" src="https://user-images.githubusercontent.com/2896608/28595890-d621fffe-714a-11e7-902b-34b593ac6bb5.png">

## For unauthenticated users
**continue using `localStorage` to remember favs**

**Comment by kristinashu** [comment]
Nice, seems to be working well for me!

**Comment by alanmoo** [comment]
Great, this behaves exactly as I'd hope. Nice work!

**Comment by xmatthewx** [comment]
Works perfectly. The experience is surprisingly easy peasy.

**Comment by xmatthewx** [comment]
🚀 🎸 💥 🥇

**Comment by xmatthewx** [comment]
yay
