### ISSUE TITLE
Design UI for People views

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#609]
Continuing work started in [v3 deck](https://github.com/mozilla/network-pulse/issues/580#issuecomment-313744096), complete UI to prep for implementation. 

 - [x] Entry includes creators and submitter
 - [x] Names link to profile view when available
 - [x] Profile view lists person's related entries (created, submitted, fav'd)
 - [ ] User has means to edit profile fields (design pending)
 - [ ] Pulse has notion of mini vs full profile, full profile unlocked by moderator
 - [ ] Adding a creator offers autocomplete with existing people (maybe we indicate when a user has a profile? or include location when known to clarify name dupes?)
 - [ ] Profile shows or links to an expanded view with more info. Includes or links to interview view
 - [ ] ...?

**Comment by kristinashu** [comment]
Adding designs to https://redpen.io/p/of380006b3156e2c51

**Comment by kristinashu** [comment]
@xmatthewx I've asked you to confirm a few things in [redpen](https://redpen.io/p/of380006b3156e2c51). I think all the screens have been covered and just need some fine-tuning. 

I'll be meeting with devs tomorrow to review the comps.

**Comment by xmatthewx** [comment]
All the views look great. I have two things I'd like to discuss: 

 - flow: when do people create their profile? do we need/want to do it immediately when creating an account? i think there are pros/cons. 
 - profile entries: i wonder if there's an approach other than tabs to display favs/posts/projects on a profile. the tabs are likely to have a bunch of duplicates (user posts a thing they create and fav it b/c they're their my own biggest a fan). a visitor wants to know what that person is associated with b/c they're cool, but probably want to see all the stuff all at once. what about a single view of entries with a way to flag things as created/posted/favorited?

Curious what you think. Let's discuss. None of this should block the start of engineering.

**Comment by kristinashu** [comment]
Thanks for the feedback. Next week I will address the updates and create a user flows diagram for signup and creating a profile.

**Comment by kristinashu** [comment]
Closing this ticket and opened new ones for next heartbeat:
- Design updates to UI for People view #619
- Create user flows for creating a profile #618
