### ISSUE TITLE
Finalize Profile fields

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#612]
We have an idea of the fields in mockups and on network profiles, but should finalize a list here. List should be split into fields for everyone (e.g. linkedin url), and fields hidden unless unlocked by an admin (e.g. role).

**Comment by xmatthewx** [comment]
Draft list...

Open to all Users:
 - Name
 - Location (city, country)
 - Image
 - Twitter URL
 - Linkedin URL
 - Website URL
 - 5 Issues (which they care most about) 
 - Bio (short, twitter like)

Unlocked by moderator for User: 
 - Role (within the network)
 - Partnership logo
 - Quote
 - Affiliations (companies, nonprofits, universities, orgs, projects)
 - Interview URL (currently story engine. Medium or within Pulse TBD)

**Comment by xmatthewx** [comment]
@Sydette @jessevondoom – any additional fields? These fields will be used both by [profile view on pulse](https://docs.google.com/presentation/d/14dLEg1UagoIwQkTGV4VRc6QN3UxraGyHFSqNJlRR9nQ/edit#slide=id.g1f81451dc0_0_4) and should serve [featured people on Network site](https://network.mofoprod.net/people/).

**Comment by xmatthewx** [comment]
- Skills – We should offer users a list of skills that match our [help categories](https://github.com/mozilla/network-pulse/issues/601#issuecomment-316730609). So we can do match-making. Fun!

**Comment by jessevondoom** [comment]
Few thoughts:

- Should we think about storing the actual StoryEngine content as a "long bio" type of field? I feel like this might be perfect for a full profile versus a mini profile, and the content should ultimately live here.
- Are the five issues user-generated tags or our IH key issues? We may want to give checkboxes for IH issues as well as a limited ability to add interest tags that are user generated. 
- What about an explicit project connection (with text-field role) as part of the unlocked full profile?

**Comment by xmatthewx** [comment]
> Should we think about storing the actual StoryEngine content as a "long bio" type of field?

Yes and maybe. Pulse doesn't currently have markdown/wysiwyg powers. No rich fields. So I aim to add profiles in this first phase with URL for interview. And then follow up to pull in the interviews. You'll see these in the designs early next week. 

 > We may want to give checkboxes for IH issues as well as a limited ability to add interest tags that are user generated.

Yes, 5 checkboxes for THE issues. I was thinking it might be fun/interesting to use tags on projects fav'd and created by a person to dynamically tag the person. Probably just under the hood, but we could use this for search and suggestions, both for the user themselves and other users.  

> What about an explicit project connection (with text-field role) as part of the unlocked full profile?

Do you mean for projects where I'm listed as a creator, I can specify my role? If so, we have a lot to figure out about how people will claim and confirm association with a project. We can keep this in mind, but it'll take some time to get there.

**Comment by jessevondoom** [comment]
I like the dynamic tagging idea a lot. 

And yeah...as for the project connection, thinking of that as a longer-term thing so not something we need in there right now.

**Comment by xmatthewx** [comment]
@kristinashu - a few more thoughts and then we can probably call close this ticket. 

 - Github URL
 - Languages? A powerful way for non-english speakers to find each other. 
 - For location, I think we should consider: 
   - Country (drop-down select) (allows us to link to find others)
   - City/Location (text field, open to interpretation)

**Comment by kristinashu** [comment]
I've these to the comps https://redpen.io/p/of380006b3156e2c51

Closing this ticket but please feel free to add comments in the Redpen.
