### ISSUE TITLE
Update font to Zilla

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#614]
Zilla is now on google fonts https://fonts.google.com/specimen/Zilla+Slab so we should update to match [Mozilla's new brand direction](https://mozilla.ninja/).

New designs are here: https://redpen.io/p/of380006b3156e2c51

Everything should be Zilla with the exception of the following, which should be Open Sans:
- main nav
- button text
- tab nav (only seen in new v3 design)

**Comment by xmatthewx** [comment]
Someone mentioned that the reverse highlight version wasn't available yet. I guess that affects Pulse less than network site, but might be good to do it all at once.

**Comment by kristinashu** [comment]
Right, Pulse doesn't use the reverse highlight so it shouldn't matter (also, not sure they will ever have the reverse???).

**Comment by mmmavis** [comment]
@gvn @alanmoo does this also require changing some code in`mofo-bootstrap`? i.e., https://github.com/mozilla/mofo-bootstrap/blob/22300d26116d6ca2525ea0c0cf668fcd9f3fd952/src/scss/overrides/_variables.scss#L8

**Comment by mmmavis** [comment]
If there's no objection I will work on this + file a PR on `mofo-bootstrap` to update default font family to Zilla @kristinashu @gvn @alanmoo

**Comment by kristinashu** [comment]
That would be amazing! Thank you!

**Comment by xmatthewx** [comment]
There's a PR to update the Network site to Zilla. I've asked designers to review for font-size or other quirks. https://github.com/mozilla/network/pull/643#issuecomment-321296468. We'll want to review Pulse as well. 

Will any other properties be affected by an update to mofo-bootstrap? I'm ok if we introduce a little funniness to other sites, but we should be ready to review for problems.

**Comment by mmmavis** [comment]
It won't unless that site has opted in to always use the latest `mofo-bootstrap`. Do we want to do a major release for this (i.e., mofo-bootstrap `v4.0.0`) @gvn @alanmoo ?

**Comment by gvn** [comment]
If we change the font family in mofo-bootstrap then yeah we should do a major revision IMO.
