### ISSUE TITLE
Implement moderator Feature toggle

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#616]
Design moderator Feature toggle #602 
API endpoint in #572

On https://www.mozillapulse.org/moderation with "Approved" dropdown selected, a users will see an additional check box. If they check it then that post will be featured.
<img width="363" alt="screen shot 2017-07-26 at 9 56 45 am" src="https://user-images.githubusercontent.com/1068783/28633465-c165aad6-71e8-11e7-825c-ac4e2b87d793.png">

We also need to add "Featured" to this v drop down so users only see what is featured there (and can uncheck posts).

<img width="356" alt="screen shot 2017-07-26 at 9 56 02 am" src="https://user-images.githubusercontent.com/1068783/28633538-fa04985c-71e8-11e7-97e7-b9ea302144b3.png">

**Comment by mmmavis** [comment]
Instead of adding an option to the existing dropdown let's create a 2nd control to filter "featured" entries since "moderation states" and "featured" are not mutually exclusive filters.

**Comment by xmatthewx** [comment]
That sounds good @mmmavis.

I think you can remove the help text "Filter by moderation state:" and "Keywords:" from the top of moderation. It's pretty self-evident. Save some space and make it nicer on mobile.

**Comment by mmmavis** [comment]
PR in review. Page will look like

![screen shot 2017-08-09 at 11 16 42-fullpage](https://user-images.githubusercontent.com/2896608/29137171-3f8d54fc-7cf4-11e7-88fc-e182e39d7953.png)

**Comment by kristinashu** [comment]
Nice!

**Comment by xmatthewx** [comment]
I'll leave this in the prior milestone since it is just pending review. cc @alanmoo

**Comment by mmmavis** [comment]
on staging pending verification: https://network-pulse-staging.herokuapp.com/moderation

**Comment by xmatthewx** [comment]
Is it possible @mmmavis to hide the featured checkbox, and display it only when moderation state is Approved? It's not absolutely critical, but if it's not hard, it would improve the UX. In my test, I checked the box, looked for the item on featured, and then took a minute to realize my mistake.

**Comment by mmmavis** [comment]
Will there be cases where a previously approved featured entry can later become not approved? If so I think we should keep the featured checkbox since marking an entry away from a moderation state doesn't affect its featured state. Plus technically speaking it's not only approved entries can be featured.

**Comment by xmatthewx** [comment]
My note might have been confusing. I meant to suggest we hide the featured checkbox on entries, not in the page level filter at the top.  

If an entry is not Approved, its Featured state is irrelevant. An entry should never be accessible via API for public viewing if it is not Approved. 

From a moderators perspective, there's no need to see or change the Featured state unless the Moderation state is Approved. I know the system better than a typical moderator, and I still got confused when I tried to feature a thing. A moderator can easily have this experience: "I checked the featured box ... now the item should be featured ... but it isn't. It seems broken."

**Comment by xmatthewx** [comment]
Again, if this is a big lift, we can skip it. We'll just need to update our nonexistent training doc for moderators. :)

**Comment by Pomax** [comment]
This sounds like follow-up: can a new issue be created so we can track these iterations?

**Comment by xmatthewx** [comment]
okey dokes
