### ISSUE TITLE
Create user flows for creating a profile

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#618]
Based on design in #609 and will influence design in #619

**Comment by kristinashu** [comment]
Still a WIP and lines are very messy but here is the start of the flows https://docs.google.com/a/mozilla.com/presentation/d/12o0P9wWGlUEuY-247fWuHluVQsdfm9Htqlfuo8OQUio/edit?usp=sharing

cc @xmatthewx

**Comment by xmatthewx** [comment]
@kristinashu – if you run out of time to do this before your travel, please assign to me. Glad to do it. I think it's probably more important that you focus on cross-site stuff. What do you think?

**Comment by kristinashu** [comment]
Sounds good! I'm feeling a little stuck on it anyways.

**Comment by xmatthewx** [comment]
I think we can call this done.
