### ISSUE TITLE
Build profile model

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#621]
Note: We should set the stage for "who can edit this profile" so that organization profiles can be a thing. (By default, a user can edit their own profile.)

**Comment by xmatthewx** [comment]
Should we start with doc. Talk through the fields? I [started a doc and hastily dropped in some thoughts](https://docs.google.com/document/d/1gpjXAZJlQ0pfcxG71AuAunr3okwWSyJs3fNrmF7DBxQ/edit#) 'cuz I gotta head home now.

**Comment by xmatthewx** [comment]
This is noted in profile model. Pretty sure no work required beyond that. Closing.

**Comment by alanmoo** [comment]
This ticket is for API implementation. I think you meant to close #612?

**Comment by xmatthewx** [comment]
Oye. I'm going to delete that misplaced comment and move it to 627 (enable organization profile).

**Comment by xmatthewx** [comment]
- Path /profile/id
   - Probably makes sense for people & groups/orgs
 - Owner ID
   - Defaults to User ID
 - is_group
 - Name
   - Defaults to google name
 - Location
   - City/town, Country
 - Avatar
 - URLs
   - Twitter URL
   - Linkedin URL
   - Github URL
   - Website URL
 - 5 Issues
   - booleans
 - Bio (140 char string)

We will file three things as distinct work for later
 - [ ] Languages
 - [ ] Skills - these relate to help categories
 - [ ] Unlocked by moderator fields

**Comment by Pomax** [comment]
much of this work has been done in https://github.com/mozilla/network-pulse-api/pull/175, with some things that we should discuss,

Location is currently set to "city" + "country", and not a lat/long datatype to prevent straying into PII territory. However, this comes with some issues (also pointed out in the source code) that we need to take into account if we want to *do* anything with this data (like finding colocated creators, submitters near someone, etc):

- A country might have two or more cities with the same name, but in different administative regions of that country. We don't capture that with a city/country pair.
- Some cities lie in two countries, with wildly different names (I know, that's crazy, but it's a thing).
- Some people live or work or associate with more than one location, especially if they live near an easily crossed border such as in many European countries, such that making them pick only one for their profile makes no sense.

Making this do the right thing is going to take more work than any initial model implementation can achieve, so I would suggest the city/country tuple as initial datatype mostly to prevent bikeshedding while we make profiles a real thing.

URLs have been made "arbitrary" in that a user can set zero or more URLs, with an optional associated service name. We literally have no way of knowing all social media and sharing services that our popular in subsets of our network so this solution lets us determine a few we do know of, without ruling out potentially wildly popular services in some region that we've never heard of.

**Comment by xmatthewx** [comment]
Oh geo-political complexity. Why do you torment us?

re: `URLs` — I checked with Kristina and Jesse. We want to stick with Twitter, LinkedIn, Github, Blog/Site. These have specific strategic value in the network. It offers some flexibility, especially with the last link, but keeps us from being too diffuse to build critical mass. A user could still choose to link to a site that aggregates their preferred platforms, but for the majority, we encourage them to connect with spaces that we support. This profile isn't intended to be a person's home on the internet, just their calling card within the network. We can keep an eye on feedback and the 4th URL, to seek opportunities to support additional channels.

**Comment by Pomax** [comment]
In that case in terms of MPV Profile let's only do the fixed list of URLs. Maintaining both a fixed set and a fluid set will make it a lot harder to iterate.

**Comment by Pomax** [comment]
The model has been updated to use explicit twitter, linkedin, github, and website fields.

**Comment by Pomax** [comment]
model updates have landed with https://github.com/mozilla/network-pulse-api/pull/175, work will focus on the view and rest endpoints to view and update this data.
