### ISSUE TITLE
Build MVP profile view in client

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#622]

**Comment by xmatthewx** [comment]
MVP is person's details and simple list of all associated entries below. 

https://redpen.io/qua34b5932cdb6cf9f

**Comment by kristinashu** [comment]
I believe this is what the MVP profile page would look like and should include:

- edit profile which links to [form](https://redpen.io/bk7c2a3cbaafdcd47a)
- all projects the person/organization has uploaded and/or is listed as a creator on (no duplicates)

Info the user adds:
- profile pic
- name (from google account but updatable in user form) - this is the only required
- location (city, country) - not sure if MVP is clickable?
- languages (multiple separated my commas)
- website URL
- bio (140 character limit)
- clickable 'interest' tags
- clickable 'can help with' tags

Admin adds via django:
- role 
- URL to story engine interview

![full profile mvp 2x](https://user-images.githubusercontent.com/1068783/28890635-893418d4-777c-11e7-9d5b-62994875bf44.png)

For reference, here is the form:
![profile form 2x](https://user-images.githubusercontent.com/1068783/28890365-b02219f6-777b-11e7-82a6-92e644fd447c.png)

**Comment by mmmavis** [comment]
@kristinashu thanks for the list. Could you provide mockup for mobile view? I'm afraid the following section will look super clustered if you are letting me design it haha.

<img width="553" alt="screen shot 2017-08-02 at 12 41 33 pm" src="https://user-images.githubusercontent.com/2896608/28891612-f652dd3a-777f-11e7-86f9-423054522841.png">

**Comment by kristinashu** [comment]
How about something like this?

<img width="316" alt="screen shot 2017-08-03 at 8 24 00 am" src="https://user-images.githubusercontent.com/1068783/28929568-23873756-7825-11e7-8e27-c03f1ed7ca87.png">

**Comment by mmmavis** [comment]
Thanks @kristinashu 

I wonder if we should break `language`, `Read Story`, `link` into its own line with an icon like what you have for the `location` field. If an user has indicated more than 1 language or the full url of the link is long, these meta mostly likely won't fit into one line.

**Comment by kristinashu** [comment]
Yeah, that sounds good! I'll work on the icons.

(note that most people won't actually fill in all that info)

**Comment by mmmavis** [comment]
> Yeah, that sounds good! I'll work on the icons.

We can use font-awesome icons if you'd like.

**Comment by kristinashu** [comment]
Cool, I'll chose some font awesome ones and mock it up.

**Comment by kristinashu** [comment]
#### Here are the icons:
m icon is custom [icon-mozilla-role.svg.zip](https://github.com/mozilla/network-pulse/files/1198288/icon-mozilla-role.svg.zip)
Font awesome icons are 12px:
fa-map-marker [&#xf041;] 
fa-comment [&#xf075;] 
fa-quote-left [&#xf10d;] 
fa-user-circle-o [&#xf2be;]

#### Looks like:
![full profile mvp 2x](https://user-images.githubusercontent.com/1068783/28938359-b60ca602-7842-11e7-8516-a7a278b66a88.png)
<img width="320" alt="screen shot 2017-08-03 at 11 56 04 am" src="https://user-images.githubusercontent.com/1068783/28938400-cde1b93e-7842-11e7-8116-515dd1f04d9b.png">

**Comment by xmatthewx** [comment]
nice suggestion @mmmavis! looks great. one suggestion: a globe or something different the user-ciricle-o ... since someone could drop in an organization website.

**Comment by kristinashu** [comment]
Sounds good, here's the globe: 
  fa-globe [&#xf0ac;]

**Comment by mmmavis** [comment]
Hey @kristinashu sorry if the following questions have been clarified somewhere already - do you have a chart or something to help clarify what the flows are like for different types of users trying to access to their own profile? I assume each screen will look differently on different scenarios?

- before logged in
- after logged in 
  - never updated his/her profile (default profile view)
  - profile has been updated before

How do users access their own profile? By clicking on the "Hi [name]" on the nav bar? Have we settled on the url path for this page?

**Comment by kristinashu** [comment]
Good questions!

Yes, they access their profile by clicking on their name in the nav bar or by clicking on their name in ono of their a post (creator or post-er). 

I believe the URL is `/profile/idnumber` while `/myprofile` will be the edit/create form (@Pomax can you please confirm?).

- before logged in (Mmaki would see what other users would see)
<img width="1018" alt="screen shot 2017-08-22 at 11 41 23 am" src="https://user-images.githubusercontent.com/1068783/29581649-dc7358d6-872e-11e7-93f0-ff4c0d31940a.png">


- after logged in 
  - never updated his/her profile (default profile view) (CTA to fill in profile)
<img width="1017" alt="screen shot 2017-08-22 at 11 38 45 am" src="https://user-images.githubusercontent.com/1068783/29581693-077f2168-872f-11e7-95ee-2328a20a9385.png">

  - profile has been updated before (edit and log out links)
<img width="1017" alt="screen shot 2017-08-22 at 11 38 45 am" src="https://user-images.githubusercontent.com/1068783/29581681-f756546e-872e-11e7-8cc2-f788a8b971d7.png">

**Comment by mmmavis** [comment]
@kristinashu thanks for the comps. Can you advise where we should place the "Hi [username]" link on mobile? I can't seem to find a good place for it.

![screen shot 2017-08-23 at 10 42 17](https://user-images.githubusercontent.com/2896608/29630071-dcd4ce4c-87ef-11e7-920c-1aa7b2f79e3d.png)

**Comment by kristinashu** [comment]
@mmmavis how about something like this? Ignore the all black logo but realizing the nav items should be open sans (since it is considered a UI element). Long names could fit on two lines.

<img width="318" alt="screen shot 2017-08-23 at 10 52 37 am" src="https://user-images.githubusercontent.com/1068783/29630476-3d151fea-87f1-11e7-89f7-87de6540665e.png">

**Comment by alanmoo** [comment]
Closing this as it's landed on the feature branch. We'll close the epic when it actually lands in production
