### ISSUE TITLE
Enable editing of entries to link existing creators to profiles

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#623]

**Comment by xmatthewx** [comment]
We might not need this ticket. Or maybe it needs to be reframed. Let's discuss. 

In most cases, I believe that a moderator's task would be to merge creators, replacing a "stub" Creator (name string only), with a "real" creator (has associated profile). I suppose that there could be John Smith scenarios where you don't actually want to migrate all entry<>stub relationships, but those will be the exception. 

So, maybe we need a simple frontend moderator tool. Select two Creators. Hit a merge button. They could use this to migrate a stub to a real, or a stub-typo to a proper stub.

**Comment by alanmoo** [comment]
Another possibility that comes to mind is that when a user is logged in and viewing either an entry they submitted or they're a superuser, there's an icon next to each "stub" creator that opens a list of available "full profile" creators to choose from and bind that stub with. Maybe similar to what you're describing with a different UI in mind.

**Comment by xmatthewx** [comment]
That's interesting. Maybe more complicated, but worth considering. 

note: This is not MVP. We can ship profiles to production without this. Most everything else in the Epic feels like a pre-requisite.

**Comment by xmatthewx** [comment]
I'm going to close this. I'll open a new ticket to figure out frontend work to allow new entries to point to existing creators.
