### ISSUE TITLE
Refactor Entry.creator to be a list of profiles or a string

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#624]
An Entry's "creator" field can be a list of 
a.) proper users of the site
b.) some arbitrary names that someone typed in which isn't associated with a user of the site
3.) a mix of the two. 

When an item on the list is a real user of the site, the list item should include the user's name and profile ID so we can generate a link to their profile.

**Comment by Pomax** [comment]
@xmatthewx @gideonthomas @alanmoo there is an interesting problem with the PR for this where it is currently not possible to determine "the user's own profile" when a user also curates group profiles. For instance, say I have my own profile but I also curate the Mozilla Pulse and Mozilla Network profiles, then getting the list of all profiles and removing all profiles that represent a group will leave only 1 profile that can reasonably be assumed to be "mine", but is this a situation that will always be the case?

Will we only ever allow 1 real profile per user, plus N group profiles?

**Comment by alanmoo** [comment]
Let's avoid that potential rabbit hole and assume "yes". And if that should ever change (though I really can't fathom why), we can worry about it then.

**Comment by Pomax** [comment]
In this case, that sounds fine. Though in general, the "let's not worry about it now, let's worry about it later" often means a false saving, with exponentially more work later =)

**Comment by alanmoo** [comment]
Agreed, but I think it's enough of a slim chance that it's worth it.

**Comment by alanmoo** [comment]
@gideonthomas still to write tests before closing

**Comment by gideonthomas** [comment]
Fixed in https://github.com/mozilla/network-pulse-api/pull/216
