### ISSUE TITLE
Create client side "edit profile" view

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#626]

**Comment by xmatthewx** [comment]
comp: https://redpen.io/bk7c2a3cbaafdcd47a

profile view lives at: /user/[id]

 - [ ] display profile on success
 - [ ] display errors on failure
 - [ ] validate URLs
 - [ ] TBD country validation
 - [ ] TBD limit on bio char count
 - [ ] responsive
 - [ ] pulls name from google account
 - [ ] user can edit via link on their profile view
 - [ ] nobody else can edit
 - [ ] checklists can be existing mvp style 
 - [ ] all fields are optional

**Comment by xmatthewx** [comment]
We likely wouldn't share with the public without Country validation if we believe we're going to do that. Hide behind feature flag.

**Comment by mmmavis** [comment]
Work has been merged to the feature branch. Up for @xmatthewx do decide if we are good to close this ticket.

**Comment by xmatthewx** [comment]
When I tap "Hi Matthew" I'm taken to /profile/me. View reports "Profile not Found" since I haven't made one yet.   

We probably need to do a migration pre-launch to establish default profiles for existing users. True? If sol can we file a ticket @gideonthomas? 

Should /profile/me redirect to the form when nothing is found? This would guard against errors. If so, we can file this as a follow up. 

cc @alanmoo

**Comment by xmatthewx** [comment]
p.s. I'm looking at https://network-pulse-staging-pr-691.herokuapp.com/. Is this the latest branch?

**Comment by xmatthewx** [comment]
When I view https://network-pulse-staging-pr-691.herokuapp.com/myprofile/

I see the form but no fields. 

<img width="614" alt="image" src="https://user-images.githubusercontent.com/53411/31180790-8490007a-a8ed-11e7-8503-380d432b6a7e.png">

**Comment by xmatthewx** [comment]
Hold the phone. The API might be down. @alanmoo is investigating.

**Comment by alanmoo** [comment]
https://network-pulse-staging-pr-691.herokuapp.com/myprofile works again

**Comment by xmatthewx** [comment]
This is looking good. 

One thing I noticed ... but we can probably file as a follow up .... my profiled defaulted to name from google (that's good), but when i edit my profile, name field is blank. this is not terrible, but odd.

**Comment by mmmavis** [comment]
@xmatthewx Let's file a new ticket for that. Since edit form is working... can we close this ticket now?

**Comment by xmatthewx** [comment]
Yes! This is a big one! You want to have the joy if hitting the button? 💥💥💥💥

**Comment by mmmavis** [comment]
Implemented as part of https://github.com/mozilla/network-pulse/pull/691 🎉
