### ISSUE TITLE
Update dark grey to black

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#628]
[New Mozilla brand](https://mozilla.ninja/) uses black instead of dark grey. We need to update the 'add project' icon and the footer to black.

https://redpen.io/projects

Related to font update https://github.com/mozilla/network-pulse/issues/614

**Comment by Sudip7** [comment]
hey @kristinashu  though I don't have much knowledge on design, I would like take this ticket. Would you please assist in location the css files for this project. I was looking at https://github.com/mmmavis/network-pulse/tree/gh-pages/css to get some idea but similar structure is not available here. Please assist.

**Comment by kristinashu** [comment]
Awesome, it would be great if you did this @Sudip7! Unfortunately I don't know where the file is either. @mmmavis are you able to point it out? Is it related to our [Mofo Bootstrap](https://github.com/mozilla/mofo-bootstrap)?

**Comment by Sudip7** [comment]
@kristinashu , m not sure but I believe it's probably a  forked repository or a new one created by her. 
@mmmavis  would you please assist me on this. Then I may able to try the #614 .

**Comment by mmmavis** [comment]
For changing background colour of the footer we should update [mofo-bootstrap](https://github.com/mozilla/mofo-bootstrap) so this colour change will reflect on other sites like the Network site. (I'll create a ticket on mofo-bootstrap and self assign)

For changing the colour of the "Add Project" button on Network Pulse it'll only require updating a [colour value](https://github.com/mozilla/network-pulse/blob/93492bdb0d5cb5633be24e1c4281a1f3036622ae/components/navbar/navbar.scss#L51) in a `SCSS` file.

@Sudip7 the `gh-pages` branch on my forked repo was for Pulse v1 (jQuery-based, uses vanilla CSS). We are no longer updating that branch and the branch you should be looking at would be the `master` branch of this Mozilla repo 😃 Pulse is now React-based and uses SCSS which its syntax is pretty CSS-alike. Let me know if you'd like to work on updating the colour of the "Add Project" button (the plus sign button at top right of Pulse page)!

**Comment by Sudip7** [comment]
I would love to do that. Should I look for main.scss or any other file to change the font or color. Pulse v1 repo css config was bit straight forward but still I would like to dirty my hands. Please assist.

**Comment by mmmavis** [comment]
Hey @Sudip7 take a look at my previous comment. I've included a link that brings you directly to the line of code that needs changing. This one should be straightforward to fix.

**Comment by Sudip7** [comment]
@mmmavis and what about #614, is that too belongs to mofo-bootstrap or can be done in pulse.

**Comment by mmmavis** [comment]
@Sudip7 I might need to loop other devs in for that one. Let's bring this conversation over to #614.

**Comment by Sudip7** [comment]
Thanks @mmmavis . Do you use standard color codes or you have anything specific for mofo projects?

**Comment by Sudip7** [comment]
I looked into https://mozilla.ninja/visualelements/ and believe #000000 should accomplish the task.  @kristinashu please confirm.

**Comment by mmmavis** [comment]
@Sudip7 either `#000000`, `black`, or `$black` will work technically. However, for colours that have been declared as variables (for example, https://github.com/mozilla/mofo-bootstrap/blob/ce155ef07cb380bf33169b291c78eb2fbcc3577c/src/scss/custom/_colors.scss) I tend to use `$variablename`. In this case I would do `$black`.
