### ISSUE TITLE
Draft QA Script

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#63]
Let's draft a list of expected rendering and interaction behaviors to prep for QA tests.

**Comment by xmatthewx** [comment]
Edit and add to this list...

### Pulse opened
 - [ ] projects load
 - [ ] cards display in rows of equal height
 - [ ] cards display in columns to fit browser width
 - [ ] cards contain title, a paragraph or two of text, and buttons for...
 - [ ] ____ button opens a external link in a tab
 - [ ] link button reveals a URL to share (selected to copy on desktop)

### Project shared. User opens link.
 - [ ] single project detail view displayed

**Comment by kristinashu** [comment]
@xmatthewx added a bunch of tests ^

**Comment by xmatthewx** [comment]
This is done. Added to [the wiki](https://github.com/mozilla/network-pulse/wiki/Quality-Tests). Communicating in #77
