### ISSUE TITLE
Form allows empty creator

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#632]
It seems like a user can click "add another creator" but leave it blank, submit it and set an empty creator. See comas in two entries below.  

<img width="721" alt="screen shot 2017-08-02 at 11 29 29 am" src="https://user-images.githubusercontent.com/53411/28881367-e46cd9e0-7775-11e7-9830-de4fe689cfce.png">

**Comment by mmmavis** [comment]
PR in review: https://github.com/Pomax/react-formbuilder/pull/43

**Comment by Pomax** [comment]
reopening because just fixing formbuilder doesn't necessarily fix this here  =)

**Comment by Pomax** [comment]
formbuilder v0.7.0 pushed to npm
