### ISSUE TITLE
Code improvement for project card related components

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#633]
This is a followup for https://github.com/mozilla/network-pulse/pull/617 based on @Pomax 's suggestion: https://github.com/mozilla/network-pulse/pull/617#pullrequestreview-53665838

@Pomax could you suggest how we can improve project card related things better?

**Comment by Pomax** [comment]
do we want to keep this issue open? If so, what work is required?

**Comment by mmmavis** [comment]
@Pomax if you could suggest how we can solve the "too many components are imported" issue in both https://github.com/mozilla/network-pulse/pull/617/files#diff-7fcf4b685bc6ee5d5d682e1c6cf12627 and https://github.com/mozilla/network-pulse/pull/617/files#diff-9ce64733fe7a204e270fad8337eecef5 I'd love to make those improvements. There used to be just one `project-card` component with tons of if-else checks there and this made updating the code hard there. Since now that we have different project card views (regular list view, moderation view, detail view) and they differ quite much I extracted share components into their own files and had two `project-card` components (one for list view one for detail).

**Comment by Pomax** [comment]
If all these "meta" components are "for the same purpose" we could namespace them. For instance:
```
import ReactGA from 'react-ga';
import { Link } from 'react-router';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import bookmarkManager from '../../js/bookmarks-manager';
import ModerationPanel from '../moderation-panel.jsx';
import BookmarkControl from '../bookmark-control.jsx';
import * as Meta from './meta';

...
render() {
  ...
  <Meta.Creators ...>
  ...
  <Meta.Description ...>
  ...
}
```
Does that feel like a decent start at simplifying the code prior to a heavier refactor to unify the different project cards as much as possible? (I'd recommend doing that as a separate issue, too, to keep the tasks small)

**Comment by mmmavis** [comment]
Sounds good!

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
