### ISSUE TITLE
Enable users to preview before submitting an entry

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#636]
Submitting an entry is scary and error prone. Editing a moderated submission later is [complicated](https://github.com/mozilla/network-pulse/issues/472#issuecomment-320081926). To address these, let's consider a preview during submission. 

Form > Preview > Submit

Is this technically complicated?

**Comment by kristinashu** [comment]
I'm not sure what the best UX is but here's one option.

#### 1) Add a "Preview" button to form:

![desktop - form 2x](https://user-images.githubusercontent.com/1068783/29438259-5ccf992c-836a-11e7-9b33-c49ea060c5e2.png)

#### 2) Show preview with notification at the top: 

- main nav and footer are hidden (not sure if that's best?)
- links in post are active??

![desktop details latest 2x](https://user-images.githubusercontent.com/1068783/29438260-5cd45246-836a-11e7-95bd-55e6cabe0283.png)

**Comment by xmatthewx** [comment]
This looks good. I wonder if we don't want to simplify the form by removing Submit and only offer Preview as the next step. In addition to catching typos, the Preview will do wonders to improve lackluster copy and poorly cropped photos.

**Comment by kristinashu** [comment]
I like the idea of forcing people to preview but worry people won't read the button, click Preview and then leave thinking they are done posting.

**Comment by xmatthewx** [comment]
Ah... great point. Let's go with your instinct on this. 

Left alignment on that preview button feels funny, but it might just be me.

**Comment by kristinashu** [comment]
Ok, I've grouped the two buttons together https://redpen.io/zv6f73b34b59d981c7

@mmmavis does this work for you? Have any questions?

**Comment by kristinashu** [comment]
Good point @mmmavis. I agree we should disable our links (like tags, usernames, share and fav icons) but am on the fence about disabling links the user added (like Visit and Get Involved) since they might want to double check these. I think as long as they open in a new tab, then it should be ok for them to be active. But I'm also open to disabling all links.

**Comment by xmatthewx** [comment]
Good catch @mmmavis. I also agree that the links are useful for testing, even checking to see if you've linked to the right creator.

Could we intercept and make all preview links open in a new window?
