### ISSUE TITLE
Explore discovery via Interests

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#638]
For both Pulse and the Network site, we have an opportunity to enable discovery in fun ways. In addition to the 5 issues, we can leverage our thematic priorities (open data, misinformation), as well as more informal interest areas (games) or affinities. 

Following our current priorities, this could be one of the things we dig into next.

To start, let's gather benchmarks from Spotify, Meetup, Pinterest, and other platforms to wrap our heads around the opportunity.

**Comment by cadecairos** [comment]
This seems a bit out of date (i.e. the five issues), lets close it out and it can be re-filed based on actual work that can be prioritized in the future.
