### ISSUE TITLE
Add MoFo in the News

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#64]
Articles about Mozilla Foundation are a valuable asset. They're currently tracked by Kevin, shared and archived in all staff emails. 

Let's add articles from first half of 2016 to Pulse. They're in an email with subject: [Mozilla Foundation in the news](https://mail.google.com/mail/u/1/#inbox/155bb2c051e85662) << This link _might_ work. I already added The Atlantic Article.

This is an opportunity to observe staff adding assets to Pulse. Would be good to include Lotta.

**Comment by KevZawacki** [comment]
@xmatthewx Hey, happy to help here. Can you re-share the upload form for Pulse? Thanks!

**Comment by xmatthewx** [comment]
Thanks @KevZawacki. The form definitely isn't optimized for articles at this stage. Please keep notes about your experience using it. 

Note: we aim to keep the form relatively simple, and then add additional info during triage in the spreadsheet to identify relationship to programs, issues, etc. I'll send you spreadsheet edit access for additional columns.

Look for the big plus button on https://mzl.la/pulse

**Comment by KevZawacki** [comment]
@xmatthewx Thanks! I've just added several recent stories. A couple notes:

-- This will be a great tool for tracking down [Read, Write, Participate](https://medium.com/read-write-participate) content

-- On that note: Perhaps add a "How Can Interested People Contact You?" section to Basic Info. 

-- Can we find an easy way for the "Get Involved" button on the front end link to an email send?

-- Possible to organize the spreadsheet on the back-end in reverse chronological order?

**Comment by xmatthewx** [comment]
Great questions @KevZawacki.

> Perhaps add a "How Can Interested People Contact You?" section to Basic Info,

For this MVP version, spreadsheets limit us in terms of privacy, so we won't collect personal info. We could add a submitted by field (for staff submitting things created by someone else). I bet most entries won't be too difficult to track down. 

We're going to do a concerted test with staff in the near future (#48). If that goes well, we can explore setting up a real backend.

 > Possible to organize the spreadsheet on the back-end in reverse chronological order?

We might be able to set up a secondary tab, prepped for sorting and filtering. 

> Can we find an easy way for the "Get Involved" button on the front end link to an email send?

Do we have a media/press inquiry page for you? You could link there for articles you submit. If we don't have one, we might add one on the wiki or under something like mozilla.org/foundation/inquiries. 

[New design](https://redpen.io/mve7a49a24885c95c0/3) coming soon!

**Comment by KevZawacki** [comment]
@xmatthewx Thanks for the quick response. Re: Q3 -- Yep, I can track down a contact page to use. 

New design looks excellent!

**Comment by xmatthewx** [comment]
Thanks @KevZawacki. I can add the contact page link to each item when you've got it. I've filed tickets for other bits.

**Comment by xmatthewx** [comment]
Follow up tickets filed. Done enough for me.
