### ISSUE TITLE
Search includes moderation param in URL

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#643]
A search incorrectly appends URL with a moderation param. It does this even if a user is _not_ logged in. Note: this does not effect search results, so it is not broken. 

Steps to Repeat
 - Go to https://www.mozillapulse.org/search
 - Search for "mozfest"
 - URL is now: https://www.mozillapulse.org/search?keyword=mozfest&moderationstate=Pending

If you visit https://www.mozillapulse.org/search?keyword=mozfest directly, parameter does not get added. It only happens with interaction on search form. It's also odd that the param is pending, but pulse displays approved.

**Comment by xmatthewx** [comment]
@mmmavis I still see this bug on production. Staging looks good. Maybe the fix hasn't been promoted? We should promote stuff every Monday as part of our routine unless a thing is blocked. cc @alanmoo 

<img width="732" alt="screen shot 2017-08-30 at 1 46 51 pm" src="https://user-images.githubusercontent.com/53411/29886921-bf4e5452-8d89-11e7-9fba-3bc001ff0e55.png">

**Comment by mmmavis** [comment]
(I just did a prod push)

> We should promote stuff every Monday as part of our routine unless a thing is blocked

Yup yup sounds like a great idea!
