### ISSUE TITLE
Refine Get Involved for empty fields 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#645]
If an entry has no Get Involved elements (text, link, categories), we shouldn't display the Get Involved header. 

The first two entries submitted that included Get Involved categories, didn't have text or a link. The help tags almost look like buttons to Get involved. I wonder if there's  placeholder text we could put in there in this scenario with categories but no text, no link. 

<img width="831" alt="screen shot 2017-08-11 at 2 31 18 pm" src="https://user-images.githubusercontent.com/53411/29227180-dc63e89a-7ea2-11e7-82e8-b7045ae43ebf.png">

**Comment by xmatthewx** [comment]
Scenarios
 1. no link, text, categories => hide section
 2. categories only => fallback text?
 3. text or link only => display normal?

### 2 fallback text

does this work?

<img width="832" alt="screen shot 2017-08-11 at 2 38 29 pm" src="https://user-images.githubusercontent.com/53411/29227311-67a1019a-7ea3-11e7-8330-05ea20ea0739.png">

**Comment by kristinashu** [comment]
Seems like a good solution to me!

**Comment by xmatthewx** [comment]
@mmmavis - we have a bit of follow up on this to deal with entries with missing "get involved" info. 

Scenario => What we display  
 - no link, no text, no categories => hide section
 - text or link only => display normal
 - categories only => display fallback text: "Help with this, or find other projects that have similar ways to get involved." (see mockup above)

**Comment by kristinashu** [comment]
@xmatthewx can you please also review this one? Everything is much better and showing up as you suggested. The only case where it still feels slightly odd is when there is only a link. So we see the title "Get involved" followed by link "Get involved" e.g. https://network-pulse-staging.herokuapp.com/entry/201 Is that ok?

**Comment by mmmavis** [comment]
https://network-pulse-staging.herokuapp.com/entry/336
 https://network-pulse-staging.herokuapp.com/entry/336
 https://network-pulse-staging.herokuapp.com/entry/336
 https://network-pulse-staging.herokuapp.com/entry/336

**Comment by mmmavis** [comment]
I've created some test entries

 https://network-pulse-staging.herokuapp.com/entry/336
 https://network-pulse-staging.herokuapp.com/entry/337
 https://network-pulse-staging.herokuapp.com/entry/338
 https://network-pulse-staging.herokuapp.com/entry/339
 https://network-pulse-staging.herokuapp.com/entry/340

**Comment by xmatthewx** [comment]
Thanks so much for the handy QA links @mmmavis!!! yer the best. 

@kristinashu – re: link only.  Hmm.... not ideal. Maybe we could display the URL as a link if there's no description, but keep it as "Get Involved" if there is a description?

**Comment by xmatthewx** [comment]
@mmmavis - this otherwise looks awesome. Thanks for the speedy and diligent _if else if else if else if_ work.

**Comment by kristinashu** [comment]
Awesome thanks @mmmavis!

@xmatthewx ah there's gonna be some long ugly URLs out there...

Let's close this and push it to prod. We can always open up a new ticket if it really bothers us.

**Comment by xmatthewx** [comment]
I'm a nerd and took a look at the DB. About 10% of featured posts have a link but no description. About a third of all posts with a help link have no description. I think we
