### ISSUE TITLE
Communicate shortlink

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#65]
I've created a shortlink. Let's use it. Check off your name when you've memorized it.

### https://mzl.la/pulse

 - [x] @kristinashu 
 - [x] @acabunoc 
 - [x] @mmmavis 
 - [x] @cadecairos 
 - [x] @hannahkane 

> Pulse – A stream of assets from peers across the Mozilla Network

**Comment by cadecairos** [comment]
too long, needs to be more memorable ;)
