### ISSUE TITLE
Extend Profile with 'Official' Fields

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#657]
These fields are unlocked by a moderator and then revealed on a profile and profile form. From a user's perspective, they are just an extension of the profile. 

Functionality
 - [x] A staff editor should be able to toggle an extended profile on/off
 - [ ] A user should be able to edit their extended profile, after it is unlocked by staff moderator

See mockup: https://redpen.io/qua34b5932cdb6cf9f

**Comment by xmatthewx** [comment]
These extended existing profile model. Should we discuss in a google doc first and then bring back here? cc @alanmoo 

Moderator
 - Extended (true/false)

General
 - Location (City, Country)
   - As string for now? gOptimized from the start?
 - Language(s)
   - Not MVP

Program (0 to many)
 - Program Type (ex: Tech Policy fellow)
 - Program Year
 
Affiliation (2? 0 to many?)
 - Org #1
   - rel: is_group profiles
   - Title #1
 - Org #2 
   - rel: is_group profiles
   - Title #2

Bio
 - Quote (212 characters or less) (about internet health, movement, fellowship etc.)
 - Long Bio (long enough to fit a story engine interview)

**Comment by xmatthewx** [comment]
We will need to unblock orphan profiles that have no user.

**Comment by Pomax** [comment]
bio thoughts: see if there's a way to set wiz'e'wig to markdown mode, if not it's probably easiest to just give people the standard edit field for filling in their bio

**Comment by xmatthewx** [comment]
I added a few more notes in list above as well to capture some of the discussion.

**Comment by Pomax** [comment]
@xmatthewx we currently have the 140 character bio, is the 212 short bio the same thing but with a new limit? Or is this a different short bio?

**Comment by alanmoo** [comment]
@Pomax I'm like 99% sure the 212 is for a quote by the person about the open internet. So, different thing.

**Comment by xmatthewx** [comment]
@Pomax I think it's that we have a 140 character limit on bios in pulse, and 212 limit on bios in foundation site model. it's like twitter old and almost new. We can up our Pulse limit so we don't have to shorten existing strings. It won't impact design. 212 is an odd number, but definitely what I see we're requesting from fellows.

**Comment by xmatthewx** [comment]
it's the same short bio. one field, lengthened to 212 char, to fit content we will eventually copy-paste from foundation site to pulse.

**Comment by Pomax** [comment]
roger!

Secondary question: is program type a specific list of type-of-fellowship, or just the single "Mozilla Fellow"?

**Comment by xmatthewx** [comment]
Hmm... are you asking whether we should identify a person as a Fellow (any kind), and then identify their specific program separately? If so, good question. If not, please clarify. 

It's probably a good idea to have a fixed fellow boolean or category in addition to staff defined program categories that will evolve. Like staff, they're a pretty unique case.  Others like this: board member, grantee, grantor. I think that covers all the common people/orgs we'd profile with a significant legal or financial relationship. True? Anything else? 

Straw fox: 
 - profile.type | .relationship : null | staff | fellow | board | grantee
 - profile.program : null | tech policy fellowship | mozfest speaker | ... [added by moderator]
 - profile.program.year : null | YYYY

**Comment by Pomax** [comment]
That's indeed it. Do we:
- mark users as "Mozilla Fellow" with an (optional?) way to say their specific fellowship is "Science", or
- mark users as "Mozilla Science Fellow", "Mozilla Open Internet Fellow", etc.

Right now for mvp we're just using "Mozilla Fellow" with no additional field to indicate the "kind" of fellowship.

As for the straw foxes:
- can any of staff/fellow/board/grantee overlap? (can someone be a fellow _and_ grantee, for instance?)
- this sounds like an admin-modifiable list, so we'll probably need a new Model for that and then mark it as a relation so we can do the live-editing by admins on the site
- Is there a start date we want to cap from? (right now it's set to start the list at 2001, even though the foundation itself didn't yet exist back then)

**Comment by xmatthewx** [comment]
For fellow program, I think we can assume Mozilla and say "Senior Fellow". We'll want staff to update program names, so we should assume some messiness. 

Something like this?
 - `GET /api/pulse/profiles/?relationship=fellow`
 - `[{ name: 'Georgia', relationship: 'fellow', program: 'Senior Fellow', program_year: '2017' },...]`

> can any of staff/fellow/board/grantee overlap?

I think we can rule out more than one designation at the same time. People might switch, but I can't think of an instance of someone overlapping.

> this sounds like an admin-modifiable list, so we'll probably need a new Model for that

Sounds right.

> Is there a start date we want to cap from? 

Maybe 2010? Nice round number?

**Comment by alanmoo** [comment]
>> can any of staff/fellow/board/grantee overlap?
>
>I think we can rule out more than one designation at the same time. People might switch, but I can't think of an instance of someone overlapping.

Which means I would think they should be able to have multiple relationships attached, so when someone moves from, say, fellow to staff we can still see them in the list of fellows for a previous year. Sound right?

**Comment by Pomax** [comment]
The choice for 2001 is mostly because it lets me start a python numbered dictionary at array possiong 1 = 2001, 2=2002, etc. @xmatthewx would 2011 be fine, too? then we can do 1 = 2011, 2 = 2012, etc =)

**Comment by xmatthewx** [comment]
> would 2011 be fine, too? 

Yep @pomax. Whatever makes implementation easier.

**Comment by xmatthewx** [comment]
> Which means I would think they should be able to have multiple relationships attached, so when someone moves from, say, fellow to staff we can still see them in the list of fellows for a previous year. Sound right?

That's true @alanmoo, but still probably rare. We should implement now if it's trivial work or saves wild effort later. Else, we can wait if situation arises.

**Comment by alanmoo** [comment]
After a call with Pomax, we've figured out the following work needs to be done:

Profile type needs to be added (null | staff | fellow | board | grantee) (Many:1)
Profile program (Science Fellow, Tech Policy Fellow, etc) (Many:1)
Program year (Many:1 for profile:year)
Affiliation (char field for now)

In terms of accessing this:
Query set that can be filtered on profile type, program, and/or year (i.e. `/api/pulse/profile?type=fellow&program=tech_policy_fellow&year=2018`). Routes for displaying these options will not be necessary for MVP.

We need migrations to ensure minimal values for these are present.

**Comment by xmatthewx** [comment]
>  Program year (Many:1 for profile:year)

Are years independent of program? Ideally, if I have two programs and two years, I won't be included in a query for both programs for both years, just one year per program. (my brain has turned to work week mush. sorry if this isn't clear)

**Comment by alanmoo** [comment]
Years are independent of program, so we don't have to go through the program model to get a year. Everyone gets to pick one of each for now, we can add support for people having multiple programs/years afterwards, once the API is working and it's not blocking the front-end.

**Comment by alanmoo** [comment]
>Again, if we build this a 0-to-1, that's fine. But it should never be 0-to-many like this. 
I'm not sure I understand this line, but I agree with the rest of your message. We need to have that functionality, but it's not helpful *today*. 

We can add that to the structure of the models next without changing the actual API endpoints, so I think it's important to get this moving so the front-end of the directory can be built.

**Comment by Pomax** [comment]
As I read this, my main question is: are profiles supposed to reflect the now (e.g. forum profiles etc.) or track a user's history (e.g. facebook etc). Because while both of those yield identical query APIs, the latter is far more complicated, and requires a redesign of the data structure and logic that we use server side to track units of related information over time.

That said, they're not mutually exclusive, so I think Alan's idea makes the most sense for MVP around extended profiles right now: the simple snapshot version of profiles gives an API that the front end and move forward with, which should now give use about a year to plan in the backend redesign to turn static profiles into history-tracking profiles. without having to change the API side of things. Does that sound like a reasonable path?

**Comment by xmatthewx** [comment]
I think yes. You're right, we have a year before things could get complicated. I'm all in favor of keeping things simple now. I just didn't want to surprise you later. That wouldn't be nice.

I wonder if we should just drop the year field and include that in the value set in program (e.g. program: 'science fellow 2017'). That will give us a longer list of programs, but reduces complexity.

**Comment by Pomax** [comment]
I think, looking at how Django does URL argument filtering, if we do that we lose the built-in way to query the current year, so the gain in simplicity on the model side would probably be offset by the increase in difficulty to intercept the API search parameters and rewrite them to work with the simplified model.

Post-mvp we should probably make a model that captures a full "program", so with a name, a year/year range, and its affiliation(s), and then linke profiles and programs as 1(profile)-to-many(programs) so that we can link any person to zero or more specific programs. At that point also we can also update the filtering to easily "fall through" to the values contained by individual programs.

From a technical stand point, Django does that in a rather interesting way. Unlike trying to match two different queries into the same field, requires quite a bit of custom code, "going deeper" is baked right into Django already and means changing `program_year__value` (which resolves a `profile -> program_year`) to `program__year__value` (resolving to `profile -> program -> year`) without any additional work.

**Comment by xmatthewx** [comment]
You're right. My suggestion was silly at best. We definitely need a separate field for year.
