### ISSUE TITLE
Build a "Collections" feature for CMS authored Pages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#661]
Background: Mozilla programs need to gather and present the people and projects impacted by the program. This serves recruitment, fundraising, reporting, and more. 

Idea: Enable an author who creates a Page via CMS to optionally specify a Pulse query to pull in Projects and/or Profiles. 

 - Requirements gathering started in #630. See [notes](https://docs.google.com/document/d/1dZ4ZwfTjJA_AdN8lWG3oW650e2-nPttg0rZmrGEFqGA/edit#).
 - Quick mockup drafted in #646 to guide discussion. See [comp](https://redpen.io/vzf9efadfec9443e15).

**Comment by gideonthomas** [comment]
done
