### ISSUE TITLE
Bug: Links to Anchors hidden under fixed nav

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#662]
As noted by @arush0311, links that point to mid-page anchor links, scroll to content that then gets hidden by the fixed position nav. It's confusing to users. 

This can't be universally solved by adding white space in the content or padding on headers since an anchor could fall before any element and a big white space can make the content look broken. 

Should we consider a lightweight JS solution that sniffs out anchor link clicks and adjusts the scroll based on the height of the nav bar? Good idea? Bad idea? 

This isn't a mission critical bug, but one worth squashing. 

cc @gvn @alanmoo

**Comment by mmmavis** [comment]
@xmatthewx wrong repo? 😉

**Comment by xmatthewx** [comment]
Issue moved to [mozilla/network #675](https://github.com/mozilla/network/issues/675) via [**ZenHub**](https://www.zenhub.com/)

**Comment by xmatthewx** [comment]
whoopsie doopsie
