### ISSUE TITLE
Delete Creator 244 and associations. Name is empty.

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#667]
The two most recent posts have some odd commas. Is this because users are randomly adding commas or is it something on our end?

<img width="629" alt="screen shot 2017-08-17 at 10 55 55 am" src="https://user-images.githubusercontent.com/1068783/29432779-b8ba2892-8351-11e7-8448-94a27c7b25d5.png">

cc @xmatthewx @Pomax @mmmavis

**Comment by xmatthewx** [comment]
My guess: if you hit the add creator button, but leave the last space blank when you send, we add a creator called "(blank)". I just checked, and Mrs Blank has contributed to more projects than everyone else, accept Mozilla.

**Comment by mmmavis** [comment]
Good catch. A patch has been pushed live few days ago which should prevent this from happening in the future.

Related ticket: https://github.com/mozilla/network-pulse/issues/632

**Comment by xmatthewx** [comment]
Creator_ID = 244

**Comment by Pomax** [comment]
@xmatthewx you should be able to delete this user through the admin, by hitting up https://api.mozillapulse.org/admin/creators/creator/244/change/ and clicking "delete". This should also "unlink" it from all entries that make use of it in their creator list.

**Comment by xmatthewx** [comment]
Done. Thanks. Sorry I was in a tags migrations mindset ... overlooked the obvious.
