### ISSUE TITLE
Search terms creates a unique url

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#67]
As mentioned in https://github.com/mozilla/network-pulse/issues/58, if I enter a search term I should be able to copy that url and send it to someone so they go straight to a page with those search results (and any new ones that my have been posted during fitting the criteria). This is something that came up in an interview today and would be very useful.

@mmmavis what do you think?

**Comment by mmmavis** [comment]
Yup yup I like this idea. However, we need something to trigger the URL update. Currently the searching feature searches as you type, i.e., users don't have to hit enter to trigger the search. I'm not sure at which stage we should update the URL so that it includes the search terms.

**Comment by xmatthewx** [comment]
Fantastic idea. Let's keep our eye on core MVP features, but I love this. 

We could have a small link icon by search. This would reveal that people could share a specific list. 

@mmmavis – if it's not jittery, we could just update as they type. If it is, we could update when they tap link icon. 

We shouldn't require enter – I think that is a less good search experience – just for this edge case.

**Comment by mmmavis** [comment]
@xmatthewx ummm let's not update the URL as people type - this approach seems pretty uncommon 😬

**Comment by xmatthewx** [comment]
You are so so right @mmmavis. I think I was asleep at the wheel. Don't git while driving! 🚗 💥 🚚 💨   

What if we updated when the user shows more intent? 
 - update on blur following input
 - update on enter (even though enter doesn't do anything else)

**Comment by kristinashu** [comment]
@mmmavis what did we say about this yesterday? Tackle it next heartbeat?

**Comment by xmatthewx** [comment]
I'd like to give this a try, even if it's a small pain. It can be hacky for now. It's a small feature that will demo big possibilities for program staff.

If it becomes a nightmare, we can pull the plug.

**Comment by kristinashu** [comment]
Ok, moving to next heartbeat.
