### ISSUE TITLE
"Favs"

### ISSUE THREAD

**Issue by gvn** [mozilla/network-pulse#671]
This spelling seems odd to me. I feel like I've always seen "Faves" as short for favorites.

I guess there's [some debate](https://www.fastcompany.com/3034831/fave-vs-fav-a-linguistic-explanation) though.

`¯\_(ツ)_/¯`

**Comment by hannahkane** [comment]
I'm on Team Faves :)

**Comment by xmatthewx** [comment]
Omg. I love that the linguist preferred to remain anonymous in this debate. I'm on Team Fav, though moved slightly by Zimmerman's note that "Some people prefer ‘fav’ as a noun and ‘fave’ as a verb."

**Comment by kristinashu** [comment]
Haha let the battle begin! I _slightly_ prefer Favs but only because it's _slightly_ shorter, so it fits better in the nav.

**Comment by gvn** [comment]
If Pulse is ever translated it'll get longer (or if someone increases their text size).

#justsayin 😉 

I'd suggest "Faves" and then a ❤️ wherever space is at a premium.

**Comment by hannahkane** [comment]
Closing, as this is a religious debate that will never be solved to everyone's satisfaction.
