### ISSUE TITLE
"Location" field on profile

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#675]
@Pomax @xmatthewx @hannahkane @kristinashu @alanmoo @gvn 

I think we've briefly talked about this during the stands before, but I can't recall if we've come to a conclusion. Have we decided what to store for the location field? Is it just one field that is comprised of `City/Town, Country` as one string? Or when showing on the front end, a combined meta that is comprised of two fields - `City/Town` and `Country` . 

Mockup for profile form: https://redpen.io/bk7c2a3cbaafdcd47a
Mockup for profile page: https://redpen.io/qua34b5932cdb6cf9f

**Comment by gvn** [comment]
I believe that the Google location API will return a structured object, which I would suggest storing in its entirety (or storing select fields as structured data since we don't want to get too specific for privacy reasons). 

If we ever want to do more than display an address string you're going to want to work with structured data. Creating structured data from single string addresses would be extremely difficult.

**Comment by mmmavis** [comment]
Agree that storing structured data is better for this case. I will check out Google Places API docs today but others please feel free to leave your thoughts here.

**Comment by xmatthewx** [comment]
We want to store parts of google's blob. For users, we want to leverage City/Town and Country. 

Next step: 
 - [ ] We need to add Location to the Profile model. File ticket: @gideonthomas @mmmavis  @alanmoo

**Comment by mmmavis** [comment]
I read through the docs and did some tests. I think we can use the [Google Place Autocomplete API](https://developers.google.com/places/web-service/autocomplete) to fetch place suggestions. We can restrict the search type to [`cities`](https://developers.google.com/places/web-service/autocomplete#place_types) so we don't record anything more specific than "city" info.
> the `cities)` type collection instructs the Places service to return results that match `locality` or `administrative_area_level_3`.

and from https://developers.google.com/maps/documentation/geocoding/intro#Address%20Types%20and%20Address%20Component%20Types

> - `locality` indicates an incorporated city or town political entity.
> - `administrative_area_level_3` indicates a third-order civil entity below the country level. This type indicates a minor civil division. Not all nations exhibit these administrative levels.

- If user types in an address like `163 West Hastings St` the Place API responses back with 0 result as there's no such "city" called `163 West Hastings St`.
- If user types in a "city" name or a name that's belong to higher geographic level the Place API will responses with matching places.

Sample response schema can be found [here](https://developers.google.com/places/web-service/autocomplete#place_autocomplete_responses).
See response from searching "Vancouver" [here](https://jsonblob.com/42290da6-943a-11e7-80fd-75be2164b3ee).

Example requests:
- https://maps.googleapis.com/maps/api/place/autocomplete/json?&types=(cities)&key=YOUR_KEY&input=163%20West%20Hastings St
- https://maps.googleapis.com/maps/api/place/autocomplete/json?&types=(cities)&key=YOUR_KEY&input=Vancouver
- https://maps.googleapis.com/maps/api/place/autocomplete/json?&types=(cities)&key=YOUR_KEY&input=British%20Columbia

(Get your API key [here](https://developers.google.com/places/web-service/get-api-key))

**Comment by gvn** [comment]
Yeah I think so as long as we can parse city and country from the response.

**Comment by alanmoo** [comment]
🕸
