### ISSUE TITLE
Design empty screens

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#68]
Need copy and design for empty favs, failed search, and category screens.

**Comment by kristinashu** [comment]
Here are some rough screens to get the ball rolling. I don't think we need to have the empty category screen, we should just make sure we have something for each category.

![mobile - empty likes 2x](https://cloud.githubusercontent.com/assets/1068783/17232581/0795fc8c-54de-11e6-8651-0b4ca0809825.png)
![mobile - empty search 2x](https://cloud.githubusercontent.com/assets/1068783/17232582/07a28330-54de-11e6-8eb8-fd46dd10ce1e.png)

@xmatthewx can I leave copy to you?

Few references http://pttrns.com/?scid=30

**Comment by flukeout** [comment]
For an empty Likes screen, you could show recent projects below the copy so someone could find something they like quicker.

**Comment by xmatthewx** [comment]
Here's some copy @kristinashu 

 - Search: **Nothing found** // Try another search or submit something new!
 - Empty favs: **Save your Favs** // Tap the heart on any project to save it here.
 - Issues landing: **Our Issues** // Mozilla has identified five issues critical to a healthy and open internet. Tap above to browse by issue.
 - 404: **Something's wrong** // Check your URL or try a search. Still no luck? Let us know [github link].

**Comment by kristinashu** [comment]
Perfecto, thanks @xmatthewx! All updated https://redpen.io/p/by8c797c413d39c620
