### ISSUE TITLE
Broken styling on issues

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#682]
![screen shot 2017-09-05 at 3 34 15 pm](https://user-images.githubusercontent.com/5816130/30080040-3e95aa38-9250-11e7-91be-7d6ba4115afd.png)

See that on prod ^. Not sure if this was already filed or not so feel free to close.

**Comment by mmmavis** [comment]
@gideonthomas if you give it a few secs to load do you see buttons like this?

![Uploading Screen Shot 2017-09-05 at 12.48.57 PM.png…]()

**Comment by gideonthomas** [comment]
Hmm I still see it as simple links...don't see any styling with it. Tested both FF and Chrome

**Comment by xmatthewx** [comment]
Strange. I see the buttons in Chrome and FF. Refreshed a few times, but remained okay.

**Comment by gideonthomas** [comment]
I swear I'm not crazy :P it wasn't working before, but now it is. Closing, sorry!
