### ISSUE TITLE
Spawn a Heroku instance for "all-things-profile-related" branch

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#684]
We have a feature branch [`all-things-profile-related`](https://github.com/mozilla/network-pulse/tree/all-things-profile-related) for profile related work. To make it easier for people on the team to check out the ongoing profile work we should spawn a Heroku instance. I'm unsure what needs to be done so this Heroku instance has backend properly set up / is whitelisted from Pulse API (staging? production? or?).

/cc @alanmoo @gideonthomas @Pomax

**Comment by alanmoo** [comment]
Once that branch is ahead of `master`, open a PR labeled "WIP" and a PR will be spun up automatically.

As for the API, I believe we'd want to point it at staging, since it should have the endpoints you need to be able to open PRs, though they might not be deployed. So then I believe we'd need to set an env variable on the staging API to allow the client side review app to access it.

**Comment by xmatthewx** [comment]
So... can we close this issue then?

**Comment by mmmavis** [comment]
Not yet as we haven't had a instance set up for the `all-things-profile-related` branch. I can open a PR once `all-things-profile-related ` is head of `master`. We also need to make sure that Heroku instance is able to make API requests to staging Pulse API as well.

**Comment by mmmavis** [comment]
k here it is: https://network-pulse-staging-pr-691.herokuapp.com/featured @alanmoo @Pomax @gideonthomas do we add that url to staging Pulse API's `CORS_ORIGIN_WHITELIST`?

**Comment by alanmoo** [comment]
Yup, I believe so. Wanna do that then close out this ticket?

**Comment by mmmavis** [comment]
Done! https://network-pulse-staging-pr-691.herokuapp.com 🎉 🎉 🎉

**Comment by mmmavis** [comment]
Reopening this ticket cuz @gideonthomas and I were able to get the `redirect_url` on pulse api properly set up. We will have to pick @Pomax 's brain on this when he's back from PTO.

Status so far:

1. https://network-pulse-staging-pr-691.herokuapp.com set up
2. updated 3 env vars on **staging** Pulse API: csrf, cors, redirect_uris (we didn't touch Google Client cuz we didn't have access to it)
3. GET calls seem fine
4. Problem is we are unable to log in via that Heroku instance. @gideonthomas said this might be the reason why - https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L43 (it only takes the first value in that env var as the redirect_url )

**Comment by mmmavis** [comment]
Oops I thought I reopened this last week 👀 apparently i didn't...

**Comment by alanmoo** [comment]
Seems like this is working now?

**Comment by mmmavis** [comment]
Confirm that https://network-pulse-staging-pr-691.herokuapp.com/featured is working.

One of my browser addons were blocking cookies that's why login didn't work for me 😅
