### ISSUE TITLE
Profile pages - messages for anonymous users

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#685]
We should decide what messages we wanna show or what pages to redirect anonymous users to for each of the following cases. (anonymous users = users who are not loggedin)

### Edit Profile page
- anonymous user visits `/myprofile` directly
- after loggedin user hits "sign out" on Edit Page

### My Profile page
- anonymous user visits `/profile/me` directly
- after loggedin user hits "sign out" on My Profile Page

Any other scenarios we should consider?

/cc @kristinashu @xmatthewx

**Comment by xmatthewx** [comment]
Do we have a generic 404? I'm okay with that as a first step. Then enhancing that to say something like: 
> "You do not have access to this page. [Login](#) or see [Featured projects](#)."

**Comment by kristinashu** [comment]
Adding...

### Edit Profile page
- anonymous user visits `/myprofile` directly
> "You do not have access to this page. Login or see Featured projects."
- after loggedin user hits "sign out" on Edit Page
> Redirect the user to landing page (like we do now when someone is adding a post)

### My Profile page
- anonymous user visits `/profile/me` directly
> "You do not have access to this page. Login or see Featured projects."
- after loggedin user hits "sign out" on My Profile Page
> Redirect the user to landing page

**Comment by mmmavis** [comment]
Work has been merged to feature branch. Closing.
