### ISSUE TITLE
Default [name] to show on my profile page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#687]
Comp: https://redpen.io/xy10b353c284b04a34 `Alan Davidson` is the `name` field we wanna discuss here.

When this person Alan Davidson visits his profile for the first time, what `name` do we wanna show there? @gideonthomas could you help list all the `name` fields that we are storing in the backend?

I don't know much about the design or backend infrastructure for profile page for **organization**. Is it another scenario we wanna include here?

/cc @xmatthewx @kristinashu

**Comment by xmatthewx** [comment]
My thinking (might be naive) was that...
 - On first sign-in, we create `User` and related `Profile`
 - Google provides `name`, we add it to `User.name`. We also add same thing to `Profile.name`
 - A user can edit their profile, changing `Profile.name` to whatever. 
 - On the frontend, we always display `Profile.name`, never `User.name`
 - `User.name` cannot be edited (only displayed in django, potentially useful for admin) 
 - We always rely on `Profile.id`, for unique identification, linking Entries, etc, not something like `Profile.username`. 
 - `User.id` is just for account purposes, editing `myprofile`, not displaying or linking public profiles. 
 
Please feel free to debate these assumptions. Forgive blunders. Let me know if anything is unclear or ambiguous. 

cc @gideonthomas

**Comment by gideonthomas** [comment]
All sounds good. Two things that still need to be done - `Profile` doesn't have a `name`, but a `custom_name` which isn't automatically set to `User.name` the first time the user logs in (yet), and, it looks like a profile isn't automatically created when a user logs in (though I might be wrong about that).

**Comment by xmatthewx** [comment]
Is this still blocked? Should we move to Up Next?

**Comment by mmmavis** [comment]
Currently front end shows `Profile.custom_name` if it exists in the `Profile.profile`, else it falls back to `name`. If this is the intended behaviour we can close this ticket :)

**Comment by xmatthewx** [comment]
That sounds right to me! I'm going to start a ticket with a QA checklist to make sure test this.
