### ISSUE TITLE
Identify key Analytics Events

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#69]
Let's identify useful things to track. And then identify feasible things with highest value. Edit and update this list: 

### High Value

Item action
 - [ ] Share Intent – User taps `Link button` to reveal URL
 - [ ] Visit – User taps `Visit button` and exits
 - [ ] Get Involved – User taps `Get Involved` and exits
 - [ ] Fav – User taps `Heart button` to Fav a project (Don't worry about un-Favs right now. We need to track activity, not an accurate count.)

Nav action
 - [ ] Views – Track as page views (Featured, Recent, Favs, Categories)
 - [ ] Item view – Track detail views as page views (Ex: .../network-pulse/?id=p1470188181000)
 - [ ] Issues – Track as page views (Ex: .../network-pulse/privacy or  .../network-pulse/?cat=privacy)

Search
 - [ ] Search – User puts focus on the search field 
 - [ ] Found – User visits a search link shared by someone else. Track as page views. (Ex: .../network-pulse/?q=foo)

### Other

 - Add new intent – Someone taps big plus button
 - Sign-up intent – Someone taps footer sign-up link
 - Search – Search terms. Not MVP. Maybe not ever. 
 - Un-Fav – Eh. useful? We see people managing their Fav list.

**Comment by kristinashu** [comment]
Not sure if we'd want to or can we could track how many people click on the + to add a post? Could see clicks vs actual posts?

Also under Other: footer links like Email Signup and Repo link. I guess if no one is clicking on it we could remove them?

**Comment by xmatthewx** [comment]
Yes and yes.

**Comment by xmatthewx** [comment]
I think we can call this done. Implementation tracked in #27.

**Comment by mmmavis** [comment]
reopening this ticket since I have some questions 🐹 

> Get Involved – User taps and exists to visit link

Are these 2 different events to track? Not sure if we will be able to track if user exists to visit link after he/she taps the share link button. We can track them as separate events 1) when user clicks on the share link icon 2) user visits Network Pulse via a direct project link (e.g., https://mozilla.github.io/network-pulse/?id=p1469825978000 )

**Comment by kristinashu** [comment]
Not too sure what you mean? Get Involved seems separate to Share link and the Direct link to a project. But Get Involved aside, it would be best to track Share link clicks separate to the number of visitors to a project detail view (aka a shared post).

**Comment by mmmavis** [comment]
@kristinashu ahhhh sorry i didn't realize those are referencing to the actual buttons on UI - thought they were just descriptions of the event we wanna track

**Comment by xmatthewx** [comment]
Yep. Some Events will have a UI button. Others don't. I'll look at the list now and see if I can clarify anything.

**Comment by xmatthewx** [comment]
I added some notes above. Focus on things you're able to track now. Don't worry about other parts that aren't ready yet. We can add those later.

**Comment by hannahkane** [comment]
Moving to current heartbeat, so I can close past milestones

**Comment by kristinashu** [comment]
Oh, I think we can close this again. @mmmavis please reopen if you still need it
