### ISSUE TITLE
Add an image to Entry 431

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#693]
Solana contacted us with the handy correction link contact form. Missed the option to add an image to her entry. https://www.mozillapulse.org/entry/431

Entry description might also be edited to let visitors know that link leads to an interview.

**Comment by xmatthewx** [comment]
@solanasaurus - you can add an image and edits here if you want. We'll get that fixed for you.

**Comment by Solanasaurus** [comment]
Here's the photo ![dw and mozilla](https://user-images.githubusercontent.com/22150791/30474983-9d923422-9a05-11e7-8c60-275086c08f6e.jpg)

And entry edit: 

Deutsche Welle Akademie is Germany's leading organization for international media development. Mozilla paid them a visit for a lunchtime talk about Internet health for staff in Berlin (and Bonn via video). Check out the link for a DW interview with Solana Larsen, Mozilla's editor of the Internet Health Report.
