### ISSUE TITLE
Design Sign in screen with Terms 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#694]
@kristinashu, let's discuss/explore design options based on constraints in https://github.com/mozilla/network/issues/738. We'll have to show this to legal, which will go less sadly with a good looking mockup. 

(I'll leave this in backlog to respect other work on your plate. Nudge this along when you a moment or need a break from the big stuff.)

**Comment by kristinashu** [comment]
Here's a comp of the most basic page. If we don't have a checkbox then knowing if a user already has an account or not becomes less important. We will still need to work out the copy tho.

![sign in 2x](https://user-images.githubusercontent.com/1068783/30830830-39c70312-a1fa-11e7-9e3a-fd54eb045ba3.png)

**Comment by xmatthewx** [comment]
Thanks @kristinashu. I will email Abigail to explain the technical constraints and get feedback on the exact wording for this.

**Comment by kristinashu** [comment]
@xmatthewx we need copy before I can open an implementation ticket, please and thank you.

**Comment by xmatthewx** [comment]
Right-o. Here's what I propose:

> Sign in or sign up to post your projects and connect with others who care about a healthy internet. 

> By logging in, you agree to be bound by the [Mozilla Terms of Service](https://www.mozilla.org/about/legal/terms/mozilla/), and you agree to have a profile that displays your name.

**Comment by xmatthewx** [comment]
Note for implementation: we currently have a view with login button that appears when someone taps the plus-+ button. That view does not update the URL in browser (though it probably should), so we can point to it from header. (oddly, this view doesn't appear when you tap login on favs view)

**Comment by kristinashu** [comment]
#### So for implementation, we will need to:
- make it so no matter where someone enters from (Signup/Signin, Add entry, click fav icon) they go to this screen before the Google signin
- make this screen have the URL? https://www.mozillapulse.org/signin ?
- redirect appropriately depending on where the user entered from

#### Here's the comp:
![sign in 2x](https://user-images.githubusercontent.com/1068783/31247942-02f1a28c-a9c7-11e7-8196-e1753100d73f.png)

This is replacing the screen on production that looks like:

<img width="451" alt="screen shot 2017-10-05 at 12 21 56 pm" src="https://user-images.githubusercontent.com/1068783/31248230-e3170712-a9c7-11e7-81d4-35b64078ae15.png">

**Comment by kristinashu** [comment]
I've opened an implementation ticket https://github.com/mozilla/network-pulse/issues/735
