### ISSUE TITLE
Update image on entry 436

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#698]
We received a request from @thornet to update the image on the entry for [Trustmark for IoT](https://www.mozillapulse.org/entry/436).  

@thornet – can you post the image here? We'll swamp that i for you.

**Comment by thornet** [comment]
Thank you! Attaching. The other image had a weird cursor ghost. 

![trustmark for iot cover image](https://user-images.githubusercontent.com/739174/30538410-2abe418c-9c6e-11e7-8e4b-35afbc2ee12c.png)

**Comment by xmatthewx** [comment]
done!
