### ISSUE TITLE
Update grey background to white

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#700]
From alignment work in https://github.com/mozilla/network/issues/582. To align better with [new brand](https://mozilla.ninja/), [mozilla.org](http://mozilla.org/), [Network site](https://network.mozilla.org/), and [IRH site](http://internethealthreport.org/) we need to replace the light grey background with white.

- [x] replace grey background with white
- [x] adjust padding on thumbnails so text lines up with the image edges

Quick mockup:
<img width="770" alt="screen shot 2017-09-19 at 1 26 32 pm" src="https://user-images.githubusercontent.com/1068783/30613792-2ff997fc-9d3e-11e7-89f0-40f9a32d13f9.png">

**Comment by mmmavis** [comment]
this is covered as part of https://github.com/mozilla/network-pulse/issues/720 and can be closed once we do a prod push next week.

**Comment by mmmavis** [comment]
Done!
