### ISSUE TITLE
Design updates based on feedback from legal

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#703]
### Feedback from Abigail:

- [x] **“Email” field:** Let users know that email address will not be publicly displayed on their profile page.

- [x] **“Bio” field:** Add language telling users not to include any personal information in their descriptions.

- [x] **Profile pic field:** “Only submit photos that you have permission to use in this context.”

- [x] **Add a “Contact Us” link** on profile page for example if a user wants content or account deleted, if a user’s Google account is deleted and the user wants to edit her profile. If this happens, we’ll need to figure out how to authenticate the user’s identity, whether to permit old account to be joined to a new one, etc.

- [x] **Terms of Service:** Currently Pulse includes a ToS consent event each time a user submits a Pulse entry; however, there is no ToS consent event that covers users’ engagement with the site in full, meaning that we need to get users to agree that the ToS governs their profile submissions. One solution is to add the same consent language to the bottom of the profile form before it’s submitted. A friendlier solution, if feasible, would be to capture users the first time they log in to Pulse from Google and send them through a one-time consent flow that covers all engagement with the site going forward. The consent language could then be removed from each Pulse entry form and from the profile form. Under this second option, users who are already using Pulse would need to be sent through the flow at next log-in. Also, Mozilla should record a date/time stamp for the user’s consent.

- [x] **Content rights:** Under the ToS, users grant Mozilla broad rights to use their uploaded content, but they don’t release their content under a CC license nor give Mozilla the right to release their content under a CC license. Hopefully this is consistent with your expectations; if not, I’m happy to talk further about how to address. The current CC license reference in the footer isn’t explicitly that only some of the content on the site is available under that license, but I’ve been working on a site-wide update that will help with this as it’s an issue for many Mozilla sites.
   - update from mw: we can adjust footer when that's ready. otherwise, i think we're good for now.

- [x] I noticed you wrote “We will email current users and invite them to complete their profile”; however, the Terms of Service & Privacy Policy generally don’t allow Mozilla to email users about site enhancements, etc., unless they’ve specifically opted in to receiving updates of this nature.
  - update from mw: we'll handle this separately. we wont do a mass email but will inform people through other channels. 

- [x] **Clarify** what “A user may post links to other profiles and sites with contact info.” means
  - update from mw: this isn't anything important. just meant that we won't offer means to contact users, but users could link to other sites with their contact info. 

cc @xmatthewx

**Comment by kristinashu** [comment]
@xmatthewx here's an updated version of profile page.

![profile form copy 2x](https://user-images.githubusercontent.com/1068783/30879308-e783541a-a2b3-11e7-9c04-c70d08a890d5.png)

**Comment by xmatthewx** [comment]
@kristinashu - all your changes look great. Let's make sure that @mmmavis knows what's new. 

 1. Intro copy 
    - I'm thinking plain and simple. How's this? "Tell everyone about yourself, so we can connect and collaborate!"
 2. Email 
    - help text looks good
 3. User name
    - let's label this "Name"
 4. All fields optional
    - Let's move this below Name and Email, since they're required.
    - Copy: "All fields below are optional"
 5. Profile pic 
    - help text looks good
 6. Legal at bottom
    - "By submitting your profile, you agree to be bound by the Mozilla Terms of Service[link]."
    - Contact us statement looks good. Link: https://mzl.la/pulse-contact

**Comment by mmmavis** [comment]
@xmatthewx some thoughts about the Name field.

I think you can't really edit the name we pull from your Google account (am I right, @gideonthomas ?). On the public profile page we use your Google name as the fallback name if you don't have a "custom name" in the database. If we are just showing  one `Name` on the edit page it might confuse people. e.g., you clear the "Name" field and hit submit. You go to your profile but you still see your (Google) name appear on the profile name. As an user you probably won't know it is your Google name that we are using as a fallback.

**Comment by gideonthomas** [comment]
@mmmavis yeah that's right!
Suggestion: Why not have 2 fields? One is a readonly field (greyed out) that says "Name" and the input box will show the google name (non-editable), the other is an editable input field called "Preferred Name".

**Comment by kristinashu** [comment]
I'm reluctant to add more complexity to the user's view of the form. Could we pre fill the name field with someone's google account name but format it like a regular field so they can easily update it? We can keep both names in the back end but the user only see the one name.

<img width="978" alt="screen shot 2017-09-29 at 9 37 39 am" src="https://user-images.githubusercontent.com/1068783/31026132-051f5b98-a4fa-11e7-96cb-3ae1df818bf1.png">

**Comment by kristinashu** [comment]
From meeting: need to make name field a required field.

**Comment by kristinashu** [comment]
Here's the update comp!

@xmatthewx should we run this past legal and come up with intro text?

![profile form with legal 2x](https://user-images.githubusercontent.com/1068783/31027755-435fdb48-a500-11e7-893d-391e3344b96b.png)

**Comment by kristinashu** [comment]
Or maybe we don't need any legal copy/link in the intro text?

**Comment by mmmavis** [comment]
@xmatthewx do we need to add legal copy to the intro text? If not, let's close this ticket since all other todos have been implemented: https://network-pulse-staging-pr-691.herokuapp.com

**Comment by xmatthewx** [comment]
> We can keep both names in the back end but the user only see the one name.

Agreed. the `User.name` will always be their google name, but it is never displayed. `Profile.name` will be pre-populated with `User.name` by default. This can be edited and used for display.

**Comment by xmatthewx** [comment]
> do we need to add legal copy to the intro text? If not, let's close this ticket since all other todos have been implemented

All copy on staging looks fantastic. Let's close this!

**Comment by kristinashu** [comment]
Yeah looks good! 
<img width="770" alt="screen shot 2017-10-05 at 12 11 39 pm" src="https://user-images.githubusercontent.com/1068783/31247744-64d121c2-a9c6-11e7-83b7-6d2b3c46fcc6.png">

**Comment by mmmavis** [comment]
🎉 🎉 🎉 🎉 🎉
