### ISSUE TITLE
Enable new entries to identify existing creators with autocomplete

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#706]
When a User fills the form to submit a new entry, they name a series of creators. To improve accuracy and simplify their experience, let's...

Enable autocomplete on names that match an existing Creator.

If possible: let's distinguish a Creator who has a profile from a "stub" creator (has name string only). The goal: get them to click the creator with a profile, since it is more likely to be the right one. (If it's wrong, we have a contact link they can use on the entry)

@gideonthomas - do we need to file a ticket for work on the API side? Or is that covered already?

**Comment by gideonthomas** [comment]
That ticket is already filed here: https://github.com/mozilla/network-pulse-api/issues/215

**Comment by xmatthewx** [comment]
@kristinashu - I took a quick stab at how we might handle autocomplete on creators. And how list creators on form after entered. The goal is to encourage submitters to link to users with profiles. Feel free to revise this. 

### Autocomplete 

![image](https://user-images.githubusercontent.com/53411/30876144-bfe6224c-a2c3-11e7-8b11-b8be0de64f1e.png)

### List to submit

 - A remove icon seems helpful. Probably better UX than inserting a cursor and deleting characters, triggering autocomplete again.
 - It would be very cool if icon could link to profile, but that's not mvp unless it's easy. 
 
![image](https://user-images.githubusercontent.com/53411/30876590-1343e554-a2c5-11e7-92e8-49c5d78879d2.png)

**Comment by kristinashu** [comment]
Sounds good @xmatthewx. Also, sweet table!

**Comment by alanmoo** [comment]
@gvn to start based on known response schema, even if that response doesn't come from anywhere yet

**Comment by gvn** [comment]
@gideonthomas Can you give me some dummy data (and/or schema) for the autocomplete route?

**Comment by alanmoo** [comment]
Reminder: tags already has auto-complete, let's see if we can leverage that component with this.

**Comment by xmatthewx** [comment]
@gvn - this comment might be useful for some context on creators model, though it contains more than you need to know. https://github.com/mozilla/network/issues/713#issuecomment-333219639

**Comment by gideonthomas** [comment]
@Pomax can provide data that you will fetch for autocomplete.

For submitting the entry with autocompleted creators, you will no longer use the `creators` property any more. Instead, here's the schema for another property that you would use:
```js
"related_creators": [{
  "id": number | <id of the creator autocompleted. Will be null if the creator was not autocompleted and was manually typed in>,
  "name": string | <name of the creator typed in, not autocompleted. Will be null if the creator was autocompleted>
}, ...]
```
Either the `id` or the `name` must be provided. Since it is an array, the order the objects are in should be the order they were entered into the input field.

**Comment by gvn** [comment]
@xmatthewx Implementing the UI for creators is currently problematic due to some limitations with the `react-formbuilder` library (filed issue https://github.com/Pomax/react-formbuilder/issues/55).

Would it be acceptable to use the same UI pattern as tags for creators?

**Comment by xmatthewx** [comment]
Probably?  So comma separated names? Is the change on react-form builder significant?

I guess we start with tags-like UI, then refactor later if it seems like a problem. 

 What do you think @kristinashu?? Seem viable?

**Comment by gvn** [comment]
> Probably? So comma separated names? Is the change on react-form builder significant?

Yeah, comma separated names just like tags. 

I don't know how significant a change it is to react-formbuilder, but even if it's added it'll be more complex to implement. It's also possibly a little more accessibility/assistive-device-friendly as a single field.

> I guess we start with tags-like UI, then refactor later if it seems like a problem.

That sounds good to me. It'll allow me to move forward faster as well.

**Comment by alanmoo** [comment]
This makes a lot of sense to me. MVP.

**Comment by gideonthomas** [comment]
@gvn, tweaked the schema slightly - instead of `id` we're calling it `creator_id` now.

**Comment by xmatthewx** [comment]
This is looking great. @gvn @gideonthomas -  I've noticed two things testing this so far:

 1. If I check the box "I am one of the creators" and enter myself below... I am included twice on the entry. We should de-dupe creator_ids on submission. 
 2. We want to add an icon for creators who have a profile_id. We can file this as a follow up, but it's important for MozFest. It'll help users pick the right person and avoid orphan creators, typo creator names, etc.

**Comment by alanmoo** [comment]
I poked at the module we're using for autocomplete, and it looks like it only renders strings into the suggestions. So the most basic way we can quickly succeed on (2.) above is to add text/emoji/unicode to the username that indicates they're a profile. Like `😃 Daffy Duck`.

**Comment by xmatthewx** [comment]
Hmm. Okay. Interesting. That sounds a bit hacky. Question: After the suggestion is accepted, does the item carry the creator_id? Or are we just sending back strings with the form? That probably wouldn't be good, since names don't have to be unique.

**Comment by xmatthewx** [comment]
So... 
 1. this is resolved by https://github.com/mozilla/network-pulse-api/pull/246. true??
 2. we'll tackle this as a follow up
