### ISSUE TITLE
Bug: thumbnail should not be an required field for Profile

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#712]
Heroku instance that shows current profile work: https://network-pulse-staging-pr-691.herokuapp.com/myprofile

<img width="922" alt="screen shot 2017-09-28 at 9 26 41 am" src="https://user-images.githubusercontent.com/2896608/30978494-8f9f0348-a42f-11e7-9f8a-4520e0a1c5a0.png">

Currently thumbnail is set as required field but it should really be optional. I might have done something wrong on the front end. Will check.

**Comment by gideonthomas** [comment]
No this is def a backend issue that makes it required (I used to disable it when testing coz I didn't want to manually base64 encode images when testing :P). Feel free to assign to me.

**Comment by mmmavis** [comment]
@gideonthomas just did 😉
