### ISSUE TITLE
Draft User story as QA tool for Profiles launch

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#713]
We'll soon launch a major feature – Profiles! Let's craft a simple tool to help the team assess our status and identify any gaps in our build before launch. 

This could take a few forms:
 - slide deck with comps
 - a checklist of steps 
 - flowchart

Doesn't need to be fancy, just thorough. 

Here's [an etherpad](https://public.etherpad-mozilla.org/p/pulse-profiles-user-story) where we can gather a list of steps. 

cc @mmmavis @gideonthomas

**Comment by kristinashu** [comment]
I've started to add some slides at the beginning of our slide deck for a more visual representation https://docs.google.com/a/mozilla.com/presentation/d/12o0P9wWGlUEuY-247fWuHluVQsdfm9Htqlfuo8OQUio/edit?usp=sharing

Re can also reference https://public.etherpad-mozilla.org/p/pulse-profiles-checklist

**Comment by mmmavis** [comment]
Hey @xmatthewx are we thinking about launching the profile work before MozFest? If so I'm really worried about the time and resource we have. It would be super helpful if you could take a look at [what has been implemented](https://network-pulse-staging-pr-691.herokuapp.com) and flag things that are blocking us from launching.

**Comment by xmatthewx** [comment]
Yes, we plan to launch profiles for MozFest. We can probably pull in help from Gavin/Alan if needed. We can walk through what's done, what remains with the whole group to take stock.

**Comment by kristinashu** [comment]
@xmatthewx @mmmavis @Pomax @gideonthomas @alanmoo I've update the slide deck and divided things into P1, P2, and P3 (each one building on top of the other). Still a WIP but please add any questions/comments!

**Comment by xmatthewx** [comment]
I'm going to call this done. For QA, we'll just have to ask a few staff to create their profile, note their browser/device, and report hiccups. I'll set that up.
