### ISSUE TITLE
Design 404 broken link screen

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#72]
From @cadecairos "I also just realized I should try loading the page with a bogus project id in the query string. You end up with just the lightbox without content. Is there a better way of handling this?"

We should either redirect people to the landing page or show a "project not found" message with a link to the landing page.

**Comment by kristinashu** [comment]
All done!

![mobile - 404 2x](https://cloud.githubusercontent.com/assets/1068783/17337180/652bd70c-5896-11e6-8629-06e15d55a364.png)

**Comment by mmmavis** [comment]
hey @kristinashu Where does "Let us know" link to?

**Comment by kristinashu** [comment]
Link to this repo please.

**Comment by xmatthewx** [comment]
.../issues/new

**Comment by mmmavis** [comment]
Question about what triggers this 404 screen.

- going to a direct project link that doesn't exist?
- and what else?

**Comment by kristinashu** [comment]
I guess 
- a project link with a typo in it
- a link to a project that has been taken down
Can't really think of anything else?

**Comment by mmmavis** [comment]
Cool, let's just go with this.
