### ISSUE TITLE
Thumbnail card style updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#720]
From alignment work in mozilla/network#582 and to align better with new brand, mozilla.org, Network site, and IRH sites.

- [x] Change default body color on Pulse to black (`#000000`) 

**Project cards**

- [x] Update pink titles to black
- [x] Hover state of title is black underline
- [x] Update list of names from grey to black and from Zilla to Open sans
- [x] Remove intro text
- [x] Remove gradient over intro text
- [x] Remove Read more link
- [x] Move heart up
- [x] Add vertical space in between rows of cards

Old / New https://redpen.io/vxb765b626268eb55c
![screen-shot-2017-10-02-at-3 19 40-pm](https://user-images.githubusercontent.com/1068783/31102316-5fe6b286-a786-11e7-8e39-278be0dd8edf.png)

@mmmavis let me know if you foresee any issues with this.

**Comment by mmmavis** [comment]
@kristinashu are all cards in the same height? If so we should consider wrapping creator list as it can get quite long.

**Comment by mmmavis** [comment]
Or we can set a min-height for card but they them grow as tall as they need to... like 

![screen shot 2017-10-04 at 12 27 42-fullpage](https://user-images.githubusercontent.com/2896608/31195518-7271d47e-a8ff-11e7-9b3e-9600b771cfdb.png)

(we should really have placeholder thumbnail 😂 )

**Comment by kristinashu** [comment]
Here's a placeholder image but most people do add an image https://www.mozillapulse.org/latest

![placeholder](https://user-images.githubusercontent.com/1068783/31196467-bac33404-a902-11e7-9d24-56e18235c240.png)

**Comment by kristinashu** [comment]
Looks like title length is very narrow. I think the text can go right up to the heart. (This will also be better once https://github.com/mozilla/network-pulse/issues/700 is done and the card text width will be wide.r)

From staging:
<img width="365" alt="screen shot 2017-10-04 at 12 49 34 pm" src="https://user-images.githubusercontent.com/1068783/31196490-d789e542-a902-11e7-850a-ab586fa026c6.png">

**Comment by mmmavis** [comment]
current status: pending verification on staging before we can close this ticket

**Comment by xmatthewx** [comment]
Looks rad to me, but I'll let @kristinashu have the joy of reviewing and closing this.

**Comment by kristinashu** [comment]
Yup looks awesome!
