### ISSUE TITLE
Image fallbacks

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#721]
- [x] placeholder image if user doesn't upload an image
- [x] what to do if user upload an image that isn't the correct aspect ratio
- [ ] update gradient placeholder to css (newly added)

**Comment by mmmavis** [comment]
@kristinashu is it possible that we use SVG as placeholderimage  instead of [png](https://github.com/mozilla/network-pulse/issues/720#issuecomment-334270030) ?

**Comment by alanmoo** [comment]
Or even a CSS generated gradient? https://www.css-gradient.com/

**Comment by alanmoo** [comment]
In fact, as we use gradients across the new design language, it would be great to have them all entirely in CSS.

**Comment by mmmavis** [comment]
@alanmoo I haven't checked how other MoFo are doing it. But yea either way would work.

**Comment by gideonthomas** [comment]
superseded by UI refresh
