### ISSUE TITLE
Sign out from /favs should update [name] on nav bar

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#722]
Sign out should update `Hi [name]` on nav bar. 

Attaching screencap here soon.

**Comment by mmmavis** [comment]
@kristinashu um weird. Do you remember the steps to reproduce this issue? I just tried logging out from the Add page and the Edit profile page... both seemed to be working properly for me.

**Comment by kristinashu** [comment]
We might be thinking of different things. When I'm not signed on https://network-pulse-staging-pr-691.herokuapp.com/featured I should see a Signup/Signin link in the top right nav bar.

Staging:
<img width="1197" alt="screen shot 2017-10-05 at 2 18 57 pm" src="https://user-images.githubusercontent.com/1068783/31253106-5f404d52-a9d8-11e7-8039-84986633321a.png">

Comp: (ignore styling)
<img width="532" alt="screen shot 2017-10-05 at 2 20 59 pm" src="https://user-images.githubusercontent.com/1068783/31253122-70f357f6-a9d8-11e7-8f14-12b2f5e63089.png">

**Comment by mmmavis** [comment]
This bug was from our Tuesday's call... you were screensharing and after you clicked on the sign out link (I forgot on which page) the nav bar still said "Hi, Kristina". Can you recall? If not I think I'm gonna close this ticket since I can't seem to reproduce it. Maybe I was just daydreaming after my nth morning meetings without ☕️

**Comment by kristinashu** [comment]
It happens when I logout from the Favs screen. I click Logout but my name is still in the nav bar.

**Comment by kristinashu** [comment]
<img width="1211" alt="screen shot 2017-10-05 at 3 09 31 pm" src="https://user-images.githubusercontent.com/1068783/31254853-392e1732-a9df-11e7-978e-a4f5734ae5e2.png">

**Comment by mmmavis** [comment]
kk, I'm putting this ticket on hold since eventually it will be solved by https://github.com/mozilla/network-pulse/issues/734 (remove signin from Favs page)

**Comment by kristinashu** [comment]
I also opened https://github.com/mozilla/network-pulse/issues/739

**Comment by mmmavis** [comment]
Closing as we have decided to add [`Signup/in` link to the nav bar](https://github.com/mozilla/network-pulse/issues/739) and [remove signin/up prompt from the Favs screen](https://github.com/mozilla/network-pulse/issues/739).
