### ISSUE TITLE
MozFest poster for Pulse & Site

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#726]
Content: 
 - Add your projects to Pulse!
 - See latest news on foundation.mozilla.org. Join the list. 

Size: A5
Quality: Lo-fi. I think this can be flyer like. 
Print: at Ravensbourne
Qty: 50? 100?

cc @jessevondoom for thoughts on content.

**Comment by xmatthewx** [comment]
Include shortlink to feedback form?

**Comment by kristinashu** [comment]
@xmatthewx something like this? Having a logo for Pulse and then nothing for the Foundation makes it hard to separate the two so I've used Mozilla and grouped Pulse + Foundation copy together. 

<img width="464" alt="screen shot 2017-10-10 at 10 58 48 am" src="https://user-images.githubusercontent.com/1068783/31402171-12ebe15c-adaa-11e7-86c7-be29acf4acdd.png">

cc @sabrinang for feedback on brand.

**Comment by xmatthewx** [comment]
This looks great. 

I wonder if there's any simple way to make this feel like a call to action, rather than a info poster. If there's no quick ideas, don't worry about it. This is plenty good.

**Comment by kristinashu** [comment]
Ok, I've shortened the copy and made it more about the URLs.

<img width="503" alt="screen shot 2017-10-10 at 2 42 59 pm" src="https://user-images.githubusercontent.com/1068783/31412287-5b8d6042-adc9-11e7-8522-4e4709babfd9.png">

**Comment by xmatthewx** [comment]
ah, perfect. i think that does the job well.

**Comment by xmatthewx** [comment]
@edrushka - this is a small A5 flyers for mozfest. it'd be good to have them at House. In a stack if there's no where to hang them. Feasible? Who could facilitate this?

**Comment by edrushka** [comment]
Very lovely. There is nowhere to hang in the venue (very strict rules about what we can put on the walls i.e. nothing 😉 ) A stack at the House reg desk _may_ be possible. However, please confirm with @lucieclick.

**Comment by kristinashu** [comment]
Here is the print pdf: [PulseMozFestPoster-A5.pdf](https://github.com/mozilla/network-pulse/files/1376873/PulseMozFestPoster-A5.pdf)

**Comment by xmatthewx** [comment]
Fab. Closing this. Tracking printing here: https://github.com/MozillaFoundation/mozfest-design-2017/issues/78
