### ISSUE TITLE
Profile edit form should inlude default name

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#727]
As an existing user, on staging, my profile defaulted to my name from google. ✔️ That's good. But,  when i went to edit my profile, the name field was blank. This required me to retype my name. I didn't notice, and my submit failed. Not a huge deal, but it adds odd friction for our users.

**Comment by mmmavis** [comment]
This is somewhat blocked by https://github.com/mozilla/network-pulse-api/issues/229 (so that we can rely on the API response to determine what "name" to show on front end). I could get a interim solution in first but not sure if I should as it introduces some complexity to the codebase.

**Comment by xmatthewx** [comment]
verified on staging!! closing.
