### ISSUE TITLE
Design promo for profile feature

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#733]
Design promo to appear on Pulse landing page to promote the new profile feature. This could be just a feature post or an actual banner or notification. 

cc @xmatthewx for copy

**Comment by xmatthewx** [comment]
If it's a notification, we could do something like this:  

 - Signed in: "Pulse now has profiles! Add yours [link to /myprofile]. Discover and connect with the people behind these great projects."
 - Signed out: "Pulse now has profiles! Sign up [link to /signin] and add yours. Discover and connect with the people behind these great projects."

It is fun to think about adding an entry as a way to announce this. 

Visit link could point to profile form. Contribute link could invite people to help us add future features.

**Comment by kristinashu** [comment]
Is this too much? In the future we could then use this promo banner to introduce what Pulse is to people not signed in. 

![pulse home notification copy 2x](https://user-images.githubusercontent.com/1068783/31289216-e55f1c8e-aa7c-11e7-9392-177fa3d1d28d.png)

**Comment by xmatthewx** [comment]
I think it's brilliant. Showing all those faces will really change everyone's first impression of what pulse is and can be for them. Probably just displayed on /featured, right?

**Comment by kristinashu** [comment]
Yes, this would only appear on the feature page. I've opened an implementation ticket https://github.com/mozilla/network-pulse/issues/743
