### ISSUE TITLE
Remove Signin from Fav screen

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#734]
Now that we have Signup/Signin in the nav, we can remove it from the Fav screen.

### Currently on production:

Signed out
<img width="1356" alt="screen shot 2017-10-05 at 12 05 57 pm" src="https://user-images.githubusercontent.com/1068783/31247476-96879d1e-a9c5-11e7-8d59-1234832c4e53.png">

Signed in
<img width="1355" alt="screen shot 2017-10-05 at 12 02 48 pm" src="https://user-images.githubusercontent.com/1068783/31247379-402b0596-a9c5-11e7-846e-d68df0369075.png">

### Proposed Signout:
- [ ] remove "Sign in with Google." text

### Proposed Signed in:
- [ ] remove "Hi [username]!"
- [ ] keep "Did you add favs while logged out? You can import from this browser." when applicable.

cc @xmatthewx

**Comment by mmmavis** [comment]
@kristinashu are we keeping `Log out` link on the screen?

**Comment by kristinashu** [comment]
No, you can remove `Log out` as well.
