### ISSUE TITLE
Signin screen updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#735]
### Currently on production:
- user taps the plus Add Entry button in nav: goes to Signin screen (screen cap below)
- this signin screen does not update the URL in browser
- user taps Signin on Fav screen: goes straight to Google Signin

<img width="451" alt="screen shot 2017-10-05 at 12 21 56 pm" src="https://user-images.githubusercontent.com/1068783/31248230-e3170712-a9c7-11e7-81d4-35b64078ae15.png">

#### Need to:
- make it so no matter where someone enters from (Signup/Signin or Add entry) they go to this screen before the Google signin
- make this screen have the URL? https://www.mozillapulse.org/signin ?
- redirect appropriately depending on where the user entered from

#### Here's the comp:
![sign in 2x](https://user-images.githubusercontent.com/1068783/31247942-02f1a28c-a9c7-11e7-8196-e1753100d73f.png)

#### Copy:
> Sign in or sign up to post your projects and connect with others who care about a healthy internet. 

> By logging in, you agree to be bound by the [Mozilla Terms of Service](https://www.mozilla.org/about/legal/terms/mozilla/), and you agree to have a profile that displays your name.

**Comment by kristinashu** [comment]
cc @xmatthewx @Pomax might be _slightly_ more complicated than originally thought ^

**Comment by xmatthewx** [comment]
I reviewed the copy with legal. Let's revise to:

 > Signup or signin to post your projects and connect with others who carte about a healthy internet. . We automatically create a public profile for you that you will be able to edit.

> By signing in, you agree that your use of Pulse will be bound by the [Mozilla Terms of Use](https://www.mozilla.org/about/legal/terms/mozilla/) and [Privacy Policy](https://www.mozilla.org/privacy/websites/).

After we land this, we can remove the general consent language from profile and entry form (but keeping things specific to those forms).

**Comment by kristinashu** [comment]
Here's the updated comp:
![sign in 2x](https://user-images.githubusercontent.com/1068783/31522697-0fbead1e-af64-11e7-84e1-4e70a387d6f8.png)

@xmatthewx in your comment above, what do you mean by "(but keeping things specific to those forms)"?

Do you mean we can remove this text from upload from?
<img width="752" alt="screen shot 2017-10-12 at 3 44 21 pm" src="https://user-images.githubusercontent.com/1068783/31522767-73059cfc-af64-11e7-949f-301853ee2da3.png">

and this text from profile from?
<img width="623" alt="screen shot 2017-10-12 at 3 45 13 pm" src="https://user-images.githubusercontent.com/1068783/31522765-716f63a0-af64-11e7-8071-7891daf1d972.png">

**Comment by xmatthewx** [comment]
Great. 

All of the cleanup on other forms can wait until after MozFest. 

> what do you mean by "(but keeping things specific to those forms)"?

Yes, I mean that we can remove "By submitting ... you agree." But, we should keep "your entry may be edited lightly..." and "Please contact us..." and anything above about images, personal info, etc.

**Comment by kristinashu** [comment]
I've opened two new implementation tickets. Please edit them if needed.

- Implement signin screen updates #755
- Remove legal copy on forms #756
