### ISSUE TITLE
Rename "Online Privacy & Security" to just "Privacy & Security"

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#736]
It seems like "Privacy & Security" is the internet health issue name being used elsewhere (correct, @kristinashu) ? If so we should consider renaming "Online Privacy & Security" to just "Privacy & Security".

This will involve both frontend and backend work

**Back End**
- migrate all "Online Privacy & Security" bits to "Privacy & Security"
  - `/api/pulse/issues`
  - `/api/pulse/entries/?issue=Online Privacy & Security`
  - and other things I'm hoping @Pomax can lend a hand here to provide further info

**Front End**
- redirect `/issues/online-privacy-and-security` to `/issues/privacy-and-security`
- verify that all the hardcoded "Online Privacy & Security" text gets replaced.

/cc @xmatthewx @alanmoo

**Comment by alanmoo** [comment]
I temporarily changed the name of the issue on the staging back-end to remove "Online" and everything sees to work there just fine. Only issues I saw were on the front end, specifically the issue name and links on https://network-pulse-staging.herokuapp.com/issues/ went to the wrong spot. The tags within the entries were all updated appropriately and the url `/issues/privacy-and-security` worked just fine too.

**Comment by Pomax** [comment]
@xmatthewx do we want to do this?

**Comment by xmatthewx** [comment]
My thinking: Yes? If it's easy, then yes! If there are complexities or risks, then yes but not now.

**Comment by alanmoo** [comment]
Let's do this after Mozfest. Shouldn't be hard, but not worth the time right now.

**Comment by alanmoo** [comment]
@mmmavis This is pretty old, but do you know why it's blocked?

**Comment by AdityaSrivast** [comment]
@mmmavis I am a first time contributor and want to work on this issue. Can you tell me what all needs to be done, please?

**Comment by mmmavis** [comment]
Hi @AdityaSrivast 😃 Welcome!

It's been more than a year since I filed this ticket so I'm not sure if this is still something our team wants to fix. Let me check with people first.

@gideonthomas @alanmoo @xmatthewx thoughts?

**Comment by gideonthomas** [comment]
Yeah we should still do this.

I'll have to do the backend fix in the admin interface but I can only do that after the front-end update since it will break functionality.

@AdityaSrivast you can do the front-end fixes for this -- as @mmmavis mentions in the first comment, you need to redirect all links to `/issues/privacy-and-security` and replace all hardcoded strings.

The first thing you want to do though is to setup your local environment per instructions in the README. Let us know if you have any questions.
