### ISSUE TITLE
Prep for Research at MozFest

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#738]
Let's plan some light user research at MozFest, on both Pulse and the foundation site. I'm imagining simple, informal qualitative research to surface problems and opportunities. 

We'd love to Collaborate with @pfzenke and Abdoul on this. 

Possible Questions
 1. Have you looked at Pulse or the Site? Did you discovered a person, initiative, or interesting news? Start a new collaboration?
 1. Did you sign up for the list?
 1. Did you post to Pulse? 
     - Yes: What did you think?
     - No: Want to try it now with me?

This could take a few forms  
 - Conversations at science fair / demos
 - 1-1 conversations in common spaces or by kiosk
 - Question thread in slack
 - ~~Formal focus group with clipboards, OJ, and bagels~~

What does success look like?
 - We gathered one or more insight with small investment of work
 - We exercised our user research muscles
 - We strengthened collab with insights team
 - ~~We created a new massive undertaking and produced an extensive report on findings~~

cc @jessevondoom @kristinashu

**Comment by xmatthewx** [comment]
cc @stephaniemcv

**Comment by taisdesouzalessa** [comment]
Scheduled a meeting with Paul, Abdoul and Matthew (Tuesday, Oct 17th) to discuss collaboration and get a plan together for MozFest.

**Comment by xmatthewx** [comment]
done. closing!
