### ISSUE TITLE
UI: Add Signup / Signin to nav bar

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#739]
When I user is not signed in or has just signed out, then the name should be replaced with "Signup / Signin" 

Clicking it should redirect as required. 

Comp:
<img width="532" alt="screen shot 2017-10-05 at 2 20 59 pm" src="https://user-images.githubusercontent.com/1068783/31253122-70f357f6-a9d8-11e7-8f14-12b2f5e63089.png">

**Comment by mmmavis** [comment]
PR has been merged and things can be tested and verified on https://network-pulse-staging-pr-691.herokuapp.com/
