### ISSUE TITLE
Add tab for sorting & filtering project

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#74]
@mmmavis – would it be possible to set up a secondary tab in our spreadsheet that pulls everything from the primary tab? This would allow Kevin and others to sort and filter projects.

Not critical, but useful if it is easy. Adding to the next milestone rather than this one.

**Comment by mmmavis** [comment]
@xmatthewx you mean a tab that mirrors the first tab?

**Comment by xmatthewx** [comment]
Yes. I believe that sorting the first tab will impact IDs. So, a second tab for viewing might be useful. A hacky temporary solution. Again, let's not worry about this until the next heartbeat.

**Comment by xmatthewx** [comment]
Closing. Will reopen if needed later.
