### ISSUE TITLE
[name] displayed for loggedin user should be that person' custom name (if it exists)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#741]
Green circled text should all be `mmm` (my custom name)

![screen shot 2017-10-05 at 3 35 08 pm copy](https://user-images.githubusercontent.com/2896608/31256187-c9de35f4-a9e5-11e7-836e-e4982df8ce1a.jpg)

and

![screen shot 2017-10-05 at 3 35 21 pm](https://user-images.githubusercontent.com/2896608/31256169-aa3c5e24-a9e5-11e7-990b-16cc4250065f.jpg)

Related backend ticket: https://github.com/mozilla/network-pulse-api/issues/229 so we can easily get a user's `name` by calling `/userstatus` endpoint

**Comment by xmatthewx** [comment]
verified on staging! hurrah. closing.
