### ISSUE TITLE
Add creator entries to Profile view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#742]
Currently, our new profiles only include entries `Submitted` by the person. Let's add things they `Created` as well. 

Note: MVP can just lump all entries together. Later, we'll want to separate by header or tabs. So let's proceed with that in mind.

@gideonthomas and @mmmavis – let's discuss:
 - how do we handle this on the frontend? is backend work required?
 - how big a body of work is this? feasible to land before mozfest? 

cc @alanmoo for awareness since profiles will be limited at mozfest without it.

**Comment by mmmavis** [comment]
Front end profile page is just consuming `/api/pulse/profiles/<id>/` (and/or `/api/pulse/profiles/me/`)

e.g., https://network-pulse-api-staging.herokuapp.com/api/pulse/profiles/8/

So yea backend work is definitely needed.

And if we want creator's name to be hyperlinked to that person profile page... creator list returned from backend will need to include profile id as well.

**Comment by xmatthewx** [comment]
@Pomax @gideonthomas - let's huddle up around this at the end of stand on Thursday.

**Comment by gideonthomas** [comment]
Filed the backend issue: mozilla/network-pulse-api#234

The creator objects sent back for entries should already have the profile id in them. You need to use the `creators_with_profiles` property instead of the `creators` property.

**Comment by Pomax** [comment]
backend issue landed and merged

**Comment by xmatthewx** [comment]
verified on staging! i think this and everything else is ready for some thorough QA!
