### ISSUE TITLE
Implement promo banner

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#743]
Based on design in https://github.com/mozilla/network-pulse/issues/733

To let people know about the new profile feature we will have a banner on the Landing Feature page.

#### Copy:
 - Signed in: "Pulse now has profiles! Add yours [link to /myprofile]. Discover and connect with the people behind these great projects."
 - Signed out: "Pulse now has profiles! Sign up [link to /signin] and add yours. Discover and connect with the people behind these great projects."

#### Comps: https://redpen.io/bp607c4412d1f24328
![profile banner copy 2x](https://user-images.githubusercontent.com/1068783/31298039-26114fac-aa9d-11e7-8d5b-afee069ab038.png)
![profile banner 2x](https://user-images.githubusercontent.com/1068783/31298038-25a4b554-aa9d-11e7-87c3-dcb7b47c5799.png)
![banner copy 1x](https://user-images.githubusercontent.com/1068783/31298650-f70537b6-aa9f-11e7-916e-6bd680de9a24.png)

#### Assets
![profile-image](https://user-images.githubusercontent.com/1068783/31298044-29d2ccf6-aa9d-11e7-9a41-e416e47cd066.png)

**Comment by xmatthewx** [comment]
I love this, but I think the ship has sailed. We can reopen this if another need pops up.
