### ISSUE TITLE
Prep Analytics for Profiles

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#746]
Let's wire this up so we can monitor success and hiccups during launch. 

Steps:
 1. Matthew to identify events and taxonomy [in spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=1060389854)
 2. File engineering ticket.

**Comment by xmatthewx** [comment]
I've added 5 new events in the [spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=1060389854), lines 22-26. 

Two would be very valuable during MozFest. Others could wait. 
 - [ ] profile - social link tap
 - [ ] edit profile - submit error

**Comment by xmatthewx** [comment]
@alanmoo - is this a thing you could tackle? Or, is this a good contributor task. We have other events wired up to demo our pattern.

**Comment by xmatthewx** [comment]
While we do this, we might try and add more info to the `Label` for `Category: 'Add New'; Action: 'Submit Error';`. That's related to Entry Form not profiles. It's scope creep, but currently we don't know why users fail. 

![image](https://user-images.githubusercontent.com/53411/31786839-dbc1f394-b4d7-11e7-941e-06f73f354149.png)

**Comment by alanmoo** [comment]
Are you looking for the validation-time errors here?

**Comment by xmatthewx** [comment]
UX-wise, we want a view into whether our form and instructions aren't clear. To see what might be tripping people up, causing user errors. It's okay if Label is a little verbose, but the full messages are probably too much. Maybe a list of input names that failed? If this gets tricky, let's land the events first, worry about this after.

**Comment by xmatthewx** [comment]
@alanmoo did you start on this? @mmmavis, want to pick this up?

**Comment by alanmoo** [comment]
I started poking at it, but nothing substantial was done. I ran into some difficulty trying to decide what was actually worth reporting. 

Relevant but separate: I believe @patjouk built some monitoring for failed submissions on the server side.

**Comment by patjouk** [comment]
@alanmoo We set up an alarm on logentries that will warn us if posting fails.

**Comment by xmatthewx** [comment]
@mmmavis we have a related issue. you can keep separate or do together, whatever makes sense. #844

**Comment by mmmavis** [comment]
@xmatthewx this awaits your verification on staging! 😃

**Comment by xmatthewx** [comment]
everything looks good. i'll double check the results after a few days on production.

**Comment by xmatthewx** [comment]
thanks!
