### ISSUE TITLE
Pulse Moderation at MozFest

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#748]
MozFest will create a high pace of entries. it'd be great to coordinate moderation, so we can facilitate a realtime experience. 

 1. get items from moderation to latest
 2. get items from latest to featured
 3. get items from featured into stories on the site and medium

I think that @Sydette has 2 and 3 covered on that list. I'm glad to support however useful.

For the first item, I think we'll want a small team, and a schedule for hourly moderation. 
 - @acabunoc will likely be involved b/c of mentor projects
 - there will also be things connected to sci fair. i reached out to Esme. 
 - hopefully there'll be tons of organic activity as well.

@hannahkane - should we have space wranglers in on this since they'll know many of the people and projects? 

@jessevondoom - i wonder if we should tap and train a couple of other staff people.

**Comment by acabunoc** [comment]
I plan on moderating all the mentored stuff to 'Latest' and leaving 'Featured' for the experts to decide :)

Anything with the tag "open leadership zone" is for me

**Comment by ryanwarsaw** [comment]
If you need anyone to moderate I'd be happy to help out ;p

**Comment by xmatthewx** [comment]
Thanks @ryanwarsaw! I'll ping you if we can't keep up with the pace.

One note for the group: entries shouldn't be used to advertise sessions as happened last year. They should be for things useful after the festival is over. I'd say that documentation of a session is useful, especially if it less of a recap and more about lessons learned or remixable activities.

**Comment by xmatthewx** [comment]
Another note: during review, we should add mozfest tag to items, especially if they'll be featured.

**Comment by acabunoc** [comment]
I added `mozfest` to the ones I approved. I noticed there's also a `mozilla festival` tag. Just to confirm, we're doing `mozfest` instead of `mozilla festival`?

**Comment by xmatthewx** [comment]
Great. Yes, let's use `mozfest`.

**Comment by xmatthewx** [comment]
I created 1-page moderation guide so we can onboard a couple of staff. I'd welcome feedback @jessevondoom @Sydette @hannahkane 

https://mzl.la/pulse-moderation

**Comment by xmatthewx** [comment]
We're ready!
