### ISSUE TITLE
Add a Your Name field to form

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#75]
In many cases, assets will be submitted by someone other than the creator (e.g. program staff after an event). Consider adding a Your Name field under the Optional Details heading. 

Opinions? @kristinashu @acabunoc 

We don't need to display this, but could include to give props to helpful network curators.

**Comment by xmatthewx** [comment]
We could also specify creators & collaborators & contributors ... or add distinct fields.

**Comment by xmatthewx** [comment]
related to #34

**Comment by kristinashu** [comment]
The simpler the form the better so I'd lean towards not having a name field since it doesn't have any major value.

**Comment by xmatthewx** [comment]
We can discuss this is #34. Closing.
