### ISSUE TITLE
Remove legal copy on forms

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#756]
Once https://github.com/mozilla/network-pulse/issues/755 is done we can remove the legal copy above the submit buttons on both forms.

### Add entry form
Current copy:
> By submitting your entry, you agree to be bound by the Mozilla Terms of Service, and you agree that your entry may be edited lightly for clarity and style.

New copy:
> By submitting your entry you agree that it may be edited lightly for clarity and style.

### Profile form
Current copy:
> By submitting your profile, you agree to be bound by the Mozilla Terms of Service. Please contact us if you have any questions or concerns.

New copy:
> Please [contact us](https://mzl.la/pulse-contact) if you have any questions or concerns.

**Comment by shikhar-scs** [comment]
@kristinashu May I work on this issue please?

**Comment by kristinashu** [comment]
Thank you @shikhar-scs but unfortunately this issue is blocked by #755

**Comment by shikhar-scs** [comment]
@kristinashu Ok. So once #755 is done away with, I'll get back to this and make the required changes. Thankyou
