### ISSUE TITLE
Fix our broken Hearts ♥ ♥ ♥

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#759]
Our hearts are sometimes broken. 💔 😢  

Some fav hearts are fine, some are cut off on the left and right edge. The bottom-left entry below is fine, the rest are cropped. 

![image](https://user-images.githubusercontent.com/53411/31556276-44543356-b012-11e7-8e3f-957c442119e8.png)

**Comment by mmmavis** [comment]
😞 @xmatthewx which browser was this screencap taken from?

**Comment by xmatthewx** [comment]
Looks good for me on FF Nightly. Screenshot is from Chrome.

**Comment by mmmavis** [comment]
up on https://network-pulse-staging.herokuapp.com for verification

**Comment by ryanwarsaw** [comment]
🕺 🎉 ❤️ 🙈

**Comment by xmatthewx** [comment]
👍
