### ISSUE TITLE
"Add" form: show character count on all fields that have character limit

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#769]
- [x] title
- [ ] description
- [ ] interest ("Why might this be interesting to other people in our network?")
- [ ] get_involved ("Looking for support? Describe how people can do that.")

@kristinashu can you double check and see if the above list includes all the fields we need to show character count on?

**Comment by kristinashu** [comment]
Curious what others think but I believe Title is the only field that really needs it. 

Now that we have a dedicated page for each post, we probably don't need a counter for the Description (or Interest and Get involved). I would prefer to encourage people to write and if it becomes a problem then we can start to enforce a limit but until then, let's not deter people from posting.

But yeah, this can wait until post-mozfest!

**Comment by xmatthewx** [comment]
Your call @kristinashu. I guess I'd keep some limit, so people don't go nutz, (or malicious people don't try and crash things) but it's fine to expand, but glad to expand things if it's better for users.

**Comment by mmmavis** [comment]
We should keep character/word limits in the backend. Posting things that exceed their limit will probably result some server error back. We can either do validation on the front end level (character count, before user is able to submit the form) or display the server error in a user friendly way (this is after user submitted the form)

@Pomax thoughts?

**Comment by gideonthomas** [comment]
done
