### ISSUE TITLE
Communicate Quality Tests in wiki

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#77]
I added [Quality checklists](https://github.com/mozilla/network-pulse/wiki/Quality-Tests) to the wiki. 

Let's:
 1. add new and missing features
 2. test across devices as we ship things 

Check off your name below if 
 - you know the QA checklist exists, 
 - and are committed to using it in pursuit of quality

Don't check off your name if you object to the QA tests or these patronizing (checklists for knowledge transfer 😫 )
 
 - [ ] @mmmavis 
 - [x] @acabunoc 
 - [x] @kristinashu 
 - [x] @hannahkane 
 - [ ] @cadecairos

**Comment by hannahkane** [comment]
Am checking off to say I reviewed the QA checklist, not that I've done any QA. Is that right?

**Comment by xmatthewx** [comment]
No need to review at this time. Checking off that you know the QA checklist exists, and are committed to using it in pursuit of quality, justice, and happiness for all!

**Comment by hannahkane** [comment]
Can I get that on a bumper sticker?

**Comment by acabunoc** [comment]
I think these would be more useful if the checklist contains what is currently implemented with new features added as we go along. Tried to use it in this review, but it wasn't super helpful:
https://github.com/mozilla/network-pulse/pull/86#issuecomment-237369632

While it'll be more upkeep, I think it would help keep up the quality as we add features. Might not be worth it if we add all these features soon :) (I think this might be the case)

**Comment by xmatthewx** [comment]
Thanks @acabunoc – the list reflects the new UI and our goal with MVP. A few things might drop off, but we tried to avoid items that definitely won't land in MVP. 

For a release, we'll want to run thru the whole script. For a PR review, we can just hit the items that would likely be impacted.

**Comment by xmatthewx** [comment]
Thanks for testing it! Maybe we can mark things as coming soon in the list, and remove that label after it lands.

**Comment by acabunoc** [comment]
We're much closer with the last couple PRs! And I really like the idea of using a list like this. I think 'coming soon' is a good compromise in the meantime.

**Comment by kristinashu** [comment]
Everyone seems to be using it, success!
