### ISSUE TITLE
"Profile" form: show character count on all fields that have character limit 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#770]
## Update (Jan 22, 2018)

Follow https://github.com/mozilla/network-pulse/issues/770#issuecomment-359518065 for specs instead

---

## Original ticket description

- [ ] `custom_name` ("Name")
- [ ] `user_bio` ("Bio (do not include any personal information)")

@kristinashu can you double check and see if the above list includes all the fields we need to show character count on?

**Comment by xmatthewx** [comment]
Note: this is not critical pre-mozfest. 

Cool. Ideally we can just see if the model has a character limit, and then show the count. Rather than manually identify and set up each field.

**Comment by kristinashu** [comment]
I don't think these fields should show the character count. It will feel pretty overwhelming for users if every fields has a counter.

**Comment by mmmavis** [comment]
( similar discussion: https://github.com/mozilla/network-pulse/issues/769#issuecomment-336982805 ) 

If not showing character count, do we wanna keep character/word validation on the front end?

**Comment by himanish-star** [comment]
@mmmavis , I would like to take this issue up after completion of #907 . May I ?

**Comment by himanish-star** [comment]
@xmatthewx , Thanks for the details.

**Comment by mmmavis** [comment]
Hey @himanish-star yea and please refer to @xmatthewx 's comment for specs!

**Comment by himanish-star** [comment]
Yeah, I sure will

**Comment by codexdelta** [comment]
Shall we close this issue?
