### ISSUE TITLE
Sign-in Experience

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#771]
This epic collects the new sign-in view, copy, and issues to related to UX, flow, redirects.

**Comment by xmatthewx** [comment]
We added a link from the "thanks for your submission view" to encourage profile edits. I filed a ticket #867 to do the same for staff/moderators. It makes this other work less critical. Still valuable, but less critical.

**Comment by Pomax** [comment]
closing due to having just completely redesigned this for the 2019 incarnation =)
