### ISSUE TITLE
Add links to Moderation view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#776]
Entry cards in our Moderation view don't currently include the main link or the get involved link. We should add those so moderators can check the quality. 

Link text can display full URL so we can see bad things like in the mockup below. 

 `Link: <a href="[content_url]" target="_blank">[content_url]</a>`
 `Help: <a href="[get_involved_url]" target="_blank">[get_involved_url]</a>`

![image](https://user-images.githubusercontent.com/53411/31787754-b44ff6b4-b4da-11e7-89ff-15ecba1abdf5.png)

@alanmoo - if you have some down time this week or next...

**Comment by mmmavis** [comment]
`get_involved_url` should already be there if it exists. If not then it would be a bug 😉

**Comment by xmatthewx** [comment]
Ah yes! You're right.... Get involved is there already. I guess I saw several posts that didn't use it.

We should add the main link and also consider displaying URLs since anyone can post anything.

**Comment by alanmoo** [comment]
What do you mean by "consider displaying URLs"?

**Comment by mmmavis** [comment]
@alanmoo I have time today so I can take this on if you haven't started working on it already.

As for `consider displaying URLs` I think Matthew probably meant listing the actual URL than just a hyperlinked text.

**Comment by alanmoo** [comment]
Go for it

**Comment by mmmavis** [comment]
@xmatthewx this is what we have currently
<img width="370" alt="screen shot 2017-10-23 at 11 08 06 am" src="https://user-images.githubusercontent.com/2896608/31905274-7ca724e8-b7e2-11e7-8591-8dd484ada1cf.png">

Do you want the "Get involved" hyperlinked removed from that section and add a *new* section that displays full URLs of the `content_url` and `get_involved_url`?

**Comment by xmatthewx** [comment]
I think we can keep. Doesn't matter too much on moderation view. Use your judgement.

**Comment by mmmavis** [comment]
Sure, I can add an additional section there so moderation during MozFest can be easier. My only concern is the cards will get extra long with full URLs displayed. I guess if that becomes a problem hovering over on any hyperlinked element to check the full URL in browser can always be a solution.

For example: on Firefox, hovering over a hyperlinked element (in this case, "Visit") will show the full URL at bottom left

<img width="795" alt="screen shot 2017-10-23 at 12 24 48 pm" src="https://user-images.githubusercontent.com/2896608/31908927-51cb7ffc-b7ed-11e7-9955-4951671f610d.png">

**Comment by xmatthewx** [comment]
We'll likely do a bunch of moderation on mobile since the interface is so nice.
