### ISSUE TITLE
Set up alerts if posting fails

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#778]
Maybe we could get a slack ping if a user gets an error so we can check it out?

**Comment by cadecairos** [comment]
Plan: Create a label in LogEntries that will apply to logs which indicate a posting failed. This will trigger a Slack post to `mofo_network_pulse` to inform us of the error.

**Comment by patjouk** [comment]
The alarm and tag were created on logentries. Closing this ticket 🎉
