### ISSUE TITLE
Staging QA: Mobile - (+) button overlaps footer content.

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#788]
The `(+)` button overlaps some of the content in the footer. Can we add some extra padding to the bottom or right of the footer?

![image](https://user-images.githubusercontent.com/25212/31901830-87713f36-b7d7-11e7-8937-b20149886328.png)

**Comment by kristinashu** [comment]
This won't be an issue with the new UI updates https://github.com/mozilla/network-pulse/issues/731 so closing this ticket.
