### ISSUE TITLE
Staging QA: Plus (+) button hard to see in footer.

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#789]
On mobile we don't get a hover state, so the plus button will always be black. It's hard to see against the footer...

![image](https://user-images.githubusercontent.com/25212/31901906-cf0598b0-b7d7-11e7-9a6d-3cf3ac2ee66e.png)

**Comment by kristinashu** [comment]
This won't be an issue with the new UI updates https://github.com/mozilla/network-pulse/issues/731 so closing this ticket.
