### ISSUE TITLE
Staging QA: Entries have double <hr> below the Get Involved section.

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#790]
Suggestion would be to just add some padding or extra space instead. Looks like there is missing content or something.

![image](https://user-images.githubusercontent.com/25212/31901974-2123a1dc-b7d8-11e7-8690-eca678d40826.png)

**Comment by xmatthewx** [comment]
Yep. Good catch. Note: this happens even with all optional fields filled in. We can drop sidebar <hr> on narrow views.

**Comment by mmmavis** [comment]
Works good on staging and will be on production tomorrow!
