### ISSUE TITLE
Staging QA: Get involved link & heading seem strange.

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#795]
For many entries, the Get Involved section just includes a Get Involved link below it, which looks strange or unfinished somehow. Possible to change one or the other?

* Heading: Want to help? / How to help.
* Link: Get involved.

Or maybe just list the actual URL as the link for getting involved?

![image](https://user-images.githubusercontent.com/25212/31902376-7f03bc32-b7d9-11e7-8a61-c7e4c1c0be28.png)

**Comment by xmatthewx** [comment]
We could have placeholder copy when there's no Description copy. "Help with this project..."

**Comment by xmatthewx** [comment]
We currently display default copy, but only if there's no text AND no link. 

 - We should display default copy it if there's no text, regardless of whether there is a link or not. 
 - We might also change copy on that link to "Start here". 
 - I recommend we always put the link on a new line, below the copy. 
 - Lastly, I wonder if we should have a header above help tags. 

cc @kristinashu for feedback, sanity check, and typography


#### scenario: no link, no text (currently implemented)

![image](https://user-images.githubusercontent.com/53411/32908879-eed43dd2-cad2-11e7-809e-7de0928b774c.png)

#### scenario: has link, but no text (proposed)

![image](https://user-images.githubusercontent.com/53411/32909020-62e0e14e-cad3-11e7-8560-1a182b41f2ee.png)

#### scenario: has link, has text (proposed)

![image](https://user-images.githubusercontent.com/53411/32909128-bd58e7ca-cad3-11e7-876f-eebd622cdbab.png)

**Comment by xmatthewx** [comment]
Another option: if they have a link, require some text. I hate to add blockers, but it might be reasonable. That would cut out the middle option.
