### ISSUE TITLE
Staging QA: Improve placeholder text for Google Form inputs, they all say "Your Answer"

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#796]
While name and email are pretty obvious, maybe can use it to give suggestions or help frame the message field. Or maybe just inject some personality...

* Field: Your name
* Placeholder: Pleased to meet you!

Or something like that.

![image](https://user-images.githubusercontent.com/25212/31902510-fee2ae04-b7d9-11e7-9ea4-5ec3bba6d6d7.png)

**Comment by xmatthewx** [comment]
@flukeout google forms doesn't seem to allow customizing this. true? or am i missing something?

**Comment by flukeout** [comment]
No, you are right - I just assumed it would be possible! Lame! You _can_ add a description below the field if you want, but no placeholders.
