### ISSUE TITLE
Staging QA: "1 Results Found" <- fix pluralization for results when there is only one

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#797]
The Syria tag only has one entry, but it says `Results` instead of `Result`

https://www.mozillapulse.org/tags/syria

![image](https://user-images.githubusercontent.com/25212/31902656-712596f2-b7da-11e7-8055-5d4586dfb8df.png)

**Comment by mmmavis** [comment]
haha thought I had this covered but apparent I did not

```js
let counterText = `${this.state.totalMatched} result${this.state.totalMatched > 0 ? `s` : ``} found`;
```

😂 😂 😂 😂 😂

**Comment by mmmavis** [comment]
Fixed!
