### ISSUE TITLE
Staging QA: Tag list shows 0 Results Found briefly before actual count

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#798]
If you refresh https://www.mozillapulse.org/tags/syria a few times, you'll notice that it shows 0 Results Found before showing the actual count. Let's hide this heading until the action is complete and we show the correct result?

![results-found](https://user-images.githubusercontent.com/25212/31902779-e92d7c00-b7da-11e7-8b69-b26038de2090.gif)

**Comment by codexdelta** [comment]
Shall I show a loader instead of 0 till the promise is resolved?

**Comment by xmatthewx** [comment]
Thanks. There's already a loading indicator below. I think we can just hide the "results found" element until we get a reply from the server as you suggest.

**Comment by codexdelta** [comment]
@xmatthewx, can we close this issue?
