### ISSUE TITLE
Move this repo over to mozilla

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#8]
Hey @xmatthewx I don't have the rights to add collaborators to this repo. Can you add @cadecairos so he can move this repo over to mozilla?

I think we can probably just delete the forked repo: https://github.com/mozilla/network-pulse 😀

**Comment by cadecairos** [comment]
@xmatthewx I need admin privileges for this repo to transfer it over

**Comment by xmatthewx** [comment]
done!
