### ISSUE TITLE
Shorten the Item link

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#80]
Instead of https://mozilla.github.io/network-pulse/?id=p1455656415000, we can use https://mzl.la/pulse?id=p1455656415000 for our share links.

**Comment by xmatthewx** [comment]
Note: no `/` between `pulse` and `?`

Magic happens here: https://github.com/mozilla/network-pulse/blob/4aa48c504c2cca9a7de9ada900e751a7cbbb094d/js/utility.js#L35

**Comment by mmmavis** [comment]
I was told before that having a trailing slash before `?` is a better practice... but I could have remembered it wrong. @cadecairos any suggestion?

The app should work as expected with or without the trailing slash. But I think it would be good if we stick with one format when we share out links.

Note before things get more complicated that https://github.com/mozilla/network-pulse/issues/169 needs to be fixed before I tackle this ticket.

**Comment by xmatthewx** [comment]
I should have mentioned: bit.ly won't properly forward the request with the slash. I tried it both ways. It does, however, seem to add the slash to match the spec.

`https://mzl.la/pulse?id=p...` yields `https://mozilla.github.io/network-pulse/?id=p...`

**Comment by cadecairos** [comment]
Oh, I didn't realize we had a path after the domain. We should be fine in that case
