### ISSUE TITLE
Staging QA: Confusing UX around Promote tag in get involved.

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#800]
Entry https://www.mozillapulse.org/entry/469 has a Promote button at the bottom in the Get Involved section...

![image](https://user-images.githubusercontent.com/25212/31902925-62ae9b54-b7db-11e7-91d6-565445a3d776.png)

Clicking it links to https://www.mozillapulse.org/help/Promote which seems a bit confusing. I would expect a "Promote" button to maybe fire up some social media sharing options. My guess maybe is that this is a project that needs promoting, clicking the button loads other projects that need promoting? Unsure.

**Comment by nileshgulia1** [comment]
Hello @flukeout, may be the writing `Get involved` there is more focused  rather than promote ,as it is already written that it is asking for people to get involved ,or may be the button should named something else?
