### ISSUE TITLE
Staging QA: When navigating to "Add" page, scroll page to the top.

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#803]
Steps to reproduce

* Browse a long list in narrow, single column layout mode and scroll way down
* Now hit the add button
* You go to the add page
* Page is scrolled to the bottom of the form
* Expectation: Page is scrolled to the top

This also happens with the tag list view as filed in #801

**Comment by xmatthewx** [comment]
👍 this is good to ship
