### ISSUE TITLE
Staging QA: Add page "Terms of Service" links to "Terms of Use"

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#804]
Let's change the link to be consistent with the page people are navigating to?

![image](https://user-images.githubusercontent.com/25212/31903313-9f839812-b7dc-11e7-8edc-acdc921a69c7.png)

Goes to [Terms of Use](https://www.mozilla.org/en-US/about/legal/terms/mozilla/)

**Comment by himanish-star** [comment]
I would like to take this issue up, may I ?

**Comment by xmatthewx** [comment]
Sure. Thanks @himanish-star! For this, we just need to change the string from `Mozilla Terms of Service` to `Mozilla Terms of Use`.

**Comment by mmmavis** [comment]
Yay fix is now live on production. Thanks for the help @himanish-star 👍
