### ISSUE TITLE
QA: Increase social media icon size on mobile

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#805]
On mobile, social icons are pretty tiny. Should have minimum of 40px touch target.

**Comment by mmmavis** [comment]
Do we want to 1) make those icon bigger (40px wide) or 2) add spacing in between icons?

**Comment by kristinashu** [comment]
Icon size is ok, just made the hint area bigger please.

**Comment by xmatthewx** [comment]
this  screenshot shows the relative size of icons on profile versus entry. the profile ones still feel small to me. we can live with this, nobody will be injured, but seems like a good opportunity to align styles.  

<img width="219" alt="image" src="https://user-images.githubusercontent.com/53411/32967259-ef2f63aa-cbaa-11e7-849f-978bcc1eb8a7.png">

**Comment by kristinashu** [comment]
Oh I didn't realize you where talking about the links in profiles... I'll take a look.

**Comment by mmmavis** [comment]
The fix to increase hint area has been merge to `master` and pushed to staging. If we want to change icons on profile so they align with icons on entry we should file a new ticket!

**Comment by mmmavis** [comment]
@kristinashu I saw you moved this to the "Up Next" pipeline. Give me a ping when this is ready for implementation again!

**Comment by kristinashu** [comment]
@mmmavis could you please make the profile icons (Twitter, LinkedIn, and GitHub) the same height as the post icons are (heart and Twitter share). And then make all their hit areas 40x40px.

**Comment by mmmavis** [comment]
@kristinashu 

> Could you please make the profile icons (Twitter, LinkedIn, and GitHub) the same height as the post icons are (heart and Twitter share). And then make all their hit areas 40x40px.

Making the hit areas exactly 40x40px would be a bit complicated as each icon has different dimensions plus we have consider padding and margin. I'll try to balance things out and make the hit areas as close to 40x40px as I can.

**Comment by mmmavis** [comment]
@kristinashu ah forgot to ask -- Are these changes for mobile only? (as described in Matthew's ticket description)

**Comment by kristinashu** [comment]
Roughly around 40x40px is great. These updates can be for both mobile and desktop.

**Comment by himanish-star** [comment]
@mmmavis , is this issue still available. Can I fix this ?

**Comment by mmmavis** [comment]
@himanish-star thanks for offering help. I have not yet had time to tackle this. Would you be interested in taking on this ticket? 😃

**Comment by himanish-star** [comment]
@mmmavis , Yeah sure

**Comment by mmmavis** [comment]
@himanish-star Awesome! :1st_place_medal:

**Comment by himanish-star** [comment]
@mmmavis , User profile doesn't get updated while running on `localhost:3000` . And thus without updating social media links how to I see the icon size changes locally as the icons don't show up. Is there any other way of testing
![image](https://user-images.githubusercontent.com/30361728/34702044-9973d7b2-f511-11e7-8697-e5e7f059d351.png)

**Comment by mmmavis** [comment]
Hey @himanish-star Ah there's something we need to fix on the API side... I'll file a ticket. Meanwhile I think you can just use my staging profile to fix this UI sizing issue.

You should be able to see my profile on `/profile/8` (if you are using the staging API)

**Comment by himanish-star** [comment]
@mmmavis , Thanks a lot.

**Comment by mmmavis** [comment]
@himanish-star 's fix has been merged into `master` branch and pushed to staging. I'll do a prod push next week and close this ticket once that's done.

**Comment by mmmavis** [comment]
Yay. Fix has been pushed to production. Thanks @himanish-star 🎉
