### ISSUE TITLE
Staging QA: "Add Page" form error messages are hard to notice.

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#806]
Here's a cap of a field with an 'error state'. I think it's too subtle given that we already use red for headings. Also on "mobile/narrow" mode, we don't scroll the page up when you have errors, so the user is left having to scroll up to notice these.

Some ideas..
* Add red border to field
* Red background, white text on the indicator
* Move indicator closer to field
* Add little arrow pointing up

![image](https://user-images.githubusercontent.com/25212/31903374-c7d07ec0-b7dc-11e7-83ae-2a3bb354aadc.png)

**Comment by kristinashu** [comment]
Yeah let's do what was in the comps! 

- Red border around the field
- Indicator close to field
- X next to text

<img width="685" alt="screen shot 2017-11-08 at 3 19 10 pm" src="https://user-images.githubusercontent.com/1068783/32580014-46d356b2-c498-11e7-9dab-e71cc7578f48.png">

**Comment by mmmavis** [comment]
Works on staging!
