### ISSUE TITLE
Show Favs help text for logged-in users

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#807]
This view only shows the empty view tip to save your favs if a user is not logged in. Logged in users just get an empty view if they have no favs. 

![image](https://user-images.githubusercontent.com/53411/31903459-270d66a0-b7f6-11e7-87ee-e0defe25e564.png)

**Comment by alanmoo** [comment]
Just to be clear- the request here is that "the content of the screenshot should show up if a user is logged in but doesn't have any favs", is that correct?

**Comment by xmatthewx** [comment]
Yes, everyone should see this help text if they have no favs, regardless of auth state.

**Comment by xmatthewx** [comment]
perfecto
