### ISSUE TITLE
Staging QA: "Add" Page has wording around "Are you a creator?" field

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#808]
![image](https://user-images.githubusercontent.com/25212/31903515-2b147e00-b7dd-11e7-904f-5c5beb0f394d.png)

Seems stilted. Can we simplify to 

`[ ] I am one of the creators` without a label?

or change to 

`[ ] Yes` and keep the label above.

**Comment by xmatthewx** [comment]
We had some technical limitations. 

Let's go without second option. Leave heading and change checkbox copy to...
`[ ] Yes `
