### ISSUE TITLE
Consider how metrics are revealed

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#81]
How can we reveal underlying metrics, info, stats?  Are there small ways (e.g. item count on issue menu), or big ways (e.g. dedicated metrics view).

**Comment by xmatthewx** [comment]
cc @arlissc https://redpen.io/mve7a49a24885c95c0

**Comment by kristinashu** [comment]
@xmatthewx can you please elaborate a little more on this? Do you mean metrics that a user could see and track?

**Comment by xmatthewx** [comment]
This would be very valuable at Mozfest. Also could be useful as we evaluate the pilot test.

**Comment by xmatthewx** [comment]
@vojtechmzl – I'm interested in exploring how we can reveal some metrics within pulse. Discussion coming soon. (Sorry for the deluge of message this afternoon!)

**Comment by xmatthewx** [comment]
Some info/data we could work with...
 - trending items (views, shares, favs)
 - patterns or map of creators+projects
 - Issue, tags, keywords ... numbers and trends (we could have our own curated list of keywords like IoT and not just rely on tags)
 - dates? eh. probably not that interesting
 - others???

**Comment by kristinashu** [comment]
## Option 1
Have a dedicated page where people can see stats pulled from google analytic. It would be a page full of charts and graphs. Could use these [google charts](https://google-developers.appspot.com/chart/interactive/docs/gallery) or something like the [copyright campaign dashboard](https://datastudio.google.com/open/0B5UMbl9u1_wQRnZOU0pYc1FPSWs), but on a single page within the pulse app.

## Option 2
Work the data into the existing pages.

#### Landing:
Add sort filers like Most Popular (posts with the most views), Most Favorited...

<img width="715" alt="screen shot 2016-11-28 at 12 06 57 pm" src="https://cloud.githubusercontent.com/assets/1068783/20684117/841b7828-b563-11e6-90c8-e41c57b6e9db.png">

#### Search:
Surface popular tags, creators....

<img width="808" alt="screen shot 2016-11-28 at 12 07 05 pm" src="https://cloud.githubusercontent.com/assets/1068783/20684124/88cc48ca-b563-11e6-8d1a-513ad944bd02.png">

#### Issues:
Add the total number of issues to each filter

<img width="686" alt="screen shot 2016-11-28 at 12 07 18 pm" src="https://cloud.githubusercontent.com/assets/1068783/20684130/8e020f78-b563-11e6-8fbf-93f38bd3d6a0.png">

#### Detail:
Could show tags and number of favs on the detail view.

<img width="773" alt="screen shot 2016-11-28 at 12 07 30 pm" src="https://cloud.githubusercontent.com/assets/1068783/20684159/a607f7f4-b563-11e6-8061-8d9ae5e16217.png">

These tags and creators could be clickable and show filter view with number of results

<img width="741" alt="screen shot 2016-11-28 at 12 08 21 pm" src="https://cloud.githubusercontent.com/assets/1068783/20684203/c1e61cda-b563-11e6-8ba9-d351d858077f.png">

<img width="739" alt="screen shot 2016-11-28 at 12 08 31 pm" src="https://cloud.githubusercontent.com/assets/1068783/20684204/c1e949d2-b563-11e6-9b01-9b96f212b2cd.png">

**Comment by xmatthewx** [comment]
These are all good. We should probably implement most of it when v2 is ready and after we do a bit of feedback in redpen. And... I still think we should explore less obvious, more bold possibilities. Things that can reveal and express the network's footprint. 

When we hit triple digits on a Issue (we already have 65 or so in Open Innovation), the numbers alone still don't tell us that much. What are the common tags or words in Open Innovation? How are they different than other issue areas? Do all issues steadily increase at the same rate, or could a sparkline graph reveal different patterns? We can look at a list of all Ford Foundation fellow projects, but what could a node map with them at the center show? How do the fellows and projects they support then branch out to other projects? 

A view of top shares or favs will encourage people to game the system, reinforcing projects from people that already have influence and audience, rather than great projects from new creators.  Could a single view feature trending shares and favs and creators achieve something different? Or, would a more magazine style layout engage visitors?

There are dozens and dozens of fellowship projects and mozilla initiatives and hive projects that are still yet to be captured. And the tide they comprise together is yet to be felt. How can numbers, and connections, and patterns make this visible, visceral, and real?

**Comment by kristinashu** [comment]
I've added a comp for a dedicated data view page: https://redpen.io/p/nzcd35d57dd04ad6dc It's very rough and I'm open to ideas of what sort of data we could potentially show.

cc @acabunoc

**Comment by kristinashu** [comment]
@xmatthewx can we close this? 

Numbers have been added to issues.

**Comment by xmatthewx** [comment]
Sure we can close it. But I do hope to come back to the idea this fall.
