### ISSUE TITLE
Critical: profiles display all entries, regardless of moderation state

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#814]
My profile, regardless of login state, displays two declined entries. https://www.mozillapulse.org/profile/85

**Comment by xmatthewx** [comment]
I'm on mobile. Hard to test. Please confirm.

**Comment by mmmavis** [comment]
https://network-pulse-api-production.herokuapp.com/api/pulse/profiles/85/ does included the 2 declined entries. Let's fix this at the API level

**Comment by Pomax** [comment]
agreed - we should make the API only pull `Entries.objects.filter(moderation_state=Approved)`

**Comment by Pomax** [comment]
filed https://github.com/mozilla/network-pulse-api/issues/248 on the API side
