### ISSUE TITLE
Optimize header & nav for small screens

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#820]
Pulse is awesome on mobile. It could use a little TLC up top on small screens. When 320px wide (iphone 5), the search icon falls to the second line. Sign-up, sign-in gets cut off (could we just say "Login" up there?). 

![image](https://user-images.githubusercontent.com/53411/31951487-4a6b6ca8-b8ac-11e7-8f97-1eb0abba2c53.png)

cc @kristinashu

**Comment by kristinashu** [comment]
We could either turn the logo into the "m" only or go with just "Signin"?

**Comment by xmatthewx** [comment]
I think yes to both

**Comment by kristinashu** [comment]
New nav should solve this https://github.com/mozilla/network-pulse/issues/731

Can we close?

**Comment by xmatthewx** [comment]
addressed in #731
