### ISSUE TITLE
cache historic profile views

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#821]
profiles seem to not be recorded in the app history. STR:

- load a profile, preferably a beefy profile with lots of published/created entries
- click on one of the entries to load it
- on the entry page, click back

expected: profile was cached and is restored instantly
actual: profile gets fetched from the API anew, leading to long load times and probably wasted bandwidth

**Comment by Pomax** [comment]
do we want to fix this before mozfest @matthew @alanmoo? (feels like we might not have the FTEs for that)

**Comment by alanmoo** [comment]
Is this purely front-end or is there a back-end component to this too? I wonder how long it takes to build my profile on the backend vs simply serve it across the pipe. (https://api.mozillapulse.org/api/pulse/profiles/93/?format=json)

**Comment by xmatthewx** [comment]
Profiles are noticeably the slowest thing on Pulse. It's worth doing if we have the time and energy.
