### ISSUE TITLE
Create a People list view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#825]
Now that we have Profiles of people, accessible via entries, it would be great to have a list view of all of these profiles. 

~~Design of a profile summary card could probably happen in parallel with setting up an MVP /profiles view.~~ We could build this out on production, leave it off the primary nav until ready. We could add a link at bottom of an individual profile that says "See more profiles".

**Comment by xmatthewx** [comment]
Actually, we can reuse the the profile component as is, just add a simple divider. 

 - 3em of margin on top and bottom of the `<hr>` on desktop. 
 - Name and thumbnail should link to the profile 

![image](https://user-images.githubusercontent.com/53411/32000051-6019666a-b963-11e7-97e7-8af1a969a917.png)

**Comment by xmatthewx** [comment]
@alanmoo @gideonthomas this could be a great task for one of humph's students. Would be amazing to have this to share at the end of MozFest.

**Comment by mmmavis** [comment]
I might be mistaken but currently there's no API endpoint to retrieve all users or all profiles on Pulse. Gonna mark this ticket blocked :stop_sign:

**Comment by gideonthomas** [comment]
done
