### ISSUE TITLE
Fix quirky cloning items

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#83]
When I view an individual project, the auto check for new projects loads a new clone. Keep the tab open for a while, and you'll spawn many new items in the lightbox.  

🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑  🐑

**Comment by mmmavis** [comment]
This should go away after PR #112 gets merged.

**Comment by mmmavis** [comment]
FIXED! 🎉
