### ISSUE TITLE
Improve developer ergonomics

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#834]
Sister ticket to https://github.com/mozilla/network-pulse-api/issues/258

We should focus on making this repo easier for people to spin up for the first time. (Some of these may already be done, I'm just making a list of things we need to check)

- [x] Make sure the staging API is configured to allow access and login from a local instance of the client-side repo
- [x] Make sure the documentation reflects anything special that needs to be done for this (local forwarding of test.example.com, for instance)
- [x] Make sure sample/default env files are set up correctly for first time use after copy, with clear indicators for settings that need to change to access a locally hosted API

**Comment by mmmavis** [comment]
- [ ] Make sure review apps are whitelisted by staging API

**Comment by alanmoo** [comment]
Great point, I think that one is the most useful of all of these @mmmavis - I keep having to log into heroku and whitelist a specific client-repo review app

**Comment by mmmavis** [comment]
- [ ] Include some dummy data for devs to run locally (not sure if this is backend thing or devops thing)

**Comment by alanmoo** [comment]
@mmmavis That's in the pulse-api repo. Through the link in the original comment here, you'll find https://github.com/mozilla/network-pulse-api/issues/196

**Comment by patjouk** [comment]
I think we're done for those issues. If we run into new ones, we should open a new ticket.
