### ISSUE TITLE
Update fav icon

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#838]
Please update the fav icon the 'm' bug like on [Foundation site](https://foundation.mozilla.org/).

**Comment by mmmavis** [comment]
@kristinashu can you help export files (180x180 @ 2x and 196x196 @ 2x) ? I realized PNG files on https://github.com/mozilla/foundation.mozilla.org/tree/master/source/images/favicons are not for retina.

**Comment by kristinashu** [comment]
Here are the retina images and the svg in case you need it too:
![apple-touch-icon-180x180 2x](https://user-images.githubusercontent.com/1068783/32967550-e67aa6ec-cb92-11e7-8a1b-2c79db79d71f.png)
![favicon-196x196 2x](https://user-images.githubusercontent.com/1068783/32967551-e69949da-cb92-11e7-8757-9afc88fc9f78.png)
[moz-fav.svg.zip](https://github.com/mozilla/network-pulse/files/1483736/moz-fav.svg.zip)

**Comment by mmmavis** [comment]
@kristinashu I'm gonna do a prod push if this looks good on staging.

**Comment by kristinashu** [comment]
Go for it!

**Comment by mmmavis** [comment]
🎉
