### ISSUE TITLE
Update eLife entries

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#839]
A bunch of entries were started during MozFest, but content was completed afterward. We need to lend a hand to update them. Content in [this doc](https://docs.google.com/document/d/1gE_z_ZAxDg4lGcgPOkBJwGdmoOtJeVK4UKnry6So9nw/edit). Hopefully everything transfers easily and doesn't require back and forth with our contact.

**Comment by xmatthewx** [comment]
@stephwright is going to valiantly lend me a hand on this.

**Comment by stephwright** [comment]
Updated the doc for content.  Noted those items which just need editing on existing entries and made comments on those where I'll reach out to the project leads to add new entries themselves.  There are a couple where I need to reach out to the project leads and get more info.  I've noted those as well.

**Comment by xmatthewx** [comment]
Thanks @stephaniemcv. Let's follow up with each other next week to see what's left.

**Comment by stephaniemcv** [comment]
Always up for a chat! My calendar is up-to-date, but I'll probably be of no use to you @xmatthewx. ;-)

**Comment by xmatthewx** [comment]
Ooopsie doopsie 😊

**Comment by stephwright** [comment]
Ha!  Oops... just caught this!  Got time next week to follow up @xmatthewx ?
