### ISSUE TITLE
Implement UI changes for Project Cards

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#84]
For Sketch file refer to: https://github.com/mozilla/network-pulse/issues/59

- [x] styling
- [x] add date
- [x] display image (if any) #57

**Comment by mmmavis** [comment]
@kristinashu could you please export a filled version of heart and drop it to https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2irLVDJivhLWmZlZ0stNEd1a2c&usp=drive_web ? Thanks! 🐹

**Comment by kristinashu** [comment]
Added!
