### ISSUE TITLE
Remove Featured from nav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#840]
@xmatthewx how do you feel about removing Featured from the nav and just relay on the Mozilla logo to link to the Featured page. 

#### Pros
- fewer options feels less overwhelming for users
- fits better on mobile
- it's what the Foundation site does
- more modern trend

#### Cons
- might not be as obvious for everyone so Featured might get less traffic

Can analytics help us decide?

**Comment by xmatthewx** [comment]
I took a look at Analytics, specifically at new users who arrive via a link to something specific. For people who landed on /tags/mozfest as their first page, roughly 50% who stayed went to /featured. For people who landed on our highest traffic entry /entry/438 (Ding magazine), roughly 33% who stayed went to /featured. So there's some risk with new users who arrive via a link to a subpage. 

One option would be to relabel it as Home. Like the foundation site, show it on small screens, not on desktop. I'd bet that we'd see an increase going to Latest, and fewer tapping the logo to go Home. If the bounce rate doesn't go up, that's okay. If we had higher traffic, we could run an a/b test, but I don't think we have the numbers for that at this stage.

I'm open to some AI exploration. A richer homepage could include topics and toggle between featured and latest. The nav could be add About and keep Favs, have room for search input.

**Comment by kristinashu** [comment]
Closing this in lieu of https://github.com/mozilla/network-pulse/issues/863
