### ISSUE TITLE
Add a persistent search bar to signal this feed is also an archive

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#841]
Feedback from a user was that a more prominent search bar would help the app feel more like an archive of info. I will play around with some designs.

@xmatthewx is that right?

**Comment by xmatthewx** [comment]
Yes, but I was the user who said that. I also wonder if adding Featured/Trending tags and help categories at the top of the landing page (with or without search bar), could also send that signal. Worth discussing and then maybe some quick mock ups.

**Comment by xmatthewx** [comment]
Designs from @kristinashu 

![image](https://user-images.githubusercontent.com/53411/35932098-c498d316-0c04-11e8-850e-1a5611d0e23c.png)

https://redpen.io/dze10a5f7dca45e587
