### ISSUE TITLE
Update in text links to black with underline

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#842]
Text links (that are not main titles) should be black with underline and update to blue on hover (like how they are on [profile page](https://www.mozillapulse.org/profile/me) and [IRH site](https://internethealthreport.org/2017/10/19/if-not-a-chatbot-then-what-the-next-report-is-taking-shape/)).

Needs updating:
- users with a profile
- 'Contact us.' link on project detail view
- 'Learn more.' link on landing page
- links in forms

Example on staging of how ^ should look:
<img width="505" alt="screen shot 2017-11-14 at 1 55 46 pm" src="https://user-images.githubusercontent.com/1068783/32807047-8ba2bbd4-c943-11e7-8781-7017e2892513.png">

**Comment by mmmavis** [comment]
@kristinashu fix is on staging now. Good to push to production? https://network-pulse-staging.herokuapp.com

**Comment by kristinashu** [comment]
Good good!

**Comment by mmmavis** [comment]
:man_dancing: 💃 :man_dancing: 💃 :man_dancing: 💃 :man_dancing: 💃 :man_dancing: 💃 :man_dancing: 💃
