### ISSUE TITLE
Left align posts

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#843]
Currently on staging when there are 1-2 post then they are centered, but this looks a little off since everything else is left aligned. Please update the posts so they are left aligned.

#### Screen cap from: https://network-pulse-staging.herokuapp.com/profile/2
<img width="1261" alt="screen shot 2017-11-14 at 3 19 26 pm" src="https://user-images.githubusercontent.com/1068783/32810319-49d2104a-c94f-11e7-8651-6da3fd5b092d.png">

#### How it should be:
<img width="1261" alt="screen shot 2017-11-14 at 3 19 26 pm" src="https://user-images.githubusercontent.com/1068783/32810420-a73621c2-c94f-11e7-8e6f-64ceb33e9abd.png">

**Comment by xmatthewx** [comment]
Do we want this for all views? Or just Profiles? (I'm fine either way)

**Comment by kristinashu** [comment]
All views please.

**Comment by mmmavis** [comment]
@kristinashu good on staging? https://network-pulse-staging.herokuapp.com

**Comment by kristinashu** [comment]
Looks great!

**Comment by mmmavis** [comment]
Yay!
