### ISSUE TITLE
Remove legacy GA Event on Nav 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#844]
We have some legacy Analytics Events on our navigation from the Pulse prototype. These are now covered by our routes and Page views. The legacy events actually make it harder to evaluate things, because we get some duplication and ambiguity. 

Let's remove anything with `Category: 'nav link'` and `Action: 'clicked'`

**Comment by mmmavis** [comment]
@xmatthewx If things look good on staging let's close this ticket! 👍

**Comment by xmatthewx** [comment]
Looks good. I'll double after it's on production for a few days.
