### ISSUE TITLE
Better /issues/ child routes handling

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#852]
Currently only the following 5 child routes under `/issues/` will load projects of a particular internet health issue as expected. Any other route under `/issues/` will just load ALL projects on Pulse.

- /issues/online-privacy-and-security
- /issues/open-innovation
- /issues/decentralization
- /issues/web-literacy
- /issues/digital-inclusion

[A bug](https://github.com/mozilla/network-pulse/issues/787) was discovered on profile page due to wrong route mapping. To prevent similar bug from happening again, let's consider the following solutions (suggestions welcomed!)

---

**Suggested solutions:**

1. redirect `/issues/<issue name>` to their corresponding "known" route 
  e.g., https://www.mozillapulse.org/issues/Online%20Privacy%20%26%20Security --> https://www.mozillapulse.org/issues/online-privacy-and-security
2. OR make all unknown routes on /issues/ 404 (e.g., https://www.mozillapulse.org/issues/Online%20Privacy%20%26%20Security will be a 404)

/cc @xmatthewx @alanmoo

**Comment by alanmoo** [comment]
I don't think a 404 is necessary, but if a route isn't matched we could just lop off the issue and redirect to `/issues/`

Yes/No? If this is agreed on, let's make this a "help wanted" item, as I don't think it's a significant issue.

**Comment by mmmavis** [comment]
Works for me. I didn't like the 404 solution either... but just wanted to put it out there.

/cc @kristinashu ^^

**Comment by mmmavis** [comment]
working fine on staging!
