### ISSUE TITLE
Profile - separate published projects and created projects into their own tab

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#855]
@kristinashu

Amazing people like [An-Me](https://www.mozillapulse.org/profile/77) have tons of associated projects on the profile profile. The current implementation/design makes it hard to spot the created project section. I wonder if we can come up with an idea to help created project list less buried. Section header treatment? Tabs?

**Comment by xmatthewx** [comment]
Yep. Full profile [design](https://redpen.io/qua34b5932cdb6cf9f) has tabs, though we'd need to figure out mobile. We could try and tackle this alongside adding the Favs, which will make it even more important.

**Comment by gideonthomas** [comment]
done
