### ISSUE TITLE
Form submission related analytics

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#856]
Followup for https://github.com/mozilla/network-pulse/issues/746
Spreadsheet of all GA events we are tracking: https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=1060389854

---

We have 2 forms on Pulse - **add new entry form** and **profile edit form** and they are built using the `react-formbuilder` library. 

### Fields that failed validation
When a form get validated, the current version of `react-formbuilder` only returns a boolean to tell if form passes validation. If we'd like to track which fields are tripping users up more work is required on `react-formbuilder`.

### Counts?
I would like to get some clarity on this. Do we wanna track number of failed tries before the form was successfully submitted or? If so maybe we can combine `submit error` and `submit success` events to just one?
```js
{
  category: nameOfForm, // "add new"  or "edit profile"
  action: `submit success`,
  label: `nth tries` // if it's `3th tries` it means there were 2 failed attempts before the form was successfully submitted
}
```

Thoughts? @xmatthewx 👀

**Comment by xmatthewx** [comment]
Interesting. I like counting before success, if it's not tricky to implement. And... we'll want to capture failure events that lead to abandonment too, not just success. So I wouldn't get rid of `submit error`.  

> `react-formbuilder` only returns a boolean to tell if form passes validation

Where do we get the inline error messages from? Does form building include those inline without reporting to you in the response? Is there no way to capture those affected field names and return to our event label?

**Comment by mmmavis** [comment]
@xmatthewx 

If we wanna capture field names that didn't pass validation I believe we should update `react-formbuilder`. Doing it elsewhere would probably consider hacky. Tagging @Pomax to confirm.

For `submit error`, when would you like the event to be sent? If we are sending that GA event every time user clicks the submit button that means if it took an user 4 times to successfully submit the form the following GA events will be sent and I wonder if that's what we intend to get

1. submit error, 1st try
2. submit error, 2nd try
3. submit error, 3rd try
4. submit success

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
