### ISSUE TITLE
Fetch google avatar for profiles by default

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#857]

**Comment by xmatthewx** [comment]
@alanmoo - can we use google account avatars? maybe cut out our avatar uploads altogether? a quick look at viability would be useful.

**Comment by alanmoo** [comment]
@Pomax maybe you have thoughts, but I believe this is a nontrivial amount of work. Is it a problem the way it's currently set up?

**Comment by gideonthomas** [comment]
blocked on legal review

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
