### ISSUE TITLE
Enhance About info

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#862]
Pulse could use a bit more info about the platform, the value, and how to get involved. 

Requires
 - [ ] define audience against personas (partners, project leads, contributors)
 - [ ] craft content
 - [ ] design: add visuals?
 - [ ] fontend: build route and simple template
 - [ ] after: link tagline to new view

**Comment by alanmoo** [comment]
This seems old and ambiguous. Is it still relevant?

**Comment by xmatthewx** [comment]
Still relevant. Just not a priority.

**Comment by codexdelta** [comment]
is design available for this?

**Comment by xmatthewx** [comment]
No. I'm going to close this. Will re-open when we actually have time to focus on the content and design.
