### ISSUE TITLE
Track entries by origin/organization

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#864]
To explore partnerships, we want to add a feature that allows us to categorize entries (and people?) by their origin or organizational relation.  

First step: Clarify a few things: 
 - Is origin identified by user selecting options on the form? Or is it added via a query param? (partner could link to `pulse.org/add?origin=foo`)
 - Do want to build for a few origins, or should we abstract this as groups, potentially allowing user created groups in the future?

**Comment by xmatthewx** [comment]
@alanmoo & @xmatthewx to check in with @jessevondoom at all hands on mvp approach and requirements.

**Comment by alanmoo** [comment]
@xmatthewx Is this still a thing we want to do?

**Comment by xmatthewx** [comment]
This is related to @gideonthomas' work on org profiles. But we can close this. Reopen if/when we're able to move partnership stuff forward.
