### ISSUE TITLE
Update thanks message for unmoderated submissions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#867]
When a User submits a new entry, we display a thank you message. We have one version for non-moderators (thanks w/o published entry), one version for moderators (thanks w/ published entry).

For non-moderators, we recently updated their thank you message to point them to their profile and encourage them to edit it. 

For staff/moderators, we should do something similar. 

Proposed implementation for staff/moderators:
 - [ ] shorten header to "Thanks!" 
 - [ ] add paragraph text with link to profile 
 - [ ] add button with link to edit profile
 - [ ] no other changes to submission flow or display of entry

![image](https://user-images.githubusercontent.com/53411/33140754-e4c31326-cf7e-11e7-8d60-a0b8570bdf50.png)

Their new entry appears below this thank you message (no change from current implementation).

**Comment by mmmavis** [comment]
@xmatthewx It seems like the `/api/pulse/profiles/me/` endpoint doesn't include projects that haven't been approved. So either we update the backend or we change the "submission was added to your profile" line to something else.

**Comment by mmmavis** [comment]
Oops I guess I read the ticket description wrong - was the proposed mockup for staff/moderator?

**Comment by xmatthewx** [comment]
Yes. I edited my initial comment to try and make it more clear. Slack me if this is still confusing. I can't login to staging right now to add more screenshots.

**Comment by mmmavis** [comment]
This is the screen a moderator would get after posting an entry.

![screenshot-2017-11-29 yay xmas - mozilla network pulse](https://user-images.githubusercontent.com/2896608/33400824-1853df1c-d50c-11e7-93f8-27a70e7a91cc.jpg)

@xmatthewx is the plan to replace everything (Thanks for Submitting + entry details) with the messages and CTA you mentioned in the ticket description?

**Comment by xmatthewx** [comment]
> is the plan to replace everything (Thanks for Submitting + entry details) with the messages and CTA you mentioned in the ticket description?

No. We should only replace "Thanks for Submitting" with the new copy and CTA. We should keep the entry details. 

Note: the /submitted page for non-moderators should also show button that says Edit Profile. Gideon and I implemented that at MozFest.

**Comment by mmmavis** [comment]
> Note: the /submitted page for non-moderators should also show button that says Edit Profile. Gideon and I implemented that at MozFest.

Nice catch. Yea the button is still there. It's just when I took the screencap I cheated by editing some code so I could skip the entry submission part to get to that screen. 😂

**Comment by mmmavis** [comment]
@xmatthewx @kristinashu 

Ummm... we might wanna consider another treatment for this. It looks a bit odd with a big message block at top.

![screenshot-2017-11-29 flowers 3 - mozilla network pulse 1](https://user-images.githubusercontent.com/2896608/33403744-6c86f6e6-d516-11e7-951f-dfdc38a94fe1.jpg)

**Comment by xmatthewx** [comment]
Yep, yep. Thanks.
 - [ ] Remove the heart
 - [ ] Cut the visual space between the notice and header gradient in half 
 - [ ] Put a light gray line below the message, above the entry. 
   - [ ] Full width like the header gradient. 
   - [ ] Should be about halfway between content above and below. 
   - [ ] `border-bottom:1px solid #c8c8ca;` 
 - [ ] [file as new issue] The red on Thanks could be updated globally to match the left edge of gradient. I think that color is leftover from the prior design. It's also used on fav heart. 

Does this make sense?

**Comment by kristinashu** [comment]
@xmatthewx what if we styled it like the [light purple notification bar](https://redpen.io/kz577880de19fe569c) in the new designers?

<img width="995" alt="screen shot 2017-11-30 at 9 58 16 am" src="https://user-images.githubusercontent.com/1068783/33446491-0e95570e-d5b5-11e7-8747-36c1b7ac46db.png">

**Comment by mmmavis** [comment]
Seems like we are still figuring out the specs and design. Gonna unassign myself but please feel free to assign me back once things are ready for implementation.

**Comment by xmatthewx** [comment]
That's cool. We'll miss the benefit of an edit button getting more existing users to add theirs, but this a better, more useful notice component. 

Let's run with this design.

**Comment by xmatthewx** [comment]
@mmmavis - do you think this is a good approach? Do you have enough to move ahead with this?

**Comment by mmmavis** [comment]
I think I'm good. I'm gonna refer to @kristinashu 's Sketch files for styling details.

**Comment by mmmavis** [comment]
Changes are on staging! @kristinashu @xmatthewx not sure who I should tag for verification on staging 😁

**Comment by xmatthewx** [comment]
fantastic! tested and everything looks and works great.

**Comment by mmmavis** [comment]
Yay!
