### ISSUE TITLE
Don't block ❤️ 

### ISSUE THREAD

**Issue by gvn** [mozilla/network-pulse#879]
Right now it appears that clicking the hearts to fave doesn't toggle the animation until the XHR callback occurs, which makes UI feel laggy.

We should do an "optimistic" UI update and do the animation immediately. If the XHR fails then we should display an error, but otherwise assume it's fine.

**Comment by xmatthewx** [comment]
🚧 ❤️ 🚧

**Comment by mmmavis** [comment]
works great on staging!
