### ISSUE TITLE
Bottom align buttons

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#88]
On desktop / large devices, use masonry layout instead of equal height rows.

<img width="498" alt="screen shot 2016-08-02 at 5 24 17 pm" src="https://cloud.githubusercontent.com/assets/2896608/17349823/08884da6-58d6-11e6-93c0-320bd1ea129c.png">

**Comment by xmatthewx** [comment]
Cool. Nice to have, but less critical than other pieces.

**Comment by xmatthewx** [comment]
cc @kristinashu - consider design if we can't do masonry

**Comment by mmmavis** [comment]
there are 2 options to implement masonry

1. CSS only solution: projects will be arranged from top to bottom and left to right. (vs what we have currently: left to right and top to bottom)
```
1 4 7             1 2 3
2 5 8     --->    4 5 6
3 6 9             7 8 9
```

2. Option 1 + JavaScript hacks to fix project ordering. We will need to rely on external library for this: http://masonry.desandro.com/

**Comment by kristinashu** [comment]
Thanks Mavis! I don't think Option 1 is really an option. Most Recent tab would be very misleading if the order is all messed up.

What are the concerns/negatives to going with Option 2's external library?

**Comment by mmmavis** [comment]
I'm fine with using external library. Thoughts? @xmatthewx @cadecairos @acabunoc

**Comment by xmatthewx** [comment]
If that library is widely used and is okay performance wise, fine by me. I wonder if it would ignore rendering on mobile since it isn't required in a single column.

**Comment by kristinashu** [comment]
Since this is a bigger deal than we originally thought, lets hold off on it and reassess after we've implemented the detail view. Since copy lengths will very less, it might not be as big of a deal. 

But if we don't do this, then we should at least bottom align the bottom buttons and links.

**Comment by mmmavis** [comment]
Talked to other devs on ways of enabling masonry layout and the conclusion is it's not something we can do without using JS to arrange the layout. We could use 3rd party library for this jQuery-based prototype but once Pulse has been reactified mixing jQuery and React isn't a good idea.

I'll bottom align buttons instead.
