### ISSUE TITLE
Design profile tabs for favs

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#880]
We're going to add a User's Favs to their profile. 

The group decided that MVP version of this should include tabs so that Favs can be loaded separately to optimize how we engineer and serve this visitors. 

For now, tabs will just include Projects and Favs. Possibly extended later. 

 - [x] Review @kristinashu's  [desktop comp](https://redpen.io/ns0835f2e5d9956858) design-wise. Update as needed. 
 - [x] Design mvp tabs for mobile
 - [x] Review with engineers

Note: Projects will include both Published and Created as currently implemented. Down the line, I'd like to mix this as a single list in the Projects tab, perhaps adding a simple icon to indicate something is publish (@gvn suggested maybe something like twitter's retweet icon). We won't tackle this right now engineering wise, staying focused on Favs. 

cc @gvn @mmmavis for awareness

**Comment by kristinashu** [comment]
@xmatthewx do you mean that for now we will have three tabs (called Published, Created, and Favs)? These three should fit ok on mobile so we can postpone design of it until we need it.

**Comment by xmatthewx** [comment]
Huddle up with Mavis and see if she can proceed without a comp. 

For now, we'll just have 2 tabs: Projects, Favs. Projects will include Published and Created as currently implemented (for now so we can focus just on shipping favs).

**Comment by kristinashu** [comment]
@xmatthewx @gvn if this sounds good to you then I will open a front-end dev ticket

Here's an updated comp https://redpen.io/ns0835f2e5d9956858

**Tabs styling:** 
- same font, size and weight as the main nav except blue (same blue and buttons)
- selected and hover state has blue underline
- reduce subtitle under Projects tab ("Published Projects" and "Created Projects") to Zilla Slab Medium 16px in black

**URLs**
- if looking at my own profile /profile/me/projects and /profile/me/favs
- if looking at someone else /profile/[userID]/projects and /profile/[userID]/favs

![my complete profile copy 2x](https://user-images.githubusercontent.com/1068783/33733052-44eb320a-db3d-11e7-9593-5e358977f038.png)

**Comment by kristinashu** [comment]
Actually, looks like pomax has commented on URLs https://github.com/mozilla/network-pulse/issues/860#issuecomment-349741301

**Comment by kristinashu** [comment]
Opened an implementation ticket https://github.com/mozilla/network-pulse/issues/887

**Comment by xmatthewx** [comment]
@kristinashu - Let's think about empty states. We can do this as a follow up or include with initial build. 

 - If a user has neither Projects nor Favs, we should probably omit tab navigation. 
 - If a user has Projects, but no Favs, do we omit the favs tab? Or gray it out? Or have an empty Favs placeholder?
 - If a user has Favs, but no Projects, do we default to Favs view? Do we omit the projects tab or gray it out.  An empty projects placeholder feels sad since many users may never submit or create a thing.

**Comment by kristinashu** [comment]
Good point @xmatthewx! 

### For users looking at someone else's profile, we should hide the tab. Like we do now for projects.

e.g. profile with no saved Favs
<img width="586" alt="image" src="https://user-images.githubusercontent.com/1068783/33778811-26a24a46-dbff-11e7-8f73-2b1a75fdba65.png">

### For users looking at their own profile, we should add a CTA. For Favs, we can show the message we have now and for Projects we should add a message.
I can mock these up.

**Comment by kristinashu** [comment]
Still working on illustrations but empty states on a users own profile could look something like this:


![empty projects](https://user-images.githubusercontent.com/1068783/33789287-667c2f10-dc2c-11e7-8afd-25932229e76c.png)

![empty favs](https://user-images.githubusercontent.com/1068783/33789286-666a68c0-dc2c-11e7-824a-260f4254e56b.png)

**Comment by xmatthewx** [comment]
Yes, this is done or filed elsewhere. Thanks.
