### ISSUE TITLE
Design default profile avatar

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#881]
Avatars help bring Pulse to life by revealing the people behind the projects. A default avatar will do this across the platform, filling the gap when users haven't added a photo. 

MVP: A simple icon/illustrator. Should work large on profile page and tiny for future use on project cards.

**Comment by gurjarshakti** [comment]
Can you tell me the size of avatar and type of file you need. I can help you with avatar design.

**Comment by shikhar-scs** [comment]
@xmatthewx
I would like to take up this issue.
I guess we need to just add an `else` case to this. 
https://github.com/mozilla/network-pulse/blob/f0dd723664841ae3b29cd85928f8d337556ce173/components/bio/bio.jsx#L14-L24

As far as the avatar is concerned, there are multitudes of them. We can also pick the one used at `mozilla/fxa-content-server` . Or the default `firefox` profile icon. whatsay ?

**Comment by shikhar-scs** [comment]
Well, if that's the case, once we have the avatar ready, I would love to fix it in place. I hope that happens soon :smile:

**Comment by xmatthewx** [comment]
@kristinashu - do you want to take a stab at this? Or, if you're swamped, I can pull in another designer.

**Comment by kristinashu** [comment]
Let's use what Tais made for the foundation site! https://github.com/mozilla/foundation.mozilla.org/issues/1114#issuecomment-369059732

**Comment by taisdesouzalessa** [comment]
Here is the asset, ready to be used:
![profile-placeholder](https://user-images.githubusercontent.com/22157921/36802673-6ea7b366-1c6a-11e8-9e4d-e00a840c9f66.jpg)

Closing the issue, feel free to reopen it if needed

**Comment by xmatthewx** [comment]
I opened a ticket to implement this: https://github.com/mozilla/network-pulse/issues/928
