### ISSUE TITLE
Visualize people, projects, topics

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#883]
Explore an visualization that leverages real data on people, projects, and topics. 

Goals and scope and such discussed in [a doc](https://docs.google.com/document/d/1aDj2uRMBm-FFTji2nc9qMcAY4iv9VKWd7nKXTp8yakE/edit#).

**Comment by sabrinang** [comment]
@gvn Whenever you need any design help on this issue let me know!

**Comment by xmatthewx** [comment]
@gvn - @sabrinang collected some example visualizations for potential directions: https://github.com/mozilla/foundation.mozilla.org/issues/926

**Comment by codexdelta** [comment]
I have requested to access the doc. Please let me know if I can contribute in this issue.

**Comment by xmatthewx** [comment]
Thanks @codexdelta. Feel free to work on this if it seem interesting to you ... and ... keep it mind that it is more of an experiment and we won't necessarily be able to support or maintain a visualization tool.
