### ISSUE TITLE
Expose user's favorites via endpoint

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#886]
On the front end, we'll be showing entries marked as favorites on each user's profile. We should expose these as an endpoint, most likely at `/api/pulse/profiles/#{id}/favs` (though open to other approaches)

**Comment by Pomax** [comment]
Given the code already in place, the suggestion is to:
- refactor the current `/entries/bookmarks` such that the part that actually fetches data is a new def `getUserBookmarks(user)`, with the entries/bookmarked route looking up the user from session, then returning whatever `getUserBookmarks` returns
- create a new route `/profiles/:id/bookmarks` which gets the user from the profile id, and then calls `getUserBookmarks(user)` to return the same data.

**Comment by alanmoo** [comment]
See also https://github.com/mozilla/network-pulse-api/issues/304

**Comment by alanmoo** [comment]
Actually, I'm going to close this in favor of that one, as it encompasses this too. It's also in the right repo.
