### ISSUE TITLE
Add images to select items

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#89]

**Comment by kristinashu** [comment]
I've added images to the assets folder https://drive.google.com/open?id=0B2irLVDJivhLWHVXVXh4QTNTeTA

There are images for all the Featured posts and a few random other ones.

@mmmavis let me know if I can help add these in any way?

**Comment by xmatthewx** [comment]
Thanks!! This is getting awesome. I loaded images into github. We just need to paste URLs into spreadsheet. 

agate : https://cloud.githubusercontent.com/assets/53411/17423469/d7176554-5a88-11e6-93d5-11d14cf6346d.jpg

cardsagainst : https://cloud.githubusercontent.com/assets/53411/17423467/d7172828-5a88-11e6-893e-168a655ff5ad.jpg

codemoji : https://cloud.githubusercontent.com/assets/53411/17423470/d7180072-5a88-11e6-93c0-1c3ee672304a.jpg

eraseallkittens : https://cloud.githubusercontent.com/assets/53411/17423468/d717305c-5a88-11e6-8947-0ae5f0d54dce.jpg

flexboxfroggy : https://cloud.githubusercontent.com/assets/53411/17423471/d7188e20-5a88-11e6-842a-898f930a0b14.png

southafricakickstart : https://cloud.githubusercontent.com/assets/53411/17423472/d718a7ca-5a88-11e6-815c-da45afdca6ef.jpg

teachingkit : https://cloud.githubusercontent.com/assets/53411/17423473/d721fe42-5a88-11e6-9952-7656a1cf57c6.jpg

**Comment by mmmavis** [comment]
Done!
