### ISSUE TITLE
Determine approach for recognizing contributors to Pulse on profiles

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#890]
The output of this ticket is simply an approach, likely an epic that gets filed. Not the actual work.

We want to promote contributors to Pulse with recognition on the project itself. How can we do that, from a technical approach? We can have some sort of label on their profile, but how do we build a way to add that automatically? Can we use the github api to check if the github profile in their URL has contributed to pulse or network-pulse-api? Is there an easier approach for an MVP of this functionality? @mozilla/mofo-eng

**Comment by xmatthewx** [comment]
Cool. We could design an icon or something. I'd suggest we manually flag people via the admin until the work do that is greater than the work to automate it. Less fun, but more practical.

**Comment by alanmoo** [comment]
![](https://media1.giphy.com/media/26FKT1K97Wuiddros/200w.gif)

Ok I guess that makes sense.
