### ISSUE TITLE
De-couple environmental variables from client-side bundle

### ISSUE THREAD

**Issue by gvn** [mozilla/network-pulse#895]
Bundling env during build via webpack is preventing us from using Heroku pipelines because env becomes permanently embedded/static. We had the same issue on the Foundation site and I solved by pulling env via XHR as part of the front end bootstrapping process.

I'm happy to take this on...

CC: @alanmoo @mmmavis @cadecairos

**Comment by alanmoo** [comment]
What's your plan for emitting the env vars?

**Comment by gvn** [comment]
Probably need to customize the server code a bit to add a route to expose whitelisted env as JSON like we did on the Foundation site.

**Comment by alanmoo** [comment]
Can’t we leverage the fact that we’re using a node server to grab the env var and inject it into the script that the client gets on the first transfer? Something like

```
<script> let apiServer=`${process.env.apiServer}`</script>
```
on https://github.com/mozilla/network-pulse/blob/master/server.js#L100 ?

**Comment by cadecairos** [comment]
It would be better if we can avoid adding inline scripts.

**Comment by gvn** [comment]
We could inline pure JSON instead of script and just scrape and `JSON.parse` it.

**Comment by alanmoo** [comment]
If that works for @cadecairos I think it's worth a shot. Seems like it might be easier than creating another endpoint, too?

**Comment by cadecairos** [comment]
I think that should work.

If we have a CSP that might block a script tag that's inline, we could try this approach: https://mathiasbynens.be/notes/json-dom-csp#hidden-element
