### ISSUE TITLE
Offer users Newsletter sign-up

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#897]
We should offer Pulse users a way to sign up for MoFo's primary newsletter ... since we'll drive a lot of people there to create profiles, it's a natural place to indicate that subscription. 

Step 1 is to consider technical constraints
 1. maybe MVP is a checkbox on edit profile view (rather than trying to flow with g-auth) (can users unsubscribe with checkbox or do we include link to manage?)
 1. we'll need to figure out integration with salesforce

Step 2 is design

**Comment by codexdelta** [comment]
we don't have support for newsletter subscription in API? 

If we store the subscription information in user schema, we would be able to dispatch newsletter based on subscription status and we can provide unsubscribe link support from API side in all the newsletter dispatched. 

Why Salesforce?

**Comment by alanmoo** [comment]
We're already currently using Salesforce to manage our newsletter subscribers. It's really just a POST request to a Mozilla endpoint, but we need to make sure we're getting appropriate permission from the users/the UI is correct. I'd lean towards a simple "sign up" button on the profile page that pulls in the user's email, but doesn't concern itself with the existing status of the user's subscription.

**Comment by xmatthewx** [comment]
thanks @codexdelta - we have to do some design around this before it's ready for implementation.
