### ISSUE TITLE
Add extended bio to profiles

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#898]
Many core Pulse users have been interviewed via our story engine process. We'd like to connect these to profiles in pulse and foundation site. 

To start, we need to make a few decisions:
 - where should interviews live? on pulse? or as a page on network site?
 - are interviews a single block of content with basic metadata like date and name? or, is a question/answer added as an element?
 - do they require markdown or raw html? do we need more than paragraph breaks? do we need a wysiwyg editor (i hope not)? (note: all can be entered by staff moderators. doesn't require frontend or user access. staff can write and edit html.)
 - what do we do with audio interviews? embed as soundcloud player?

We have a basic design already for an interview/story tab on pulse profiles. But we should dig into these other requirements first. 

cc: @alanmoo for tech considerations

**Comment by jessevondoom** [comment]
So here are my thoughts:

- The interviews should live in Pulse, as markdown, available by API and showing on the a person's profile — this will allow us to pull into the foundation site later should we want to, but linking to the Pulse profile is perfect for now
- A single block is fine, but there are a few bits of metadata we'll need:
   - date
   - title
   - summary (short version for previews, etc)
   - description (bit different than the summary — we can explicitly state it's an interview using the storyengine process, time/date/context, etc.)
   - image (url for a preview image — additional images can be inlined)
   - license name (default to CC BY)
   - license url (default to CC BY declaration but allow us to link to specific license terms)
- Agree that we don't need any kind of WYSIWYG. Markdown is easy and these can be entered by editors and staff moderators
- Not a fan of doing audio as SoundCloud links — fine for a start but I'd prefer hosting MP3s on S3 and doing our own inline players. We have open options. @alanmoo let's discuss. Happy to be talked into SoundCloud and I'm sure my own biases are on display here.

**Comment by alanmoo** [comment]
This makes sense @jessevondoom, but maybe one of you can clarify one thing: When you say "interviewed via our story engine process", do you mean these interviews aren't actually on StoryEngine and we want somewhere for them to live? Is there any overlap with ones that are on StoryEngine?

As for the audio, this is not my field of expertise, but I'd like to stick with web standards as much as possible. Ghostery seems to block the SoundCloud player, so I'd like to avoid that type of UX/resulting optics if we can.

**Comment by jessevondoom** [comment]
@alanmoo Yeah we're moving away from Storyengine as a destination, and pulling the interviews into Pulse as long-form bios. The idea is to own that stuff a bit and provide canonical URLs for people in our network — including the interview pieces. Ultimately Loup will start to own storyengine as a thing and put more non-Mozilla content on storyengine.io. 

And I've got some experience with audio/players so I'll work out some pros/cons...but yeah I think going raw and playing it with our own solution is the way to go.

**Comment by xmatthewx** [comment]
API work has started. Links to this discussion. Closing this as more or less resolved.
