### ISSUE TITLE
Bug with Help tags & routes

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#899]
Some Help routes work, some do not. 

[Take action](https://www.mozillapulse.org/help/Take%20Action) works but is not encoded `https://www.mozillapulse.org/help/Take Action`. Others don't work at all. 

STR
 - view [entry 563](https://www.mozillapulse.org/entry/563) 
 - tap the help tag to localize
 - points to `https://www.mozillapulse.org/help/Localize %26 translate` and shows zero entries

**Comment by shikhar-scs** [comment]
@xmatthewx If you could be a bit more clear on what you mean, I might be help. Can I take this issue ?

**Comment by xmatthewx** [comment]
Thanks @shikhar-scs. @mmmavis probably knows the source of this bug ... and whether or not it makes sense as an issue for you to tackle.

**Comment by shikhar-scs** [comment]
Ok I'll wait for her response on this.

**Comment by mmmavis** [comment]
Hey @shikhar-scs thanks for offering help.

I think this is something to do with the param we are passing to the API endpoint got double encoded...

In `main.jsx`, let's decode the query param before passing it as a part of the prop to `<SingleFilterCriteriaPage>`
```jsx
const Help = (router) => {
  let searchParam = { key: `help_type`, value: decodeURIComponent(router.match.params.helpType) };
  return <SingleFilterCriteriaPage searchParam={searchParam} headerLabel="Help" />;
};

const Tag = (router) => {
  let searchParam = { key: `tag`, value: decodeURIComponent(router.match.params.tag) };
  return <SingleFilterCriteriaPage searchParam={searchParam} headerLabel="Tag" />;
};
```

And in `single-filter-criteria-page.jsx` let's remove `decodeURIComponent()` from line 21 since `searchParam.value` should already be decoded.

Let me know if you are interested in filing a PR for this! 😄

**Comment by shikhar-scs** [comment]
@mmmavis 
> Let me know if you are interested in filing a PR for this! :smile:

Yep, I'll take help from your comment and file a PR soon.

**Comment by mmmavis** [comment]
@shikhar-scs 's PR has been merged (thanks!) I'll close this ticket once it's been pushed to production.

**Comment by shikhar-scs** [comment]
Welcome @mmmavis , also, Thanx for your help :smile:

**Comment by mmmavis** [comment]
Yay fix is live! 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by shikhar-scs** [comment]
Thanx a lot :smile:

**Comment by xmatthewx** [comment]
@mmmavis @alanmoo - this fix doesn't seem to be live on production or staging. 

Production: `https://www.mozillapulse.org/help/Plan%20%26%20organize` 
Staging: `https://network-pulse-staging.herokuapp.com/help/Localize%20%26%20translate`

Prod entry: https://www.mozillapulse.org/entry/566
Staging entry: https://network-pulse-staging.herokuapp.com/entry/378

**Comment by xmatthewx** [comment]
To clarify, URLs should look like this: `.../help/plan-&-organize`. Sorry if this wasn't clear before: 

 - [ ] replace space with hyphen
 - [ ] lowercase

/help/
/help/
/help/attend
/help/create-content
/help/code
/help/design
/help/fundraise
/help/join-community
/help/localize-&-translate
/help/mentor
/help/plan-&-organize
/help/promote
/help/take-action
/help/test-&-feedback
/help/write-documentation

**Comment by xmatthewx** [comment]
closing. I will file this as a new issues. thanks all, sorry for the noise.
