### ISSUE TITLE
De-couple environmental variables from client-side bundle

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#900]
We should be able to use Heroku pipelines to properly promote our projects, so that environmental variables aren't bundled into the code. At first glance it appears the variable in question is the API server. Let's see if we can figure out how to access that dynamically.

**Comment by gvn** [comment]
I believe this is a dupe of https://github.com/mozilla/network-pulse/issues/895

**Comment by alanmoo** [comment]
Ah, I searched but didn't find it. I'm gonna change the title of the other one so it more clearly states the problem we're trying to solve
