### ISSUE TITLE
Remove index.html file from repo

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#904]
Pulse serves pages server side and the HTML code is all in the `server.js` file. Let's remove `index.html` from codebase since it's not being used anywhere.

**Comment by mmmavis** [comment]
**Don't tackle this yet. There might be a bug we need to fix first. I'll update this ticket once the bug has been fixed.**

**Comment by mmmavis** [comment]
This is being handled in PR https://github.com/mozilla/network-pulse/pull/901. We can close this ticket after the PR gets merged and pushed.

**Comment by gvn** [comment]
Done!
