### ISSUE TITLE
Add Name to page Title on profile views 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#909]
When a user views an entry, the <title> tag includes the project title. When they view a profile, however, the <title> is just Profile. Let's add the person's name to improve SEO and make a visitor's browser history more useful.

 - Current: `<title>Profile - Mozilla Network Pulse</title>`
 - Expected: `<title>Geraldo Barros - Mozilla Network Pulse</title>`
 - See: https://www.mozillapulse.org/profile/9

cc @alanmoo since this might be a quick and useful patch to assign to staff or contributor

**Comment by himanish-star** [comment]
@xmatthewx , I would like to fix this issue. May I ?

**Comment by alanmoo** [comment]
Of course, go ahead and file it! Tag me and I can find someone to review it.

**Comment by mmmavis** [comment]
PR merged and pushed to staging. I will close this ticket once the fix is on production. Thanks @himanish-star  !

**Comment by mmmavis** [comment]
Yay. Fix has been pushed to production. Thanks @himanish-star 🎉
