### ISSUE TITLE
Clean up Help URLs

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#910]
The /help/ URLs are odd, and don't match how we handle /issue/ URLs. Let's iterate. 

 - Current: `https://www.mozillapulse.org/help/Plan%20%26%20organize` 
 - Expected: `https://www.mozillapulse.org/help/test-&-feedback`

Here's a staging entry with all help categories: https://network-pulse-staging.herokuapp.com/entry/378 

 - [ ] replace space with hyphen
 - [ ] lowercase
 - [ ] `&` unencoded
   - For issues, we use `and` instead of `&`. I'm fine with either, and think `&` is best, but I don't know if it's a bad practice to use that for some reason. 

All URLs:
/help/attend
/help/create-content
/help/code
/help/design
/help/fundraise
/help/join-community
/help/localize-&-translate
/help/mentor
/help/plan-&-organize
/help/promote
/help/take-action
/help/test-&-feedback
/help/write-documentation

cc @alanmoo to triage

**Comment by shikhar-scs** [comment]
@xmatthewx I would like to take up this issue. May I ?

**Comment by alanmoo** [comment]
Sure! Though `&` will need to be replaced by `and` because that character must be perecent encoded in URLs.

**Comment by shikhar-scs** [comment]
@alanmoo can you help me on where to make these exact changes?

**Comment by alanmoo** [comment]
These aren’t just string changes; I believe these help categories are stored in the database, so you’d probably need some logic around encoding URLs for the browser that act differently than XHR requests to the API. Though thinking about it again, that could result in some inconsistencies depending on the specific tags used (particularly ones with `&`). @gideonthomas do you have any thoughts?

**Comment by shikhar-scs** [comment]
@gideonthomas

**Comment by alanmoo** [comment]
He’ll see this Monday, Eastern Standard Time.

**Comment by shikhar-scs** [comment]
oops ok :+1:

**Comment by gideonthomas** [comment]
@alanmoo this is really a client-side routing issue! All we store in the database is the name of the help type. All the routing including transforming the help type name into a route is done client-side via react-router. 
Right now the front-end just `encodes/decodes` the name of the help type to figure out the route. You can probably change that to use some js slug library instead but would need to find out how to retrieve the non-slugified version once you hit the route so that you can retrieve data from the api.

**Comment by shikhar-scs** [comment]
>  All the routing including transforming the help type name into a route is done client-side via react-router.

Yes that's true. I managed to find the exact code from where the `help/helpTypes` were being retrieved. 
As far as changing `&` to `and` was concerned I did that in the following code and it was pretty well reflecting on the `entry/378` page mentioned in the first comment.

https://github.com/mozilla/network-pulse/blob/f0dd723664841ae3b29cd85928f8d337556ce173/components/project-card/meta/get-involved.jsx#L29-L35

making any changes to `helpTypes` variable here does the trick.

Here are some related screenshots. Look carefully at the console
The console contains the original `helpType` and then the `encodeURIComponent(helpType)` .

this was the original thing:

![demofor 2](https://user-images.githubusercontent.com/25258877/35257740-22c3b720-0021-11e8-94ac-320c9bda724a.png)

![demofor 3](https://user-images.githubusercontent.com/25258877/35257767-4a74cb7e-0021-11e8-9cca-adf2d7560d87.png)


After altering the code to this

```
renderHelpLabels() {
    if (!this.props.helpTypes) return null;

    return this.props.helpTypes.map(helpType => {
       helpType = helpType.split('&').join('and');
      return <Link to={`/help/${encodeURIComponent(helpType)}`} className="btn btn-xs btn-tag" key={helpType}>{helpType}</Link>;
    });
  }
```

![demofor 1](https://user-images.githubusercontent.com/25258877/35257792-6b3fe672-0021-11e8-822e-29cf2bd55873.png)

![demofor 4](https://user-images.githubusercontent.com/25258877/35257798-7155e7b4-0021-11e8-8296-8203913debf3.png)



I guess this solves our problem. Could any of the mentors please tell if there is anything else we need

**Comment by gideonthomas** [comment]
Simply changing the link won't work. You also have to change how the page that the link takes you to behaves since it relies on the last bit of the route to figure out what to show. For e.g. your last screenshot should show more than 1 result for the help type "Localize & translate" since the link for it was found on the "help category test" page.

We also need to deal with spaces and case in the help type (not sure if we care about other special characters).

**Comment by shikhar-scs** [comment]
> Simply changing the link won't work. You also have to change how the page that the link takes you to behaves since it relies on the last bit of the route to figure out what to show. 

then maybe if we really need these changes we'll have to make changes to the routes in the first place.
  

> We also need to deal with spaces and case in the help type (not sure if we care about other special characters).

Once we decide on what format we want to have (eg a `dash` for a `space`, `and` for `&`, etc.) , getting it done would be a small task only I guess. 

So @gideonthomas we need to decide upon what we want to change.

**Comment by gideonthomas** [comment]
Yep, absolutely @shikhar-scs. We would need to figure out to what extent we want to sanitize the url first. Then, we would just create `helpTypeToHelpTypeUrl` and `helpTypeUrlToHelpType` (obviously with better names) functions and use them to generate the routes and to determine what to show on the helptype page.

Unfortunately, these decisions are outside my purview but hopefully @alanmoo can guide you through this.

**Comment by shikhar-scs** [comment]
Yeah sure, lets wait for @alanmoo to help us.

**Comment by alanmoo** [comment]
> Once we decide on what format we want to have (eg a `dash` for a `space`, `and` for `&`, etc.) , getting it done would be a small task only I guess. 

Sounds good

**Comment by shikhar-scs** [comment]
So basically should I get started with these changes?

**Comment by alanmoo** [comment]
Yup!

**Comment by shikhar-scs** [comment]
@alanmoo  Read this again
> Simply changing the link won't work. You also have to change how the page that the link takes you to behaves since it relies on the last bit of the route

From where can I alter the actual routes ? So that even after locally changing routes, I still get results on the prescribed pages.
Also as I guess the actual routes might exist on a master database, do I just need to do the changes to the route contents locally?

**Comment by alanmoo** [comment]
The actual routes are based off of the results at https://api.mozillapulse.org/api/pulse/helptypes/. For example, https://api.mozillapulse.org/api/pulse/entries/?help_type=test%20%26%20feedback.

So when the client hits https://www.mozillapulse.org/help/Test-and-feedback, you need to make sure the XHR request that gets made is to https://api.mozillapulse.org/api/pulse/entries/?help_type=test%20%26%20feedback

**Comment by shikhar-scs** [comment]
Oh! Thanks Thanks

**Comment by shikhar-scs** [comment]
@alanmoo I've made all the required changes and filed a related PR #913. Please review it

**Comment by mmmavis** [comment]
This thread is long... sorry if this has been discussed already - do we care about redirecting current routes to the new ones? @xmatthewx @alanmoo

**Comment by mmmavis** [comment]
Another question - do we wanna do the same treatment for `/tags/` routes as well? @xmatthewx @alanmoo

**Comment by xmatthewx** [comment]
I checked analytics. There's no need to redirect `/help/` routes.

We probably should do something similar for tags. Do you mind opening a new ticket? I feel like sanitation of tags on the way in should cover this.

**Comment by shikhar-scs** [comment]
> do we care about redirecting current routes to the new ones? 

I am unaware of what these routes are referring to

> We probably should do something similar for tags.

If yes, I would like to take that up :+1:
