### ISSUE TITLE
Add RSS link to head 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#914]
@patjouk setup RSS for us on the backend. w00t. Let's add a link to that in the head of our frontend. 
`<link rel="alternate" type="application/rss+xml" href="[URL]" />`

@patjouk - what's the URL?

**Comment by anweshknayak** [comment]
I can take this up?

**Comment by xmatthewx** [comment]
Thanks @anweshknayak! We have two URLs. So let's do two links unless there's a reason to only do one. In that case, let's use /latest.   

 - https://api.mozillapulse.org/rss/featured
 - https://api.mozillapulse.org/rss/latest

**Comment by alanmoo** [comment]
@anweshknayak Are you still going to take this on?

**Comment by anweshknayak** [comment]
hey @alanmoo sorry. I will send a PR asap.

**Comment by anweshknayak** [comment]
also @alanmoo can you assign some doable issues :smiley: I dont see much beginner issues open here

**Comment by alanmoo** [comment]
I try to as they come up, but it's sometimes a matter of the amount of time to explain an issue can take longer than someone familiar with the project just doing it. It's also challenging to identify work that we'd like to get done yet isn't on the active roadmap, but we're trying!

**Comment by anweshknayak** [comment]
thanks for the heads up. :smiley: I understand

**Comment by irrationalRock** [comment]
Is someone still working on it? I would like to make a PR on this issue if no one is working on this.

**Comment by xmatthewx** [comment]
Thanks @irrationalRock - we'd welcome your help on this.
