### ISSUE TITLE
Clean up tag urls

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#915]
Similar to #910, let's make tag urls less ugly. @shikhar-scs you wanted to take this?

**Comment by shikhar-scs** [comment]
Yeah sure 👍 . Can you please confirm that #910 is correct ?

**Comment by shikhar-scs** [comment]
@alanmoo if you could provide me the path where I can check my changes on the tag urls please :smile: .

**Comment by alanmoo** [comment]
I'm not quite sure what you're asking but this should help:

`https://network-pulse-staging.herokuapp.com/tags/women%20&%20girls` and `https://network-pulse-staging.herokuapp.com/tags/command%20line` should each have one result. So check locally using `https://pulse-api.mofostaging.net/` as your API, and change the domain in the above links to localhost.

**Comment by shikhar-scs** [comment]
Thank you @alanmoo for helping me out with that :+1:

**Comment by shikhar-scs** [comment]
@alanmoo I tried searching for the tag urls extensively. I did manage to find about from where they are rendered to the frontend. Its from this -

https://github.com/mozilla/network-pulse/blob/8c9bdef07735401f24a9e752a98191888ff9f8b8/components/project-card/meta/issues-and-tags.jsx#L12-L15

However, finding the backend request is coming out to be hard, backend request means the code which actually sends the request with tag type. In the help urls it was from `service.js`

For the tags I guess it is from one of these two places. Could you please help out a bit.

https://github.com/mozilla/network-pulse/blob/8c9bdef07735401f24a9e752a98191888ff9f8b8/components/bio/bio.jsx#L93-L100

OR

https://github.com/mozilla/network-pulse/blob/8c9bdef07735401f24a9e752a98191888ff9f8b8/components/project-card/project-card-detailed.jsx#L142-L153



Also, the workflow is that first the following gets called.

https://github.com/mozilla/network-pulse/blob/8c9bdef07735401f24a9e752a98191888ff9f8b8/components/project-card/project-card-detailed.jsx#L142-L153

Next, 

https://github.com/mozilla/network-pulse/blob/8c9bdef07735401f24a9e752a98191888ff9f8b8/components/project-card/meta/issues-and-tags.jsx#L12-L15
Only, if I get to know from where the request gets fired, it would complete the process

**Comment by mmmavis** [comment]
FYI, @shikhar-scs this PR might be related to the issue we are trying to solve here.

**Comment by shikhar-scs** [comment]
Thankyou @mmmavis for the help, I'll look that up :+1:
