### ISSUE TITLE
Change user's profile to use /profile/[id]

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#916]
Currently, when a user views their own profile via header nav, they see it at `...pulse.org/profile/me`. This is easy to remember! Yay. 

But, this makes it impossible to copy and share your profile with others. The only way to learn your ID and URL is to post a project, view the project, tap your name. In fact, the fellowship team needs me to get everyone's id from the database. 

@kristinashu - what do you think about adding a second link below edit profile? (option 2 below) I think UX-wise it is less good, but it probably would be easier to implement. 

To resolve this, I see a few options: 
 1. stop using `/me`:
    - a) redirect `/me` to `/[profile_id]`
    - OR... b) on header username link, use `/[profile_id]`
    - (either case: profile would need to display edit link to user)
 1. keep using `/me`:
    - on `/me`, add a link below `edit profile` that says `view public profile`

**Comment by xmatthewx** [comment]
cc @auremoser

**Comment by kristinashu** [comment]
Agree, option 1 is a much better user experience but option 2 would work as a quick band-aid.

**Comment by xmatthewx** [comment]
@alanmoo - assigning this to you, to review options and figure out how we'll tackle this and who will do the tackling.

**Comment by alanmoo** [comment]
The `userstatus` endpoint has been updated on `pulse-api` (it'll be live on staging momentarily), so now this should be doable.

**Comment by codexdelta** [comment]
hi @alanmoo, Are you working on this? if not I would be interested in.

**Comment by xmatthewx** [comment]
Thanks @codexdelta - have you had a chance to look at this yet?

**Comment by codexdelta** [comment]
Yeah I am looking into it. I have gone through the API documentation for /userstatus. 

Currently updating the app-user with additional incoming params like profileId and loggedIn. There will be no profile/me only profile/id. If loggedin then user can have the option to edit profile else it will always lead to public profile. 

Correct me if I am going wrong in the flow. I will revert back by EOD with detailed flow. 

Will be sending a PR by tomorrow for your review.

**Comment by xmatthewx** [comment]
Great. Thanks. Just to make sure everything is clear, based on conversation thread above, here are the requirements (option 1b above): 

 - [ ] when logged in, a user's name in header links to /profile/[profile_id]
    - [ ] tapping that displays user's profile
 - [ ] when logged in, a user's own profile includes two links
    - [ ] a link to edit (/profile/myprofile) 
    - [ ] a link to logout
 - [ ] a profile does not display edit and logout link to other users

See images below...

# User name link

 - The user name in header links to /profile/[profile_id]

![image](https://user-images.githubusercontent.com/53411/36225573-1d0fdda2-1199-11e8-9e2c-6f29d999a32e.png)

# Profile view

 - Profile conditionally displays 2 links when a user views their own profile. 
   - edit
   - logout
 - No links are displayed to other people. 

![image](https://user-images.githubusercontent.com/53411/36225670-6b6be00e-1199-11e8-8015-fc1c2cb4c5fb.png)

**Comment by codexdelta** [comment]
on submitting data on PUT /myprofile I am getting following error
`CSRF Failed: Referer checking failed - Referer is insecure while host is secure.`

even though X-CSRFToken is being passed in request's header with token string. 

My env vars 
`
PORT=3000
PULSE_API=https://pulse-api.mofostaging.net/api/pulse`

**Comment by alanmoo** [comment]
What url are you accessing the site from, `localhost:3000`?

**Comment by alanmoo** [comment]
Also, you shouldn't need to worry about actually submitting data on that page. As long as the links work, we should be good.
