### ISSUE TITLE
Build extend profiles (frontend edit form)

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#920]
to enable fellows and staff to edit their own extended profile info

**Comment by codexdelta** [comment]
Hi, I would be interested in taking up this task.

**Comment by alanmoo** [comment]
This need a bit more coordination for it to be ready to work on. In addition, it's on our priority roadmap, so one of the staff engineers will be taking it on. Please check out issues labeled "Help wanted" though!

@xmatthewx Do designs exist for this already?

**Comment by mmmavis** [comment]
@xmatthewx would this be the next Pulse ticket i should work on?

**Comment by xmatthewx** [comment]
I think yes. We should take a look at any comps @kristinashu did and draft a requirements list before you jump in. A few things that jump to mind: 

 - [ ] only show extended fields to people who have their extended profile flag checked
 - [ ] don't show these fields on frontend: profile type, program type, year. those should be maintained by staff via the admin, not by users.

**Comment by mmmavis** [comment]
@xmatthewx

FYI, afaik, data returned from API doesn't directly tell you if a profile has `extended profile` toggled on or not. When `extended profile` of a profile is enabled and any meta in the "extended profile" section is available, API will automatically emit that info (e.g., include a `user_bio_long` property in the JSON).

**Comment by xmatthewx** [comment]
Well, maybe that's okay. Unless I'm mistaken, I think long bio is the only field we would want to add to the form. We could just add that as a clearly optional field. And... that begs the question: do we need a flag to enable/disable extended profiles? If the "official" fields are only accessible via django, the flag might be unnecessary, even for use cases on foundation site. 

I'm curious what @mmmavis and @gideonthomas think. This is not a technical question, but more about how we expect users, admins, and sites to use pulse.

**Comment by mmmavis** [comment]
(attaching a screencap here in case it's useful as a reference)
<img width="477" alt="screen shot 2018-06-26 at 10 39 46 am" src="https://user-images.githubusercontent.com/2896608/41929554-4bc138f2-792d-11e8-8783-be33bc309c32.png">

If the `user long bio` is the only field in that section we are allowing users themselves to change, then I agree with @xmatthewx that we could probably just get rid of the `extended profile` flag and make sure `profile type`, `program type`, `program year`, and `affiliation` fields are editable only via the Django dashboard.

However, since I wasn't involved in this extended profile design work, I'm curious what the reasons were that we wanted to have a `extended profile` flag as well as other "controlled" fields initially. It's possible that there are important aspects that we are missing here. @gideonthomas thoughts?

**Comment by mmmavis** [comment]
As for comps, @xmatthewx I *think* this is the latest one @kristinashu did. I'm not sure how up to date it is though since this was made months ago. The "story" content there looks way more complicated than what I would imagine a `long bio` would be.

Redpen link: https://redpen.io/qua34b5932cdb6cf9f

**Comment by xmatthewx** [comment]
The design was a bit speculative. We do plan to input storyengine interviews, but looking at those again, they're just text, headings, links, and lists ([example](https://storyengine.io/stories/mozilla/dixie-ching/)). They have a fancy image at the top, but that can be covered by our profile image. 

I believe the original thinking was that there would be some data we would want only certain individuals to be able to add and edit. Like affiliation. So, in 2 years, a fellow could update their affiliation on their own, but regular users would be confused by that field, or be able to abuse it. 

I vote that we keep the flag, but don't worry about using it right now. We can give all users access to long bio, and keep everything else in django.

**Comment by xmatthewx** [comment]
Another question for us @mmmavis, is how we want to indicate markdown support above the field. I guess we can ship this without that, and enhance it with that later. Mostly, it'll be used by us and fellows.

**Comment by gideonthomas** [comment]
yeah I think let's go for the simpler solution and not worry about the flag. We can file a follow up issue about it and discuss if we need to add actual functionality to it or repurpose it to be useful in some other way

**Comment by mmmavis** [comment]
> I vote that we keep the flag, but don't worry about using it right now. We can give all users access to long bio, and keep everything else in django.

@xmatthewx does this mean by default the "extended profile" tag is on for everyone?

**Comment by xmatthewx** [comment]
No, let's leave it off be default and ignore it. If we ever need it for semi-official fields, it'll be better to turn it on for a few select fellows, than toggle it for all users.

**Comment by mmmavis** [comment]
@xmatthewx just making sure - this field is available only when that user's profile has extended profile toggled on, right?

**Comment by xmatthewx** [comment]
No, let's not worry about the flag for now. The API isn't sending that boolean to you. And I don't think it matters that much if all users have access to this.

**Comment by mmmavis** [comment]
@gideonthomas I just did a quick test 

1. When "extended profile" is off, JSON returned from `/profiles/<id>` endpoint will not `user_bio_long` info at all
2. When "extended profile" is on, JSON returned from `/profiles/<id>` endpoint will have `user_bio_long` as a property even if this meta has empty value. e.g., `{..., user_bio_long: "", ...}`

@gideonthomas are my findings above correct? If so, I can determine the status of `extended profile` flag by checking whether or not `user_bio_long` is a property of the JSON returned from API.

I hope this proposed approach can work! We have roughly 1497 profiles on Pulse production now and only a small portion of them will have the "extended profile" flag toggled on. I do think having this field available to ALL users will introduce UX issues for the majority of the users.

/cc @xmatthewx

**Comment by gideonthomas** [comment]
based on https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/profiles/serializers.py#L117-L126 I think you're right @mmmavis

**Comment by mmmavis** [comment]
Fixed!
