### ISSUE TITLE
Identify program strings to be used for api and frontend

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#921]
We need a clean list of all names for fellow focus areas or types. These will be public, attached to profiles and visible to visitors.

The person will be marked as a Fellow. We then will display focus area or type. I assume those labels should exclude the word fellow, both to avoid redundancy and migrate away from the notion of these as distinct fellowship.  

Fellow
 - Science
 - Open Web
 - Senior
 - Media
 - Open News
 - Tech Policy
 - any others?

**Comment by xmatthewx** [comment]
Done. Closing.
