### ISSUE TITLE
Hide "affiliation" field from front-end

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#922]
We need to flesh out these types still, so let's not show them on the front end yet

**Comment by mmmavis** [comment]
Pulse front end currently doesn't show affiliation meta nor allow users to add/edit that meta.

**Comment by alanmoo** [comment]
Maybe I misunderstood the initial requirement during the call- what about the fellows pages, do they show it?

**Comment by alanmoo** [comment]
@xmatthewx ^

**Comment by xmatthewx** [comment]
Yes, this is for the foundation directory in should be in the other repo. @taisdesouzalessa says we don't have that content yet.

**Comment by alanmoo** [comment]
Moved https://github.com/mozilla/foundation.mozilla.org/issues/1062

**Comment by taisdesouzalessa** [comment]
Just to give the context for this request, it came from this conversation thread with Amy: https://docs.google.com/a/mozillafoundation.org/document/d/1iiQ5lTFpAbEvRMYcNx9DqvaTmVjCE-AHwYh4PMtvveg/edit?disco=AAAABeKUvbs - in my understanding we shouldn't add that to MVP but once we have consistent information we should add.
