### ISSUE TITLE
Display extended profile on Pulse

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#923]
If a user's "extended profile" is enabled, visiting `/profile/{id}` should show all the details added as part of that extended profile

**Comment by xmatthewx** [comment]
Comp by @kristinashu  https://redpen.io/qua34b5932cdb6cf9f

**Comment by xmatthewx** [comment]
depends on #916

**Comment by mmmavis** [comment]
@xmatthewx do you think we can close this ticket as well? This to me looks like a dupe of https://github.com/mozilla/network-pulse/issues/929 ?
