### ISSUE TITLE
Duplicate GET requests for /api/pulse/entries/moderation-states

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-pulse#927]
I have ~50 items in my moderation queue locally, and when I load up `/moderation`, the client side makes a similar number of requests to `/api/pulse/entries/moderation-states/?format=json`

@mmmavis suggests this could be getting triggered by a state change in React.

sample screenshot of XHR activity:

![capture](https://user-images.githubusercontent.com/438003/36694598-d8200384-1b0c-11e8-9937-4a0d421e4fae.PNG)

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
