### ISSUE TITLE
Build extended profiles (frontend display)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#929]
We have added Extended profiles to the API. Let's add the new info to the frontend display on Pulse. 

Requirements:
 - [ ]  Add requirements checklist before development begins

** This is not ready for implementation **

**Comment by xmatthewx** [comment]
Comps are [redpen](https://redpen.io/qua34b5932cdb6cf9f). 

Note: 
 - A profile can have a type, program and year as seen in comp below. In the future, if a person has multiple programs and year, we should either display the most recent or reconsider the design
 - A profile can have an extended bio. This should go in a tab below labeled story in comp. 

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1068783/36510504-13119190-1718-11e8-920c-62bfb8d9fc08.png">

**Comment by mmmavis** [comment]
@xmatthewx is this the next ticket i should be working on?

**Comment by mmmavis** [comment]
Done! Front end can now display user's `long bio` if such meta is available in the JSON returned from API.

Closing!
