### ISSUE TITLE
Only one column filled in Safari

### ISSUE THREAD

**Issue by acabunoc** [mozilla/network-pulse#93]
More details: https://github.com/mozilla/network-pulse/pull/87/files#r73425962
![screen shot 2016-08-03 at 17 33 10](https://cloud.githubusercontent.com/assets/617994/17382838/f75f5de6-59a0-11e6-8134-bf7f95f7e867.png)

Safari Version 9.1.2 (9537.86.7.7) on OSX 10.9.5

**Comment by mmmavis** [comment]
darnnn safari!
