### ISSUE TITLE
Improve autocomplete list of creators

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#935]
Currently, if I try to name Mozilla as a creator on an entry, I can't use autocomplete, even that creator has more entries that most other users.  I have to use a comma. 

 - short names should come first. users can keep typing to get longer names. 
 - creators with profiles should come first. users will see the icon to prompt them to pick it. 

Let's this _after_ we rework our creator profile approach. https://github.com/mozilla/network-pulse-api/issues/319

## example 1

mozillla is below other longre mozilla options 

![image](https://user-images.githubusercontent.com/53411/37231607-c1b15f48-23b9-11e8-8756-a36ae364fdb9.png)

## example 2

user without profile comes before users with profile

![image](https://user-images.githubusercontent.com/53411/37231586-b6902716-23b9-11e8-9685-70a1ba17831f.png)

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
