### ISSUE TITLE
Hover state for links and buttons

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#94]
Hey @kristinashu ,

I'm not sure how buttons and links should look on hover state. Can you provide some design help? 🌈 

https://mozilla.github.io/network-pulse/

**Comment by kristinashu** [comment]
Thanks for asking @mmmavis! I've added a comp with all the hover states https://redpen.io/um12f3075ab742b445

- Menu items turn white (same as selected state)
- Category tags turn pink (same as selected state)
- Heart icon fills in pink (same as selected state)
- Link icon turns pink
- Blue text links turn to the darker tint of blue
- Buttons fill in blue (same color as the outline) and blue text becomes white. Ex smooth fade in like on advocacy.mozilla.org

**Comment by kristinashu** [comment]
Reopening for implementation!

**Comment by mmmavis** [comment]
@kristinashu 

- Link icon turns pink <<< could you export a pink version of the icon plz?
- Blue text links turn to the darker tint of blue <<< colour code? 💙

**Comment by kristinashu** [comment]
Here's the icon and the dark blue is #0490C0 (for future reference, this is the unified color palette https://redpen.io/aq798f74c9a3ad7266)

[icon link selected.svg.zip](https://github.com/mozilla/network-pulse/files/409430/icon.link.selected.svg.zip)

**Comment by xmatthewx** [comment]
And now this >>>> https://mzl.la/boostrap-demo
