### ISSUE TITLE
Application error when editing `mozsprint` tag

### ISSUE THREAD

**Issue by acabunoc** [mozilla/network-pulse#943]
When I try to edit the `mozsprint` tag I often get application error. Maybe because there are too many entries tagged?

https://api.mozillapulse.org/admin/tags/tag/400/change/

<img width="997" alt="screen shot 2018-04-10 at 9 57 33 am" src="https://user-images.githubusercontent.com/617994/38571538-9f987c3e-3ca5-11e8-806d-edd826b030ef.png">

**Comment by gideonthomas** [comment]
I think the request is timing out. Not sure what's taking long here though.
```
2018-04-10T17:23:06.201021+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/admin/tags/tag/400/change/" host=api.mozillapulse.org service=30001ms status=503 bytes=0 protocol=https
```

**Comment by alanmoo** [comment]
What are you trying to change it to?

**Comment by acabunoc** [comment]
@alanmoo - adding entries to the tag. It's easy to go this way than to go inside each entry and add this tag.

**Comment by gideonthomas** [comment]
oh @acabunoc, did you see this after you added the entries and tried to save the tag? Or when you were loading the tag page?

**Comment by acabunoc** [comment]
loading the tag page! If the page loads (very rarely), then I have no problem adding new tags

**Comment by xmatthewx** [comment]
Related to https://github.com/mozilla/network-pulse-api/issues/342

**Comment by gideonthomas** [comment]
ah thanks @xmatthewx! @acabunoc is it a very large list that you are trying to tag with #mozsprint? Otherwise, with a workaround of manually doing it on the entry, would we be able to close this and follow-up in the ticket linked above? If not, I can prioritize this.

**Comment by gideonthomas** [comment]
Thanks! I'll ping you when I have a fix up @acabunoc!
