### ISSUE TITLE
Potential security vulnerability in subdep

### ISSUE THREAD

**Issue by gvn** [mozilla/network-pulse#954]
See: https://github.com/mozilla/network-pulse/network/dependencies

<img width="569" alt="screen shot 2018-05-03 at 12 47 00 pm" src="https://user-images.githubusercontent.com/206379/39599261-2193987c-4ed0-11e8-8cf3-6a6fd707aab8.png">

**Comment by gvn** [comment]
CC: @xmatthewx @mmmavis

**Comment by mmmavis** [comment]
Thanks. I filed a ticket last week on DevOps repo: https://github.com/MozillaFoundation/mofo-devops-private/issues/132
