### ISSUE TITLE
Follow up on new Profile Favs

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#955]
I see three things worth fixing. I don't think these need to block shipping the feature, and can be follow up so we can get the feature live. @mmmavis  

 - [x] 1. someone else's profile - remove project headers on profile with no projects  
 - [x] 2. user's profile - remove headers and 2nd cta on projects tab for a user with no projects
 - [x] 3. user's profile - remove header on empty FAVs tab (i'm not sure we need this header for favs tab at all even on someone else's profile, since it just repeats the tab above. you can keep it if it's simpler though)

### 1. A profile with no projects still has headers. 

<img width="626" alt="image" src="https://user-images.githubusercontent.com/53411/39717139-5805c046-5200-11e8-8d39-3873b6573df9.png">

### 2. two CTAs

<img width="902" alt="image" src="https://user-images.githubusercontent.com/53411/39717231-99875e62-5200-11e8-83bb-e86d78be17f9.png">

### 3. favs header

<img width="813" alt="image" src="https://user-images.githubusercontent.com/53411/39717442-45231752-5201-11e8-8148-bf8f98be5d90.png">

**Comment by xmatthewx** [comment]
Thanks @mmmavis. How does this sound?... I will try and make a diagram to cover if/then scenarios. Ideally, I can find a few universal rules we can apply everywhere, so we don't have to worry about tracking lots of details.

**Comment by mmmavis** [comment]
Yay. This is done!
