### ISSUE TITLE
Setup URL for profile favs

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#958]
Our profiles now show a user's favs. w00t! It's a big opportunity for people to serve as curators. 

Can we route the URL to the favs tab, so that [/profile/85/favs](https://www.mozillapulse.org/profile/85) loads that tab? Not critical, but super useful for people who wanna be a curator. 

Curious what you think @mmmavis

**Comment by mmmavis** [comment]
Yea we can. Is our plan to also get rid of the favs tab? i.e., `https://www.mozillapulse.org/favs`

**Comment by xmatthewx** [comment]
Maybe? Good question. Let's discuss in a separate thread. We will need to consider non-authenticated users, and your nice import feature. Those feel different than this issue to share profile favs.

**Comment by xmatthewx** [comment]
> Yea we can. 

I started a message to share out profile favs with staff and fellows. Writing it, I realized I'd like to wait until we have routing for /profile/id/favs. Makes the feature much more useful.

**Comment by mmmavis** [comment]
Sure. If that's the case we probably need to change the behaviour of how tabs and headers are showing. I'm thinking we need to make the tab labels (`Projects`, `Favs`) visible at all times regardless if that profile has fav'ed projects associated with it or not. Is there anything we should tweak?

**Comment by xmatthewx** [comment]
Interesting. Are you thinking that the routes would otherwise fail and we'd need to either show a not found message or we'd need to redirect from /profile/id/favs to /profile/id? Or, are you worried about user experience?

**Comment by mmmavis** [comment]
In https://github.com/mozilla/network-pulse/issues/887#issuecomment-382505371 

> If person A is viewing person Z, I think we should just omit the tabs with no data.

This means when person A is viewing person Z's fav tab by going to `/profile/123456789/favs`... if person Z doesn't have any favs, person A will see a screen like

![screenshot-2018-5-15 mmm - mozilla network pulse](https://user-images.githubusercontent.com/2896608/40073477-cafb3a0a-582b-11e8-8cb6-48e483925e61.png)

Notice that
- "Fav" tab label is hidden
- there are no projects or message presented in the empty fav section
- a "Project" tab label is there which will confuse person A

As things are getting more complicated now and specs are buried in several ticket comments, if we are planning on enhancing the profile view, could we please have a flow chart or Sketch file that records every state of this view? It'll really help keep everyone be on the same page! 😃

**Comment by xmatthewx** [comment]
I've created some documentation to track our [rules for conditional display](https://docs.google.com/presentation/d/15Vsb-3WFCl9nJIie6MstR2MoTwbBG5um8rmIGqFLPHY/edit#slide=id.g3a0640936a_0_139
). It includes info on routing for favs tab. Let's discuss, clarify, and revise if needed. 

 - 1st priority: get routes for tabs set up. 
 - 2nd priority: consider auto switch to favs

Considerations: 
 - Many users can have many favs. Some users will have 1 project, a few will have many. 
 - Make it easy to promote favs, and reward users and visitors by displaying that activity. 
 - Our monthly active users reached to MozFest levels last month, holding steady. Global sprint nearly doubled it. I would like to capitalize on the momentum.
 - On Facebook, different users have different items on their profile's "more" menu. My sister, for example, has Books. A friend of mine doesn't have books on their more menu. If I manually append books to my friends URL, it just redirects to their top-level profile URL.

**Comment by mmmavis** [comment]
This is up and running! https://www.mozillapulse.org/profile/85/favs 🎉
