### ISSUE TITLE
Reverse order favs

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#959]
Profiles now display a user's favs. Yay! Currently, they are sorted either chronologically or by fav ID. We should reverse this so that the latest content shows up top, old stuff down below. 

The API should probably serve these up in reverse. If it doesn't, let's request a patch over there. This is not a critical bug, but definitely something we should fix.

@mmmavis @gideonthomas to discuss.

**Comment by mmmavis** [comment]
@gideonthomas should we tweak this on the API instead of (re)sorting things on front end?

**Comment by gideonthomas** [comment]
Ideally both. The heavy lifting will be done by the API, but the front-end would just need to change the url it uses to get the favs (probably just add a querystring var)

**Comment by gideonthomas** [comment]
Filed https://github.com/mozilla/network-pulse-api/issues/370 for the backend part of this work.

**Comment by gideonthomas** [comment]
To get the favs in reverse order of creation, hit up this route:
`/api/pulse/v2/profiles/<id>/entries/?favorited&favorited_ordering=-created`
per [this documentation](https://github.com/mozilla/network-pulse-api#get-apipulseprofilesidnumberentries-with-filter-arguments-and-optional-formatjson)

**Comment by mmmavis** [comment]
> the latest content shows up top, old stuff down below.

@xmatthewx did you mean latest created project first OR latest favourited project by that profile first?

**Comment by mmmavis** [comment]
> the latest content shows up top, old stuff down below.

@xmatthewx did you mean latest created project first OR latest favourited project by that profile first? For reference, on the standalone /favs tab we show latest favourited project first.

**Comment by mmmavis** [comment]
@xmatthewx is this still an issue? The /favs page is kinda buried now since we remove it from the nav. Is the plan to eventually kill the Favs page?

**Comment by xmatthewx** [comment]
It seems like new profile/fav ordering is correct, with recent stuff first. So, we can close this. 

As for the top level /favs page ... I'm not sure. Without it, non-logged users can't use favs, which was always a nice thing to offer. And, users to fav things logout can't add them to their profile. But, neither of those things are critical. I don't think we need to worry about this now. Something we could add in the future: if a non-authenticated user taps a heart, prompt them to create an account. But again, this isn't crazy critical.
