### ISSUE TITLE
Fix the Close button on Detail view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#96]
A shared link opens a single item as detail view. Currently, the close button is miles away and hard to see. (see below)

Design: We have a comp for detail view on mobile. On desktop, what's ideal? @kristinashu 

MVP Dev @mmmavis  
 - In the interim, can we do something like: `margin-right: calc(50% - 300px);` for screens wider than 650px or something like that? 
 - Also... can we increase opacity of back underneath? The add project button shows thru and sometimes looks misaligned under the X to close the modal (see below).

-------

<img width="969" alt="screenshot 2016-08-03 18 09 07" src="https://cloud.githubusercontent.com/assets/53411/17383745/97986718-59a5-11e6-8925-e7c5a5f5b2a8.png">

**Comment by kristinashu** [comment]
Do we need to fix this? The new design should be coming soon and this will no longer be relevant. It would be great if Mavis could focus on the new design.

**Comment by mmmavis** [comment]
yea we probably shouldn't worry about lightbox related improvements since we aren't using lightbox in the new design.

**Comment by xmatthewx** [comment]
Definitely fine to focus on new design. @kristinashu - how will a single card look on desktop? Centered horizontally? Vertically? Any wider than in Recent view?

**Comment by kristinashu** [comment]
Centered and the same size as a regular card.
