### ISSUE TITLE
Pulse Profile Routing MVP

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#962]
Pulse Profiles now have two tabs, one for Projects, one for Favs. To maximize the impact of Favs, enabling easy sharing, let's add routes. 

Note: a tab only displays if there is relevant content. 

Scope: add basic routing to enable direct links to .../profile/[id]/[tab]

Requirements
 - .../profile/[id]
    - [x] loads default tab (as implemented)
 - .../profile/[id]/favs
   - [x] if content: load favs tab
   - [x] if no content: redirects to up to /[id]
 - .../profile/[id]/projects
   - [x] if content: load projects tab
   - [x] if no content: redirects to up to /[id]

Notes
 - [this deck](https://docs.google.com/presentation/d/15Vsb-3WFCl9nJIie6MstR2MoTwbBG5um8rmIGqFLPHY/) has annotated wireframes on routes and conditional display. Ignore details outside the scope of this ticket. 
 - redirect up is the ideal UX to resolve those rare instances of a link to nothing. this pattern is used on at least one major social network with optional profile content. preferred ux-wise over creating empty states.

**Comment by mmmavis** [comment]
I believe this is all done too. Closing!
