### ISSUE TITLE
Optimize markdown rendering and styles

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#968]
We're adding markdown support, for use in extended profile bios. 

Step 1: We need one fix on the API side. Multi-line text pasted into the admin form is squashed into a single line. So paragraphs and lists don't work. https://github.com/mozilla/network-pulse-api/issues/381

Step 2: test styles

 - [x] basic text
 - [x] italics
 - [ ] bold
 - [ ] links --> make them blue
 - [ ] lists (blocked)
 - [ ] paragraphs (blocked)  
 - [ ] ~~h1, h2, ...~~
 - [ ] ~~images~~

@mmmavis - what other markdown elements do we need to test?

**Comment by mmmavis** [comment]
@xmatthewx I think it depends on what kind of info we want users to put there. If this is a "long bio" field to users I feel like providing support only for the the following elements would be enough.

- basic text / paragraph
- italics
- bold
- hyperlinks

**Comment by xmatthewx** [comment]
That seems right. Let's add lists too. We can encourage use of bold for simple headers. We might also want to include images (remotely hosted), but we can leave that out for now.

**Comment by mmmavis** [comment]
@xmatthewx how would users know what markdown elements are supported? Are we thinking about rendering non-supported markdown element as is? e.g., `# big header` in markdown will show up as just as plain body text `# big header` on their profile?

**Comment by xmatthewx** [comment]
Markdown is live and thriving on staging!!!

@mmmavis - I tested a bunch of markdown. Nothing looks terribly broken except headers. I think if we clean up headers, we'll be golden. Let's also add a nice style for blockquotes, which can be very useful. 

 - headers - an easy styles fix would be to set h1,h3,h4,h5,h6 to all look like h2. I don't think people really need more than one level. if you think that's a mistake, pair up with Kristina or Tais to set a few styles.
 - blockquotes - let's ask Krisinta if there's a nice simple style we could add to these. left margin. italics. slightly larger text. these can be very useful to break up storyengine interviews.
 - images - let's make sure there's a max width on these. 
 - inline code could look a little nicer without red text, but that is totally not important

here's my profile test: https://network-pulse-staging.herokuapp.com/profile/6


<img width="903" alt="image" src="https://user-images.githubusercontent.com/53411/42048712-09acff86-7ad2-11e8-9aaf-b76582f50985.png">

**Comment by xmatthewx** [comment]
@kristinashu - can you help with a quick blockquote style for pulse profile about tab? i they'll be useful to break up long profile and story engine interviews. And we need one or two levels of headers. 

see demo here: https://network-pulse-staging.herokuapp.com/profile/6/about

**Comment by kristinashu** [comment]
I'd recommend using the .feature-quote component https://foundation.mozilla.org/style-guide/


<img width="1160" alt="image" src="https://user-images.githubusercontent.com/1068783/42061796-3505aa9e-7ae0-11e8-8830-929fc4e8a9d0.png">

**Comment by xmatthewx** [comment]
This has to be a little simpler since it's done with markdown. Just like in github when you do `> he said, she said` and it yields this:

> he said, she said

We can do italics, bigger type. We should test centering vs left alignment. We could maybe include the quotation mark if Mavis thinks it's feasible. We probably can't do the attribution because it would have to be a cascading markdown style. A bit too complicated. 

@mmmavis - does this give you enough to play with and try things out?
