### ISSUE TITLE
My profile shows "About" tab even if empty

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#969]
STR:

1. Log in, visit https://www.mozillapulse.org/profile/me
2. Even if you don't have extended profile info enabled, you'll see the "About" link and be at that route.
(For example, https://www.mozillapulse.org/profile/93 doesn't have it, unless I'm logged in)

Expected behavior:
If extended profile info isn't enabled, you shouldn't see the tab/be on that route.

cc @xmatthewx

**Comment by mmmavis** [comment]
Aw I thought we always wanna make all tabs visible when you are visiting your own profile. T/F? @xmatthewx

**Comment by mmmavis** [comment]
@xmatthewx is this the logic what we wanna have going forward or just a temporary solution since currently users can't add their long bio via front end?

**Comment by xmatthewx** [comment]
I think this is how we would want it moving forward. I don't see a strong need to show the tab and a CTA to get more long bios, so this would not be a temporary change.

**Comment by mmmavis** [comment]
kk cool, thanks for updating the slide deck too
