### ISSUE TITLE
Implement tabs/pages

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#97]
tabs/pages:

- featured
- recent
- favs
- issues

design: https://github.com/mozilla/network-pulse/issues/59

**Comment by mmmavis** [comment]
should the url change when users visit each tab/page? @xmatthewx @kristinashu

**Comment by kristinashu** [comment]
Yes please! 

The url should also change for each Issue tag, if that's not a big deal to do. Thanks!

**Comment by mmmavis** [comment]
@kristinashu how about tabs/pages? e.g., featured page and recent page. Do tabs/pages share the same URL?

**Comment by kristinashu** [comment]
Recent and Feature should have different urls.
