### ISSUE TITLE
Newlines not being rendered in Profile About tab

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#977]
On staging:

![screenshot_2018-07-03 update profile - mozilla network pulse](https://user-images.githubusercontent.com/2896608/42242379-835ea908-7ec2-11e8-91a0-5ce6295901c0.png)

![screenshot_2018-07-03 mmm - mozilla network pulse](https://user-images.githubusercontent.com/2896608/42242374-8130a528-7ec2-11e8-86b8-7f6504c60137.png)

**Comment by xmatthewx** [comment]
Interesting. It seems to work for paragraphs (2 newlines) and bullets (single newline), but not a simple single line break. 

It'd be good to fix this, but it's definitely not an emergency.

**Comment by mmmavis** [comment]
@xmatthewx PR is in review already 👍

**Comment by gideonthomas** [comment]
This can be closed?

**Comment by mmmavis** [comment]
Fixed!
