### ISSUE TITLE
Add server

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#98]
For the upcoming version we want to have
- different pages/tabs: features, latest, favs, and issues. Each page needs to have an unique URL.
- filtered list needs to be sharable. e.g., a direct link that goes to a list of "Web Literacy" projects
- detail view will be displayed on a regular page (vs on lightbox). This means each project should have an unique link that goes to the project's detail view.

To satisfy the above requirements, I think we should set up a simple server to serve up pages instead of relying on one index.html file + using History API as hacks to update browser URL as users navigate within the app... this will get pretty complicated implementation-wise.

I'm thinking to turn the setup into what I did for another prototypy project: [docs-analyer](https://github.com/mmmavis/docs-analyzer)

- [Express](https://expressjs.com/) server to handle routing
- `pug` as template engine (formerly known ad `jade`)
- jQuery and other `.js` dependencies should still work 
  - (except template bits will be moved to server side & we will fetch spreadsheet data on server side instead)
- `scss` instead of css (not MVP)
- App will live on Heroku instead of as Github Page

What do you think @xmatthewx @cadecairos @acabunoc ? It will probably take me 0.5 to 1 day to switch to the setup I mentioned above. I don't anticipate tons of code rewrite other than turning `index.html` into `pug` syntax and files - existing front end JS code should still work. **OR** instead of `pug` we use `React`... this takes longer but it's probably the ideal solution as eventually we'll want to Reactify this app anyways.

/cc @kristinashu

**Comment by cadecairos** [comment]
If we're using react and react-router, it wouldn't actually need a dedicated server until we move off of spreadsheets.

**Comment by mmmavis** [comment]
Closing this ticket. As discussed in today's stand this is not something we consider doing for this phrase.
