### ISSUE TITLE
Entry creators should not link to profile if the creator has a stub profile

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#980]
We create profiles for every single creator but some have empty profiles. We determine this with the `is_active` flag but that isn't passed in the data when returning entries from the API. 

Once https://github.com/mozilla/network-pulse-api/issues/389 is done, we should conditionally link out to a creator profile or not based on the `is_active` flag.

cc @xmatthewx and @mmmavis

**Comment by xmatthewx** [comment]
For context @mmmavis - when we had the creators model in the middle, we only linked if there was a profile. Now that everything is a profile, @gideonthomas will have the API the flag, and you can conditionally link if the profile has an account (or is_active).

**Comment by xmatthewx** [comment]
@mmmavis - looks like this is unblocked and ready for frontend

**Comment by mmmavis** [comment]
@xmatthewx What if user hits up a profile URL on front end that is tied to a `is_active = false` profile? Do we wanna make it 404? Or? 

On the API side - it seems like the `pulse/v2/profiles/<profile_id>/` endpoint doesn't return `is_active` property.  /cc @gideonthomas

**Comment by xmatthewx** [comment]
Yes, we should 404 that. It's an edge case, and not super likely. Let's tackle that as a follow up issue. I don't think it blocks us turning off links to in active profiles. These links are very prominent and make the platform look very empty and inactive. Does that sound okay?

**Comment by mmmavis** [comment]
done and live!

**Comment by xmatthewx** [comment]
excellent, thanks!
