### ISSUE TITLE
404 page image broken

### ISSUE THREAD

**Issue by patjouk** [mozilla/network-pulse#981]
<img width="500" alt="screen shot 2018-08-01 at 5 40 57 pm" src="https://user-images.githubusercontent.com/481052/43532387-3eb94126-95b2-11e8-8c92-37e90cb451fb.png">

Ran into this issue on prod and staging.

**Comment by xmatthewx** [comment]
@alanmoo – a missing image on a 404 page? kinda funny. 

it's totally 404 inception.

**Comment by AdityaSrivast** [comment]
@xmatthewx I want to work on this issue. I am a first time contributor. Can you tell me what needs to be done, please?

**Comment by alanmoo** [comment]
It seems like one of [these commits] likely broke the 404 page. Check them out and see if it works in any of them, and if so attempt to open a PR with the code for `icon-404.svg` as it was at that point in time.

**Comment by AdityaSrivast** [comment]
![image](https://user-images.githubusercontent.com/31389740/51604654-72b88800-1f33-11e9-9308-6d1b443c09d7.png)

@alanmoo Is this the page we're discussing here? The image appears to be fine.

**Comment by alanmoo** [comment]
That's...odd. It doesn't work in any of my browsers on a Mac. What browser/OS are you using? @xmatthewx Do you still see this? @Pomax what about Windows?

https://www.mozillapulse.org/4oh4

**Comment by AdityaSrivast** [comment]
@alanmoo I am using Ubuntu 18.04 LTS and the image appears to be fine on Chrome, Firefox and opera as well.
