### ISSUE TITLE
Set inactive profiles to return 404

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#985]
Profiles that are inactive should return 404. As mentioned in #980 

API needs to be updated to do this. 

cc @gideonthomas to file API issue.

**Comment by gideonthomas** [comment]
Filed: https://github.com/mozilla/network-pulse-api/issues/404

**Comment by ithompson4** [comment]
Is this still open or has this been closed by the completion of #980?

**Comment by gideonthomas** [comment]
I don't think this is really needed anymore. In fact, I think it might be useful to see published/created projects in one place for named creators as well.
