### ISSUE TITLE
React-router doesn't update head tag

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#988]
From [this ticket](https://github.com/mozilla/network-pulse/issues/409#issuecomment-346513670)

>I went to Fav page first and clicked on the Issues link on nav bar to go to the Issues page
>![](https://user-images.githubusercontent.com/2896608/33155543-30671cb0-cfa6-11e7-8dde-d3e9fda7fbb9.png)

>This happens only when you visit a page without page reload. Page title on GA will always be the title of the page you just navigated away from. It seems like this is becausereact-helmet (the library we use to update document head meta) doesn't update meta on the initial render of a component. head meta gets properly updated after we have already sent GA page view event to GA (<- this happens when react-router updates its state in response to URL changes) so that causes the mismatching page title problem on GA dashboard. This is probably fixable if I spend time digging through react-router and react-helmet's docs. Not sure how bad this bug is so I'll let @xmatthewx triage this ticket!

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
