### ISSUE TITLE
Search UI functionality 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#99]
When a user begins typing:
- [x] close icon appears
- [x] hint text is hidden
- [ ] nav (and tags) are hidden
- [ ] add project button is hidden
- [x] only applicable cards are visible
- [x] Tapping the close icon or pressing esc key ends the search screen and brings back the hint text, nav, and add project button.

**Comment by kristinashu** [comment]
Also, if no search results are found then it should show a "nothing found" message https://redpen.io/pe58cf57333a0e871f

**Comment by xmatthewx** [comment]
Ideally, we can add search string to the URL /?q=foobear. If we can't land it in MVP, let's file an issue to revisit later. We can do this if someone hits enter or removes focus from input field. This would allow a user to share a query related to their program, event, or interest.

**Comment by mmmavis** [comment]
Question: how do users escape from the search view? and where are we sending them to?

**Comment by kristinashu** [comment]
The close icon will bring them back to where they were.

**Comment by xmatthewx** [comment]
If it's tricky to track (not MVP), or tracking fails, fallback to Recent?
