### ISSUE TITLE
Design refresh for auth pages

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#992]
I implemented the front-end pages for logging in/out scrappily. It probably needs to be re-done with better designs.

### Login page

<img width="1440" alt="screen shot 2018-11-14 at 3 07 13 pm" src="https://user-images.githubusercontent.com/5816130/48509800-155fd680-e820-11e8-9b23-a10594653a5c.png">

### API Homepage (rarely used...only used if you go to the pulse API homepage directly)

<img width="1440" alt="screen shot 2018-11-14 at 3 16 13 pm" src="https://user-images.githubusercontent.com/5816130/48509866-3f18fd80-e820-11e8-94bc-daa1adcd7cd6.png">

### Email verification page

<img width="1440" alt="screen shot 2018-11-14 at 3 12 17 pm" src="https://user-images.githubusercontent.com/5816130/48509873-46400b80-e820-11e8-8f1a-39365f0890b7.png">

### Existing email address page (shown when you already logged in with Google and now want to login with Github using the same email address)

<img width="1440" alt="screen shot 2018-11-14 at 3 13 30 pm" src="https://user-images.githubusercontent.com/5816130/48509895-4e984680-e820-11e8-86a9-70288adbb4f6.png">

### Connecting social accounts to pulse (shown when you have an account on pulse using one social network and want to now login to the same account using another social network)

<img width="1440" alt="screen shot 2018-11-14 at 3 13 52 pm" src="https://user-images.githubusercontent.com/5816130/48509912-5bb53580-e820-11e8-9ef0-a351911dad17.png">

**Comment by xmatthewx** [comment]
Thanks @gideonthomas. Question: when do people see the "Link a Social Account" screen?

**Comment by gideonthomas** [comment]
Did your github email address match your google login email?

**Comment by xmatthewx** [comment]
I think I figure this out (moz email alias + private window; email confirmation leading to reg window auth'd with other moz email).

Can you delete profiles 1744 and 1780, and their associated users? I don't seem to have permission for this under your new model.

**Comment by gideonthomas** [comment]
Yeah, it will only show the "link" screen if the same email is used for both Google and Github.

You should still be able to delete the users if you're using your mozfoundation email to login because you're staff. Anyway, I'll delete those profiles.

**Comment by xmatthewx** [comment]
I think these all look great. We'll just have to keep an eye on it as people roll in with the new mentorship cohort. The biggest thing at this point would be to remove the extra email verification step. This was clearly a ton of work to figure out all the scenarios and paths. Props to you for pulling it together.

**Comment by gideonthomas** [comment]
done
